### ISSUE TITLE
Consider using a high-resolution icon for menu bar

### ISSUE THREAD

**Issue by JuniperPhoton** [txthinking/brook#101]
#### Describe actual behavior
The icon in menu bar is burry.

#### What is your expected behavior
It should be high-res.

![jietu20171111-021222 2x](https://user-images.githubusercontent.com/7578386/32672379-c6bb1df8-c685-11e7-9048-619dabcfda8a.jpg)

**Comment by txthinking** [comment]
😬

**Comment by txthinking** [comment]
v20200101
