### ISSUE TITLE
Weird problem with brook wssserver after v20221010 update !

### ISSUE THREAD

**Issue by khafan11** [txthinking/brook#1013]
Hi 
I don't know that is related to v20221010 but i have problem with some ISP 
 wssserver are stop working with some isp; wsserver both tcp and udp are OK 
but wssserver i got this error 

<details><summary>Screenshot of Brook Error:</summary>

![photo_2022-10-07_22-57-15](https://user-images.githubusercontent.com/13505498/194639627-1a174dc6-67dd-419d-9075-86f35aebb8a8.jpg)
![photo_2022-10-07_22-57-11](https://user-images.githubusercontent.com/13505498/194639632-8e2bcee0-f83e-4aa6-b7c6-5cf2790a3b12.jpg)
</details>

**The Weird part is that the same brook wssserver and same isp are working with Sagernet !!** 
This all are my sagernet settings 
<details><summary>Screenshot of Sagenet :</summary>

![photo_2022-10-07_23-10-18](https://user-images.githubusercontent.com/13505498/194640966-c009be39-2a19-49e8-b5a9-31862f1262c8.jpg)
![photo_2022-10-07_23-10-14](https://user-images.githubusercontent.com/13505498/194640974-b72c1fa5-95ba-4eae-b0a6-68fbef696472.jpg)
![photo_2022-10-07_23-10-11](https://user-images.githubusercontent.com/13505498/194640979-190cb12a-e2c1-4300-8543-6a25e80463ba.jpg)
![photo_2022-10-07_23-10-08](https://user-images.githubusercontent.com/13505498/194640985-4a946e6c-0791-4545-a1bc-90e3732cd05f.jpg)
![photo_2022-10-07_23-10-03](https://user-images.githubusercontent.com/13505498/194640987-256e8d70-5f02-4fde-87e4-fde2f672679a.jpg)
![photo_2022-10-07_23-09-57](https://user-images.githubusercontent.com/13505498/194640995-f22564c0-35bd-4f08-9e48-4e839348c99b.jpg)
![photo_2022-10-07_23-09-53](https://user-images.githubusercontent.com/13505498/194640998-8dd8cd2a-d709-4fe6-b047-f9bea4ad3d82.jpg)

</details>

My brook client setting are all by default, i try to change some dns settings but nothing happened !   
until last week before the update, I did not have any problems
I tried to use the previous version of the client, but unfortunately it still didn't work!
I have also updated the server side to version v20221010 :( But I am still not sure if the problem is related to the new update or not

**Comment by khafan11** [comment]
I should also add that, as I said, some ISPs have this problem! And all those who use my brook server have this problem.
Tonight, I realized that it works with Sagernet without any problem as before!

**Comment by txthinking** [comment]
Can reproduce on latest android, maybe device or rom related
