### ISSUE TITLE
Feature request: tunnels

### ISSUE THREAD

**Issue by chenhw2** [txthinking/brook#102]
#### Describe actual behavior
NULL

#### What is your expected behavior
tunnels both UDP and TCP
Example: https://github.com/shadowsocks/go-shadowsocks2
> ### Client
>
> Start a client connecting to the above server. The client listens on port 1080 for incoming SOCKS5 
connections, and tunnels both UDP and TCP on port 8053 and port 8054 to 8.8.8.8:53 and 8.8.4.4:53 
respectively. 
>
>```sh
>go-shadowsocks2 -c ss://AEAD_CHACHA20_POLY1305:your-password@[server_address]:8488 \
>     -verbose -socks :1080 -udptun :8053=8.8.8.8:53,:8054=8.8.4.4:53 \
>                           -tcptun :8053=8.8.8.8:53,:8054=8.8.4.4:53
>```

#### Specifications like the version of the project, operating system, or hardware
Ver: https://github.com/txthinking/brook/commit/714df2f94343b2397de216565b5b5929ae1d7934

#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.
1.
2.

**Comment by txthinking** [comment]
The socks5 already supports UDP, why we still need tunnel?

**Comment by chenhw2** [comment]
Not every program we need support proxy.

For example, DNS over brook, openvpn over brook, and even rdp(remote desktop of Windows ) over brook.

**Comment by txthinking** [comment]
I assume you want to talk with(both udp and tcp) 1.2.3.4:5

[your local] <----udp/tcp---->[1.2.3.4:5]

Let me describe the tunnel you need:

[your local]<----brook client----brook server----->[1.2.3.4:5]

The command like this: brook tunnel --listen 127.0.0.1:2 --server x.x.x.x:x
--password xx --forward 1.2.3.4:5

Is this right?

**Comment by txthinking** [comment]
127.0.0.1:2 is no longer a socks5.
If we replace 1.2.3.4:5 with 8.8.8.8:53, then 127.0.0.1:2 is a dns server.

**Comment by chenhw2** [comment]
Yes, that's what I am talking about.

**Comment by jusss** [comment]
sorry to bother, I'd like to make brook as global proxy, like a vpn, I know how to use iptables to and
 redsocks to redirect TCP datum to the port brook listen on, but I don't know how to solve the dns issue, 
for example brook listen on 127.0.0.1:7070, so I should redirect the dns datum to local UDP port 7070?
or TCP port 7070?

**Comment by txthinking** [comment]
I am working on this issue, just a few days. :)

**Comment by txthinking** [comment]
If you has a brook server $ brook server ...
and you want start tunnel to 8.8.8.8:53
then you can create a DNS server with Brook:

$ brook tunnel -l 127.0.0.1:53 -t 8.8.8.8:53 -s your_server:port -p password

Test it:
$ dig google.com @127.0.0.1
$ dig +tcp google.com @127.0.0.1

Sure, tunnel can work with more, not only DNS.

```
Clouds-MacBook-Pro:brook tx$ brook tunnel -h
NAME:
   brook tunnel - Run as tunnel mode

USAGE:
   brook tunnel [command options] [arguments...]

OPTIONS:
   --listen value, -l value    Client listen address, like: 127.0.0.1:1080
   --to value, -t value        Tunnel to where, like: 8.8.8.8:53
   --server value, -s value    Server address, like: 1.2.3.4:1080
   --password value, -p value  Server password
   --tcpTimeout value          connection tcp keepalive timeout (s) (default: 60)
   --tcpDeadline value         connection deadline time (s) (default: 0)
   --udpDeadline value         connection deadline time (s) (default: 60)
```

**Comment by chenhw2** [comment]
Thanks a lot. It works very well.

**Comment by jusss** [comment]
could you write more specifically? 
run `brook server ...` on the server and run `brook tunnel ...` on the client?
 or run `brook tunnel ...` and `brook server ...` both on the server and run them both on the client?
thanks for your reply!

**Comment by jusss** [comment]
also if `brook tunnel ...` supports transparent proxy, that means I can redirect all tcp datum to the port which brook listen on directly, and without redsocks for socks5 wrap? is that right?

**Comment by txthinking** [comment]
@jusss No, it's not transparent proxy #117 .

**Comment by txthinking** [comment]
@jusss If redsocks can support UDP. You can try with your idea: https://github.com/txthinking/brook/issues/102#issuecomment-356933294

**Comment by hybtoy** [comment]
@txthinking Didn't understand the usage of tunnel. It is used with "server" or separately? 
Thanks.

**Comment by jusss** [comment]
@hybtoy the tunnel only works with `brook server`
you run `brook server` on your VPS, then you can run `brook tunnel` on your local, 
and it seems you must point the destination address if you want to use `brook tunnel`
