### ISSUE TITLE
Android stop VPN automatically

### ISSUE THREAD

**Issue by mariokart1992** [txthinking/brook#103]
My device is OnePlus 5 system is OOS 4.5.14(7.1.1)

The app version is the newest one in Google play

After I used the app for about 1-2 hours ,the VPN automatically stopped . First of all I checked the Background whitelist ,I am sure about the Brook is in it.Then I check the VPN setting ,I have set Brook to be the always use VPN.

However, the issue still happen every 1-2 hours.

**Comment by txthinking** [comment]
This may be caused by OnePlus custom ROM.
http://www.oneplusbbs.com/thread-3208649-1-1.html

Because it has been running for 24+ hours on my Pixel, no background whitelist, no extra configuration.

**Comment by txthinking** [comment]
You said the VPN automatically stopped, can you provide much more information about `stopped`, VPN(key) logo still there?

**Comment by mariokart1992** [comment]
The VPN key logo disappeared. When I use SS the issue never happened. Thanks so much for your reply. China 's network is annoying.

**Comment by Portan** [comment]
This is probably because your system cleaning process, you need to make this app alive in background.

**Comment by txthinking** [comment]
I just close it, because this is caused by your customize OS.
