### ISSUE TITLE
The iOS app issue for iOS versions bellow 15, I guess...

### ISSUE THREAD

**Issue by iamR3za** [txthinking/brook#1030]
Hi, there seems to be a problem with the iOS app for iOS versions lower than 15. After installing the Brook iOS app, adding the brook server using the brook link, and allowing the VPN profile in the iPhone settings, I tried connecting to the server; Although the app clearly shows that I am connected, the VPN icon won't show on the iPhone notification bar, and after checking my IP in Safari, it seems that I am not connected to the server. I tried this on iOS 12, 13, and 15. And it only worked correctly in 15. So I would appreciate it if you could check this issue.

**Comment by iamR3za** [comment]
> iOS <15 memory limit 15M, >=15 limit 50M, I think so by [unknown](https://t.me/brookgroup)

So, isn't there a way you can resolve it? or optimize it for 15M limit memory? Tnx

**Comment by iamR3za** [comment]
> > iOS <15 memory limit 15M, >=15 limit 50M, I think so by [unknown](https://t.me/brookgroup)
> 
> So, isn't there a way you can resolve it? or optimize it for 15M limit memory? Tnx

(reminder)

**Comment by txthinking** [comment]
Yes, next version

**Comment by txthinking** [comment]
v20230101
