### ISSUE TITLE
Invalid args, please report this error to developer。 尝试禁用缓也未解决问题存

### ISSUE THREAD

**Issue by ambrato** [txthinking/brook#1032]
![image](https://user-images.githubusercontent.com/43380345/200994423-efde9109-ade2-4213-af4a-5191dacfd3ac.png)

![image](https://user-images.githubusercontent.com/43380345/200994570-b7a82932-020a-458d-b0ca-1e62521e3b63.png)

请教下这啥原因， 看到之前有个相似的问题， 禁了缓存解决了， 我这禁缓存也没解决

**Comment by txthinking** [comment]
清除一下缓存，browser缓存了server的响应
