### ISSUE TITLE
关闭Fake Dns 的时候是否支持用系统默认dns解析域名

### ISSUE THREAD

**Issue by luuillu** [txthinking/brook#1033]
我在公司里面用brook 里面用Socks5协议连接抓包工具，以便抓包，发现开启brook之后无法访问内网域名。因为Fake Dns配置的google dns无法解析内网域名。
但关闭Fake Dns后，域名完全无法解析。所以每次都需要手修改Fake Dns，不太方便。
是否能添加一下bypass掉DNS协议的功能，允许DNS直接由内网解析，使开启brook不影响访问内网域名？
多谢！

**Comment by luuillu** [comment]
试了一下最新版本，看起来这个问题已经解决了。👍🏻

**Comment by txthinking** [comment]
you got it
