### ISSUE TITLE
Windows client cannot start up on windows 10

### ISSUE THREAD

**Issue by yuzhg** [txthinking/brook#104]
#### Describe actual behavior
IE 11 will show up for 1 sec then disappear. Brook client says cannot find IE.

#### What is your expected behavior
Is it possible to remove the hard dependency on IE? just use system default browser or sth like that....

**Comment by txthinking** [comment]
Can you provide the error message instead of `Brook client says cannot find IE`?

And do you prefer #105?

**Comment by yuzhg** [comment]
There is no error msg.

IE just shows up like for 1 ms and disappeared.

Actually I was trying to reinstalled IE 11 and some error happened. Now I don't have IE in my system at all and brook just says can't find IE...

I don't fully understand #105 since I don't know what the IE page originally planned for. As long as there is no hard dependency on IE, I'm good with the change.

**Comment by txthinking** [comment]
I just close it. Anything about IE please discuss in #105
