### ISSUE TITLE
[relayoverbrook] Use brook to create WS/WSS tunnel to relay shadowsocks

### ISSUE THREAD

**Issue by kevvvinyao** [txthinking/brook#1042]
I have questions about **relayoverbrook**, and I've searched for it in existing issues and discussions.
I found this link, seeming a introduction and tutorial about Brook Relay.
>https://github.com/txthinking/brook/wiki/How-to-run-Brook-Relay-Server-on-Linux%3F

But this link will be redirected to https://github.com/txthinking/brook

Where can I visit content about Brook Relay now?
I've visited https://txthinking.github.io/brook/, but I didn't get how to create a ws/wss tunnel by brook to relay other types of proxy (shadowsocks).
Maybe there is a new website/page introducing detailed config of ws/wss tunnel relay, but I don't know.
Chinese is my mother tongue, so I'll repeat my question again in Chinese below:

想学习一下如何使用brook构建ws或wss隧道中转其他代理协议的流量，找到了这个链接：
>https://github.com/txthinking/brook/wiki/How-to-run-Brook-Relay-Server-on-Linux%3F

但是现在这个链接会直接跳转到brook项目的github主页了

我想了解一下关于brook转发的详细内容。
我已经看了 https://txthinking.github.io/brook/ 的内容，已经实现了最基本的brook relay转发，但是没有理解如何创建ws和wss隧道。我想在落地机用shadowsocks，然后在落地机和中转机之间使用brook构建ws或者wss隧道，来中转shadowsocks的tcp流量。

**Comment by kevvvinyao** [comment]
I make a comment at another issue as same as this issue I submitted.
But I found that issue has been completed.
I'm not sure my comment can be read and replied by other people, so I create this new issue.

我在另一个`issue`下面评论了这个问题，但是那个`issue`已经被`completed`了
不知道被`completed`的`issue`下面的评论还是否会被推送，所以我直接单独写了一个新`issue`

**Comment by txthinking** [comment]
### 机器:
A, 公网IP: 1.2.3.4
B, 公网IP: 1.2.3.5
C, 公网IP: 1.2.3.6
D, 本地机器

### A: shadowsocks server

```
bash <(curl https://bash.ooo/nami.sh)
```
```
nami install joker shadowsocks
joker ssserver -m aes-256-gcm -k hello -s 1.2.3.4:10000 -U --udp-timeout 60 --tcp-no-delay
joker list
```
注意: 因为需要处理UDP, -s 监听地址必须指定IP，不能是0.0.0.0。同时，如果你的VPS提供商是NAT环境（比如Google Cloud)，就是公网IP没有挂在本机网卡上，一般情况下监听本机内网地址即可

### B: shadowsocks client, brook wsserver

```
bash <(curl https://bash.ooo/nami.sh)
```
```
nami install joker shadowsocks brook
joker sslocal -s 1.2.3.4:10000 -m aes-256-gcm -k hello -b 127.0.0.1:1080 -U --udp-timeout 60
joker list
```
```
brook testsocks5 -s 127.0.0.1:1080
```
如果B可以连通1.2.3.4:10000地址，并且你的ssserver配置正确的话，上面这条命令会输出 UDP OK 和 TCP OK
```
joker brook wsserver -l :80 -p world --toSocks5 127.0.0.1:1080
```

### D: 本地机器

```
本地机器 -> B -> A
```

```
bash <(curl https://bash.ooo/nami.sh)
```
```
brook wsclient -s ws://1.2.3.5:80 -p world --socks5 127.0.0.1:1080
```
```
brook testsocks5 -s 127.0.0.1:1080
```
如果你本地能连通1.2.3.5:80地址的话，上面这条命令会输出 UDP OK 和 TCP OK
```
curl -x socks5://127.0.0.1:1080 http3.ooo
```
如果你本地能连通1.2.3.5:80地址的话，上面这条命令会输出A机器的IP

```
当然你可以在Brook图形客户端添加如下信息
brook wsserver
ws://1.2.3.5:80
world
```

### C: brook relay

```
bash <(curl https://bash.ooo/nami.sh)
```
```
nami install joker brook
joker brook relay -f :81 -t 1.2.3.5:80
joker list
```

### D: 本地机器

```
本地机器 -> C -> B -> A
```

```
bash <(curl https://bash.ooo/nami.sh)
```
```
brook wsclient -s ws://1.2.3.6:81 -p world --socks5 127.0.0.1:1080
```
```
brook testsocks5 -s 127.0.0.1:1080
```
如果你本地能连通1.2.3.6:81地址的话，上面这条命令会输出 UDP OK 和 TCP OK
```
curl -x socks5://127.0.0.1:1080 http3.ooo
```
如果你本地能连通1.2.3.6:81地址的话，上面这条命令会输出A机器的IP

```
当然你可以在Brook图形客户端添加如下信息
brook wsserver
ws://1.2.3.6:81
world
```

**Comment by kevvvinyao** [comment]
感谢作者的亲自解答，我大概理解了这种实现方式：
把**shadowsocks**的`client`端作为**brook**的`server`端，然后本地作为**brook**的`client`端，实现链接

如果我想实现：本地成为**shadowsocks**的`client`端，通过**brook**协议传输**shadowsock**的流量，应该怎么实现呢？

*因为这样进行中转时，本地只需要在软件中设置shadowsocks代理就可以了，比较方便*
*我已经实现了使用普通的brook relay进行中转：只需要一行代码，只需要在中转机上执行，非常方便；本地连接的仍然是落地机上的代理协议*

我想利用文档中提到的：
> brook relayoverbrook 中继任何 TCP 和 UDP server, 让其走 brook 协议. 它与 brook server wsserver wssserver 一起工作

**relayoverbrook**的方式来实现：不改变协议类型，只是走一下**brook**隧道（类似*gost*隧道的功能），请问一下具体的**brook**命令应该如何写呢？

**Comment by txthinking** [comment]
### 机器ABD之间连接协议及端口概览:

```
【PC】(D) ---SS协议--> 【10000】(B) --brook协议--> 【20000 --SS协议-->30000】(A)
```

### A (公网IP: 64.225.75.20): shadowsocks server, brook wsserver

```
bash <(curl https://bash.ooo/nami.sh)
```
```
nami install joker shadowsocks brook
joker ssserver -m aes-256-gcm -k hello -s 127.0.0.1:30000 -U --udp-timeout 60 --tcp-no-delay
joker brook wsserver -l :20000 -p world
joker list
```

### B (公网IP: 157.245.75.25): brook relayoverbrook

```
bash <(curl https://bash.ooo/nami.sh)
```
```
nami install joker brook
joker brook relayoverbrook -s ws://64.225.75.20:20000 -p world -f :10000 -t 127.0.0.1:30000
joker list
```

### D: PC

```
sslocal -s 157.245.75.25:10000 -m aes-256-gcm -k hello -b 127.0.0.1:1080 -U --udp-timeout 60 --tcp-no-delay
```
```
brook testsocks5 -s 127.0.0.1:1080
```
如果D到B的10000畅通，上面应该会输出UDP OK, TCP OK
```
curl -x socks5h://127.0.0.1:1080 http3.ooo
curl -x socks5://127.0.0.1:1080 --resolve "http3.ooo:80:137.184.237.95" http3.ooo
```
上面应该会输出A的IP

**Comment by kevvvinyao** [comment]
非常感谢作者答疑解惑🙏
已经成功解决问题👍
B机器上面那个`-t 127.0.0.1:30000`实在是太妙了
