### ISSUE TITLE
metrics support 

### ISSUE THREAD

**Issue by mosajjal** [txthinking/brook#1049]
hi. thanks for this project! wondering if you've considered providing a metrics protocol (`prometheus`) support for brook. I'd be happy to co-author with you.

**Comment by txthinking** [comment]
For example, what dimensions do we need to count

**Comment by mosajjal** [comment]
request count, request sizes, bandwidth, user count, latency, top destinations, etc.

**Comment by txthinking** [comment]
It can be used as a [plugin](https://github.com/txthinking/brook/tree/master/plugins)

**Comment by mosajjal** [comment]
can be closed with the new prometheus feature. thanks!
