### ISSUE TITLE
Anything about IE Problem. Add a Change System Proxy switch into Brook Client for Windows

### ISSUE THREAD

**Issue by txthinking** [txthinking/brook#105]
#### Describe actual behavior
Now, brook GUI client for windows use IE(restart) to let proxy effect.
But many windows GUI users encountered a lot problems about the fucking IE when they start brook.

#### What is your expected behavior
In brook setting page, add a switch `Change system proxy`,
if enabled, change system proxy when start brook,
if disabled, just start brook, user need to change proxy manually(through system proxy or browser extension)

#### Specifications like the version of the project, operating system, or hardware

* Windows
* Brook GUI Client for Windows v<=20171113

#### To users
Actually, I don't want to add new configuration item, because the default Windows OS[1] works well.
Many users will not do some complex operations, like remove IE.
If some users are geek, they can choose Brook Cli for Windows.

So, If you want this feature, please +1 👍

[1]: Download iso from microsoft.com && Install Windows on Virtualbox && Download Brook GUI Client for windows && Works well

**Comment by openBetaa** [comment]
I don't think it's nessary to add this new feature, people who wanna change proxy manually can just use Proxy SwitchyOmega.

**Comment by txthinking** [comment]
@openBetaa But now when your click `start`, Brook Windows GUI client will do two things:
1. Start brook
2. Change system proxy.

**Comment by txthinking** [comment]
Fixed in v20180227
