### ISSUE TITLE
运行脚本报错

### ISSUE THREAD

**Issue by wuhaibo-jmu** [txthinking/brook#1052]
--2022-11-22 09:26:05--  https://github.com/txthinking/brook/releases/download/v20221212/brook
正在解析主机 github.com (github.com)... 20.205.243.166
正在连接 github.com (github.com)|20.205.243.166|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2022-11-22 09:26:06 错误 404：Not Found。

**Comment by txthinking** [comment]
nami
docs
