### ISSUE TITLE
Android client is fast in telegram,but iOS client is a little slow in it.

### ISSUE THREAD

**Issue by xmulder** [txthinking/brook#107]
#### Describe actual behavior
I have a Android phone(5.1.1) and a iPhone 6s plus(11.1)
I install telegram and brook on them.
When I use telegram in brook.I found a doubt.
On android,the telegram is so fast downloading from the server,but On iOS,I found telegram is connecting to telegram server frequently.So the telegram is downloading the resources so slow.
I use the some IP in brook. 

Thanks.
#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.
1.
2.

**Comment by anzhengru** [comment]
·····me too

**Comment by carry168** [comment]
me too

**Comment by txthinking** [comment]
Please try latest version, if it is still not resolved open this again. Thank you.
