### ISSUE TITLE
brook新版本无法套用cloudflare代理了吗？

### ISSUE THREAD

**Issue by hkhk368** [txthinking/brook#1071]
我过去一直用很老的版本，最近升级了新版本，发现我无法套上cloudflare代理了，能帮我看一下为什么吗？

CloudFlare上开启代理
![image](https://user-images.githubusercontent.com/109432596/206017783-6f90f91b-b7bf-4be9-b162-a906f7ad5534.png)

服务器上启动ws无证书
/root/brook wsserver --listen :10000 --password xxx

Nginx上设置转发，nginx自带let's encrypt自动证书，然后通过location转发
location / {
                proxy_redirect off;
                proxy_pass http://127.0.0.1:10000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
location /ws {
                proxy_redirect off;
                proxy_pass http://127.0.0.1:10000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
客户端
brook.exe wssclient --wssserver wss://z.xxxxxxx.com:443 -p xxx --socks5 127.0.0.1:1080
2022/12/07 04:32:49 HTTP/1.1 301 Moved Permanently
2022/12/07 04:32:51 HTTP/1.1 301 Moved Permanently
2022/12/07 04:32:54 HTTP/1.1 301 Moved Permanently

客户端无法正常使用，而用过去非常老的brook（得几年前的）使用nginx转发则没有出现这个问题，能帮我看一下吗，谢谢

**Comment by mrkoalaz** [comment]
我也出现了类似的情况，遂在此贴下附加信息：

环境：
用nami更新了服务器端brook到v20221212
Windows客户端也更新到了v20221212

用法：
平时使用WSS建立连接，完全正常。

问题：
由于公司到Brook服务端虚拟机间的链路丢包率非常糟糕，于是尝试了使用cloudflare来加速访问，Cloudflare生效后域名的ping值稳定。
之后尝试启动Brook：
出现了Windows客户端测试连通性时返回“遇到意外 HTTP/1.1 302 Found”的信息。
Android手机端v20221212在蜂窝数据下不受影响，当接入WLAN后，点击“连通性测试”后同样出现遇到意外 HTTP/1.1 302 Found”的信息。
不知道哪里出了问题，所以请求帮助。
