### ISSUE TITLE
Can't use Windows CLI client

### ISSUE THREAD

**Issue by haseoxth** [txthinking/brook#108]
I want to try the CLI one on my 386 Windows 10 laptop so I downloaded brook_windows_386.exe but it closed itself when I opend it even with quit Windows defender first. Do I need to intall anyting else first if I want to ued it?

**Comment by txthinking** [comment]
You need:
1. Win+R
2. Type cmd, press Enter
3. `cd path/to/brook_windows_386.exe/dir`
4. `brook_windows_386 -h`

**Comment by haseoxth** [comment]
Unfortunately I still had same result after these processes, brook window disappeared instantly after opened.

**Comment by haseoxth** [comment]
I tried to put brook to C:\ and used cmd command above. Seems everything works now.
