### ISSUE TITLE
joker brook守护进程一段时间后断开

### ISSUE THREAD

**Issue by ggshr9** [txthinking/brook#1087]
查了下joker log，最后几行出现这些。想问下是什么原因。
以前运行都ok，最近升级了版本出现这个问题
2022/12/18 12:29:59 cipher: message authentication failed
panic: runtime error: slice bounds out of range [126:111]

goroutine 63126 [running]:
github.com/txthinking/brook.PacketClientToRemote({0xc000182da0, 0xb, 0x10}, {0xc000708000, 0x7f, 0xffe3})
        /Users/fuck/code/brook/packetserver.go:128 +0x58e
github.com/txthinking/brook.(*Server).UDPHandle(0xc0000e28f0, 0xc0009fe1b0, {0xc000708000, 0x7f, 0xffe3})
        /Users/fuck/code/brook/server.go:374 +0xab
github.com/txthinking/brook.(*Server).RunUDPServer.func1(0xc000a405f0?, {0xc000708000?, 0xc0004d8d10?, 0xc000852150?})
        /Users/fuck/code/brook/server.go:246 +0x31
created by github.com/txthinking/brook.(*Server).RunUDPServer
        /Users/fuck/code/brook/server.go:245 +0xdb

**Comment by txthinking** [comment]
try 20230101 and feel free to comment if sth wrong

**Comment by txthinking** [comment]
v20230404
