### ISSUE TITLE
Android IPv6 support

### ISSUE THREAD

**Issue by Cuiyn** [txthinking/brook#109]
#### Describe actual behavior
I have a domain which points to an IPv6 address. I can use it in brook client of Windows, and all is well. However, I can't use it in Android client. The client doesn't have any exceptions, but I can't open any web pages, and so on. When I change to an IPv4 address, it works well.

#### What is your expected behavior
In the Android client, when I use a domain name which points to an IPv6 address, it can work well.

#### Specifications like the version of the project, operating system, or hardware
Android: 7.0, MIUI 9 Development Version, Oneplus 3
Linux server version: Debian 9, Linux 4.9.0-4-amd64, from Vultr
Android Brook client version: v20171112
Brook server Version: 20171113, Linux amd64

#### Steps to deploy the server
1. Download the brook program.
2. Run "./brook ..." following the instructions in wiki.

#### Steps to reproduce the problem
Open the Android client and use a domain which points to an IPv6 address.

**Comment by txthinking** [comment]
(Server/Cli Clients/iOS GUI/MacOS GUI/Windows GUI may work well)

Yep, Android client may not work well on IPv6, still need some work.

**Comment by Cuiyn** [comment]
When I use Shadowsocks client on Android, it can work perfect on IPv6, so I think the client of Brook on Android has some problem. 
Anyway, thanks for your effort, I really enjoy it.

**Comment by KingsFish** [comment]
brook可以支持ipv6？可以告诉我怎么开启么，我之前在我的VPS上试了一下，好像只监听了ipv4。多谢多谢

**Comment by bitkylin** [comment]
I also really like to use IPv6 to connect brook, but I don't know what I should do when I use Windows Client. Who could give me a answer ?

**Comment by aleczhminr** [comment]
我发现正常安装完后，debian 9 netsate -apn查看监听后brook没有监听在IPV4。只有IPV6的tcp6和udp6 ，是否不支持IPV4了！

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/wiki/IPv6

**Comment by tylerliu1998** [comment]
It is Oct. 2019 now. IPv6 on Android is still not supported. Hope this feature will come out soon since using IPv4 VPS in mainland China is too risky.

**Comment by txthinking** [comment]
Please try v20200801, if any problem reopen or create an issue please.
