### ISSUE TITLE
add single client session mode

### ISSUE THREAD

**Issue by emaditaj** [txthinking/brook#1098]
please add single client session mode
the purpose is to prevent the proxy/vpn from being spread and overwhelmed when shared with others/sold 

i can suggest two methods 
each have their own benefit in highly censored countries like Iran and China
1-add user/pass pairs
2-we use separate process/port for each client
in both we need to limit the connection to only one session by either checking for  simultaneous connection from different client ips or negotiating a random id in beginning of each session and blocking connections when the id is different from already connected one (in the last minute if brook starts new tcp connection for each web request)

a lazy workaround (yet need changes in code ) : print the client ip in debug mode so we can log the terminal and check for simultaneous ips using other tools and use separate port&process for each client

an outtopic request : please add UTLS ,recently governments of highly censored countries like Iran and China (which need this tool the most) detect high/big/long transfers/connections done with uncommon client Tls-Hello as vpn server and block the server ip for a few weeks/months 
this is a must for brook WssServer 
regards

**Comment by emdaitaj** [comment]
@txthinking-bot 
install script of what ?

**Comment by txthinking** [comment]
There is no strict and precise method, and it is mutually exclusive with user experience. One day you will understand that this is not a good business model. You should limit each user's bandwidth or speed test or downloader to prevent instant preemption of server resources, and traffic to correspond to the cost.

brook-manager and iptables
