### ISSUE TITLE
Request: Support Shadowsocks v3

### ISSUE THREAD

**Issue by fortuna** [txthinking/brook#11]
#### Describe actual behavior
Brook doesn't support the [AEAD ciphers](https://shadowsocks.org/en/spec/AEAD-Ciphers.html) in v3 of the Shadowsocks protocol.

#### What is your expected behavior
I'd like to not only [choose the cipher](https://github.com/txthinking/brook/issues/10), but also have the AEAD ciphers available.

**Comment by txthinking** [comment]
It looks like change stream data to chunked data. https://github.com/shadowsocks/shadowsocks-org/issues/30
I will take time to see its benefits. (Currently only concerned about anti-interference ability)

**Comment by txthinking** [comment]
Maybe next time.
