### ISSUE TITLE
iOS client connection problems

### ISSUE THREAD

**Issue by jamewhite** [txthinking/brook#111]
#### Describe actual behavior
Some domains in the white list are still connected through the proxy. Some domains are able to connect directly, but some requests cannot be sent when the server is closed.

#### What is your expected behavior
All the domains in the white list can be connected directly.

#### Specifications like the version of the project, operating system, or hardware
Brook v20171111 and later
System: iOS 11.1

#### Steps to deploy the server
nohup brook server -l :(port) -p (password) >/dev/null 2>&1 &

#### Steps to reproduce the problem
1. Visit a website ***.cn in browser it connects directly.
2. When it send some requests (example: get/login/logout) to this website (click a button), it connects through proxy. This website can only be visited with specific IPs, so I need to stop brook first before that.

#### Other problems
In iOS client, when I set the server with a domain (with both IPv4 and IPv6 addresses), I open a website through proxy after brook starts (in a network with IPv6) and then the browser said "An SSL error has occurred" or "The Internet connection is offline". When I set the server with the IPv6 address it is still the same. After I set it with the IPv4 address, or visit it in a network only with IPv4, it works properly. 

Also, I think that local addresses should be connected directly.

**Comment by txthinking** [comment]
Which domain or URL can you point out?

**Comment by txthinking** [comment]
Please like one issue one problem.

**Comment by jamewhite** [comment]
It is not proper to put the links here, could I send you an email?

**Comment by txthinking** [comment]
Yap, here is my email: cloud@txthinking.com
