### ISSUE TITLE
I am  a new hand,do not know how to install brook server

### ISSUE THREAD

**Issue by mycjc** [txthinking/brook#113]
#### Steps to deploy the server
0.firstly I use 
  **wget -N --no-check-certificate 
 https://github.com/txthinking/brook/releases/download/v20171113/brook_linux_arm64**
all thing well
1.and then I try **brook server -l :443 -p mypassword**
but linux say that 'brook' command not found
2. what should i do ?

**Comment by chenhw2** [comment]
It is **amd** NOT **arm**

**Comment by limon** [comment]
1. chmod +x brook
2. ./brook server .............

**Comment by mycjc** [comment]
Thank you ! I try it again use ./brook instead of brook.It worked!

**Comment by txthinking** [comment]
Thank you @chenhw2 @limon
