### ISSUE TITLE
There is a beta version here

### ISSUE THREAD

**Issue by txthinking** [txthinking/brook#1132]
Since there are a lot of optimizations this time, the Beta version is released here first to let the bullets fly for a while.
由于本次优化比较多，所以先发布 Beta 版本于此，让子弹飞一会。

- brook tproxy & OpenWrt: UDP bugfix, best gateway software on dual stack? 适配双栈最好的一个? 
- brook quicserver& brook quicclient: [QUIC as a transport](https://github.com/txthinking/brook/blob/master/protocol/brook-quicserver-protocol.md). QUIC 协议支持，注意这是纯 UDP 协议
- tun2brook: Programable bugfix. [上次](https://t.me/txthinking_news/188)没测试 :b
- brook plugins: It is very simple to write [brook plugin](https://github.com/txthinking/brook/tree/master/plugins), just overwrite the public function variable

[Download Beta Files. 下载 Beta 版](https://drive.google.com/drive/folders/1T39UtUCndeyO3Tjl-K0I4vEu1DHoMTY4?usp=share_link)

**Comment by txthinking** [comment]
20230217 folder

**Comment by YaoZhengWu** [comment]
很久没有使用新版本了，现在Windows的GUI 客户端，不能在右下角显示通知图标了么？

**Comment by YaoZhengWu** [comment]
> 
看到了，原来在上一个本
v20230101
Edge 不再需要. 暂无 System tray.

**Comment by txthinking** [comment]
New 20230308 folder

**Comment by txthinking** [comment]
20230317 Folder:

- $ brook dhcpserver, 可以代替路由器的DHCP功能。可搭配 $ brook tproxy 用
- 指定进出口 IP。brook --dialWithIP4 出 *subcommand* --listen 进:PORT

**Comment by txthinking** [comment]
v20230404
