### ISSUE TITLE
Can you share me Brook iOS version ipa file?

### ISSUE THREAD

**Issue by ZorianLi** [txthinking/brook#114]
Can you share me pre-compiled ipa file of latest Brook version? I need to share it internally because we cannot access the app store. 

If it's possible, please send it to my email: zorianlee@outlook.com

Thank you very much, really appreciate for your help.

**Comment by txthinking** [comment]
Please download from app store.
If you don't have US apple ID, please google how.

**Comment by rayfareast20** [comment]
please send me the old version of brook for ios（email：346283692@qq.com），the new one is not available on my phone, thanks~
