### ISSUE TITLE
flag provided but not defined: -l:445(can't run brook server)

### ISSUE THREAD

**Issue by mycjc** [txthinking/brook#115]
#### Steps to deploy the server
0.I use a centos7 vps
1.I use "**./brook server -l 445 -p mypassword**"
 linux tips that"**address 445: missing port in address**"
2.I use "**./brook server -l:445 -p mypassword**"
 linux tips that "**flag provided but not defined: -l:445**"
3.all directory rights is **777**.，**Brook version 20171113**

**Comment by txthinking** [comment]
You missed  a space.
-l :666

**Comment by txthinking** [comment]
You may need to look at the wiki
