### ISSUE TITLE
Multiple Ip servers - Socks5

### ISSUE THREAD

**Issue by reno1314** [txthinking/brook#1151]
Multiple Ip servers
Socks5 How to set the corresponding entry IP and exit IP

**Comment by reno1314** [comment]
I mean
When the server has multiple public IP addresses
How to set up

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/issues/1132#issuecomment-1473167291

**Comment by reno1314** [comment]
Thank you for your help

**Comment by txthinking** [comment]
v20230404

**Comment by reno1314** [comment]
Thank you
