### ISSUE TITLE
编译了4月1号的版本，提示了一些编译问题

### ISSUE THREAD

**Issue by mz8800** [txthinking/brook#1154]
使用.\build.sh 编译后
[main 2023-03-23T06:43:27.017Z] update#setState idle
[main 2023-03-23T06:43:27.845Z] [UtilityProcess id: 1, type: extensionHost, pid: <none>]: creating new...
[main 2023-03-23T06:43:27.870Z] [UtilityProcess id: 1, type: extensionHost, pid: 21076]: successfully created
[main 2023-03-23T06:43:30.821Z] [UtilityProcess id: 1, type: extensionHost, pid: 21076]: received exit event with code 0
[main 2023-03-23T06:43:30.821Z] Extension host with pid 21076 exited with code: 0, signal: unknown.

编译不通过，请帮助我看一下，敬谢。

**Comment by txthinking** [comment]
这是什么东西

**Comment by nursery01** [comment]
> 这是什么东西

可能是檔案列表裡有個build.sh，然後他就運行它進行編譯

不如刪除掉build.sh？

**Comment by txthinking** [comment]
运行它没问题啊（打开sh看看也很简单）
但是他粘贴出来输出很奇怪，无论是任何Linux, macOS, Windows 都不会出现他粘贴的内容：update#setState idle... UtilityProcess... extensionHost...

**Comment by txthinking** [comment]
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/brook.rb
