### ISSUE TITLE
How to deploy a Brook Client on Linux

### ISSUE THREAD

**Issue by urnotuname** [txthinking/brook#116]
#### Describe actual behavior
brook: command not found
#### Steps to deploy the server
0.su
1.chmod +x brook
2.brook client ................
**bash: brook: command not found**

#### Steps to reproduce the problem
0.
1.
2.

**Comment by mycjc** [comment]
use  **./brook**  ........

**Comment by anzhengru** [comment]
········

**Comment by txthinking** [comment]
The wiki can help you:
https://github.com/txthinking/brook/wiki/How-to-deploy-Brook-Server-on-Linux%3F

**Comment by eddiecailinux** [comment]
> The wiki can help you:
> https://github.com/txthinking/brook/wiki/How-to-deploy-Brook-Server-on-Linux%3F

this wiki is about how to deploy Brook server on linux. i have the same question about deploy Brook client on linux. 
i download [https://github.com/txthinking/brook/releases/download/v20190205/brook](url)
i try sudo ./brook client -s my_server_address:my_server_port -p my_server_passwd
It output below message. any commnet?
NAME:
   brook client - Run as client mode

USAGE:
   brook client [command options] [arguments...]

OPTIONS:
   --listen value, -l value    Client listen address, like: 127.0.0.1:1080
   --ip value, -i value        Client IP address, like: 127.0.0.1
   --server value, -s value    Server address, like: 1.2.3.4:1080
   --password value, -p value  Server password
   --tcpTimeout value          connection tcp keepalive timeout (s) (default: 60)
   --tcpDeadline value         connection deadline time (s) (default: 0)
   --udpDeadline value         connection deadline time (s) (default: 60)
   --udpSessionTime value      udp session time (s), in most cases need this (default: 60)
   --http                      If true, client start a http(s) proxy. default socks5

**Comment by eddiecailinux** [comment]
i use brook client -l 127.0.0.1:1080 -i 127.0.0.1 -s server_address:port -p password
i set my chrome browser to use sock5 proxy
the browser can not access any web site. 
the brook log shows below
2019/02/15 17:54:48 dial tcp my_server_address:my_server_port: i/o timeout

my iphone using brook app download from app store. it work well. i can access google, youtube etc. 
any idea what happened on my linux pc?
