### ISSUE TITLE
 mipsel_24kc IPK missing

### ISSUE THREAD

**Issue by pywsa** [txthinking/brook#1162]
Hello.
Please add ipk file for openWRT with **mipsel_24kc** architecture.
Thanks.

**Comment by pywsa** [comment]
I tried all ipk files none of them working.

`
Unknown package 'brook'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for brook found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package brook.
`

**Comment by txthinking** [comment]
"tried" is opkg install brook.ipk?

**Comment by txthinking** [comment]
https://www.txthinking.com/talks/articles/brook-openwrt-en.article

or build from source

```
git clone https://github.com/txthinking/brook.git
cd cli/brook/
go build
cd ../../ipk
cp ../cli/brook/brook data/usr/bin/brook
./build.sh
```

**Comment by pywsa** [comment]
Thanks.
Yes "tried" is "opkg instal brook_XXXX.ipk"
I tried all available architecture versions none of them work. Could you please build one for MIPSEL_24KC architecture?

my openwrt router is 16MB and I can't install go, git, ... to build it from source.

thanks for your time in advance. I appreciate if you could add mipsel_24kc architecture as well.

**Comment by txthinking** [comment]
I don't know how to set the GOARCH or GOMIPS for your device
https://github.com/txthinking/brook/blob/master/cli/brook/build.sh#L28

**Comment by pywsa** [comment]
How can I help? :(
I really need it.
Will providing a sample .ipk file, which has been created for MIPSEL_24KC help?

**Comment by txthinking** [comment]
[v20240214](https://github.com/txthinking/brook/releases/tag/v20240214)
