### ISSUE TITLE
Transparent proxy

### ISSUE THREAD

**Issue by limon** [txthinking/brook#117]
I run brook on my router. Is there any way to setup a transparent proxy easily, like ss-redir?

**Comment by txthinking** [comment]
same as #102 ?

**Comment by limon** [comment]
no, not a tunnel. 
I need something like this: https://gist.github.com/wen-long/8644243
which use iptables to rediect packets, and clients through the router won't aware any change.

**Comment by txthinking** [comment]
Yep. I know, this is another feature.

**Comment by nuclearn** [comment]
you must install redsocks in route in order to a transparent proxy. I wish add the feature in Brook.

**Comment by txthinking** [comment]
This feature is implemented in v20180227.

**Comment by nuclearn** [comment]
the feature is not available when using iptable redirect, ex
iptables -t nat -A BROOK -p tcp -j REDIRECT --to-ports 1080 (BROOK_TPROXY_PORT)

**Comment by txthinking** [comment]
@nuclearn https://github.com/txthinking/brook/tree/master/scripts

**Comment by nuclearn** [comment]
How to deploy the firewall when brook is installed on Openwrt Route?
Unlike ss-redir, the transparent feature is not available using iptable redirect function.

**Comment by txthinking** [comment]
Please read the wiki: https://github.com/txthinking/brook/wiki/How-to-run-transparent-proxy-on-Linux%3F

**Comment by txthinking** [comment]
@nuclearn  Brook tproxy works on mangle table
