### ISSUE TITLE
is there a way binding it to a NIC? because it's IP is dynamic

### ISSUE THREAD

**Issue by haofanurusai** [txthinking/brook#1196]
Version: 20230404
Server: Windows 8.1 x86
Client: Windows Server 2008R2 x64
Binary: brook_windows_386.exe (both)

I have 2 NICs on the server. One named 'A' is slow and limited but its ping is low, and another one named 'B' is fast but it usually does not ping from client side. So I use this proxy for better accessibility  (client connect to A and use it to access B-only websites).
I configured metrics (A=200, B=1) on the route table of my server in order to set priority, and the brook server only listen to A. But when I connect it with my client and use some tool websites to see my IP it's always A's, not B's.

What should I do? Thanks.

**Comment by txthinking** [comment]
brook --dialWithIP4 B server --listen A:port

**Comment by haofanurusai** [comment]
Thanks, and is there a way binding it to a NIC? B's IP is dynamic and changes weekly.

**Comment by txthinking** [comment]
I ignored the situation of the network card with dynamic IP, this feature should be added in the next version.

**Comment by haofanurusai** [comment]
Thanks very much. By the way, wildcard characters (e.g. 192.168.31.*) or regular expression is also considerable.

**Comment by txthinking** [comment]
keep this issue open in case I forget

**Comment by txthinking** [comment]
v20230404.5.1
