### ISSUE TITLE
When deploy client on debian8 (virtual machine) , process was killed by system

### ISSUE THREAD

**Issue by exfdren** [txthinking/brook#120]
#### Describe actual behavior
When I deploy client on debian8 (virtual machine), it was always killed by system, sometime the terminal showed:
2017/11/23 07:00:37 EOF
Killed
and sometime it was killed direct dirctly:
Killed

#### Specifications like the version of the project, operating system, or hardware
server and client version are same , v20171111 , operating system is Debian8  (virtual machine), and openwrt 15.05.1 (R6300V2)
#### Steps to deploy the server
0. wget https://github.com/txthinking/brook/releases/download/v20171111/brook
1. chmod 755 brook
2. ./brook server -l :xx -p "xxxxxxxx"

#### Steps to reproduce the problem
0. wget https://github.com/txthinking/brook/releases/download/v20171111/brook
1. chmod 755 brook
2. ./brook client -t 192.168.1.11:1235 -u 192.168.1.11:1235  -s xx.xx.xx.xx:xx -p xxxxxxxx

**Comment by txthinking** [comment]
Please see #68

**Comment by exfdren** [comment]
Thanks!
But on R6300V2, it also showed EOF 
2017/11/23 07:05:44 EOF
and the VSZ is too high
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
11250  9901 root     S     777m 310%  11% ./brook_linux_arm5 client -i 192.168.
is there any problem? I am afraid that it will cause the router crash.

**Comment by txthinking** [comment]
Let us discuss in #68 :)
