### ISSUE TITLE
SOCKS5检测结果与sstap不一致

### ISSUE THREAD

**Issue by photkey** [txthinking/brook#1208]
![513aafb484f68483b57c0721e5c723f](https://user-images.githubusercontent.com/60434581/235931528-6cc1780d-4126-4104-ac5d-d83285b8560a.jpg)

![5f0351ad4d145c54ec717847a19b5d6](https://user-images.githubusercontent.com/60434581/235931568-7eafac12-e74a-4a69-a880-7eef084d6d61.jpg)

如图所示，对UDP的支持，两者测试结果不一样

**Comment by txthinking** [comment]
那得问TA
