### ISSUE TITLE
服务端和安卓客户端均更新后，速度很慢

### ISSUE THREAD

**Issue by krokyhui** [txthinking/brook#122]
服务端和安卓客户端均更新后，速度非常慢，google play刷不出来，谷歌搜索也上不了，telegram倒是能连上，但是刷消息也很慢，明明更新前速度飞快的，不知道怎么回事。

**Comment by txthinking** [comment]
可能情况太多

**Comment by txthinking** [comment]
release 下有旧版本

**Comment by krokyhui** [comment]
好的，下个旧版试试先，客户端换旧版了，服务器端也要换旧版么？

**Comment by txthinking** [comment]
是。唉，提问题都不按格式，想帮助你都不知道怎么帮。
