### ISSUE TITLE
20230606 only available on Mac App Store?

### ISSUE THREAD

**Issue by core-code** [txthinking/brook#1223]
i see no Brook.dmg has been posted with the latest release on GitHub and the download page points to the Mac App Store. 

are macOS app downloads only available on the Mac App Store from now on or will GitHub Brook.dmg downloads be provided again?

**Comment by txthinking** [comment]
For now yes. Please download from Mac App Store, because many people don't know 'Drag app from dmg to Application folder'

**Comment by core-code** [comment]
thanks for the confirmation
