### ISSUE TITLE
QUIC timeout issue

### ISSUE THREAD

**Issue by creativebastard** [txthinking/brook#1224]
I've been running brook over QUIC for a few months now. Everything runs nice and fast and stable, but I have an issue where it seems like there's a broken loop happening every so often. During this time, my connection to my brook server(s) are just stalled.

2023/05/30 17:42:26 timeout: no recent network activity
2023/05/30 17:42:27 timeout: no recent network activity
2023/05/30 17:42:28 timeout: no recent network activity
2023/05/30 17:42:28 timeout: no recent network activity
2023/05/30 17:42:28 timeout: no recent network activity
2023/05/30 17:42:28 timeout: no recent network activity
2023/05/30 17:42:28 timeout: no recent network activity
2023/05/30 17:42:29 timeout: no recent network activity
2023/05/30 17:42:30 timeout: no recent network activity
2023/05/30 17:42:30 timeout: no recent network activity
2023/05/30 17:42:31 timeout: no recent network activity
2023/05/30 17:42:31 timeout: no recent network activity
2023/05/30 17:42:31 timeout: no recent network activity
2023/05/30 17:42:31 timeout: no recent network activity
2023/05/30 17:42:31 timeout: no recent network activity
2023/05/30 17:42:31 timeout: no recent network activity
2023/05/30 17:42:31 timeout: no recent network activity
2023/05/30 17:42:33 timeout: no recent network activity
2023/05/30 17:42:34 timeout: no recent network activity
2023/05/30 17:42:34 timeout: no recent network activity
2023/05/30 17:42:34 timeout: no recent network activity
2023/05/30 17:42:34 timeout: no recent network activity
2023/05/30 17:42:35 timeout: no recent network activity
2023/05/30 17:42:35 timeout: no recent network activity
2023/05/30 17:42:35 timeout: no recent network activity
2023/05/30 17:42:35 timeout: no recent network activity
2023/05/30 17:42:35 timeout: no recent network activity
2023/05/30 17:42:36 timeout: no recent network activity
2023/05/30 17:42:36 timeout: no recent network activity
2023/05/30 17:42:37 timeout: no recent network activity
2023/05/30 17:42:37 timeout: no recent network activity
2023/05/30 17:42:37 timeout: no recent network activity
2023/05/30 17:42:38 timeout: no recent network activity
2023/05/30 17:42:38 timeout: no recent network activity

Looking online I can see some issues going back to 2022 unrelated to brook, but with the go QUIC stack, even Cloudflare's tunnel program seems to sporadically have this issue. Anything I can do or any thoughts?

**Comment by txthinking** [comment]
Maybe https://github.com/quic-go/quic-go

We look forward to this official quic implementation: https://github.com/golang/go/issues/58547

**Comment by creativebastard** [comment]
Me too! I've switched back to wss for now. Hopefully, once this gets implemented I can switch back. Thanks for the great work.

**Comment by txthinking** [comment]
[v20240214](https://github.com/txthinking/brook/releases/tag/v20240214) wait go team's quic lib
