### ISSUE TITLE
Alfred Workflow ❤️ Brook

### ISSUE THREAD

**Issue by godbout** [txthinking/brook#1228]
你好朋友！

is there a copyright or something for the use of the Brook icon/logo? i'm doing an Alfred Workflow to start my Brook VPN directly from Alfred. will be open source and free. can i use the Brook icon or do i have to use Midjourney? 😂️

here how it looks:

https://github.com/txthinking/brook/assets/121373/0a5938fd-fb68-43a2-9b68-5e3a0dbacf12

and thanks for Brook. this is one of the best shit i've used (and read. doc is awesome).

**Comment by txthinking** [comment]
It looks great. Here I declare: Anyone can use the brook icon, no matter for free or for profit purposes, as long as it does not have a negative impact on brook.

**Comment by godbout** [comment]
thank you my love.

**Comment by godbout** [comment]
@txthinking any way to easily sponsor you? even just a little? can't you do a GitHub sponsor thing?

❤️

**Comment by godbout** [comment]
sad.

**Comment by godbout** [comment]
@txthinking what's the recommended way to install Brook for the Mac? so that if there's no Brook VPN found, i'll send the user to download Brook. currently i'm sending to this: https://apps.apple.com/us/app/brook-network-tool/id1216002642\
any better URL?

xiexieni!

**Comment by godbout** [comment]
👏️👏️👏️

**Comment by godbout** [comment]
https://github.com/txthinking/brook/assets/121373/09951390-1b3b-4c62-a922-d8eb38ffa6b7

looking good. but releasing later coz i'm fucking drunk now 🤣️🤣️🤣️

**Comment by txthinking** [comment]
Really nice, Alfred workflow looks really handy

**Comment by godbout** [comment]
v1 out: https://github.com/godbout/AlfredBrook
Alfred forum post: https://www.alfredforum.com/topic/20585-alfred-brook/

i will be using it every day! thanks for your awesome work my love.

**Comment by txthinking** [comment]
https://t.me/txthinking_news/238

**Comment by godbout** [comment]
i'm just seeing now there's a Brook Plus! nice. but i'm not clear what features it adds. am i missing something?

**Comment by txthinking** [comment]
Here is a description of the menu options:

https://brook.app/#gui-documentation

And of course the omnipotent programmable features:

https://brook.app/#programmable

And Standalone Script Example

https://github.com/txthinking/bypass

And Brook Script Builder and modules

https://modules.brook.app/
https://github.com/txthinking/bypass/tree/master/modules

And some articles:

https://www.txthinking.com/talks/

**Comment by godbout** [comment]
tbh i kinda went through that in the past (and now). i guess what i'm saying is, on this page: https://www.txthinking.com/brook.html
i'd be nice to know what Brook **Plus** adds. like there's answers to some questions, but there's no description of what the sub/purchase adds lol

**Comment by godbout** [comment]
Brook. is. amazing.

**Comment by godbout** [comment]
i'm updating the Workflow to add a built in [Updater](https://github.com/godbout/AlfredWorkflowUpdater) so that people can update directly from within Alfred next time. i've tried/am trying to add my Workflows to the new Alfred Gallery but i sweat too much and other things so i don't think my stuff are gonna be integrated.

**Comment by godbout** [comment]
> i'm updating the Workflow to add a built in [Updater](https://github.com/godbout/AlfredWorkflowUpdater) so that people can update directly from within Alfred next time. i've tried/am trying to add my Workflows to the new Alfred Gallery but i sweat too much and other things so i don't think my stuff are gonna be integrated.

forgot to mention, but the latest version of Alfred Brook gets updated through Alfred now, rather than having its own mechanism. easier to maintain, and entering a more tight Alfred ecosystem.

**Comment by txthinking** [comment]
[v20240214](https://github.com/txthinking/brook/releases/tag/v20240214)
