### ISSUE TITLE
Error: IPv6 is disabled on nexthop device.

### ISSUE THREAD

**Issue by nebulabox** [txthinking/brook#1229]
When use brook tproxy, met the following error:
```
./brook tproxy -s wss://192.168.2.11:3001 -p xxxx --tcpTimeout 15 --udpTimeout 15 --insecure 
2023/06/10 18:15:48 Error: IPv6 is disabled on nexthop device.
exit status 2
```
The server start with command:
`/usr/local/bin/brook wssserver --domainaddress 0.0.0.0:3001 --password xxxx --cert /etc/any.crt --certkey /etc/any.key`

**Comment by txthinking** [comment]
It looks like you disabled ipv6 on your linux.

### Options 1

- Enable ipv6 on your linux
- Prefer --disableAAAA if you want

### Option 2

- --doNotRunScripts
- And run iptables by yourself, like [here](https://github.com/txthinking/brook/blob/master/tproxy_linux.go#L91-L153)
