### ISSUE TITLE
wssserver 启动不成功

### ISSUE THREAD

**Issue by sunqb** [txthinking/brook#1243]
启动命令：nohup brook wssserver --domain brook.sunqb.com:443 --password jeffysun &

启动报错如下：
TLS handshake error from 168.138.95.19:52324: acme/autocert: host "brook.sunqb.com" not configured in HostWhitelist

**Comment by txthinking** [comment]
[v20240214](https://github.com/txthinking/brook/releases/tag/v20240214)
