### ISSUE TITLE
The App Store version of  Brook has been blocked in some countries, so...

### ISSUE THREAD

**Issue by finscn** [txthinking/brook#1252]
So we need  the dmg file .
Could you pleas still supply the dmg file in github ?

Thanks.

**Comment by finscn** [comment]
need dmg :'(

**Comment by txthinking** [comment]
[v20240214](https://github.com/txthinking/brook/releases/tag/v20240214)

**Comment by finscn** [comment]
> [v20240214](https://github.com/txthinking/brook/releases/tag/v20240214)

I don't find the macos version in that page, which one ?
