### ISSUE TITLE
求恢复music

### ISSUE THREAD

**Issue by iMusi** [txthinking/brook#126]
新版没找到music，原来取消了。希望能加上，挺好用的。
用旧版的brook混淆协议可以添加music吗？服务端怎么设置呢？我刚用brook。发现wiki上的music设置没有了。

**Comment by AroKz** [comment]
那个特征太明显，作者都不用了你还觉得好。

**Comment by iMusi** [comment]
因为可以ml

**Comment by txthinking** [comment]
要使用Music, 你可以在Releases找到20171111之前的版本(服务端和客户端)
服务端 -h 有帮助信息

以下是旧的文档:

---

### What is Music

Music is a part of brook protocol, and it is optional.<br/>
Music can obfuscate/camouflage as another protocol/feature.<br/>
**It is interesting that you can define your own camouflage content**<br/>
If you specify a music on your server, you must specify same music on your client.<br/>
The client will send the music data(we call it song) first to server.<br/>
A music can be one of the builtin musics or a http(s) url or a file url.

### Builtin Music List

| Music | Created At | Updated At |
| --- | --- | --- |
| `chinamobile_sdc` | 20170316 | **20170316** |
| `chinaunicom_iread ` | 20170316 | **20170316** |
| `chinaunicom_sales ` | 20170316 | **20170316** |

### URL Music

#### http(s) music

* ep: `http://domain.com/uri`
* Brook will `GET` the url and use its response body as music.

#### file music

* ep: `file:///path/to/a/file`
* Brook will use the file content as music.

**Comment by iMusi** [comment]
好的，十分感谢

**Comment by txthinking** [comment]
的确 Music 功能可以自定义伪装，以及内置的几个music可以在某些省免流。
后来发现，大部分人都用不到或懒得用自定义伪装，以及现在各种卡都出来了，流量越来越便宜了，我就把music功能去掉了。暂不知此功能多少人仍需要，我加个label吧

**Comment by txthinking** [comment]
抱歉, 暂时关闭这个issue了.
私以为伪装必有特征, 不如尽力做到没有特征.

**Comment by thomas0008** [comment]
由于IOS9只能装brook v20170331版的客户端 它有music字段 而服务器上要装哪个版本的Brook这个IOS9才能用呢？而且这服务器上要怎么装？能否指点一下 谢谢
