### ISSUE TITLE
安卓客户端有没有API接口？

### ISSUE THREAD

**Issue by photkey** [txthinking/brook#1268]
安卓客户端 有没有API接口，可以添加、删除、切换服务器？
应用场景:安卓APP自动化，目前找的一些软件安卓客户端都没有提供API，只能用自动化脚本来实现节点的添加 删除 切换，效率低，最后寄希望于brook了，不知道有没有提供API？文档里面没找到。

**Comment by txthinking** [comment]
暂无，但有一个不知道是不是符合你需求：可以脚本指定多个服务端 in_brooklinks，运行中动态决定用哪个，或随机，或其他等等  brooklinkkey。

https://brook.app/#%E4%BC%A0%E5%85%A5%E5%8F%98%E9%87%8F%E4%BB%8B%E7%BB%8D
