### ISSUE TITLE
Cannot work on my Android device.

### ISSUE THREAD

**Issue by AroKz** [txthinking/brook#127]
#### Describe actual behavior
Firefox Nightly 59.0a1 latest release(2017-11-28),Apkpure and Telegram cannot connect Internet(cannot open any website or receive  any new message) when I use Brook on my Z17.
But I can use Wechat ,and Eleme(饿了么) as usual.
It's weird.My friend's android phone and my windows10 both are normal using. 
I have given it all the permissions it needed(just three).
#### What is your expected behavior
What should i do to make this right?
#### Specifications like the version of the project, operating system, or hardware
v20171113 release including brook,brook_windows_amd64.exe,and Brook.apk
v20171114 release including Brook.apk
Android 7.1 Nubia UI 5.0
Nubia Z17
#### Steps to deploy the server
As brook wiki said.
https://github.com/txthinking/brook/wiki/How-to-run-Brook-Server-on-Linux%3F

#### Steps to reproduce the problem
Just open Brook on my phone,lol.

**Comment by AroKz** [comment]
By the way,I have the same problem in https://github.com/txthinking/brook/issues/123.

cipher：message authentication failed

**Comment by txthinking** [comment]
Please provide steps like this issue: https://github.com/txthinking/brook/issues/124#issue-276590990

**Comment by AroKz** [comment]
Oh,sorry,i see.
***
**Steps to deploy the server**

0. `wget https://github.com/txthinking/brook/releases/download/v20171113/brook`
1. `chmod +x brook`
2. `./brook servers --tcpDeadline 0 \
        -l ":1 a" \
        -l ":2 b" \
        -l ":3 c" \
        -l ":4 d"`

**Steps to reproduce the problem**

0. `Run Brook Apk.`
1. `Choose Brook`
2. `Input "1.2.3.4:2" in the address blank.Then enter`
3. `Inuput "b" in the password blank.Then enter`
4. `Use Firefox Nightly`
***
1,2,3,4,a,b,c,d not mean the real ip or password.

**Comment by AroKz** [comment]
Damn it.Stupid Nubia UI.It blocks the Brook accessing the wifi and 4G network.The setting is in a corner that can be easily ingored.Thanks for help,fantastic work!
