### ISSUE TITLE
bypassDNS does not work when it is a private address

### ISSUE THREAD

**Issue by haofanurusai** [txthinking/brook#1298]
ENV: openwrt 22.03.5 / ipk installed / tproxy
bypassCIDR4: 172.16.0.0/12
bypassDomain: 
cn
edu
bypassDNS: 172.17.0.1
openwrt lan ip is 192.168.1.1
DNS forwarding correctly configured

PROBLEM:
1. xxx.cn (an internal domain only recorded in the internal DNS) cannot be resolved
2. nslookup xxx.cn -> no response
3. add xxx.cn to hosts -> OK
(this is not a good workaround because its ip is dynamic)
4. turn off openwrt DNS forwarding -> OK 
5. set system dns manually -> OK
(In condition 4&5, google, etc. cannot be resolved correctly as usual, as it is a polluted dns)

**Comment by txthinking** [comment]
[v20240214](https://github.com/txthinking/brook/releases/tag/v20240214)
