### ISSUE TITLE
Windows error with client config

### ISSUE THREAD

**Issue by asmadeus08** [txthinking/brook#130]
#### What is your expected behavior
Expect to see working brook client connection
#### Specifications like the version of the project, operating system, or hardware
v20171111
#### Steps to deploy the server
0. Create brook server
1. Download client and configure as it must to be 
2. Receive error

https://imgur.com/a/hpjTh
https://imgur.com/a/TYfnH

P/s i use this script on server side https://doub.io/brook-jc3/

I will be glad to see help if someone can install it manually on server side and on pc

**Comment by AroKz** [comment]
It's so so so so easy to use Brook.I cannot understand why you need the script.Maybe you should ask the author of script for help.
The steps:
1. wget https://github.com/txthinking/brook/releases/download/v20171113/brook (x64) or
    wget https://github.com/txthinking/brook/releases/download/v20171113/brook_linux_386 (x86)
2. chmod +x brook
3. ./brook server -l :这里填你的端口 -p 这里填你的密码 --tcpDeadline 0
4. Done
Background:nohup ./brook server -l :这里填你的端口 -p 这里填你的密码 --tcpDeadline 0 &
Autostart? vi /etc/rc.local Then...Google what's the rc.local

**Comment by asmadeus08** [comment]
I did the same too even with original tutorial and the same error.

**Comment by zycfcn** [comment]
建议你抛弃你的脚本，从作者的 教程开始，你将成功

**Comment by asmadeus08** [comment]
I did it manually too but still failed.

**Comment by zycfcn** [comment]
What is your server startup command?
And make sure it is up and running

**Comment by asmadeus08** [comment]
Yes i check that. All is working fine on server side and it's just doesn't work on my side at all.

**Comment by txthinking** [comment]
Maybe caused by the system language. It looks like Russian? You can change
to English or Chinese and try again.

**Comment by asmadeus08** [comment]
i though about this too but it's all about pac error.

**Comment by zycfcn** [comment]
@asmadeus08 cli client prompt you pac error?   You are using cli version of the client? What is your start command?

**Comment by asmadeus08** [comment]
Using this one https://github.com/txthinking/brook/releases/download/v20171113/Brook.exe and any of win client show the same error.

**Comment by zycfcn** [comment]
What version of windows do you use?  You can send an error message to see it?

**Comment by asmadeus08** [comment]
https://imgur.com/a/hpjTh
https://imgur.com/a/TYfnH error with that pac script.

Win 7x64

**Comment by zycfcn** [comment]
You can use Firefox to set proxy internet

**Comment by asmadeus08** [comment]
Doesnt work for any browser whole system

**Comment by txthinking** [comment]
Can your recheck `First of all` in here: https://github.com/txthinking/brook/wiki/How-to-use-Brook-Windows-Client%3F

**Comment by txthinking** [comment]
Please try latest version, it has an option to do not set system proxy.
