### ISSUE TITLE
内存占用异常，1GB的内存已经爆了，需要多少内存？

### ISSUE THREAD

**Issue by bigbigbigfish** [txthinking/brook#1304]
盒子刷机openwrt,4核心+1GB内存，最近发现，passwall里面配置brook跑起来一会就卡死。
分析原因是内存已经占满了，版本一直退到0401都一样。
brook到底需要多少内存才能跑？

![123](https://github.com/txthinking/brook/assets/9393513/64e09ff3-f493-407f-b37b-0db6f45d0e47)

**Comment by zhujingwei** [comment]
![image](https://github.com/txthinking/brook/assets/8627524/57278f69-473b-4c3d-b65b-362bf5c19502)

**Comment by txthinking** [comment]
**如果整个链无其他同类相关工具**，那么有可能 tproxy 进程 memory leak，有时间的同学可以 提供/追问 相关复现环境和复现步骤进而debug

**Comment by txthinking** [comment]
[v20240214](https://github.com/txthinking/brook/releases/tag/v20240214)
