### ISSUE TITLE
服务端是否支持开启http代理

### ISSUE THREAD

**Issue by ssrsec** [txthinking/brook#1310]
就像一键开启socks5服务端一样：joker brook socks5 --listen :1080 --socks5ServerIP 0.0.0.0 --username 'aaa' --password 'bbb'，能否开启http代理

**Comment by txthinking** [comment]
能，得两键。

```
joker brook socks5 --listen :1080 --socks5ServerIP 127.0.0.1 --username 'aaa' --password 'bbb'
joker brook socks5tohttp --socks5 127.0.0.1:1080 --socks5username 'aaa' --socks5password 'bbb' --listen :8080
```

---

**永远不要在socks5上使用 0.0.0.0 之类的IP，那样创建出来的 socks5 不支持 UDP。https://www.txthinking.com/talks/articles/socks5-and-http-proxy.article**

**Comment by ssrsec** [comment]
可是这样没办法给http代理设置密码，如果开启在互联网上就会被恶意利用了。
另外就是client-httpProxy-server会不会比client-httpProxy-socks5Proxy-server更快呢

**Comment by ssrsec** [comment]
希望能够直接一键开启http代理，并且支持认证

**Comment by ssrsec** [comment]
http代理更能方便的操作中间人数据，但是希望http加上认证

**Comment by txthinking** [comment]
[v20240214](https://github.com/txthinking/brook/releases/tag/v20240214)

**Comment by caiqy** [comment]
> [v20240214](https://github.com/txthinking/brook/releases/tag/v20240214)

所以这个功能是实现了 还是没有呢，chrome浏览器无法使用socks5的认证功能
![image](https://github.com/txthinking/brook/assets/22696948/2befb424-d174-4b16-b38a-a481b49a52e8)
