### ISSUE TITLE
GUI版本无法开启应用窗口

### ISSUE THREAD

**Issue by Orenoneko** [txthinking/brook#1313]
任务管理器可以看见应用在一直闪退重启。

process monitor工具抓取可以看到一直在重复运行power shell 、net.exe 、net1.exe
![MicrosoftTeams-image](https://github.com/txthinking/brook/assets/124866496/f25aad5f-a67e-4fea-a164-563ff9e1928e)

对比正常运行只在roaming文件夹内创建了brook的文件夹，并未创建GUI.EXE文件。

怀疑是前置工作未完成，所以没到创建GUI.EXE的步骤，同时roaming文件夹下也没有.b文件。

能否指导一下修复方式？

**Comment by txthinking** [comment]
把 Brook（2）.exe 改名一下试试，Brook.exe

**Comment by Orenoneko** [comment]
> 把 Brook（2）.exe 改名一下试试，Brook.exe

感谢您的回复，这个没有什么作用。

（2）的来源是通过edge重复下载，所以被加上了标识。

**Comment by txthinking** [comment]
之前有个问题就是，Brook（2）.exe 之类的名字会启动失败。改成 Brook.exe 之后就可以了。

我刚才试了一下 Windows 11 + [Brook.exe v2023606.5](https://github.com/txthinking/brook/releases/latest/download/Brook.exe)，正常。

你可以试试删除这个目录  AppData/Roaming/.brook.20230606.5 再重新运行一下 Brook.exe

**Comment by Orenoneko** [comment]
> 之前有个问题就是，Brook（2）.exe 之类的名字会启动失败。改成 Brook.exe 之后就可以了。
> 
> 我刚才试了一下 Windows 11 + [Brook.exe v2023606.5](https://github.com/txthinking/brook/releases/latest/download/Brook.exe)，正常。
> 
> 你可以试试删除这个目录 AppData/Roaming/.brook.20230606.5 再重新运行一下 Brook.exe

感谢您的回复。
这个目录已经清除了。重新运行只生成了文件夹，没有内含的文件。
我个人感觉是net1在判断网络状态时一直不过关，所以就没有进行下一步操作了。

**Comment by txthinking** [comment]
嗯调用了
```
net session
```

要不试试再cmd里启动下 Brook.exe

```
rm -rf ~/AppData/Roaming/.brook.20230606.5
cd /path/to/
./Brook.exe
```
或者管理员权限打开 cmd

```
rm -rf ~/AppData/Roaming/.brook.20230606.5
cd /path/to/
./Brook.exe
```
我不熟悉 cmd 下如何写命令，上面命令是按照git bash环境下的写的，可自行转换。

**Comment by Orenoneko** [comment]
> 嗯调用了
> 
> ```
> net session
> ```
> 
> 要不试试再cmd里启动下 Brook.exe
> 
> ```
> rm -rf ~/AppData/Roaming/.brook.20230606.5
> cd /path/to/
> ./Brook.exe
> ```
> 
> 或者管理员权限打开 cmd
> 
> ```
> rm -rf ~/AppData/Roaming/.brook.20230606.5
> cd /path/to/
> ./Brook.exe
> ```
> 
> 我不熟悉 cmd 下如何写命令，上面命令是按照git bash环境下的写的，可自行转换。

感谢您的建议。
我试试看。

**Comment by Orenoneko** [comment]
> 嗯调用了
> 
> ```
> net session
> ```
> 
> 要不试试再cmd里启动下 Brook.exe
> 
> ```
> rm -rf ~/AppData/Roaming/.brook.20230606.5
> cd /path/to/
> ./Brook.exe
> ```
> 
> 或者管理员权限打开 cmd
> 
> ```
> rm -rf ~/AppData/Roaming/.brook.20230606.5
> cd /path/to/
> ./Brook.exe
> ```
> 
> 我不熟悉 cmd 下如何写命令，上面命令是按照git bash环境下的写的，可自行转换。

作者您好，尝试CMD也无法开启应用，但是已经找到问题所在了。感谢您的关心。

最终原因是，操作系统的“server”服务（service.msc）停止了，服务名称：LanmanServer，显示名称server。
这个可能导致了端口不通，net1检测不过关的问题。
