### ISSUE TITLE
no connection anymore when located in China?

### ISSUE THREAD

**Issue by godbout** [txthinking/brook#1314]
been using Brook for the last 6 months when i'm in China without any issue. server is in Singapore. but those past days i haven't been able to get to the Internet. the server is reachable even without VPN, the Brook VPN connection is ON, but no Internet. as soon as i'm out of China it works. any idea what i can do to debug? 辛苦了

**Comment by godbout** [comment]
> the server is reachable even without VPN, the Brook VPN connection is ON, but no Internet.

ok to precise on this, actually i can't ping from China. but i seem to be able to connect to the server via Brook? but no Internet. when Brook is connected i can ping the server lol

**Comment by godbout** [comment]
and like GitHub is accessible in China without a VPN now? lmao

**Comment by godbout** [comment]
> https://t.me/txthinking_news/185 and whether it's VPS or Cloud, they often adjust routes, for many reasons, possibly due to costs. by [unknown](https://t.me/txthinking)

thanks. fair. yeah Vultr sg. crying a bit for now. will find a solution hehe. thanks again for the hard work!

**Comment by godbout** [comment]
so yeah, created a new server, resintalled and opened port and boom, on again. i guess until i use the server a bit too much...

**Comment by godbout** [comment]
谢谢男朋友。辛苦了！

**Comment by godbout** [comment]
new server blocked already 哈哈哈哈哈哈哈哈哈哈

**Comment by txthinking** [comment]
I never use vultr ip and others cheap and many people used. a tip is try let it behind aws or other videos in the list:
https://www.youtube.com/watch?v=4jGrUps4eTg&list=PLwDQR8zI95UpfGE0CgDxwBew0yu-s1hIK&index=3&pp=gAQBiAQB

**Comment by godbout** [comment]
> I never use vultr ip and others cheap and many people used. a tip is try let it behind aws or other videos in the list: https://www.youtube.com/watch?v=4jGrUps4eTg&list=PLwDQR8zI95UpfGE0CgDxwBew0yu-s1hIK&index=3&pp=gAQBiAQB

i see. hmm. may need to review my VPS strategy then. i have a lifetime from VPN Unlimited too. been using for ages and it works well, but for sure slower than own instance. although they do provide own instances for like 20USD a month. but Brook is so easy and fun to use through nami, joker, jinbe and Alfred 😂️
