### ISSUE TITLE
Where could download macos version ? 

### ISSUE THREAD

**Issue by finscn** [txthinking/brook#1316]
There is no Brook  in  the  Mac App Store of China .

Where could download macos version  (.dmg) ?

**Comment by txthinking** [comment]
[v20240214](https://github.com/txthinking/brook/releases/tag/v20240214)

**Comment by finscn** [comment]
> [v20240214](https://github.com/txthinking/brook/releases/tag/v20240214)

I don't find the macos version in that page, which one ?

brook_darwin_arm64 is not a GUI app

**Comment by JarvanMo** [comment]
Hey, it's not easy to get US apple id. Is there any easy approach to get GUI client for macOS?
