### ISSUE TITLE
一些简单的建议，希望作者能看到

### ISSUE THREAD

**Issue by Sunser** [txthinking/brook#132]
使用brook 已经有1个月之久了写一些小小的建议望采纳

1. 现有的程序只支持后缀增加启动参数来启动，希望能有一个引用配置文件功能

2. 现有的 relay 模式以及 socks5 模式 个人觉得完全可以剔除 主要原因 在国内这个大网环境下很多劫持之类的效果并不是很理想

3. 希望能支持 shadowsocksR 模式 以及可以出一个类似 SSTAP 的客户端来解决代理玩网络游戏的需求。这个估计很多人都需要

4. IOS/Android 客户端 密码星号显示，以及多服务器选择，或者能记录历史增加的记录，避免每次切换服务器都是手工输入。

5. 客户端建议可以自定义 PAC 或者 在线 pac 可供选择 ，PC端 默认是走的全局模式，手机端 默认只走 GFWlist 列表 这些特殊的情况，无法满足

6. (纯属个人喜好)客户端中的版本号和联系邮箱，可以单独弄个关于按钮 把一些须知 联系方式以及版本信息等描述过长的内容放置进去。让客户端更简洁更美观

7. 希望大佬能开设个QQ 群便于小伙们交流

8. 希望能有个日志等级功能 输出日志并保存以便 解决错误或者浏览记录等消息

**Comment by auroneboss** [comment]
我觉得用命令行可以接受，主要还是功能需要再完善一些。例如ipv6和局域网的支持，我这里对这两个是硬性要求。。。

**Comment by DavidCai1993** [comment]
同希望客户端支持 PAC ~

**Comment by txthinking** [comment]
Sorry, I just close this.
Please one issue one topic.
https://github.com/txthinking/brook/blob/master/.github/CONTRIBUTING.md
