### ISSUE TITLE
Cannot get local link ipv6 from tun

### ISSUE THREAD

**Issue by Hosseinht** [txthinking/brook#1339]
I get this error:

Error
Cannot get local link ipv6 from tun

**Comment by txthinking** [comment]
I think the latest windows OS support ipv6 stack default, even if your network does not support ipv6, it will give every interface a link local address, I guess.

https://www.txthinking.com/ai/share.html?id=1&session=757bb041-79b7-4be1-b526-0477821223a8

**Comment by Hosseinht** [comment]
Thank you. It fixed
IPv6 was disabled in the registry.
