### ISSUE TITLE
Weird: Can't work with WIFI under my Android phone

### ISSUE THREAD

**Issue by padicao2010** [txthinking/brook#134]
#### Describe actual behavior

With WIFI and a shadowsocks server, Brook android app can start, but the browser cannot cross the wall and shows "Cannot connect to the server".

However, with 4G of China Unicom, it works well.  

The statistics of the connection shows that, size of the received bytes is about 12KB, and it hardly grows.

I also try the brook server, it presents the same.

[shadowsocks/shadowsocks-android](https://github.com/shadowsocks/shadowsocks-android) works well under both WIFI and 4G.

#### What is your expected behavior

Brook android app should works well under WIFI.

#### Specifications like the version of the project, operating system, or hardware

Brook: v20171113

Shadowsocks server: shadowsocks-libev 3.0.8

Android: 7.1.2 (Meilan Note 6)

#### Steps to deploy the server

0. ss-server -u -c config.json

```
{
    "server":"0.0.0.0",
    "server_port":xxxx,
    "local_address":"127.0.0.1",
    "local_port":xxxx,
    "password":"xxxx",
    "timeout":300,
    "method":"aes-256-cfb"
}
```

#### Steps to reproduce the problem

0. Connect to server with Brook android app
1. Browser youtube.com

**Comment by txthinking** [comment]
If you use shadowsocks protocol on Brook Android, your shadowsocks server must full support UDP

**Comment by padicao2010** [comment]
It works well under 4G of China Unicom so I think the server supports UDP.

**Comment by txthinking** [comment]
Sorry I can't help you. Brook Android Client, must need your server support full UDP.
You can try $ brook server or $ brook ssserver.
If it works in your 4G, that means your server and your client are set correctly.
It not works in your wifi, I think this maybe caused by your wifi network, router or ISP about UDP block or other somthing.
