### ISSUE TITLE
How to configure on android app?

### ISSUE THREAD

**Issue by ctpxyza** [txthinking/brook#1340]
I have configured a brook server, and it works well, i also have a linux client, it also works.
But now i install a new boork android app(V20240404)， it's not work.

linux client link:  /usr/bin/brook client --socks5 127.0.0.1:1080 -s xxxxxxx:8859 -p pwd

android app:
 type : book server  
server  xxxxxxx:8859  
all model disable by default, brook plus have ordered.
result : link test ok, but after connect, no link can open
email:ctpxyza@foxmail.com

**Comment by txthinking** [comment]
I think there no big difference with prev version on Client-side CLI and GUI. I uninstall and reinstall apk just now, and it works well.

1. Is there any ERROR log in the Activity?
2. Does your server support IPv4 or IPv6 or both?
3. Does your local support IPv4 or IPv6 or both?
4. Your server is IPv4 or IPv6 or domain?
5. After connected, how about Echo Client, Test IPv4, Test IPv6 result? try multiple times
6. If you are in china, in recent days, there may be a lot of fluctuations in international routes.

If this is the first time you are using android client, checkout 1-5. Otherwise if v20240214 apk works, but v20240404 apk does not work, checkout 6, or try again v20240214? maybe.

**Comment by ctpxyza** [comment]
1.[activity_log.txt](https://github.com/txthinking/brook/files/14518385/activity_log.txt)
2.server is only ipv4
3. local support all
4.server support all
5.After connect, android app is not stable, st link is ok, st is not, Before the paid Android version, it was relatively stable. Compared to the Linux PC client (free), there were basically no issues with connections failing to open.
6.linux pc client works well, both are in same network.
7.I noticed this issue a long time ago when using the Android app, as the app had a hard time connecting, but the PC client had no problems. So I always thought I needed to pay to resolve it. Recently, I paid for it urgently, but I still encountered the issue. Therefore, I'm not sure if it's related to the configuration. By default, all modules are turned off. Currently, I've manually enabled "Bypass China Domain" and "Bypass China Domain A," but I'm unsure if there are any other configurations that need to be enabled.

Thanks for your help.

**Comment by txthinking** [comment]
If your type domain.com:8859, and if your domain has A and AAAA, it may choose AAAA record, this means prefer connect to your IPv6 IP

If your server does not support IPv6, you may this https://www.txthinking.com/talks/articles/brook-fakedns-en.article, and enable block google secure DNS module, and enable block AAAA module. Then you should not see v6 IP on Activity.

someone said it's android ROM need to set DNS on system side manually, but I don't know the ROM, I just developed and tested on google pixel.

**Comment by ctpxyza** [comment]
> If you type domain.com:8859, and if your domain has A and AAAA, it may choose AAAA record, this means prefer connect to your IPv6 IP
> 
> If your server does not support IPv6, you may this https://www.txthinking.com/talks/articles/brook-fakedns-en.article, and enable block google secure DNS module, and enable block AAAA module. Then you should not see v6 IP on Activity.
> 
> someone said it's android ROM need to set DNS on system side manually, but I don't know the ROM, I just developed and tested on google pixel.

after close system secure dns, it seems works, thank you very much.

**Comment by txthinking** [comment]
v20240606 released
