### ISSUE TITLE
Operation not permitted when try to raise UDP Receive Buffer Size

### ISSUE THREAD

**Issue by codeskyblue** [txthinking/brook#1341]
Help wanted. How to fix
```bash
2024/03/08 14:30:31 {"warning":"kern.ipc.maxsockbuf: 3014656\nsysctl: kern.ipc.maxsockbuf=3014656: Operation not permitted\n","when":"try to raise UDP Receive Buffer Size"}
```

**Comment by txthinking** [comment]
This is a warning, you can ignore it.

more:
this is only for quicserver, you can run with root to let it do not print this message. 
But I know, the code print the message even if your server is not quicserver, this should be fixed in next version.
