### ISSUE TITLE
testsocks5 udp测试总是请求到127

### ISSUE THREAD

**Issue by dongziyudongziyu** [txthinking/brook#1351]
![屏幕截图 2024-04-26 134014](https://github.com/txthinking/brook/assets/48708932/342bdc6f-1723-4db3-acce-e1d139b2b022)

最后一行日志
read udp 127.0.0.1:37200->127.0.0.1:1090: read: connection refused

为什么不是请求到目标主机？

**Comment by txthinking** [comment]
简单讲：你的 server(192.168.50.118) 告诉 client(brook testsocks5) 它的 UDP dst 是 127.0.0.1:1090

可能你的 server 的实现不标准，或 在NAT之后但又没有给你提供手动指定其 UDP dst 的能力 或 你没指定。

https://www.txthinking.com/talks/articles/socks5-and-http-proxy.article

**Comment by dongziyudongziyu** [comment]
好的 已经改好
