### ISSUE TITLE
Device or app installation identifier along side with token for userAPI

### ISSUE THREAD

**Issue by cornzzy** [txthinking/brook#1355]
Hope you have a good day. `--ipLimitMax`  can cause many false positives and false negatives:

Let's consider setting the IP limit to 3.

False Negative Example:
An office floor with 20 computers sharing the same IP address.

False Positive Example:
A user on their phone while driving, experiencing frequent IP changes.

To address these issues, Brook could send an additional identifier, such as an ID generated during installation or a hardware ID. This solution would work as follows:

1. Each time Brook sends a new identifier to the user management API, it is saved.
2. If the list of identifiers exceeds 3, the oldest identifier is removed.
3. If an old identifier tries to use the service, the API will respond with a non-200 status code.
4. If the identifier is still in the pool or the pool has not yet reached the limit of 3, the API sends a 200 response as usual.

This is also how [ivpn](https://www.ivpn.net/) handles user limitations.

**Comment by txthinking** [comment]
It may be considered, but it may also involve sensitive issues. A more
common method is to limit the traffic for each user, and the goods sold to
users are traffic.

**Comment by cornzzy** [comment]
Thank you for your response.

I have another question: I have experience with Flutter and want to write a simple Brook client GUI app for both Android and iOS. How much of the work is already done, and what tasks will I need to handle myself?
