### ISSUE TITLE
[求助]在ubuntu server 中使用cli client翻墙没效果

### ISSUE THREAD

**Issue by lsx1994** [txthinking/brook#1359]
版本：
v20240606   brook_linux_amd64

命令：
./brook client -s="ip:port" -p="密码" &

然后在Ubuntu服务器上执行 ping www.google.com  还是连不上。  还需要设置什么吗？

服务器是没问题的， 我使用安卓版brook客户端可以正常翻墙。

**Comment by lsx1994** [comment]
配置 --http即可

**Comment by txthinking** [comment]
此文章可以回答 https://www.txthinking.com/talks/articles/socks5-and-http-proxy.article 

还有 https://github.com/txthinking/tun2brook
