### ISSUE TITLE
How to transparently transmit dns requests if socks supports udp

### ISSUE THREAD

**Issue by eric-gitta-moore** [txthinking/brook#1366]
How to transparently transmit dns requests if socks supports udp?

like this: [With Brook: Fake DNS Off ](https://github.com/txthinking/brook?tab=readme-ov-file#with-brook-fake-dns-off)

I don't seem to see any buttons on the app to set

**Comment by txthinking** [comment]
Just choose Fake DNS off, it will treat dns request as a normal request

**Comment by eric-gitta-moore** [comment]
> Just choose Fake DNS off, it will treat dns request as a normal request. the GUI path: home page - `DNS` button - Fake DNS - Off

Oh, oh, I see. I see. Thank you very much. But this is supposed to be a brook plus feature. Unfortunately I can't navigate to the dns Settings page.
