### ISSUE TITLE
IPv6 connecting problems

### ISSUE THREAD

**Issue by jam178945** [txthinking/brook#140]
#### Describe actual behavior
The server address can only be set to an IPv4 address.

#### What is your expected behavior
Support both IPv4 and IPv6.

#### Specifications like the version of the project, operating system, or hardware
v20171112, iOS 11.2.1

#### Steps to deploy the server
- The server has an IPv6 address
- Start Brook server with `brook server -l :port -p :password`
- It can be found by `netstat` that the Brook server listens on tcp6.

#### Steps to reproduce the problem
- Start iOS client with `server_ipv6_address:port`, it will start with no Internet connections.
- The client cannot be started if it starts with `[server_ipv6_address]:port` or `"server_ipv6_address":port`.
- If the server address is set to a domain which is resolved to an IPv6 address, the same thing will happen (start with no Internet connections).

**Comment by auroneboss** [comment]
yeah... I have the same problem. But I found that if i started brook at my window and linux pc using a domain which is resolved to  an IPv6 address, it worked. But ,not android and ios.

**Comment by bitkylin** [comment]
I also really like to use IPv6 to connect brook, but I don't know what I should do. Who could give me a answer ?

**Comment by txthinking** [comment]
Please follow #109
