### ISSUE TITLE
Request chrome extension support

### ISSUE THREAD

**Issue by phoebek17** [txthinking/brook#141]
你好，请求开发支持chrome的扩展以用在chrome OS上面，感恩你的付出让我们有这么好的软件可以用，非常感谢！

**Comment by phoebek17** [comment]
SwitchSharp 只是一个管理代理插件啊，不是需要前端先运行代理程序来配合吗，比如SS，现在这个前端没有，我指的是支持chrome OS。

**Comment by phoebek17** [comment]
我意思是支持chrome OS的Brook chrome app，而不是指用于Windows下的chrome浏览器。SS就有SS chromeapp 可以安装在chrome OS上面。

**Comment by txthinking** [comment]
Now ChromeOS can install Brook android client, and it works well.
