### ISSUE TITLE
the request address is not vaild in its context

### ISSUE THREAD

**Issue by Elder-Wu** [txthinking/brook#143]
![image](https://user-images.githubusercontent.com/19809616/35205050-511d44ba-ff6d-11e7-9cd7-aad15ac229a0.png)

I have try so many ip address,but all of them are failed.So which ip address can i use?

**Comment by Elder-Wu** [comment]
and question:Can this vpn auto proxy?

**Comment by txthinking** [comment]
Try  -l :8384

**Comment by txthinking** [comment]
Do you want to run server or client?
