### ISSUE TITLE
New feature wanted

### ISSUE THREAD

**Issue by SakurabaKiyoka** [txthinking/brook#144]
When i open the Brook,it automatically set to itself as system proxy[pac,but some old software dosen't support it..]. but i don't wan't to let the system proxy changed by brook,so new version, could you add a manual setting of proxy setting?
by the way,sometimes pac mode,youtube will lag,must refreshing the page to let it work...
but STD socks5 mode no problem

**Comment by txthinking** [comment]
Fixed in v20180227
