### ISSUE TITLE
小米mix2 打开白屏

### ISSUE THREAD

**Issue by helloworld19951213** [txthinking/brook#146]
**小米mix2 打开白屏**

**Comment by txthinking** [comment]
请试试 这个评论下的版本
https://github.com/txthinking/brook/issues/138#issuecomment-361149962

**Comment by helloworld19951213** [comment]
感谢回复，我自己发现了个黑操作，小米自带的分屏任务，分屏运行brook，然后 点上面的结束分屏就可以全屏使用了。

**Comment by GeekHank** [comment]
显示 屡次停止运行
