### ISSUE TITLE
Is it possible to prevent webrtc from leaking the real IP？

### ISSUE THREAD

**Issue by zycfcn** [txthinking/brook#147]
#### Describe actual behavior
When I open site  https://whoer.net , I can see my real public network IP and private IP.
#### What is your expected behavior
Does brook have a way to stop this behavior.
#### Specifications like the version of the project, operating system, or hardware
I run in Socks5
#######
Of course, I know I can turn off the webrtc functionality of the browser, but I just want to know if the proxy software can do the similar function.

**Comment by txthinking** [comment]
#117  #68  Maybe the solution. Please follow that.
