### ISSUE TITLE
Can't access website blocked by gfw

### ISSUE THREAD

**Issue by thekingofcity** [txthinking/brook#149]
#### Describe actual behavior
using IE, get INET_E_RESOURCE_NOT_FOUND

#### What is your expected behavior
use brook normally

#### Specifications like the version of the project, operating system, or hardware
Both client and server version is v20180112.
Server: Ubuntu 16.04.3 LTS (GNU/Linux 4.12.8-041208-generic i686)
Client: Win 10
ISP: China Telecom / Shanghai

#### Steps to deploy the server
Follow the instruction on wiki, also instruction at https://doub.io/brook-jc1/.
Enabled ubuntu firewall via `iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 2333 -j ACCEPT`

#### Steps to reproduce the problem
0. Start server
1. Follow the instruction on wiki starting the client.
2. Open IE, visit google
3. Get 
    `There was a temporary DNS error. Try refreshing the page.`
    `Error Code: INET_E_RESOURCE_NOT_FOUND`

PS: No error on server side. However I do get
    `2018/01/30 11:07:50 cipher: message authentication failed`
after change the password on server without change on client, which I guess the client can connect to server but somehow I can't access Google.

**Comment by nuclearn** [comment]
looks like a DNS error

**Comment by txthinking** [comment]
Did you try Chrome?

**Comment by thekingofcity** [comment]
Definitely, Chrome with SwitchyOmega return a similar error like IE saying DNS error.

**Comment by txthinking** [comment]
> 2018/01/30 11:07:50 cipher: message authentication failed

Usually your password is wrong

**Comment by thekingofcity** [comment]
However I do get
     2018/01/30 11:07:50 cipher: message authentication failed
after change the password on server without change on client.

After password was changed to correct one, no message appear so I have no idea what went wrong.
