### ISSUE TITLE
Android客户端异常

### ISSUE THREAD

**Issue by Ryanforfun** [txthinking/brook#151]
大概从这个月15号开始，我的Brook安卓客户端无法正常使用，要么连不上，要么时断时续，速度不稳定。而同时，我的windows和IOS客户端一切正常，请问有其他用户反正这一问题吗？

我目前在两个安卓手机上做了测试，都不行。
设备1：红米NOTE4X  系统:MIUI8.5稳定版(Android版本6.0)
设备2：魅族MX2 系统：Flyme OS 4.5.7.1A（Android版本5.0.1）

**Comment by TempXman** [comment]
新部署的server，Brook安卓客户端也不正常，和楼上一样，要么连不上，要么时断时续，速度不稳定。windows端正常。

nexus 5   6.0.1版本

**Comment by GeekHank** [comment]
我的小米6也无法正常使用 无界面

**Comment by SkyBridge007** [comment]
我的mi6 是正常的，就是界面出来的慢一点。

**Comment by Ryanforfun** [comment]
我重新下载了一个20171114版本的BROOK 现在恢复正常了，大家可以试试。
