### ISSUE TITLE
Successfully accessed blocked websites via Chrome, but failed in Edge and IE

### ISSUE THREAD

**Issue by Chunhaozou** [txthinking/brook#152]
im now using brook version 20180112
![image](https://user-images.githubusercontent.com/25983648/35730789-5f0476ae-084e-11e8-8c82-e2a69522f998.png)
as u can see, i can access google via chrome 
![image](https://user-images.githubusercontent.com/25983648/35730813-71684a64-084e-11e8-817a-31eb4512f388.png)
but this attempt failed in microsoft edge
![image](https://user-images.githubusercontent.com/25983648/35730922-d4ce5d8c-084e-11e8-806c-00fbf54abbcd.png)
and so did ie
![image](https://user-images.githubusercontent.com/25983648/35730946-e76fadec-084e-11e8-8681-dc02b1c54dfb.png)
but i havent changed any internet options!
im using default dns, default lan settings and default hosts file
other proxies or vpns like shadowsocks are not on 
so it seems strange...

plus, i found brook local settings page isnt  functioning in ie, but in edge it is

**Comment by txthinking** [comment]
Please don't share your server IP/port/password, I just removed for you

**Comment by txthinking** [comment]
Brook Client do:

* Create a socks5 proxy: socks5://local.txthinking.com:1080 (If IPv4 it also: 127.0.0.1:1080)
* Create pac served by HTTP: http://local.txthinking.com:1980/pac
* Set system proxy(IE) with pac address(Chrome use this configuration)

For now, I don't know why IE/Edge ignore the system proxy.

**Comment by basten1899** [comment]
using EDGE can not open "http://local.txthinking.com:1980 " , that's the reason

**Comment by txthinking** [comment]
Please love to use Chrome/Firefox. :)

**Comment by txthinking** [comment]
It looks like Edge does not support socks5 proxy on PAC. You can try Brook cli version with HTTP proxy and customize PAC.
