### ISSUE TITLE
Local connections

### ISSUE THREAD

**Issue by hybtoy** [txthinking/brook#154]
#### Describe actual behavior
Can not access local website with turn on brook
#### What is your expected behavior
Bypass local connections
#### Specifications like the version of the project, operating system, or hardware
Android & iOS
#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.
1.
2.

Is there anyway to bypass brook for local connection? 
192.168.0.0/16
10.0.0.0/8
127.0.0.1/8
172.16.0.0/16

**Comment by txthinking** [comment]
Fixed in 20180401
