### ISSUE TITLE
brook 能否支持局域网其他 PC 链接？

### ISSUE THREAD

**Issue by wmjlxl** [txthinking/brook#159]
#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.
1.
2.
------------

服务端
brook ssserver -l :9999 -p password

客户端
brook ssclient -l 127.0.0.1:1080 -i 127.0.0.1 -s server_address:port -p password

vps 和 mac 下分别用上面的命令可以很好的运行，但是局域网内的其他PC 想通过mac 的 brook来上网却不行，请问有是不支持还是需要特别的设置？

还有个问题就是 Surge for Mac 下用不到 brook 生成的 socks5 代理。

谢谢。

**Comment by txthinking** [comment]
If your LAN IP is 192.168.1.2, try:
$ brook ssclient -l 192.168.1.2:1080 -i 192.168.1.2 -s server_address:port
-p password

**Comment by wmjlxl** [comment]
i tried both on NAS and Mac. it didn't work.

**Comment by ifixupit** [comment]
try
$ nohup ./brook ssclient -l 0.0.0.0:1080 -i 0.0.0.0 -s server_address:port -p password > /dev/null 2>&1 &

127.0.0.0 only allowed locahost connect

**Comment by txthinking** [comment]
@ifixupit About -i https://github.com/txthinking/brook/issues/96#issuecomment-343127726
