### ISSUE TITLE
Some problems of linux amd64

### ISSUE THREAD

**Issue by Kinfedge** [txthinking/brook#160]
#160 When brook start default with sock5, it shows that

brook client -l 127.0.0.1:1080 -i 127.0.0.1 -s serverIP:port -p password
2018/02/08 10:38:11 Invalid Version
2018/02/08 10:38:11 Invalid Version
2018/02/08 10:38:11 Invalid Version
2018/02/08 10:38:11 Invalid Version
2018/02/08 10:38:11 Invalid Version

**Comment by txthinking** [comment]
Please confirm your application supports socks5.
