### ISSUE TITLE
getsockopt: connection timed out

### ISSUE THREAD

**Issue by waini1110** [txthinking/brook#161]
#### Describe actual behavior
I installed brook , But the speed is very slow
#### What is your expected behavior
Comparing the speed of v2ray, I hope they are the same.
#### Specifications like the version of the project, operating system, or hardware

CPU model            : QEMU Virtual CPU version (cpu64-rhel6)
Number of cores      : 1
CPU frequency        : 2199.998 MHz
Total size of Disk   : 13.5 GB (1.8 GB Used)
Total amount of Mem  : 982 MB (32 MB Used)
Total amount of Swap : 2047 MB (0 MB Used)
System uptime        : 0 days, 1 hour 2 min
Load average         : 0.00, 0.00, 0.00
OS                   : Ubuntu 16.04.3 LTS
Arch                 : x86_64 (64 Bit)
Kernel               : 4.14.18-041418-generic
Brook : v20180112
#### Steps to deploy the server
0. from github get the brook  
1. and run the server ,brook server -l :2333 -p password
2. ufw ebable and allow the 2333 port

#### Steps to reproduce the problem
0. The speed of the Internet is very slow
1. show the log,  
    2018/02/08 17:42:48 dial tcp 216.58.217.196:443: getsockopt: connection timed out
    2018/02/08 17:59:35 dial tcp 216.58.217.196:443: i/o timeout

Please check this issue. Thanks

**Comment by txthinking** [comment]
Thank you.
Based this `2018/02/08 17:42:48 dial tcp 216.58.217.196:443: getsockopt: connection timed out`
This issue may be related to your server stability.
