### ISSUE TITLE
android 客户端无法检测到ip6

### ISSUE THREAD

**Issue by sasdsky** [txthinking/brook#162]
vps 服务端自带ip4  和 ip6，
客户端网络只有ip4 ，window ，ubuntu ，mac 用的都是Client (CLI)版，连接后都可以同时获得ip4 和 ip6支持，
android 是google play版客户端， 连接后只能检测到ip4
shadowsocks 没有这个问题，希望改进

检测网站 
http://test-ipv6.com/
http://ipv6-test.com/

**Comment by txthinking** [comment]
#109
