### ISSUE TITLE
some issues for brook

### ISSUE THREAD

**Issue by ghhk** [txthinking/brook#163]
首先感谢txthinking大神的作品，很给力！下面是我的一点建议，希望您看看
1.建议电脑可以像ss那样，可以切换代理模式，添加brook链接等。
2.安卓版本无法设置全局代理，默认是pac代理模式。
3.安卓版本建议添加通知栏流量显示工具。

**Comment by hybtoy** [comment]
Hide password in Android app, for security reasons.

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/blob/master/.github/CONTRIBUTING.md
