### ISSUE TITLE
IOS版本在系统设置界面中的配置显示是错误的

### ISSUE THREAD

**Issue by xtons** [txthinking/brook#164]
#### Describe actual behavior
不管在Brook界面中如何修改配置，但在设置->通用->VPN->Brook中查看的类型始终是Brook，服务器始终是local.txthinking.com

#### What is your expected behavior
希望能正确显示在Brook界面中的设置

#### Specifications like the version of the project, operating system, or hardware
在我的iphone 5S与6S上均有此情况。IOS版本均为11.2.5

**Comment by txthinking** [comment]
Here is not your server information. Don't care this.
