### ISSUE TITLE
How to run brook server mode in windows?

### ISSUE THREAD

**Issue by 5points** [txthinking/brook#165]

**Comment by txthinking** [comment]
You may need download windows cli version: https://github.com/txthinking/brook/releases/download/v20180112/brook_windows_amd64.exe

and run with windows CMD.(If need please google it)

**Comment by 5points** [comment]
Thx your report.
I have a question , i use setup client for windows feel not good , could you make simple client again?(like version20180112) thank a lot

**Comment by txthinking** [comment]
v20180112 is still available, you can find it on https://github.com/txthinking/brook/releases

**Comment by 5points** [comment]
thank you .
I still use this version of client , i  have a question you would like to ask , Will future updates be as simple as this version , without of setup? 
thank a lot
