### ISSUE TITLE
客户端能否调节全局和PAC模式呢？

### ISSUE THREAD

**Issue by Sharkkkk** [txthinking/brook#167]
客户端能否调节全局和PAC模式呢，默认全局太耗服务器流量了，而且速度也很慢。希望作者能添加这个功能，谢谢！

**Comment by zzh1290** [comment]
@Sharkkkk  逗比根据地上有个 易语言类似ssr客户端的，满足你这个需求

**Comment by Sharkkkk** [comment]
@zzh1290 希望作者直接加上，更喜欢原生，，，，

**Comment by txthinking** [comment]
目前默认的是内置白名单模式，非全局模式。
等不太忙了，会把自定义规则加上的 :)

**Comment by txthinking** [comment]
Please track #54
