### ISSUE TITLE
Android 7.1.1  运行客户端页面空白，无任何IP、端口填写处

### ISSUE THREAD

**Issue by taozi9** [txthinking/brook#168]
#### Describe actual behavior
安装安卓客户端，并打开运行，客户端页面空白，无任何IP、端口填写处
#### What is your expected behavior
打开页面，填写IP+端口，正常运行
#### Specifications like the version of the project, operating system, or hardware
版本：20180112  操作系统：Android 7.1.1   
#### Steps to deploy the server
0. NO
1. NO
2. NO

#### Steps to reproduce the problem
0. 打开并运行安卓客户端
1. 运行成功，页面显示为空白，无任何IP、端口填写处
2. 退出清理数据并重新运行，仍是空白页面，无任何IP、端口填写处

**Comment by txthinking** [comment]
#138
