### ISSUE TITLE
arm7 client error:  syntax error: unexpected word (expecting ")")

### ISSUE THREAD

**Issue by zxy95** [txthinking/brook#170]
Describe actual behavior: 
在梅林路由中运行 brook arm7 客户端，错误 error:  syntax error: unexpected word (expecting ")")
What is your expected behavior：

Specifications like the version of the project, operating system, or hardware：
梅林， arm7
Steps to deploy the server:
Steps to reproduce the problem:

**Comment by psyvirgin** [comment]
兄弟，你的arm7是如何安装的，这个下载的文件没后缀名，不知道怎么安装的
