### ISSUE TITLE
It's blank on MX6.

### ISSUE THREAD

**Issue by andyliu24** [txthinking/brook#173]
#### Describe actual behavior
Download from Play store and open it.
It's blank and i can do nothing.
![s80222-030102](https://user-images.githubusercontent.com/24978668/36499898-973be4e2-177d-11e8-8173-69663d59a249.jpg)

If I download apk file directly and try to install it, it will be failed.
![s80222-025723](https://user-images.githubusercontent.com/24978668/36500340-0592f196-177f-11e8-98e1-c83ee76a1f31.jpg)
By the way, other apk files can install properly and will not be forced to install from the store.

#### What is your expected behavior
It works!

#### Specifications like the version of the project, operating system, or hardware
![s80222-030356](https://user-images.githubusercontent.com/24978668/36499872-889ad556-177d-11e8-8cca-fcf55db4e1af.jpg)
- Phone: Meizu MX6.
- Flyme Version: 6.2.5.0A
- Android Version: 7.1.1

**Comment by qingmui** [comment]
I have the hash data so you can compare with it.
Brook.apk
MD5：	0D05AFC2C4D0FFFEF70A37DAF64CD711
SHA1：	28CB2CCD2AA9840350DCE14A337DF46A10ADA85B
CRC32：8662C558

Some times I have the same blank issue, but I force close it, and re-open again. it works.
Don't know if that helps.
Good Luck.
