### ISSUE TITLE
Provided local IP address in  `-l` option,Why we need  `-i`option ?

### ISSUE THREAD

**Issue by ihipop** [txthinking/brook#175]
Provided local IP address in  `-l` option,Why we need  `-i`option ?

#### Describe actual behavior
to Bind to `127.0.0.1:1080` we need 
`brook client -l 127.0.0.1:1080 -i 127.0.0.1 `

#### What is your expected behavior
to Bind to `127.0.0.1:1080` we  Just need 
`brook client -l 127.0.0.1:1080`
local IP is `127.0.0.1` and local port is `1080` from the string `127.0.0.1:1080` passed by `-l` option
this is no point  for   `-i`option 

#### Specifications like the version of the project, operating system, or hardware
Linux, v20180227
#### Steps to deploy the server
Irrelevant

#### Steps to reproduce the problem
Irrelevant

**Comment by txthinking** [comment]
`-i` used to tell socks5 client which UDP IP should be used
https://github.com/txthinking/brook/issues/96#issuecomment-343127726

**Comment by ihipop** [comment]
should `-i` have the default value from `-l`
eg: if `-i` is not provided and `-l` is provided as  `127.0.0.1`:`1080`,  take the value `127.0.0.1` as the default value of `-i`
