### ISSUE TITLE
Brook的socks5 在iOS上有异常

### ISSUE THREAD

**Issue by wulongji2016** [txthinking/brook#176]
你好 Brook的socks5 功能有异常。
版本：iOS 最新版 
socks 服务器已经可以翻墙，用作中转。
Brook启动socks5代理之后，
在iOS上可以登录谷歌 YouTube等。但是WhatsApp等聊天软件无法使用。
请问 这样情况 是聊天软件的问题 还是Brook的socks的问题？ 
谢谢大家！！！

**Comment by MiK-JLin** [comment]
同感觉brook的Socks5功能有异常
实测通过firefox浏览器自带的代理设置可以正常使用brook的Socks5
但是使用_SocksCap64_或者_SSTap_链接brook的Socks5代理，测试时会提示**无法通过代理服务器连接**。
使用腾讯QQ最新版客户端登录窗口中的Socks5代理测试，多次测试大都提示无法通过，偶尔几次测试成功。

**Comment by txthinking** [comment]
@wulongji2016 it's not related socks 5. Please track #177
