### ISSUE TITLE
Can't connect WhatsApp on iOS

### ISSUE THREAD

**Issue by txthinking** [txthinking/brook#177]

**Comment by eqwoot** [comment]
anyway to fix Brook on iOS so we can use WhatsApp? thanks!

**Comment by wulongji2016** [comment]
iOS：11.2.6  
SOCKS 服务器： V2ray socks5 代理中转
brook ISO ： v20180112 
协议SOCKS5

WhatsApp 和Instagram 都无法连上。
但是浏览器可以访问谷歌，可以访问YouTube。

**Comment by eqwoot** [comment]
連接不了Whatsapp的問題有辦法解決嗎?

**Comment by txthinking** [comment]
Fixed in 20180401

**Comment by dwsr36** [comment]
I cannot connect to WhatsApp now in v20180601 (iOS 11.4). I'm using brook protocol. I've tried global and whitelist mode but both of them fail to connect. Other programs such as Gmail connect to their servers correctly.

In a few network environments WhatsApp can receive messages but I've found the traffic does not go through the proxy. It seems that WhatsApp ignores all the proxy settings, including brook VPN and proxy settings of WiFi. It will connects through the proxy only when I logged in.

**Comment by dwsr36** [comment]
@txthinking I hope you can provide a solution in the next version.

**Comment by txthinking** [comment]
I have tried WhatsApp, it can connect successfully, but connection is slow.
Please try quit WhatsApp and open it again.

**Comment by txthinking** [comment]
https://i.imgur.com/tZOnDcZ.png

**Comment by wulongji2016** [comment]
测试了 几次 都是无法连接  有可能哪里有问题？

**Comment by dwsr36** [comment]
Please notice

> Sometimes WhatsApp can receive messages but I've found the traffic does not go through the proxy.

> It will connects through the proxy only when I logged in.

When I opened WhatsApp I found it ignored my proxy settings (including brook VPN and proxy settings of WiFi) because there was no brook connection in my server. Maybe your network operator does not totally block WhatsApp.

@txthinking Please check the network connections in your server when you open WhatsApp, or disable your brook VPN and try it again if you does not mind that.

**Comment by wulongji2016** [comment]
因为pac设置引起的是否走代理么？ WhatsApp不同国家的用户使用的IP不一样吧？

**Comment by wulongji2016** [comment]
![brook](https://user-images.githubusercontent.com/24681808/41843284-d2c985ce-7875-11e8-9cf8-53781d1fea59.jpg)
brook 20180601 版本 服务器和客户端都是这个版本 （20180707也测试了）
都是浏览器可以翻 ，聊天软件无法翻。

**Comment by wulongji2016** [comment]
补充一下 采用全局模式。
软件不是中国区域下载的，是不是他们走的域名不一样？

**Comment by txthinking** [comment]
Brook iOS client now only set system proxy. It looks like whatsapp ignore
system proxy.

**Comment by dwsr36** [comment]
@txthinking Maybe we need IP rules for WhatsApp

@wulongji2016 For Telegram, please see https://github.com/txthinking/brook/issues/285

**Comment by wulongji2016** [comment]
请教一下 brook和其他软件区别在哪里？ 其他软件支持WhatsApp走代理，是什么原理？

**Comment by dwsr36** [comment]
Maybe a real VPN mode can solve this problem instead of using sytem proxy? Just like Shadowrocket.

**Comment by dwsr36** [comment]
Also, now Telegram will try connecting to the server directly first in version 20180601 on iOS. It will ask for proxy settings after the connection is time out.

In my opinion, I hope the next version of Brook on iOS can change system IP rules in VPN mode. Then Telegram can connect through Brook without setting the proxy.

**Comment by georgexu78** [comment]
brook ios客户端也好久没有更新过，不知道是不是这个原因，ios无法连接whatsapp

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/issues/426#issuecomment-442312225

**Comment by txthinking** [comment]
#689

**Comment by bacontse** [comment]
路由器挂ss或者v2ray， 手机端能正常收发文字图片，电脑端web.whatsapp.com无法收发图片，但是文字可以，这种情况怎么解决？

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/wiki/How-to-run-transparent-proxy-on-Linux
