### ISSUE TITLE
Some software can not use socks5（（E.g   SocksCap64 ， SSTap

### ISSUE THREAD

**Issue by MiK-JLin** [txthinking/brook#178]
#### Describe actual behavior
Brook在本地创建的Socks5代理无法被部分软件正常连接。
#### What is your expected behavior
支持Socks5代理的软件均可正常连接Brook的Socks5代理。
#### Specifications like the version of the project, operating system, or hardware
Windows 7 x64，Brook GUI客户端及命令行客户端均已尝试
#### Details
实测通过firefox浏览器自带的代理设置可以正常使用brook的Socks5代理
使用_SocksCap64_或者_SSTap_链接brook的Socks5代理，测试时会提示无法通过代理服务器连接。

> 测试已开始...
> 地址: 127.0.0.1:1080
> 代理类型: SOCKS 5
> 用户名: [空]
> 密码: [空]
> 正在连接到代理服务器...
> 连接已建立.
> 正在测试通过代理服务器的连接...
> **通过代理服务器的连接已经失败.**
> 测试结束.

**Comment by txthinking** [comment]
There are not enough to prove to be socks5 problem.
Please try http://www.proxycap.com/download.html

**Comment by kot4ri** [comment]
已经复现了这个问题，能不能连得上全凭运气。
较大的概率会失败。
![qq 20180328125933](https://user-images.githubusercontent.com/20045613/38009659-014f90d4-3288-11e8-85bd-efc828d4e4eb.png)
![qq 20180328125956](https://user-images.githubusercontent.com/20045613/38009660-0180e54e-3288-11e8-960d-28f2a3ef2a7c.png)
![qq 20180328130007](https://user-images.githubusercontent.com/20045613/38009661-01af4614-3288-11e8-931f-e4b547c0a832.png)
