### ISSUE TITLE
The Brook client Force Closed on x 86 platform Android device

### ISSUE THREAD

**Issue by YandexStudio** [txthinking/brook#179]
It's not related to the server because it creshed at the app boot, without any configuration of server.
It might a x86 compatibility issue.
Device information:
Asus Zenfone2 (ZE551ML), Intel Atom Z3560, currently running Lineage OS 14.1(Android 7.1.2)
The Brook client was downloaded from Play Store.

**Comment by txthinking** [comment]
Please try https://github.com/txthinking/brook/releases/download/v20180227/Brook.apk

**Comment by YandexStudio** [comment]
Thanks, it works, waiting for next release on Play Store

**Comment by txthinking** [comment]
Yep, but my google play developer account has been suspended by Google, I'm
negotiating with Google. :(
