### ISSUE TITLE
请问brook如何配置IPV6

### ISSUE THREAD

**Issue by ben-august** [txthinking/brook#181]
#### Describe actual behavior
按照wiki的教程在linux服务端配置了brook（最新版20180227），并且安卓客户端可以正常连接使用。但是想配置IPV6，不知道brook如何配置，我的服务器有IPV6地址。
#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.直接将客户端地址改为我的IPV6地址无效
1.
2.

**Comment by txthinking** [comment]
#109
