### ISSUE TITLE
作者是否考虑增加路由器平台的插件

### ISSUE THREAD

**Issue by wdl214311131** [txthinking/brook#183]
因为家中多台设备需要科学上网，特别是网络电视等，因此原来用的是基于路由器平台的SSR插件。但是现在GFW封锁SSR的能力太强大了，因此不太敢用了，现在用Brook效果挺好，但是只有电脑和安卓插件，看电视这些太麻烦了。因此想请作者开发基于路由器的插件，这样方便大家，谢谢！
具体原来用的是华硕的AC1900P，用的是基于华硕原套件修改的梅林套件，然后国内有一个koolshare的网站上的作者对该套件进行的修改，增加了SSR功能，连接是该套件的hub，供作者参考！
https://github.com/koolshare/koolshare.github.io

**Comment by txthinking** [comment]
Sorry, no plan for this.

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/wiki/How-to-run-transparent-proxy-on-Linux%3F
