### ISSUE TITLE
Can a linux box run as client, tunnel & tproxy at the same time

### ISSUE THREAD

**Issue by cutemanworking** [txthinking/brook#185]
#### Describe actual behavior
Just want to build a busybox which will handle proxy, vpn and dns redirect in the same time.

#### What is your expected behavior
 Can I input multi-options in /etc/default/brook? 

#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.
1.
2.

**Comment by txthinking** [comment]
For now.
If you use binary file directly, then you can:
```
$ nohup brook client ... &
$ nohup brook tunnel ... &
...
```

If you run brook with systemd, you can create multiple service files:
```
/etc/systemd/system/brookclient.service
/etc/systemd/system/brooktunnel.service
```
Each `ExecStart` run different commands
