### ISSUE TITLE
Manage pac file by myself

### ISSUE THREAD

**Issue by Rhinocros** [txthinking/brook#186]
#### What is your expected behavior
manage pac myself, like shadowsocks，without use Proxy SwitchyOmega
#### Specifications like the version of the project, operating system, or hardware
macOS   Windows
#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.
1.
2.

I hope it's possible
Manage pac file by myself, like shadowsocks add my own via proxy URL，without use Proxy SwitchyOmega on macOS and Windows

**Comment by txthinking** [comment]
#54
