### ISSUE TITLE
Wiki里面"How to use Brook Windows Client?"下面有一处错误？

### ISSUE THREAD

**Issue by Steve789** [txthinking/brook#188]
Download Brook.Setup.exe for **MacOS** 

另外小小的建议：
1.客户端支持中文。
2.第一次配置好服务之后打开客户端默认开启服务。而不是现在每次开启客户端后手动开启。

**Comment by txthinking** [comment]
Yes, that's a mistake, thank you.

**Comment by txthinking** [comment]
Please one issue one topic. Thank you :)
https://github.com/txthinking/brook/blob/master/.github/CONTRIBUTING.md
