### ISSUE TITLE
请教一下,在Windows下如何使用

### ISSUE THREAD

**Issue by benzhenzhang** [txthinking/brook#19]
我用管理员权限运行brookserver.exe,弹出框一闪就没了,不知道哪里出了问题
已有git和go的环境

**Comment by txthinking** [comment]
如果你的远端服务器是windows系统，想运行brook 服务端，需要在cmd窗口下，以命令行模式运行(和linux差不多)

如果你是在本地windows电脑运行客户端，建议下载brook windows客户端

**Comment by benzhenzhang** [comment]
如果我本地电脑想用这个翻墙上网 改如何使用

**Comment by txthinking** [comment]
请查看wiki
