### ISSUE TITLE
路由器安装brook求助

### ISSUE THREAD

**Issue by psyvirgin** [txthinking/brook#193]
#### Describe actual behavior
路由器安装brook
#### What is your expected behavior
下载了brook_linux_arm7,该如何安装，这个文件后缀名没有，如何安装？
#### Specifications like the version of the project, operating system, or hardware
华硕AC68U，小宝固件
#### Steps to deploy the server
0.服务器采用的是逗比网的一键插件，macOS和IOS可以正常访问，代码如下
1.wget -N --no-check-certificate https://softs.fun/Bash/brook.sh && chmod +x brook.sh && bash brook.sh
2.服务器平台是GCP，开放了https和http，端口和防火墙是自动开的

#### Steps to reproduce the problem
0.这个brook_linux_arm7文件没后缀名是如何安装的？
1.作者可否抽出时间写一篇linux使用的教程，我的ubuntu系统也不知道如何使用，感谢

**Comment by nuclearn** [comment]
不需要安装，使用命令即可

./brook_linux_arm7 client -l ....

**Comment by txthinking** [comment]
You may need:
https://github.com/txthinking/brook/wiki/How-to-run-Brook-Server-on-Linux%3F
https://github.com/txthinking/brook/wiki/How-to-run-transparent-proxy-on-Linux%3F
