### ISSUE TITLE
1232

### ISSUE THREAD

**Issue by TACKPAR770** [txthinking/brook#197]
#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.
1.
2.

**Comment by kataras** [comment]
What is that? Why you do that to an open-source project and a community of 3000+ developers with issues like that? This is so dissapointed, we are Programmers, we must act like Programmers, in the near future we'll be responsible for airplane crashes and people deaths if we do something wrong, please respect yourself.
