### ISSUE TITLE
brook tproxy with iptables custom rules

### ISSUE THREAD

**Issue by vongoethe** [txthinking/brook#198]
#### Describe actual behavior
透明代理设置成功 但是无法国内国外分流

#### What is your expected behavior
利用不同的ipset，使国内与国外访问分流使用
国外的ipset叫gfwlist

#### Specifications like the version of the project, operating system, or hardware
openwrt on arm5 cpu

#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.
1.
2.

请教iptables如何设置

**Comment by txthinking** [comment]
Like the description on this page: https://github.com/txthinking/brook/wiki/How-to-run-transparent-proxy-on-Linux%3F

You can add more RETURN rules like:
```
sudo iptables -t mangle -A BROOK -d 172.16.0.0/12 -j RETURN
```
e.g. You don't want China IP to be passed to BROOK

Add this https://github.com/txthinking/pac/blob/master/china_cidr.list like above command

**Comment by vongoethe** [comment]
Thanks!
another problem
It's weird here when I use rules like:
`sudo iptables -t mangle -A BROOK -d 172.16.0.0/12 -j RETURN`
then I run this command:
`iptables -t mangle -A PREROUTING -p tcp -m socket -j BROOK
iptables -t mangle -A PREROUTING -p tcp -j TPROXY --tproxy-mark 0x1/0x1 --on-port 1080`
it just stuck there and I have to reboot my router.

and when I change the command as this:
`sudo iptables -t mangle -I PREROUTING -d 172.16.0.0/12 -j RETURN`
it works just fine, what the difference?

**Comment by vongoethe** [comment]
"stuck" means I cannot ssh to that router, and I cannot web-manage that router.
but I can ping it.

**Comment by nuclearn** [comment]
Yes, i have also the problem in my openwrt route. Using the way from txthinking, the route cannot be ssh. I wish the tproxy feature can work on the nat table (using REDIRCTED feature), just like ss-redir.

**Comment by nuclearn** [comment]
I fixed it. You just do it on your route like:

# Setup the ipset

ipset -N chnroute hash:net maxelem 65536

for ip in $(cat '/etc/chinaip.txt'); do
  ipset add chnroute $ip
done

iptables -t mangle -A PREROUTING -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A PREROUTING -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A PREROUTING -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A PREROUTING -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A PREROUTING -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A PREROUTING -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A PREROUTING -d 240.0.0.0/4 -j RETURN

iptables -t mangle -A PREROUTING -d BROOK_SERVER_IP -j RETURN

 # Allow connection to chinese IPs
iptables -t mangle -A PREROUTING -p tcp -m set --match-set chnroute dst -j RETURN
iptables -t mangle -A PREROUTING -p tcp -j MARK --set-mark 1
iptables -t mangle -A PREROUTING -p tcp -j TPROXY --tproxy-mark 0x1/0x1 --on-port BROOK_PORT

**Comment by vongoethe** [comment]
Holy shit!
You really genius!!!
work like a charm

one more question
why no udp lines? as:

`iptables -t mangle -A PREROUTING -p udp -m set --match-set chnroute dst -j RETURN
iptables -t mangle -A PREROUTING -p udp -j MARK --set-mark 1
iptables -t mangle -A PREROUTING -p udp -j TPROXY --tproxy-mark 0x1/0x1 --on-port BROOK_PORT`

**Comment by nuclearn** [comment]
Yes, you can add these lines if you require an udp proxy.

**Comment by vongoethe** [comment]
thanks
