### ISSUE TITLE
能不能提供一个编译用的总的功能开关文件

### ISSUE THREAD

**Issue by 523860169** [txthinking/brook#199]
https://github.com/v2ray/v2ray-core/blob/master/main/distro/all/all.go
类似v2ray提供的，在编译之前，通过编辑该文件，可以实现只保留某功能，比如我只想编译一个新版brook协议的，不想有ss、stream协议的，我就可以把该文件的某些行注释掉，这样编译出来的文件应该会小很多

**Comment by txthinking** [comment]
Sorry, no plan for this :(
