### ISSUE TITLE
Ths ios client is not available in China App Store

### ISSUE THREAD

**Issue by zhejianggaoxiao** [txthinking/brook#201]
#### Describe actual behavior
The ios client is not available now ( 2018-3-21 ).
![20180321152159855499890.png](http://ohfvjymgx.bkt.clouddn.com/20180321152159855499890.png)
#### What is your expected behavior
I hope you can make this client available in the AppStore of China.
#### Specifications like the version of the project, operating system, or hardware
——
#### Steps to deploy the server
——
#### Steps to reproduce the problem
——

Thanks a lot~

**Comment by txthinking** [comment]
#133
