### ISSUE TITLE
 Koolshare LED软路由中的brook安装后无法使用

### ISSUE THREAD

**Issue by qiu18** [txthinking/brook#202]
用的是Koolshare软件中心的brook，安装后路由器后的设备还是无法上国外的网，国内的正常。看下面的记录是不是防火墙部分出问题了？
root@LEDE-X64:~# /koolshare/scripts/brook_config.sh
【2018年03月21日 13:13:50】: brook符合启动条件！~
【2018年03月21日 13:13:50】: 删除 brook 相关的名单配置文件.
【2018年03月21日 13:13:50】: 关闭 brook 进程...
【2018年03月21日 13:13:50】: 关闭 redsocks2 进程...
【2018年03月21日 13:13:50】: 加载nat规则!
【2018年03月21日 13:13:50】: 尝试先清除已存在的iptables规则，防止重复添加
【2018年03月21日 13:13:51】: 先清空已存在的ipset名单，防止重复添加
【2018年03月21日 13:13:51】: 清除重复的ip rule规则.
【2018年03月21日 13:13:51】: 删除ip route规则.
【2018年03月21日 13:13:51】: 创建ipset名单
cat: can't open '/etc/config/pppoe': No such file or directory
【2018年03月21日 13:13:51】: 写入iptables规则到nat表中...
iptables v1.6.1: Set gfwlist doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.6.1: Couldn't load match `geoip':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
RTNETLINK answers: File exists
iptables v1.6.1: Couldn't load match `geoip':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
【2018年03月21日 13:13:51】: 加载ACL规则：所有模式为：大陆白名单模式
【2018年03月21日 13:13:51】: 开启chromecast功能（DNS劫持功能）
【2018年03月21日 13:13:51】: 开启 brook 主进程...
【2018年03月21日 13:13:51】: 开启 redsocks2 主进程...
【2018年03月21日 13:13:51】: 开启 dnsforwarder 主进程...
【2018年03月21日 13:13:51】: 创建国内CDN解析优化配置文件
【2018年03月21日 13:13:51】: 创建国外GFW解析优化配置文件
【2018年03月21日 13:13:52】: 创建状态检测解析优化配置文件
【2018年03月21日 13:13:52】: DNS解析方案国外优先，优先解析国外DNS.
【2018年03月21日 13:13:52】: 重启dnsmasq服务...

**Comment by txthinking** [comment]
I think you should create a issue on that project who provides `/koolshare/scripts/brook_config.sh`
