### ISSUE TITLE
Can't open setting windows

### ISSUE THREAD

**Issue by aiwonanjing** [txthinking/brook#203]
I just add my server to the windows gui client, and click save.
After it, I click the setting, but it do nothing.
I can't start it.
我账号加进去了，保存了，打不开设置按钮。点toggle，闪了一下ie然后就没了。
系统win10，浏览器默认chrome
求解决方案。

**Comment by vongoethe** [comment]
add port#

**Comment by xuyilu1986** [comment]
I encountered some problem. I added the port number but still the same problem happened.
