### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by Zokio1** [txthinking/brook#206]
#### Describe actual behavior
After clicking "toggle", the IE browser pops up and disappears.
When the client starts, it doesn't seem to work.
P.S.There is no problem in the use of the client in the Android system
#### What is your expected behavior
Access to Google in China

I am a Chinese, with a limited English level. I hope you can understand my meaning.

**Comment by Zokio1** [comment]
I change the browser (chrome) to test the client, it can works.Why the client can't be used in edge browsers?

**Comment by txthinking** [comment]
#150
