### ISSUE TITLE
About download speed

### ISSUE THREAD

**Issue by nuclearn** [txthinking/brook#208]
#### Describe actual behavior
The download speed is limited, which may be from a high CPU consumption?
#### What is your expected behavior
The problem may be solved by using a ChaCha20 encryption?
#### Specifications like the version of the project, operating system, or hardware
A route with ARM architecture
#### Steps to deploy the server
None

#### Steps to reproduce the problem
None

**Comment by nuclearn** [comment]
In my system (ARM route), the highest download speed is limited at ~40Mbps. What's happened?

**Comment by txthinking** [comment]
Please follow #223
