### ISSUE TITLE
Can't use  in the macos

### ISSUE THREAD

**Issue by alyato** [txthinking/brook#21]
i can't use it in macos. The link is `https://github.com/txthinking/brook/releases/download/v20170330/brookmacos`
it show me that 

> 未能打开文稿“brookmacos”。文本编码“Unicode  (UTF-8)”不适用

Then i set config to support it, but it doesn't work.

**Comment by txthinking** [comment]
If you need brook server for MacOS, you should:
``` 
$ mv brookmacos brook
$ chmod +x brook
$ brook -h
```

If you need brook client for MacOS, please download `Brook.app.zip`
