### ISSUE TITLE
Connection failure on Android

### ISSUE THREAD

**Issue by everxq** [txthinking/brook#213]
#### Steps to reproduce the problem
Screenshot attached 
![screenshot_20180402-014445_01](https://user-images.githubusercontent.com/26721844/38207913-ed358b68-36e1-11e8-91f4-44c5c59cf0a5.jpg)

**Comment by txthinking** [comment]
Is `‘xxx.xx.xx.xxx'` your server domain?

After you tap `Start`, Brook will query your server domain IP first.
Can your network(dns) resolve your server domain?

**Comment by zenyusy** [comment]
having the same problem.  dns resolve gives correct result.

**Comment by everxq** [comment]
xxx.xx.xx.xxx is my IP address, which is why I wiped that area.

**Comment by txthinking** [comment]
1. Is your server address which you typed in the `server input box` IP or domain?
1. If it is IP, assuming it is 1.2.3.4:5, then please type `1.2.3.4.xip.io:5` in the `server input box`, and try

**Comment by zenyusy** [comment]
changing "1.2.3.4:5" to "1.2.3.4.xip.io:5" doesn't help.

btw, the problem only occurs under my univ wifi too (no more problem when under 4G data)

**Comment by everxq** [comment]
Does not work... 
![screenshot_20180403-233117](https://user-images.githubusercontent.com/26721844/38259780-7cf2248a-3798-11e8-9cfc-9cb91ec4b05f.jpg)

**Comment by txthinking** [comment]
@zenyusy So, I think there is a problem with your wifi network.

**Comment by zenyusy** [comment]
it does resolve DN correctly (otherwise i can't even visit websites, i suppose?)
i started a Shadowsocks server on that same VPS with the same IP and SS can be connected without problem on android under my univ wifi.

**Comment by everxq** [comment]
I also have Brook and SSR configured on the same VPS, SSR works fine ( but slow ) on both Android and fine under the same network. 
As I mentioned in the beginning,  the Window version of Brook works fine , and the previous Android  version of Brook works fine as well.
