### ISSUE TITLE
博主 你的WIKI出个中文可好？

### ISSUE THREAD

**Issue by 23hp** [txthinking/brook#214]
博主好，感谢你花时间给大家做的软件。

我想给服务器装上brook，可以英文读的很别扭（英语不好 嘿嘿）。

读了几个Issues 发现博主原来是中国人 (ｷ｀ﾟДﾟ´)!!

为啥不用中文来写说明呢，慕名而来的很大一部分是中国人吧 囧

希望博主抽时间写写  方便大家使用  非常感谢

题外话，很喜欢博主的面具，V字仇杀队 有意思，嘿嘿。

**Comment by Z-fly** [comment]
教程系列请参考：https://doub.ws/dbrj-7/
可以当作中文wiki了
博主的官网说他是来自北京的全栈工程师，他对于很多中文Issues都用英文回的，做不做中文wiki全看他个人意愿了。

在我回复本Issue时，我已经无法正常访问github了。
![](https://ws1.sinaimg.cn/large/006S5Qj1gy1fq4beyunfvj30ik0bzq3d.jpg)
Good Luck.

**Comment by txthinking** [comment]
有时间了把中文wiki补上 :)
