### ISSUE TITLE
Fail to use `tproxy` on virtual machine

### ISSUE THREAD

**Issue by p24ce** [txthinking/brook#215]
I want to establish a `VPN`  or  `transparent proxy` with brook on ubuntu in VMware, so that i can download some torrents and use IRC/Telegram and share an uncensored network handily.

I run `./brook server -l :9999 -p password` on VPS firstly, then connected to ubuntu with putty, and writen a bash script:
```
#!/bin/bash

sudo sysctl -w net.ipv4.ip_forward=1
sudo ip rule add fwmark 1 lookup 100
sudo ip route add local 0.0.0.0/0 dev lo table 100
sudo iptables -t mangle -F
sudo iptables -t mangle -X
sudo iptables -P INPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -t mangle -N BROOK
sudo iptables -t mangle -A BROOK -d 0.0.0.0/8 -j RETURN
sudo iptables -t mangle -A BROOK -d 10.0.0.0/8 -j RETURN
sudo iptables -t mangle -A BROOK -d 127.0.0.0/8 -j RETURN
sudo iptables -t mangle -A BROOK -d 169.254.0.0/16 -j RETURN
sudo iptables -t mangle -A BROOK -d 172.16.0.0/12 -j RETURN
sudo iptables -t mangle -A BROOK -d 192.168.0.0/16 -j RETURN
sudo iptables -t mangle -A BROOK -d 224.0.0.0/4 -j RETURN
sudo iptables -t mangle -A BROOK -d 240.0.0.0/4 -j RETURN
sudo iptables -t mangle -A BROOK -d BROOK_SERVER_IP -j RETURN

sudo iptables -t mangle -A BROOK -j MARK --set-mark 1
sudo iptables -t mangle -A BROOK -j ACCEPT

sudo iptables -t mangle -A PREROUTING -p tcp -m socket -j BROOK
sudo iptables -t mangle -A PREROUTING -p tcp -j TPROXY --tproxy-mark 0x1/0x1 --on-port 1080

sudo iptables -t mangle -A PREROUTING -p udp -m socket -j BROOK
sudo iptables -t mangle -A PREROUTING -p udp -j TPROXY --tproxy-mark 0x1/0x1 --on-port 1080
```
I have replace `BROOK_SERVER_IP` with real IP.
After I execute the script above,  ubuntu disconnected the SSH and couldn't be connected again.
I login ubuntu with GUI, execute `ping 8.8.8.8` , success! 
`ping 192.168.1.1`, success.  (192.168.1.1 is my router's IP)
`curl -v http://192.168.1.1`, fail.
ubuntu's IP is `192.168.50.3` and network is `NAT` and I run a http service on it.
I execute some commands on another virtual machine:
```
ping 192.168.50.3  # success
curl 192.168.50.3  # fail
```

It seems  something wrong with `iptables` .

**Comment by txthinking** [comment]
Try #198 and the new wiki https://github.com/txthinking/brook/wiki/How-to-run-transparent-proxy-on-Linux%3F
