### ISSUE TITLE
How to run brook as daemon/background

### ISSUE THREAD

**Issue by Maristie** [txthinking/brook#22]
Is it possible to run the process of proxy server as daemon process?
Won't this process be killed as soon as I disconnect the terminal session with remote promote server?

**Comment by txthinking** [comment]
There are some ways to run as deamon on linux, like `nohup`, `screen`, `systemd`, `supervisord `.
Here I use `nohup` as an example, because it is very simple.

**Start brook:**
`$ nohup brook bkserver -l :9999 -p password -t 10 &`
> brook is running in background now.

**Stop brook:**
`$ killall brook`

**Comment by Maristie** [comment]
Thanks. It works.
