### ISSUE TITLE
希望加入iOS功能（改进及提升）

### ISSUE THREAD

**Issue by DemonJimmy** [txthinking/brook#222]
1.希望在iOS版本app上增加负一屏的小工具组件方便快捷启动代理功能
2.希望增加多服务器保存、并且分开端口号和IP地址输入栏（方便输入操作）
3.希望将密码以星号或原点隐藏并且提供恢复显示功能
4.祝愿越来越好！

**Comment by ljheisenberg1072** [comment]
中国区ios版本没有啊？老哥你是怎么下载的

**Comment by txthinking** [comment]
#133
