### ISSUE TITLE
hope to hide password on GUI

### ISSUE THREAD

**Issue by smounives** [txthinking/brook#224]
#### Describe actual behavior
The password is displayed in clear text on GUI Client.
#### What is your expected behavior
Hope to add an option to hide the password on GUI.
#### Steps to deploy the server
as normal

#### Steps to reproduce the problem
as normal

**Comment by hiperioncn** [comment]
Good idea.

**Comment by bobwang3** [comment]
Agree

**Comment by txthinking** [comment]
v20180601
