### ISSUE TITLE
Custom proxy address on GUI client

### ISSUE THREAD

**Issue by Justsoos** [txthinking/brook#228]
找了一圈，没看到 wiki 里有，也没发现貌似配置文本文件在 %LOCALAPPDATA%\Programs\Brook 目录下。
issues 里也没搜到有人提问，我提个给后来人问问。

**Comment by txthinking** [comment]
Yes, currently it is.

**Comment by DreamL** [comment]
Hope to support

**Comment by Justsoos** [comment]
我已经改用 nssm 后台运行 CLI 脚本开服务了，不用 win 安装版本，又大又不方便。

**Comment by txthinking** [comment]
v20180601
