### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by baimafeima** [txthinking/brook#23]
Could you add screenshots here on GitHub to get an idea of how the GUI looks like?

**Comment by txthinking** [comment]
Do you mean how to use it?
If yes, then:
If you are chinese, can you try first:

https://github.com/txthinking/brook/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E(%E4%B8%AD%E6%96%87)

**Comment by baimafeima** [comment]
No, I meant adding actual screenshots here on GitHub? I have no idea how your software looks like, even whether it comes with a GUI.
