### ISSUE TITLE
一加手机安卓客户端每隔几十分钟或者几个小时就会自动停止

### ISSUE THREAD

**Issue by xianshenghan** [txthinking/brook#230]
尊敬的作者您好，Brook安卓客户端在我的一加手机上用每隔几十分钟或者几个小时就会自动停止，我特意允许它跑后台的，却还是会自动停止，手机上装的其他app没有问题，就Brook这样，试了各个版本都一样，我想可能是Brook本身的问题吧？如果能解决，万分感谢。

**Comment by fremff** [comment]
> 应用开启后随机停止运行，这样的情况我也遇到了。

在关闭电池优化，还有允许 Draw Over Other Apps 后，这一问题就没再出现了 。不过，我并未进行长时间的测试。

**Comment by sunxiang520** [comment]
Android的话，设置应用允许后台运行就ok了，亲测有效，魅族手机可以在手机管家=>后台管理中，选择允许后台运行就ok了

**Comment by bobwang3** [comment]
我是一加5T，安卓8.1，氧Open Beta 5，BROOK 版本v20180401。电池优化去掉了，仍然是用着用着，brook就不见了，顶部的vpn连接图标消失。装了xposed框架，已经在绿守的白名单中。

**Comment by xianshenghan** [comment]
以上各位老师提供的方法我全部在一加手机上测试了，均无效，残念。

**Comment by fremff** [comment]
如果已应用以上方法，还可尝试在多任务窗口给应用加锁，以及进入“设置”-“高级”-“最近任务管理”中选择“普通清理项”。最后如果你的手机系统中的“开发者选项”中有“Doze Mode”的话，请关闭。

**Comment by xianshenghan** [comment]
在一加手机上测试了以上各位老师提供的方法，最终只有“**在多任务窗口给应用加锁**”这个方法有效，其它无效。感谢大家！

**Comment by bobwang3** [comment]
感谢楼上的分享，点一万个赞。在你的提示之下“在多任务窗口给应用加锁”后解决了问题，这个方法的确有效，其它全部无效。

**Comment by txthinking** [comment]
It looks like it has already been solved.
