### ISSUE TITLE
DNS under the iOS

### ISSUE THREAD

**Issue by antmak** [txthinking/brook#231]
Does Brook on iOS pass DNS requests through the tunnel?
Ask you. I cannot see it neither documentation nor code.
Thanks

**Comment by txthinking** [comment]
> Does Brook on iOS pass DNS requests through the tunnel?

If the domain is in white list, `Yes`, 
If the domain is not in white list, `No`

**Comment by txthinking** [comment]
https://github.com/txthinking/pac
