### ISSUE TITLE
Brook用做中继后,隔一段时间就出现失效,需要重启在可以继续使用

### ISSUE THREAD

**Issue by tudi1909** [txthinking/brook#232]
#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.
1.
2.

**Comment by nuclearn** [comment]
try to use  the parameter --tcpDeadline

**Comment by tudi1909** [comment]
感谢解答,tcpDeadline 取值一般多少合适呢?可否根据服务器Ping延迟来取值?
