### ISSUE TITLE
Option to open brook without the settings window opening

### ISSUE THREAD

**Issue by natepley** [txthinking/brook#233]
Every time I open brook, the window to input my server and password opens up.
I don't have any reason to change the server every time I open brook.  I'd like an option for the window to not open when brook opens.  An option for brook to automatically toggle on when brook is open would be nice too.

**Comment by kimihiro233** [comment]
set a task with cli,autorun everytime when you login

**Comment by pureair** [comment]
Second this. Autostart is essential for everyday use. Adding some parameters to brook.exe (eg. brook.exe -minimised -toggle on) is enough, a tick or switch in Settings would be even better. Thanks.

**Comment by txthinking** [comment]
#436 #435
