### ISSUE TITLE
坚果pro使用brook出现以下情况，求助

### ISSUE THREAD

**Issue by gourdbaby** [txthinking/brook#234]
安装最新版本安卓客户端后输入服务器地址，点击开启
出现以下问题
![photo_2018-04-19_16-08-14](https://user-images.githubusercontent.com/12860073/38979283-4bf36e9c-43ec-11e8-9536-e7cabaea31d5.jpg)

**Comment by CtrlWTF** [comment]
这是你的域名还没有解析到ip 你试试输入ip地址链接

**Comment by txthinking** [comment]
Can you try https://ipapi.co/ip/ ?

**Comment by gourdbaby** [comment]
@CtrlWTF 我使用的IP登录的。不过重新卸载了以后没出现这个问题

**Comment by gourdbaby** [comment]
@txthinking I tried re-install it brook.   No more ip problems，but it stay in this state.  Is it because I installed ssr client on my mobile phone?
![photo_2018-04-20_16-59-48](https://user-images.githubusercontent.com/12860073/39041958-5283caf6-44bc-11e8-8ca2-a11010ff8885.jpg)

**Comment by gourdbaby** [comment]
sorry, i must start vpn keep alive  in my system setting ....
![photo_2018-04-20_17-03-27](https://user-images.githubusercontent.com/12860073/39042170-c3fa543e-44bc-11e8-9d0b-5d53a3913757.jpg)
