### ISSUE TITLE
android client can not be used

### ISSUE THREAD

**Issue by muziling** [txthinking/brook#236]
server vesion is 20180401, client version is 20180401 too.
Any app can not get connection by brook vpn, server firewall has allow tcp,udp. Both brook server and brook socks5 tested,  enable server debug option, log output is:
> 2018/04/22 02:41:06 Got UserPassNegotiationRequest: 0x1 0x5 []byte{0x64, 0x64, 0x64, 0x64, 0x64} 0x5 []byte{0x64, 0x64, 0x64, 0x64, 0x64}
2018/04/22 02:41:06 Sent UserPassNegotiationReply: 0x1 0x0 
2018/04/22 02:41:06 Got UserPassNegotiationRequest: 0x1 0x5 []byte{0x64, 0x64, 0x64, 0x64, 0x64} 0x5 []byte{0x64, 0x64, 0x64, 0x64, 0x64}
2018/04/22 02:41:06 Sent UserPassNegotiationReply: 0x1 0x0 
2018/04/22 02:41:06 Got UserPassNegotiationRequest: 0x1 0x5 []byte{0x64, 0x64, 0x64, 0x64, 0x64} 0x5 []byte{0x64, 0x64, 0x64, 0x64, 0x64}
2018/04/22 02:41:06 Sent UserPassNegotiationReply: 0x1 0x0 
2018/04/22 02:41:06 Got UserPassNegotiationRequest: 0x1 0x5 []byte{0x64, 0x64, 0x64, 0x64, 0x64} 0x5 []byte{0x64, 0x64, 0x64, 0x64, 0x64}
2018/04/22 02:41:06 Sent UserPassNegotiationReply: 0x1 0x0 
2018/04/22 02:41:06 Got UserPassNegotiationRequest: 0x1 0x5 []byte{0x64, 0x64, 0x64, 0x64, 0x64} 0x5 []byte{0x64, 0x64, 0x64, 0x64, 0x64}
2018/04/22 02:41:06 Sent UserPassNegotiationReply: 0x1 0x0 
2018/04/22 02:41:06 Got Request: 0x5 0x3 0x0 0x1 []byte{0x0, 0x0, 0x0, 0x0} []byte{0x0, 0x0}
2018/04/22 02:41:06 Client wants to start UDP talk use 0.0.0.0:0
2018/04/22 02:41:06 Sent Reply: 0x5 0x0 0x0 0x1 []byte{0xc0, 0xa8, 0xde, 0x1} []byte{0x19, 0xe9}
2018/04/22 02:41:06 Got Request: 0x5 0x3 0x0 0x1 []byte{0x0, 0x0, 0x0, 0x0} []byte{0x0, 0x0}
2018/04/22 02:41:06 Client wants to start UDP talk use 0.0.0.0:0
2018/04/22 02:41:06 Sent Reply: 0x5 0x0 0x0 0x1 []byte{0xc0, 0xa8, 0xde, 0x1} []byte{0x19, 0xe9}
2018/04/22 02:41:06 Got Request: 0x5 0x3 0x0 0x1 []byte{0x0, 0x0, 0x0, 0x0} []byte{0x0, 0x0}
2018/04/22 02:41:06 Client wants to start UDP talk use 0.0.0.0:0
2018/04/22 02:41:06 Sent Reply: 0x5 0x0 0x0 0x1 []byte{0xc0, 0xa8, 0xde, 0x1} []byte{0x19, 0xe9}
2018/04/22 02:41:06 Got Request: 0x5 0x3 0x0 0x1 []byte{0x0, 0x0, 0x0, 0x0} []byte{0x0, 0x0}
2018/04/22 02:41:06 Client wants to start UDP talk use 0.0.0.0:0
2018/04/22 02:41:06 Sent Reply: 0x5 0x0 0x0 0x1 []byte{0xc0, 0xa8, 0xde, 0x1} []byte{0x19, 0xe9}
2018/04/22 02:41:06 Got Request: 0x5 0x3 0x0 0x1 []byte{0x0, 0x0, 0x0, 0x0} []byte{0x0, 0x0}
2018/04/22 02:41:06 Client wants to start UDP talk use 0.0.0.0:0
2018/04/22 02:41:06 Sent Reply: 0x5 0x0 0x0 0x1 []byte{0xc0, 0xa8, 0xde, 0x1} []byte{0x19, 0xe9}
2018/04/22 02:41:07 Got NegotiationRequest: 0x5 0x1 []byte{0x2}
2018/04/22 02:41:07 Sent NegotiationReply: 0x5 0x2

**Comment by yunlong202** [comment]
me too.  server vesion is 20180401, client version is 20180401. My phone model is huawei mate10.
But it worked on my macbook pro.

**Comment by yunlong202** [comment]
sorry, it worked now.
I think it is the firewall problem.  I first only added tcp:4000, after  I added udp:4000 is worked.

**Comment by txthinking** [comment]
Please provide reproduction steps and reopen.

**Comment by bilijinshi** [comment]
Same thing happens here. Android client need server open both UDP&TCP ports, however linux native client only need server TCP ports. Is this normal?
I can not see any log even with -d option is enabled at server.
