### ISSUE TITLE
Brook windows GUI client cannot be toggled on 

### ISSUE THREAD

**Issue by sodabluesff** [txthinking/brook#239]
#### Describe actual behavior

The system tray icon indicates that brook is stopped.  Tried to click the toggle switch and nothing happened,  it just remained stopped and would never work.  

I don't have any other proxy software enabled, nor any antivirus software installed.  I also tried to run brook as administrator and turn off windows defender, still all efforts were in vain.

#### What is your expected behavior

Toggle switch works fine and brook can be started.

#### Specifications like the version of the project, operating system, or hardware

Brook Version: GUI client v20180401,  Windows 10 Pro 64-bit (build 16299.371),   

#### Steps to deploy the server

as described in wiki

#### Steps to reproduce the problem

![untitled](https://user-images.githubusercontent.com/26293895/39283195-c1b4ef68-493f-11e8-97bc-df70382dba59.png)

**Comment by txthinking** [comment]
Related #253 ?
