### ISSUE TITLE
iOS端的源码是不是看不到的哈

### ISSUE THREAD

**Issue by 931743010** [txthinking/brook#24]
想自己编写kcptun进去哈

**Comment by txthinking** [comment]
代码拙劣，暂不放开。
另外，KCP怎么说呢，有些争议吧。

**Comment by 931743010** [comment]
发现在mac下面也转成全局的了 ； 问下 怎么能这么牛逼呢  能解释一下吗？

**Comment by acrazing** [comment]
@txthinking ios客户端能开源么? 不想自己撸一个, 我想的是不开放app store自己编译总行吧?
