### ISSUE TITLE
TCP异常

### ISSUE THREAD

**Issue by coxlxd** [txthinking/brook#240]
服务端版本v20180401，系统debian9-64位 debian8-64位。
客户端使用安卓手机版本v20180401

经常发现手机客户端关闭使用或者切换网络后，服务器端TCP连接一直处于 ESTABLISHED状态，BROOK客户端就出现异常缓慢甚至卡顿，只能重启服务器的服务TCP连接处于FIN_WAIT1还是不会释放，只能重启服务器 。

**Comment by txthinking** [comment]
Try --tcpDeadline
