### ISSUE TITLE
doesnt work on win10

### ISSUE THREAD

**Issue by Sczlog** [txthinking/brook#242]
i has install the latest version on my server and running it on my server.
it work okay on my laptop which is running win7.
also on my android phone.
but i cant use it on my desktop, which a win10 one.
At start i thought that may be the port problem, but i had closed my firewall and it didnt work.
Later i used shadowsocksr and it work good on my desktop, brook and shadowsocksr are all using port 1080 so it isn't a port problem.
<del>My friend also can't using it successfully on win10 while some others here said it work on win10.</del>
my friend successfully using brook on win 10, so whats my problem?
Do i forget some important configuration?

![tim 20180429210242](https://user-images.githubusercontent.com/29588646/39407020-457f9596-4bf2-11e8-8c8e-2c8ac3542c0c.png)
![tim 20180429210317](https://user-images.githubusercontent.com/29588646/39407021-45c53538-4bf2-11e8-859c-5d22bba06140.png)
![tim 20180429210526](https://user-images.githubusercontent.com/29588646/39407022-4607bf5c-4bf2-11e8-93f6-dcb709e3dbd8.png)
![screenshot_2018-04-29-21-07-23-607_com android br](https://user-images.githubusercontent.com/29588646/39407033-798a47e6-4bf2-11e8-9a5e-038dcfc2a6c8.png)
![screenshot_2018-04-29-21-15-12-868_com android br](https://user-images.githubusercontent.com/29588646/39407034-79d0132a-4bf2-11e8-815c-ff64e40731e2.png)

**Comment by wilber82** [comment]
Check do you have "Internet Explorer 11" function on Windows 10.
It may lost on certain Windows 10 versions.
You have to re-install "Internet Explorer 11" if you only see "Microsoft Edge" available.

Solution:
[https://social.technet.microsoft.com/Forums/en-US/7a70bde8-5227-497e-9462-4715b9d60799/my-internet-explorer-11-just-disappeared?forum=ieitprocurrentver](url)

**Comment by txthinking** [comment]
Thank you @wilber82

**Comment by Sczlog** [comment]
![image](https://user-images.githubusercontent.com/29588646/39994122-e2187fe4-57aa-11e8-947e-67554f00ee02.png)
I have IE11 on my computer.
