### ISSUE TITLE
Reverse tunnel possible?

### ISSUE THREAD

**Issue by jadedgnome** [txthinking/brook#246]
I'm trying to expose/forward a local listening port to the socks5 server so that i can open a specified listening port on the server and forward the incoming connection to my client machine, is that possible with brook?

client ip : 7000 {listening port} <- NAT router  <- brook server:9999 <- pc connecting to ip of brook server :7000 {listening port}

similar to: ssh -R port:host:hostport

**Comment by txthinking** [comment]
Not support

**Comment by franciskim** [comment]
Still unsupported? @txthinking
