### ISSUE TITLE
Transparent proxy issue

### ISSUE THREAD

**Issue by legendlisz** [txthinking/brook#248]
I have the brook tproxy running on my router with internal interface 10.1.4.1 
(brook tproxy -l :1080 -s MyServerAddress:9999 -p mypassword)

once I redirect my traffic to tcp port 1080, seems the packet successfully reached server, but on server side, I got below error message: 

2018/05/03 04:29:33 dial tcp 10.1.4.1:1080: i/o timeout

I suppose in brook server trying to send the packet  to 10.1.4.1 instead of my router's public IP ADDR. 

The difference than the doc in WIKI is I'm using iptables with ipset instead of tproxy, this works with ss-redir or ssr-redir as transparent proxy for long time. 

the related detail as below:

create a ipset named letitgo 

all traffic need to go through proxy will be marked letitgo by dnsmasq

the traffice marked letitgo will be redirect to brook server:
iptables -A PREROUTING -p tcp -m set --match-set letitgo dst -j REDIRECT --to-ports 1080

**Comment by txthinking** [comment]
try #198 and the new wiki https://github.com/txthinking/brook/wiki/How-to-run-transparent-proxy-on-Linux%3F
