### ISSUE TITLE
linux client running into error

### ISSUE THREAD

**Issue by coldgemini** [txthinking/brook#249]
running on ubuntu 18.04

sudo ./brook client -l 127.0.0.1:1080 -i 127.0.0.1 -s server_ip:2333 -p doub.io

both with sudo and without sudo produce same error

2018/05/03 21:50:26 Invalid Version

**Comment by txthinking** [comment]
Please confirm your applications support socks5 proxy

**Comment by alyato** [comment]
@coldgemini 
how to install the linux client?
when i dowload the client and it show me `There is no application installed for “executable” files`
![brook7 09 42 55](https://user-images.githubusercontent.com/6815071/42405525-30536e5a-81ca-11e8-89f5-ad05532eff9d.png)
thanks.
