### ISSUE TITLE
DNS转发？

### ISSUE THREAD

**Issue by zeg** [txthinking/brook#255]
SS有个专门用作DNS转发的ss-tunnel 在本地路由器运行透明代理模式时配合ss-redir使用

例如本地电脑的DNS为114.114.114.114
ss-server所在远端服务器的DNS为 8.8.8.8

本地电脑进行DNS查询时 本地路由器上的iptables将查询转发给  本地路由器上运行的ss-tunnel
ss-tunnel将查询的目标(114.114.114.114) 改为8.8.8.8 并通过ss通道发送至ss-server执行DNS查询
ss-tunnel接收到正确的DNS解析后再返回给本地电脑

brook有类似功能否  或通过其他方式实现？

**Comment by chenhw2** [comment]
Refer: https://github.com/txthinking/brook/issues/102
