### ISSUE TITLE
Could You Add A Fuction To Ban Brute Force Crackers

### ISSUE THREAD

**Issue by alpha4belief** [txthinking/brook#259]
The Brook is very great but it would be better to add a function about banning some force crackers. I always found that my Brook was connected by some unknown guys... Could you add a function to ban force crackers just like Shadowsocks? Much thanks!!
[https://github.com/shadowsocks/shadowsocks/wiki/Ban-Brute-Force-Crackers](url)

**Comment by txthinking** [comment]
I will consider this topic

**Comment by txthinking** [comment]
I think this will add additional behavioral characteristics and increase the likelihood of being detected.
