### ISSUE TITLE
A large number of such similar logs?

### ISSUE THREAD

**Issue by ps2xu** [txthinking/brook#260]
#### Why does my server BROOK have a large number of such similar logs?THX.

2018/05/13 07:25:23 dial tcp 69.171.247.32:443: i/o timeout

...
2018/05/13 07:28:10 dial tcp 199.59.148.97:443: i/o timeout

2018/05/13 07:28:12 dial tcp 75.126.150.210:443: i/o timeout

2018/05/13 07:28:28 dial tcp 199.59.148.97:443: i/o timeout

2018/05/13 07:28:30 dial tcp 199.59.148.97:443: i/o timeout

2018/05/13 07:29:08 dial tcp 69.63.184.30:443: i/o timeout

2018/05/13 07:29:08 dial tcp 69.63.184.30:443: i/o timeout

2018/05/13 07:29:08 dial tcp 69.63.184.30:443: i/o timeout

2018/05/13 07:29:16 dial tcp 69.63.184.30:443: i/o timeout

2018/05/13 07:30:05 cipher: message authentication failed

2018/05/13 07:30:25 dial tcp 208.43.237.140:443: i/o timeout

2018/05/13 07:30:26 dial tcp 119.28.109.165:443: i/o timeout

2018/05/13 07:30:56 dial tcp 208.43.237.140:443: i/o timeout

2018/05/13 07:31:02 dial tcp 208.43.237.140:443: i/o timeout

2018/05/13 07:33:44 dial tcp 139.198.0.210:443: connect: connection refused

...
2018/05/13 07:38:33 dial tcp 174.36.228.136:443: i/o timeout

2018/05/13 07:40:14 dial tcp 66.220.149.32:443: i/o timeout

2018/05/13 07:40:21 dial tcp 59.24.3.173:443: i/o timeout

2018/05/13 07:40:52 dial tcp 59.24.3.173:443: i/o timeout

2018/05/13 07:41:27 dial tcp 59.24.3.173:443: i/o timeout

2018/05/13 07:41:57 dial tcp 66.220.147.47:443: i/o timeout

2018/05/13 07:42:03 dial tcp 59.24.3.173:443: i/o timeout

2018/05/13 07:43:08 dial tcp 59.24.3.173:443: i/o timeout

2018/05/13 07:43:44 dial tcp: lookup cdn.api.twitter.com on 8.8.8.8:53: no such host

2018/05/13 07:47:34 dial tcp 67.228.126.62:443: i/o timeout

2018/05/13 07:47:34 dial tcp 119.28.109.165:80: i/o timeout

2018/05/13 07:47:36 dial tcp 67.228.126.62:443: i/o timeout

2018/05/13 07:47:37 dial tcp 119.28.109.165:80: i/o timeout

2018/05/13 07:47:41 dial tcp 67.228.126.62:443: i/o timeout

2018/05/13 07:47:41 dial tcp 67.228.126.62:443: i/o timeout

2018/05/13 07:47:45 dial tcp 67.228.126.62:443: i/o timeout

2018/05/13 07:47:50 dial tcp 203.205.128.167:80: i/o timeout

2018/05/13 07:47:52 dial tcp 119.28.109.165:80: i/o timeout

2018/05/13 07:47:56 dial tcp 119.28.109.165:80: i/o timeout

**Comment by ps2xu** [comment]
[brook.log](https://github.com/txthinking/brook/files/1998037/brook.log)

**Comment by lipeng1667** [comment]
service iptables stop 
or 
systemctl stop iptables  

After I close the firewall, all is well
