### ISSUE TITLE
Android client need both TCP&UDP ports at server. Is this normal?

### ISSUE THREAD

**Issue by bilijinshi** [txthinking/brook#263]
#### Describe actual behavior
Android client need server open both UDP&TCP ports. If server firewall blocks UDP ports, android client will not work.
However linux native client only need server open TCP ports. Is this normal?

#### What is your expected behavior
Android & linux native client have same behaviors.

#### Specifications like the version of the project, operating system, or hardware
Android: 20180401
Linux: 20180401

#### Steps to deploy the server
0. Download linux server
1. In firewall settings: only open TCP ports 4321; vs open both TCP&UDP ports 4321
2. ./brook server -l :4321 -p xxxxxxxx

#### Steps to reproduce the problem
0. Android client set server: IP&port&pwd and connect.
1. VS Linux native client: sudo ./brook -d client -l 127.0.0.1:1080 -i 127.0.0.1 -s IP:4321 -p xxxxxxxx
2.

**Comment by bilijinshi** [comment]
Same problem here: https://github.com/txthinking/brook/issues/236

**Comment by txthinking** [comment]
Yes, android client need your server must open UDP support.
