### ISSUE TITLE
hi，txthinking，Can you check the problem with the iPad client? Thanks

### ISSUE THREAD

**Issue by Kejiasir** [txthinking/brook#264]
#### Describe the actual behavior

iPad mini4 can connect to VPN, but it can't use **FQ**, but it can be used normally on iPhone

#### What is your expected behavior?

I hope iPad can be normal **FQ**

#### Specifications, such as project version, operating system or hardware

iPhone System Version: iOS 11

iPad System Version: iOS 10

**Comment by lircal** [comment]
大兄弟，中文回你吧。我也用了iPhone 和iPad两个，都是iOS10的系统。一切正常，你可以尝试着再确认一下iPhone和iPad的配置，还有是否关闭了其他工具。
