### ISSUE TITLE
Mac 的gui客户端错误

### ISSUE THREAD

**Issue by lircal** [txthinking/brook#265]
#### Describe actual behavior
Mac gui版本 打不开，点了toggle后 弹了一个JavaScript error

#### Steps to deploy the server
0.
1.
2.
<img width="422" alt="2018-05-18 10 54 31" src="https://user-images.githubusercontent.com/17294858/40213835-253bc3c6-5a8a-11e8-991d-42a458373662.png">

#### Steps to reproduce the problem
0.
1.
2.

**Comment by txthinking** [comment]
Please try to uninstall and reinstall latest version

**Comment by txthinking** [comment]
Try 20180601
