### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [txthinking/brook#267]
Hello Sir. I'm a UI/UX and Graphics Designer. I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks before.

**Comment by txthinking** [comment]
The current logo looks enough and simple, is it?

**Comment by anharismail** [comment]
You're welcome, Sir. In my humble opinion, the previous logo is too generic and doesn't have powerful idea or identity of your project :grinning:

**Comment by SJTUboy** [comment]
Hi @anharismail 
Maybe you can upload your design here, we can vote for it.

**Comment by anharismail** [comment]
Allright, I'll provide my logo proposal as soon as possible @SJTUboy @txthinking

**Comment by anharismail** [comment]
Hello, @SJTUboy @txthinking  . These are my logo proposal for your project.
This logo was inspired by B initial and security element. I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.

I'll provide all file types and sizes you needed.

Hope you like it :)

### Version 1
![brook ver 1](https://user-images.githubusercontent.com/37614260/43502100-3ef32582-9583-11e8-862f-f6f7e8a361b5.png)

### Version 2
![brook ver 2](https://user-images.githubusercontent.com/37614260/43502103-43cd2224-9583-11e8-8371-d044b6c07ed1.png)
