### ISSUE TITLE
about MacOS Client GUI

### ISSUE THREAD

**Issue by Dulun** [txthinking/brook#268]
Thanks for your brook. It is amazing! The speed is wow!     Here is the issue on the macos gui client:
The Client ask for passwd  twice when it starts and ask passwd when it quit too. is that necessary?
when the mac sleep  And after a while (1or2 hours), i can't access the internet  through brook. Quit the client and  Restart the client then the button 'toggle' won't work. after i put my passwd twice,and it still shows "stopped". i have to reboot my mac.

**Comment by txthinking** [comment]
And upgrade Brook MacOS GUI to v20180707 :)
