### ISSUE TITLE
google feed无法登陆。

### ISSUE THREAD

**Issue by zhuhaijian** [txthinking/brook#275]
新版android版，不管哪种模式，google feed无法登陆。

**Comment by zhuhaijian** [comment]
边无线，无法登，youtube图片加载不出来，用4G很快，都没问题

**Comment by txthinking** [comment]
如果你用A网络没有问题, 说明:

1. A网络到达你的Brook Server, 通畅.
1. Brook 软件本身work.

如果你换了B网络, 仍是上面的Brook Server, 说明:

1. Brook 软件本身work. (因为上面已经排除这个问题), 所以可能是: 
1. B网络到达你的Brook Server 有问题.
