### ISSUE TITLE
Custom IOS Client

### ISSUE THREAD

**Issue by MrBenFTW** [txthinking/brook#277]
Hello, you never replied to my question, but you closed the thread.

I was wondering if you could open source the brook ios app. 

Or give documentation on how to  make use of the brook protocol for our own app.

**Comment by txthinking** [comment]
Hello, MrBenFTW

Yes, it really need to make more documents, I will write protocol doc when
I have time :)

**Comment by MrBenFTW** [comment]
Thanks! 

In the meantime could you make the brook ios/ brookone Xcode public so I can study it? :)

**Comment by txthinking** [comment]
Sorry, no plan currently for this.

**Comment by MrBenFTW** [comment]
Hi! it has been 6 months since I wrote this, I still would like to write my own brook client, please could you make a demo project or open source brook iOS. Thank you!

**Comment by MrBenFTW** [comment]
Hi, it has been over a year now. Please could you open source brook/brookOne
