### ISSUE TITLE
放弃i386 GUI  Custom Mode版本的的brook了吗

### ISSUE THREAD

**Issue by Sesprie** [txthinking/brook#279]
#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.
1.
2.

**Comment by txthinking** [comment]
我的电脑256的mac装了3个虚拟机, 目前无法在安装32位windows了.
如果你有32位windows, 可以很容易从源码构建的.

**Comment by Sesprie** [comment]
好的，谢谢，
