### ISSUE TITLE
Latest release v20180601 Brook.apk  部分手机无法正常使用

### ISSUE THREAD

**Issue by liaodijin** [txthinking/brook#281]
#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.Latest release v20180601 Brook.apk 在华为p20 上及小米note3 均无法正常使用
1.华为p20安装完以后，打开使用，点击开启特别慢，完了以后，通知栏有图标，但是无法科学上网
2.小米note3安装以后，打开使用，点击开启特别慢，而且无法正常开启，通知栏无图标。

**Comment by Shakespearess** [comment]
同无法使用 ,PC端使用正常.
安卓版本8.0.0
基带版本G9500ZHS2CRE2
内核版本4.4.78-13205380

**Comment by Mr-Jos** [comment]
同无法使用
服务端 linux_amd64 v20180601
PC端 windows_amd64 v20180601 brook协议与brookstream协议均使用正常
移动端 Android v20180601/v20180401 brook/brookstream 四种组合均无法使用

**Comment by bendfeng** [comment]
小米6 安卓8.0同样无法使用。

**Comment by bobwang3** [comment]
我是一加氧安卓8.1，用了一段时间觉得20180601不好用，删掉退回20180401了

**Comment by mistlost** [comment]
索尼 xz premium，安卓8.0。PC端一切正常。移动客户端在过去两个月一直正常，未发生崩溃或假死，大概自6月1日起，无论是20180401还是20180601版本都不能正常运行，不仅开启速度变慢，启动后一直无法运行，均为默认设置，brook协议。

**Comment by pureair** [comment]
20180601版一加 8.1 可以使用，点击连接后要等一会儿才会连上，但是可以连上，问题不大。但是好像使用白名单模式时，路由器访问不了，也就是内网访问不了，不知道是什么原因。

**Comment by bobwang3** [comment]
我再补充一点。我觉得20180601版不好用的原因是发生过断开重连后提示无法连接，下方会出现好多小字提示，需要我把进程完全杀掉后再启动才能正常。另外一个是开着就访问不了我局域网里的NAS，20180401是认局域网IP的，内网IP不走代理，不知道为啥版本变高后功能反而退步了。

**Comment by kjcm150** [comment]
补充，可以建立vpn，但是无法使用，在以下ROM测试：
- OxygenOS 3.6.1 (Android 6.0.1)
- MIUI 9 (Android 8.0.0)
- MoKee 81.0 (Android 8.1.0)

同一服务器，iOS 11与Windows上可正常使用。

**Comment by nemoming** [comment]
更新，问题描述同https://github.com/txthinking/brook/issues/293一致。同样OnePlus 5T 8.1系统在安装v20180601出现无法访问网络（墙内墙外）后，卸载重装v20180401也无法重新访问任何域名（墙内墙外）。

**Comment by nemoming** [comment]
更新，问题状况同https://github.com/txthinking/brook/issues/293 一致。手机是OnePlus 5T，8.1系统。在安装v20180601出现无法访问网络（墙内墙外）后，卸载重装v20180401也无法重新访问任何域名（墙内墙外）。

**Comment by TempXman** [comment]
Nexus 5
Android 6.0.1

电脑端使用正常；
手机端使用WIFI时**经常**（不知什么时候会有可以）无法科学上网，显示brook开启成功，但无法打开任何网站，服务期端午错误信息，无手机IP的连接信息。

刚发现：连接BROOK无法科学上网，先断开WIFI，使用移动网络打开google，再连接wifi就可以了，不知什么原因。

**Comment by heptaspirit** [comment]
同样问题
华为p10，Android8.0，0601版本。
iOS与win版本使用正常，安卓版本出现VPN建立后无法连接外网的情况，后台日志无异常，需等待一段时间（5min以上）方可正常连接。

**Comment by txthinking** [comment]
昨天用 Pixel 遇到这个情况

在朋友家电信宽带网络

1. 白名单模式, 点击开启按钮
1. 提示获取 https://www.txthinking.com/pac/white.list 失败
1. 重复上一步3-5次
1. 出现了按钮成为已开启状态, 但是并未出现 VPN 标示(创建VPN失败)

之后退出 Brook (划掉进程)

切换到手机联通蜂窝网络

1. 白名单模式, 点击开启按钮
1. 开启成功

初步判断是因为  https://www.txthinking.com/pac/white.list 访问不稳定的原因. 这个 URL 实际上使用的github page, 项目在 https://github.com/txthinking/pac. 感觉大陆网络访问 Github 近日有点不稳定, *不知道是否跟最近收购有关*

为了保持总是使用最新的规则, 20180601 版本改成了每次开启时从 Github 拉取规则. 若如此的话看来得考虑将**规则列表**内置的 App 里. 本来打算 App 可以想 GUI 桌面版一样可以自己配置 **规则 URL** 的, 这样的话每个人都可以搭建服务器使用自己的编写的规则(因为规则非常简单, 见 pac 项目), 但是苹果审核以不允许调用外部 API 为由没通过, 故而暂时也将 Android 版 **规则 URL** 内置且不可编辑状态.

**Comment by mycjc** [comment]
更新：
目前手头上十几部安卓设备都无法使用brook（任何版本）（之前还有几部手机可以用），电脑端无此问题。
客户端使用的是逗比的brook一键脚本（客户端版本：20180401）[https://doub.io/brook-jc3/](url)

**Comment by txthinking** [comment]
Please try Brook Android GUI Client v20180707

**Comment by nemoming** [comment]
Used for like 10 minutes, seems all the problems I mentioned above are fixed. At least everything is working appropriately atm. Thank you so much for your update! I really appreciate your time and work! THX!

**Comment by ceeji** [comment]
0707 版本小米 6 依然无法使用，无论何种模式均无法正常访问。

**Comment by heptaspirit** [comment]
华为p10
安卓8.0
Brook 0707
Brook协议

小米5x
安卓7.1.2
MIUI9.0
Brook 0707
Brook协议

1. 白名单模式,开启后出现如下提示
Platformexception(UNAVAILABLE, Attempt to invoke virtual method 'java. lang String.java.lang.Object.toString()' on a null object reference, null)
2. 无视提示，再次选择启动，Brook自动退出
3. 黑名单模式同上
4. 全局模式无异常

**Comment by txthinking** [comment]
I just close this issue. Because this issue is about 20180601.
If someone has other problem, please open a new issue and provide detailed reproduction steps.
Thank you.
