### ISSUE TITLE
能否增加x86_64 for linux的BIN？

### ISSUE THREAD

**Issue by whiskysmall5** [txthinking/brook#282]
如题，谢谢。

**Comment by txthinking** [comment]
Here, amd64 = x86_64

**Comment by whiskysmall5** [comment]
amd64的编译好的只有macos和WIN的，没有linux的。。

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/releases/download/v20180601/brook

**Comment by whiskysmall5** [comment]
谢谢，给提个建议名字能否改成linux_amd64呢，不然上来一脸蒙B都不知道哪个是X64的。。。
