### ISSUE TITLE
iOS版本断联

### ISSUE THREAD

**Issue by heptaspirit** [txthinking/brook#283]
0.iPad 2017，iOS11.3.1，0601版本。linode服务器，服务器版本0601，默认Brook协议
1.建立连接后，一段时间会自动断开VPN连接，如YouTube播放中会出现该情况。此时Brook运行正常。
3.在VPN设置中“VPN状态”重新打开VPN连接，稍等方可连接。

**Comment by yurenfenghua** [comment]
版本号：ios11.4
iPhone
同样遇到自动断连问题，需重新在设置中打开vpn

**Comment by wilber822** [comment]
Looks like it’s client issue. It’s rarely to see connectivity issues on v20180112.

**Comment by txthinking** [comment]
请按照一个问题一个issue. 谢谢.

**Comment by smounives** [comment]
same

**Comment by pkwt10** [comment]
This problem already exists in several versions.

**Comment by wilber822** [comment]
This is client issue. I updated server version but same issue. It never disconnect in client version v20180112.

**Comment by tellmerose** [comment]
i7，128G，iOS 12，Brook v20180601.

**Comment by txthinking** [comment]
Hi, friends.

The iOS limit app extension memory usage, but the new iOS allow more.
Please upgrade your iOS to latest version(for now 11.4)

**Comment by wilber822** [comment]
Hi @txthinking ,
It could be memory issue leads to Brooks unexpected quit. But please notice that my testing was on iOS 11.4 on IP7 and IP6 both. The lower version Brooks running fine on IP6.

Maybe the latest Brooks added some features that it needs more memory?

**Comment by SJTUboy** [comment]
iOS version：11.4
iPhone model：iPhone SE
Book version ：v20180601
Same issue

Thank you for your work!

**Comment by wilber822** [comment]
Hi @txthinking,
 One more feedback, Looks like it’s only happened  when select “white list”  or “blacklist“.

**Comment by txthinking** [comment]
Because of certain reasons, plz use English.
