### ISSUE TITLE
If telegram does not work on iOS

### ISSUE THREAD

**Issue by txthinking** [txthinking/brook#285]
Solution:

Open Telegram, Settings->Data and Storage->Use Proxy->Add Proxy->Socks5, Server: `127.0.0.1` (or `::1`), Port: `1090`->Done

**Telegram has a bug: always connecting/waiting for network when you set proxy first time. So Restart Telegram Client.**

more about created proxy: https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client

**Comment by SJTUboy** [comment]
TG, still "Connecting"
Brook version is v20180601. Mode: Black List. Location: Shanghai.
TG is the latest version ( up to now 2018/6/23)

**Comment by txthinking** [comment]
Please choose White List.

**Comment by SJTUboy** [comment]
Problem solved! Thanks a lot!

**Comment by trackerlyj** [comment]
how to choose White List? I meet the same question.

**Comment by trackerlyj** [comment]
how to choose White List? I meet the same question.

@txthinking

**Comment by barry0907** [comment]
Tried same setup but not working for me which is in China....

Thanks for sharing

**Comment by smkddsmk** [comment]
v20190401 has no White List. @txthinking.

**Comment by cutemanworking** [comment]
I met the same program and there isn't whitelist in v20190401.

**Comment by zch12138** [comment]
if the proxy status stuck at "waiting for network", it may not brook issus. Restart the telegram, it will work fine.
https://www.v2ex.com/t/545953

**Comment by pcprinciple** [comment]
@zch12138 Thanks. You must have rebooted the Telegram App

**Comment by unrealyan** [comment]
Is the information encrypted?

**Comment by txthinking** [comment]
Yes

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/wiki/Telegram-on-iOS
