### ISSUE TITLE
when i start it,that shows "faied to set system proxy"

### ISSUE THREAD

**Issue by filcky** [txthinking/brook#288]
hi
i wanna to tell you about my problem.
maybe i replace that host filter,when i start Brook,that always shows me "failed to set system proxy",so it had to stop.i really hope to receive your answer about this problem.
what's wrong with my Brook?
i really want to know how to do with it
thx

**Comment by txthinking** [comment]
Please provide more details that I can reproduce your problem.
Thank you.

**Comment by bicliu** [comment]
@txthinking 
My system version is windows-10 -1607, OS verion is 14393.2312.
How do I determine this problem is about the system setting or the account?
Tell me what can I do ? 
thx!

**Comment by DerinChiu** [comment]
Same here
os: Win 10 1803
Brook says "failed to set system proxy" on first time start
No other proxy installed except for SS...
How to fix it?
Thanks

**Comment by txthinking** [comment]
Please try v20180707

**Comment by DerinChiu** [comment]
@txthinking 
Problem solved in GUI Client v20180707 , thanks!
