### ISSUE TITLE
ios无法连接

### ISSUE THREAD

**Issue by fox777777777777** [txthinking/brook#289]
#### 今天ios突然无法连接，ios客户端点开始连接按钮，无法打开vpn图标，在设置vpn里面打开开关，显示断开连接，mac客户端也一样，无意中打开pac网址：https://www.txthinking.com/pac/white.list及https://www.txthinking.com/pac/black.list发现被墙，现只能用全局才能打开vpn（白名单和黑名单模式均不能打开vpn）
pc端正常

**Comment by lqdflying** [comment]
确实，补充一下，全局模式，vpn图标确实可以出现，但是依然是连不上的。PC端正常

**Comment by fox777777777777** [comment]
全局模式连接一个小时，都可以连接，也没有出现链接断开的问题。

**Comment by heptaspirit** [comment]
我自己测试的情况：
白名单与黑名单有时可直连，有时不可，但先全局再白名单就一定没问题。

**Comment by fox777777777777** [comment]
感觉apple系的客户端可能还是有问题，pc端brook tools 妥妥的没问题！

**Comment by fox777777777777** [comment]
刚试了一下，pac地址貌似恢复了！

**Comment by lqdflying** [comment]
你是最新版IOS吗

**Comment by lqdflying** [comment]
我的也可以了，但是感觉brook这个工具针对质量不好的网络没有SSR协议支撑好。举例来说，油管1080，相同的wifi网络，油管可以做到1080流畅，brook就不行了，然后把brook拿到wifi路由器5G信号较强的范围内 ，又可以了

**Comment by fox777777777777** [comment]
感觉brook相对于ssr速度有明显优势， 但是前提是开启bbr，vps速度稳定！

**Comment by lqdflying** [comment]
速度稳定的vps不多了吧，vutrl日本区被墙的烂死了

**Comment by fox777777777777** [comment]
gcp还可以，六月初被封了一次ip

**Comment by lqdflying** [comment]
gcp哪个区？

**Comment by fox777777777777** [comment]
新加坡

**Comment by lqdflying** [comment]
感谢分享

**Comment by satawait** [comment]
全局模式都不行了

**Comment by satawait** [comment]
@lipeng1667 我的ip是通的，就是连上几秒钟就掉

**Comment by fox777777777777** [comment]
时好时坏，还是两手准备！

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/issues/281#issuecomment-397863631

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/blob/master/.github/CONTRIBUTING.md

**Comment by txthinking** [comment]
Because of certain reasons, please use English.
