### ISSUE TITLE
Can not use with remote control

### ISSUE THREAD

**Issue by cw4219** [txthinking/brook#291]
#### Describe actual behavior
For tv devices, use remote control to start brook
#### What is your expected behavior
Can start brook successfully
#### Specifications like the version of the project, operating system, or hardware
Brook-v20180601.apk
XIAOMI TV 3S
Android 6.0
Amlogic S912 + 2GB RAM + 8GB ROM

#### Steps to reproduce the problem
0.Open brook apk via remote control
1.Can not control ui widget via remote control
2.

**Comment by txthinking** [comment]
Sorry. I can't help you. Plz google it.
