### ISSUE TITLE
部分安卓手机出现无法连接brook

### ISSUE THREAD

**Issue by mycjc** [txthinking/brook#293]
#### Describe actual behavior
部分安卓手机出现无法连接brook

#### What is your expected behavior
希望作者可以让brook兼容更多国产安卓手机
#### Specifications like the version of the project, operating system, or hardware
服务器版本：V20180401 测试手机：红米note3 MIUI版本：9.5稳定版 
Smartisan坚果Pro2 版本：V4.2  oppoR9 版本不详 诺基亚手机 版本不详 一加手机3 版本不详  iPhone6 版本：iOS10
测试电脑 ：win10
#### Steps to deploy the server
1.Brook20180401 在 iPhone6s oppoR9 一加3 诺基亚手机上运行良好。
2.Brook20180401 在坚果Pro2手机（V4.1）运行良好，当系统升级至V4.2 Brook可以创建Vpn符号 但无法连接至任何外网。
3.红米手机Note3（MIUI9.5）可以运行Brook**20180401**，但安装Brook**20180601**后无法连接任何外网，**卸载BrookV20180601 重装BrookV20180401后，再连接VPN 即出现无法连接外网的情况**。
4.Brook在PC上可以运行。
#### Steps to reproduce the problem
1.无法连接外网的情况在坚果Pro2复现机率100%
2.红米Note3完美运行Brook20180401，但我抱着好奇心安装Brook20180601后即出现无法连接外网的情况，即使卸载并退回至Brook20180401也无法连接外网。
3.**感谢Brook，让我的世界更美好了一点**。

**Comment by txthinking** [comment]
#281
