### ISSUE TITLE
请问服务器和密码哪里获取？

### ISSUE THREAD

**Issue by tellmerose** [txthinking/brook#294]
#### Describe actual behavior
新手，不知道该怎么使用。
#### What is your expected behavior
希望大神指导下该怎么进行了解和入门？
#### Specifications like the version of the project, operating system, or hardware
iOS 12，i7。
#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.
1.
2.

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/blob/master/.github/CONTRIBUTING.md

**Comment by txthinking** [comment]
I think you need google :)
