### ISSUE TITLE
是否考虑把kcptun集成进来

### ISSUE THREAD

**Issue by codeskyblue** [txthinking/brook#3]

**Comment by txthinking** [comment]
如果需求用户多，会考虑加入此功能

**Comment by txthinking** [comment]
kcp 以UDP传输，现在普遍有一种情况是 ISP发先UDP大流量会明显的阻断一段时间。
也就是开始的确会有加速效果，但是一定时间后会阻断，造成不稳定，比如Slack 这种长连接 web 应用会明显的不可用。

**Comment by yencn** [comment]
求加入

**Comment by sunqb** [comment]
kcp速度是真的快，用了好几年一直都是kcp，无论ss时代或者v2都是用的kcp，希望作者大大集成进来
