### ISSUE TITLE
【Android client】试用体验建议反馈

### ISSUE THREAD

**Issue by BI7PRK** [txthinking/brook#300]
太棒了，感谢为人类文明无私奉献的技术使者们！请允许我提个建议：

Android Client 体验还欠佳。

> 像【影梭】的客户端挺好的。 服务列表式，随时任意切换到某个服务器。每个服务器的连接都独立配置。而且还有测速。我觉得像那个子体验会更好。

**Comment by twzchi** [comment]
会断流

**Comment by txthinking** [comment]
#251
