### ISSUE TITLE
玩GameLoft游戏问题

### ISSUE THREAD

**Issue by twzchi** [txthinking/brook#306]
#### Describe actual behavior
玩多人游戏（比赛）模式，
#### What is your expected behavior
进游戏玩一会就会闪退
#### Specifications like the version of the project, operating system, or hardware
brook版本V20180707，Gameloft狂野飙车8，和极限越野多人比赛，在比赛进行时，突然闪退，提示无可用网络
不知道安卓8。0的问题还是软件问题，抑或网络问题，但是我使用Ssr创建的不会。
 （测试开了多端口，依旧会，不知道是不是openvz服务器架构的问题，因为我的ssr是kvm服务器）

**Comment by nemoming** [comment]
...Not an issue
