### ISSUE TITLE
ISO 12 bet1 版 浏览器可以翻墙 WhatsApp和viber 无法使用 

### ISSUE THREAD

**Issue by wulongji2016** [txthinking/brook#309]
ISO 12 bet1 版 浏览器可以翻墙 WhatsApp和viber 无法使用 
iOS 最新12 测试版
brook 最新 2018.6.1 版 
使用全局模式 
（其他翻墙软件测试：可以以上两个软件翻墙使用  故不是手机的问题）

**Comment by dwsr36** [comment]
https://github.com/txthinking/brook/issues/177#issuecomment-397946487
