### ISSUE TITLE
安卓0707版本无法开启白名单模式

### ISSUE THREAD

**Issue by heptaspirit** [txthinking/brook#310]
华为p10
安卓8.0
EMUI8.0
Brook 0707
Brook协议

小米5x
安卓7.1.2
MIUI9.0
Brook 0707
Brook协议

1. 白名单模式，点击开启，无法连接，出现如下提示
Platformexception(UNAVAILABLE, Attempt to invoke virtual method 'java. lang String.java.lang.Object.toString()' on a null object reference, null)
2. 无视提示，再次选择启动，Brook自动退出
3. 黑名单模式同上
4. 重新选择全局模式打开，无异常

**Comment by mistlost** [comment]
索尼xz premium，安卓8.0.
brook v20180707
依旧无法连接，无论是白名单黑名单抑或是全局模式。能够正常启动，但无法工作，无论国内网站或者受限网站都无法访问，没有任何提示。。。曾经卸载过重装，以及尝试过网络设定重置，但是依然没能解决问题。

**Comment by txthinking** [comment]
@heptaspirit 
Have you operated mode(any type, tap actions)?

**Comment by fox777777777777** [comment]
模式里面可以自定义url，第二行app那项，把while_app.list,改成while.pac。手头没有安卓设备，mac上面测试过，可以试一试。

**Comment by txthinking** [comment]
@fox777777777777 You are wrong, android client only accept domain list and CIDR list.
https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client#android-gui-client

**Comment by txthinking** [comment]
@heptaspirit If you DO NOT operate anything on Mode page. Just try this:
https://github.com/txthinking/brook/wiki/How-to-use-Brook-Android-Client%3F
I think it will not prompt this error

**Comment by fox777777777777** [comment]
学习了

**Comment by ZachWuE** [comment]
It will be OK if you refill the url in or just clean the Brook app data && reset the VPN settings or reinstall Brook.   I think my case is the same as yours : CIDR & APP list url keep blank after installing the new version v0707 APP without uninstall the old one.

**Comment by heptaspirit** [comment]
Solved by uninstall and reinstall.
