### ISSUE TITLE
客户端是否可以加入HTTP/SOCKS5代理之间的切换

### ISSUE THREAD

**Issue by ZZYSonny** [txthinking/brook#312]
目前Windows客户端默认使用SOCKS5而Edge/IE不支持SOCKS5。

**Comment by ZZYSonny** [comment]
或者能在您的https://blackwhite.txthinking.com/上加两个XXX List Mode with http://127.0.0.1:1080吗？

**Comment by txthinking** [comment]
If you want create new pac, ex `http_white.pac` just send PR to https://github.com/txthinking/pac

**Comment by txthinking** [comment]
check https://github.com/txthinking/pac/blob/master/README.md
