### ISSUE TITLE
Google Scholar Webpage issue

### ISSUE THREAD

**Issue by everxq** [txthinking/brook#315]
#### When accessing scholar.google.com, it says 
 We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now. See Google Help for more information.

![issue](https://user-images.githubusercontent.com/26721844/41936651-729d15c0-79c0-11e8-974e-6bcc0d7c0108.PNG)

**Comment by txthinking** [comment]
https

**Comment by everxq** [comment]
Thanks ...
