### ISSUE TITLE
The white list doesn't work on Android.

### ISSUE THREAD

**Issue by bobwang3** [txthinking/brook#317]
安卓8.1氧，手机是一加5T
brook: v20180707

最大的问题依然是打不开局域网设备，连不上我192.168网段的内网NAS。
曾经在v20180401中正常，v20180601中就又开始连不上局域网IP，以前更早的版本也不行。

于是开始在v20180707中研究白名单功能
碰到的第一个问题是，在默认的白名单IP地址https://blackwhite.txthinking.com/white_cidr.list里依然没发现有局域网网段的IP地址。
尝试将white_cidr.list下载下来传到自己的webServer上，加上几个类似192.168.0.0/16之类的内网网段后发现并不工作，断开重新连接brook后依然无法访问内网。
测试了原地址的white_app.list，经过确认发现里面有youku，但是打开youku后被提示我的IP非中国大陆地区禁止播放。

说明白名单完全没有任何作用！

清空brook的应用数据口重新执行以上操作也是一样的问题。

**Comment by bobwang3** [comment]
更新一下问题进展。
在尝试过次之后，突然能在连接状态下访问内网IP了。
但app list仍然不起作用，youku会提示所在区域禁止播放，经查询优酷app的名字叫 com.youku.phone
然后我把它加在app list里让我自己的webServer上下载下来，保存后启动brook
启动youku后登陆，youku会弹窗问我是否要切换到到海外地区。有这个提示就说明它能发现我是走的海外的代理。选择不同意切换后，点击世界杯相关视频被提示禁止播放。

**Comment by lollipuss** [comment]
能教我怎么自定义app whitelist吗？刚从ssr转到Brook，啥也不懂…

**Comment by txthinking** [comment]
URL can't be changed on 20181212. I think it still needs some work to make it better.
