### ISSUE TITLE
brook windows server失败

### ISSUE THREAD

**Issue by hkhk366** [txthinking/brook#318]
我下载了brook_windows_amd64.exe改名为brook

然后管理员模式下CMD下执行brook server -l :9999 -p password

客户端无法成功代理，服务端只是每隔一段时间显示expired request

测试环境开放了所有端口，系统WINDOWS 2008R2，IP正常，请问我的设置有什么问题吗？

**Comment by txthinking** [comment]
Please check your OS time, both server and client OS
