### ISSUE TITLE
How to make brook listen on all ip address?

### ISSUE THREAD

**Issue by ZZYSonny** [txthinking/brook#320]
I set up a brook server on an openwrt router. Port forwarding is fine and I can SSH through my public ip to my router. I've tried those command to launch the server.

1)./brook server -l :port  -p password -tcpDeadline 1800 or ./brook server -l 0.0.0.0:port  -p password -tcpDeadline 1800
I can connect to the server by HTTP mode by command line but not on my Android. I can see error log connecting websites that my router can't connect.

2)./brook server -l 192.168.31.1:port  -p password -tcpDeadline 1800
192.168.31.1 is the ip address of my router. I can only connect it through 192.168.31.1 in my Android client.

2)./brook server -l my_public_ip:port  -p password -tcpDeadline 1800
I can connect to the server through my public address in this case. But since my ip is changing, I can't use this to start my brook server automatically when the router is on.

**Comment by bhzhu203** [comment]
Maybe you could try   -l :port   without IP ?
