### ISSUE TITLE
来自macOS版本的Brook异常流量

### ISSUE THREAD

**Issue by haroldrandom** [txthinking/brook#321]
#### Describe actual behavior
我的mac装了Brook的macOS版本，服务器部署正确（浏览器已经能科学上网），同时安装有Proxifier，代理到1080端口，我的TG通过Proxifier代理流量到Brook从而实现上网，请问为何我的TG会有出现访问www.txtinking.com的流量呢？macOS版本的客户端有什么需要访问该网址呢？这个网址似乎是属于作者您的域名
![image](https://user-images.githubusercontent.com/14357159/42128338-a37d29d2-7cdb-11e8-9029-ee2a6bdc4470.png)

切换到 ShadowsocksX-NG 为代理之后异常流量消失了

#### Specifications like the version of the project, operating system, or hardware
Brook服务端最新版本，Brook macOS最近版本，macOS 10.13.4

**Comment by txthinking** [comment]
黑白名单在 https://github.com/txthinking/pac 项目

https://www.txthinking.com/pac 指向 pac 项目的 github page.
https://github.com/txthinking/pac/blob/master/CNAME
https://github.com/txthinking/txthinking.github.io/blob/master/CNAME
