### ISSUE TITLE
IOS 12 telegram always connecting……

### ISSUE THREAD

**Issue by blazing11** [txthinking/brook#328]
升级到ios12 之后telegram无法登陆…VPN不奏效，别的应用VPN可以正常使用。可能是个bug

**Comment by blazing11** [comment]
不过我之前旧的手机上的telegram都没有用proxy…

**Comment by fox777777777777** [comment]
逗比里面有个telegram专门的代理可以试一下https://doub.io/shell-jc7/

**Comment by blazing11** [comment]
@fox777777777777 这个苹果商城里面没有呀…

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/issues/285
