### ISSUE TITLE
some questions in  brook_windows_amd64.exe

### ISSUE THREAD

**Issue by Gxz-NGU** [txthinking/brook#334]
There are some problems when I use  brook_windows_amd64.exe.

#### Steps to reproduce the problem
0.I use terminal in Windows to input: ```
.\brook.exe client -l 127.0.0.1:1080 -i 127.0.0.1 -s server:port -p 
passwrod
```
1.and then: the cursor just stop in the nextline. Nothing happened, and I can't use google.
2.wait and wait, nothing happend. The cursor just stop in there.
I confused, please give me some help.

**Comment by ToyoDAdoubi** [comment]
Have you modified [System Proxy Settings]?

After launching the Brook client, the browser does not have direct access to Google.
You need to modify [System Proxy Settings] to IP: `127.0.0.1` PORT: `1080` or use the proxy management extension for the browser: `SwitchyOmega`

Are you Chinese?
If so, our exchange will be more convenient.

**Comment by txthinking** [comment]
wiki plz
