### ISSUE TITLE
Android client FC when disconnect

### ISSUE THREAD

**Issue by breadmaster** [txthinking/brook#337]
#### Describe actual behavior
app crash
#### What is your expected behavior
no crash
#### Specifications like the version of the project, operating system, or hardware
Process: com.txthinking.brook
Flags: 0x3888be44
Package: com.txthinking.brook v20180707 (20180707)
Foreground: No
Build: samsung/nobleltezh/nobleltehk:7.0/NRD90M/N9200ZHU3DRF2:user/release-keys

java.lang.RuntimeException: Unable to stop service com.txthinking.brook.BrookVPNService@2e08e1b: java.lang.IllegalStateException: Reply already submitted
	at android.app.ActivityThread.handleStopService(ActivityThread.java:3735)
	at android.app.ActivityThread.-wrap30(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1741)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1534)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1424)
Caused by: java.lang.IllegalStateException: Reply already submitted
	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:162)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
	at com.txthinking.brook.BrookVPNService.stop(BrookVPNService.java:62)
	at com.txthinking.brook.BrookVPNService.onDestroy(BrookVPNService.java:31)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:3718)
	... 8 more
#### Steps to deploy the server
0. ubuntu 16.04.4 LTS
1. download brook for linux
2. ./brook server -l :9999 -p password

#### Steps to reproduce the problem
0. open and config android client, start service and make brook running in bg
1. surfing with browser, everything is fine
2. disconnect from system notification, FC

**Comment by Ccapton** [comment]
> #### Describe actual behavior
> app crash
> 
> #### What is your expected behavior
> no crash
> 
> #### Specifications like the version of the project, operating system, or hardware
> Process: com.txthinking.brook
> Flags: 0x3888be44
> Package: com.txthinking.brook v20180707 (20180707)
> Foreground: No
> Build: samsung/nobleltezh/nobleltehk:7.0/NRD90M/N9200ZHU3DRF2:user/release-keys
> 
> java.lang.RuntimeException: Unable to stop service com.txthinking.brook.BrookVPNService@2e08e1b: java.lang.IllegalStateException: Reply already submitted
> at android.app.ActivityThread.handleStopService(ActivityThread.java:3735)
> at android.app.ActivityThread.-wrap30(ActivityThread.java)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1741)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:154)
> at android.app.ActivityThread.main(ActivityThread.java:6682)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1534)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1424)
> Caused by: java.lang.IllegalStateException: Reply already submitted
> at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:162)
> at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
> at com.txthinking.brook.BrookVPNService.stop(BrookVPNService.java:62)
> at com.txthinking.brook.BrookVPNService.onDestroy(BrookVPNService.java:31)
> at android.app.ActivityThread.handleStopService(ActivityThread.java:3718)
> ... 8 more
> 
> #### Steps to deploy the server
> 1. ubuntu 16.04.4 LTS
> 2. download brook for linux
> 3. ./brook server -l :9999 -p password
> 
> #### Steps to reproduce the problem
> 1. open and config android client, start service and make brook running in bg
> 2. surfing with browser, everything is fine
> 3. disconnect from system notification, FC

### Me too! But it doesn't matter.
### I am sure your android os is a developing version,not a released version.is it?
Android will throw errors in developing mode when apps crash.

**Comment by txthinking** [comment]
![image](https://user-images.githubusercontent.com/1241807/52031439-909b7380-2557-11e9-8e2a-509ce95856c1.png)

When I tap `Device connected to Brook`

![screenshot_20190131-124651](https://user-images.githubusercontent.com/1241807/52031463-a6a93400-2557-11e9-9773-27e31c0008f3.png)


* When I tap `OK`, just nothing happen
* When I tap `Open VPN Settings`, jump to system `Setting` app
   * I can successfully disconnect VPN in `Setting` app

I think this caused by third-party ROM.
