### ISSUE TITLE
WhatsApp could not connect to internet using latest vertion from App store v20180601

### ISSUE THREAD

**Issue by georgexu78** [txthinking/brook#338]
WhatsApp could not connect to internet

WhatsApp version 2.18.71 could not connect to internet

Brook Service: v20180707
Service System: Ubuntu 17.10 x64
CLIENT:  IOS APP VERSTION v20180601
IOS SYSTEM 11.4  

my IOS device could not connect to WhatApp under Globle, White list or Blacklist. but no problem to connect to google, youtube. 
Hope you guys could fix it. thanks very much

**Comment by SJTUboy** [comment]
Check this issue, maybe helpful.

https://github.com/txthinking/brook/issues/285

#285

**Comment by SJTUboy** [comment]
#177

**Comment by txthinking** [comment]
#689
