### ISSUE TITLE
安卓端无法连接

### ISSUE THREAD

**Issue by mycjc** [txthinking/brook#339]
#### Steps to deploy the server
centos6
使用的是逗比一键部署脚本
https://doub.io/brook-jc3/
服务器版本20180707
#### Steps to reproduce the problem
从Brook20180601开始出现安卓端能出现钥匙图标，但是无法访问外网的情况。
依照 #325  中的方法并未能解决问题。
Brook在Win和ios可以正常运行。

**Comment by aaa910618** [comment]
我也是，哎，好无奈

**Comment by aaa910618** [comment]
用ssr又不放心，怕查水表

**Comment by aaa910618** [comment]
大佬你问题解决了吗？解决了请告诉我一声
