### ISSUE TITLE
can't open on macOS10.13.6

### ISSUE THREAD

**Issue by LeiGitWing** [txthinking/brook#340]
#### Describe actual behavior
之前用得好好的，突然就打不开google等的网页了
#### Specifications like the version of the project, operating system, or hardware
Brook v20180707, macOS10.13.6
#### Steps to deploy the server
0.gcp台湾服务器搭载了魔改bbr

#### Steps to reproduce the problem
0.打开safari
1.输入YouTube
2.打不开

**Comment by SJTUboy** [comment]
It works in my MacBook, maybe you should check your VPS settings

![image](https://user-images.githubusercontent.com/13373715/43059733-7c1d4852-8e80-11e8-8ced-797516096d84.png)

![image](https://user-images.githubusercontent.com/13373715/43059743-8ba07ce0-8e80-11e8-89ab-350e0102afee.png)

![image](https://user-images.githubusercontent.com/13373715/43059770-a7bac444-8e80-11e8-8c80-12555d24a1c9.png)

**Comment by LeiGitWing** [comment]
网页突然打不开这个问题是时好时坏的，现在我又打得开了，之前也出现过好几次。vps也ping得通
