### ISSUE TITLE
Add widget on iOS to switch on and off quickly

### ISSUE THREAD

**Issue by SJTUboy** [txthinking/brook#342]
Hi @txthinking 

Due to the issues that Brook in iOS sometimes loses connection and users can't custom rules.
See discussions in these issues #305 #283 
I was wondering if you can add widget on later iOS version so that users can switch on and off Brook quickly.

![img_1684](https://user-images.githubusercontent.com/13373715/43184010-b324648a-9019-11e8-968b-3d0ada5dbf80.PNG)

![img_1685](https://user-images.githubusercontent.com/13373715/43184016-bd0be482-9019-11e8-8b00-9acc5e07e20a.PNG)

**Comment by txthinking** [comment]
Sorry, there is no such plan for the time being.
