### ISSUE TITLE
iOS client doesn't work

### ISSUE THREAD

**Issue by chenyan2002** [txthinking/brook#346]
#### Describe actual behavior
In iOS client, press "start", the button becomes "stop", but vpn icon doesn't show up. In setting, manually start the brook vpn, sometimes it works with multiple tries. Tried iOS client on three different iPad and iPhones, the problem is the same.
On the server side, there is no log, and it didn't show any ip address connected.
I have an Android client which is always working.

#### What is your expected behavior
See above.

#### Specifications like the version of the project, operating system, or hardware
Server side v20180707, iOS client v20180601. Tried to downgrade the server to 20180601, the problem is the same.
Server running on Debian x64.

#### Steps to deploy the server
script from doub.io, deployed on GCP.

#### Steps to reproduce the problem
See above.

**Comment by chenyan2002** [comment]
I have one phone that has no other VPNs, the problem is the same. On iPad, after removing JiGuang VPN, the chance of connecting is slightly up, but still pretty unstable. Any way I can help to troubleshoot this further?

**Comment by FrankZhang002** [comment]
I have the same question on IOS12, but IOS11 Brook works fine.

**Comment by xiaoxiongke** [comment]
VPN switch will change to off about 3 minutes later, this is my problems,and it seems it appears only on iOS 12 beta 6 or later.

**Comment by txthinking** [comment]
#371
