### ISSUE TITLE
Linux CLI client not responding

### ISSUE THREAD

**Issue by leosuperbugs** [txthinking/brook#347]
#### Describe actual behavior
./brook client -l 127.0.0.1:1080 -i 127.0.0.1 -s my.server:myport -p mypassword

#### What is your expected behavior
The client should start. But the client doesn't response and I have to use ctrl-c to stop it.

#### Specifications like the version of the project, operating system, or hardware
client: 0707 Linux amd64; installed with: wget https://github.com/txthinking/brook/releases/download/v20180707/brook
My client is a server on Tencent cloud, may this be the problem?

#### Steps to deploy the server
Server is ok. Running as Brook mode.

#### Steps to reproduce the problem
0. wget https://github.com/txthinking/brook/releases/download/v20180707/brook
1. chmod; install
2. ./brook client -l 127.0.0.1:1080 -i 127.0.0.1 -s my.server.com:9966 -p my_password

**Comment by txthinking** [comment]
> The client should start. But the client doesn't response and I have to use ctrl-c to stop it.

This is normal. Follow your steps. You can test with `$ curl -x socks5://127.0.0.1:1080 ifconfig.co`

**Comment by dllp007king** [comment]
test with $ curl -x socks5://127.0.0.1:1080 ifconfig.co


re：my.server.com（ip）
but i ssh my.server.com type netstat .can't see any client ip from :9966
