### ISSUE TITLE
Protocol is detected

### ISSUE THREAD

**Issue by Dr-Bluemond** [txthinking/brook#348]
#### Describe actual behavior
My server is blocked:

brook client -i 127.0.0.1 -l 127.0.0.1:1080 -s ip:port -p password
2018/08/01 08:57:30 dial tcp ip:port: i/o timeout
2018/08/01 08:57:30 dial tcp ip:port: i/o timeout
2018/08/01 08:57:30 dial tcp ip:port: i/o timeout
2018/08/01 08:57:30 dial tcp ip:port: i/o timeout
2018/08/01 08:57:30 dial tcp ip:port: i/o timeout
2018/08/01 08:57:30 dial tcp ip:port: i/o timeout
2018/08/01 08:57:30 dial tcp ip:port: i/o timeout
2018/08/01 08:57:30 dial tcp ip:port: i/o timeout
2018/08/01 08:57:30 Invalid Version

Besides, ssh is also blocked by the GFW. 

Many users have faced this problem.

#### What is your expected behavior
To have the protocol improved.
#### Specifications like the version of the project, operating system, or hardware
0707 Server:Ubuntu 14.0 Client:MacOS&Android
#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.wait for the gfw to find you
1.
2.

**Comment by txthinking** [comment]
Please learn more about GFW.
