### ISSUE TITLE
if i need to worry my information when use this app

### ISSUE THREAD

**Issue by Leeforrest** [txthinking/brook#35]
I have down load this app on my ios, first of all,  thank you for offering such a total free and good app for us,  but i fill a lot uneasy, since it is free, i am a lot worry about my information， if I should worry that

**Comment by txthinking** [comment]
**Your worry is superfluous.**

Here is a example when you visit https://www.google.com
```
You iPhone <--[chiper data]--Some ISP Nodes--[chiper data]--Brook Server(s)--[chiper data]-->Google Server
```
If you visit http://www.example.com (not https)
```
You iPhone <--[chiper data]--Some ISP Nodes--[chiper data]--Brook Server(s)--[plaintext data]-->Example Server
```

**Comment by Leeforrest** [comment]
thank you very much
