### ISSUE TITLE
Telegram Mac client not works with Brook

### ISSUE THREAD

**Issue by MonKong** [txthinking/brook#351]
My TG shows connecting when using Brook, and TG works when using Lantern.
I set up Brook server by one script on doub.io.

TG version: 4.2.2.136795Beta
OSX version: 10.13.6

**Comment by mosdeo** [comment]
Setting proxy
https://t.me/socks?server=127.0.0.1&port=1080

**Comment by txthinking** [comment]
Brook GUI Client for MacOS, only open socks5://127.0.0.1:1080 (default).
If you need a http proxy, try Brook CLI client.
