### ISSUE TITLE
ipv6 have some problem

### ISSUE THREAD

**Issue by wangjiya123** [txthinking/brook#354]
安卓版本的Brook，在中国移动的数据下开启的时候会报错，提示 SocketException:Failed host lookup:'我的IP地址'（OS Error:No address associated with hostname,errno 7) 我这边中国移动的数据流量能直接获取到Ipv6 的地址，所以我猜这个报错是因为Ipv6引起的，希望楼主修复Bug.而联通的数据使用的是Ipv4的网络，联通数据没发现这个问题。

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/wiki/IPv6
