### ISSUE TITLE
Feature Request: support file:// URL format in "white list", "black list" and "PAC" mode

### ISSUE THREAD

**Issue by johnnychen94** [txthinking/brook#355]
#### Describe actual behavior
Currently, for **white list**, **black list** and **PAC** mode, only `http:// `format URL is supported. Hence an http server is needed to provide .list and .pac files. It can't read .pac and .list files stored in local machine.

#### What is your expected behavior
I hope the following `file://` URL format is supported for **white list**, **black list** and **PAC** mode:

`file:///Users/jc/pac/white.pac` for MacOS/Linux OS
and
`file://C:\pac\white.pac` for WinOS

**Comment by SJTUboy** [comment]
Agree

**Comment by txthinking** [comment]
Fixed in v20190205.

**Comment by txthinking** [comment]
If it doesn't work, jus reopen this issue.
