### ISSUE TITLE
Brook icon(on Mac menu bar) is invisible When i check "Use dark menu bar and Dock"

### ISSUE THREAD

**Issue by acalephx** [txthinking/brook#356]
#### Describe actual behavior
Brook icon(on Mac menu bar) is invisible When i check "Use dark menu bar and Dock".
![screen shot 2018-08-19 at 18 29 47](https://user-images.githubusercontent.com/29752506/44307937-21cdc200-a3de-11e8-9831-57d9753cbe8f.png)

When i uncheck "Use dark menu bar and Dock" , the icon is visible.
![screen shot 2018-08-19 at 18 31 02](https://user-images.githubusercontent.com/29752506/44307939-25f9df80-a3de-11e8-9713-aca81298c099.png)

#### What is your expected behavior
i hope the icon color can be visible When i check "Use dark menu bar and Dock". Maybe change the icon color to gray or some other color will be one solution.

#### Specifications like the version of the project, operating system, or hardware
macOS:  10.13:	(17A360)

**Comment by txthinking** [comment]
![image](https://user-images.githubusercontent.com/1241807/44902266-18c4e500-ad3c-11e8-9f9d-8999fa3dedef.png)
