### ISSUE TITLE
请教一下，Brook无法作为服务在Centos7上启动

### ISSUE THREAD

**Issue by GSCmax** [txthinking/brook#359]
brook.service配置如下

```
[Unit]
Description=brook
After=network.target

[Service]
Type=forking
ExecStart=/usr/bin/brook server -l :8889 -p password
ExecReload= 
ExecStop= 
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

启动服务时报错如下：
![default](https://user-images.githubusercontent.com/8372598/44572128-8198e400-a7b5-11e8-8f03-711c37ccd247.png)

大家有没有遇到这个情况的，该如何配置呢？

**Comment by GSCmax** [comment]
直接运行ExecStart中的命令的可以启动Brook并正常使用的

**Comment by txthinking** [comment]
https://github.com/txthinking/dotfiles/blob/master/brook/brook.service
