### ISSUE TITLE
VPN mode, hint: Can not find default gateway.

### ISSUE THREAD

**Issue by ToyoDAdoubi** [txthinking/brook#368]
Environment: Windows 10.
Reproduce steps:
```
D:\> .\brook.exe vpn -l 127.0.0.1:1080 -s ip:port -p password
Can not find default gateway
D:\> .\brook.exe vpn -l 127.0.0.1:1080 -s ip:port -p password
Can not find default gateway
```

In addition, why is the latest version not releasing the amd64 Linux client/server?

**Comment by txthinking** [comment]
😬I forgot amd64 linux binary file. Fixed.

**Comment by txthinking** [comment]
Windows Settings -> Time & Language -> Region & Language .

![image](https://user-images.githubusercontent.com/1241807/44896524-13ab6a00-ad2b-11e8-8a66-fed57eba28fd.png)

**Comment by ToyoDAdoubi** [comment]
Windows must choose UTF-8 to use VPN mode, is it because Brook or TAP?
Because some software may be garbled due to compatibility issues when UTF-8 is selected.
Is it possible to circumvent the UTF-8 option?

**Comment by txthinking** [comment]
Caused by Brook. I build a new version:
https://storage.googleapis.com/txthinking-file/_/brook_windows_amd64.exe

Added an Option
```
--defaultGateway value      Your default gateway, Only needed on windows that are not utf8 encoded.
```
You can get default gateway by `> ipconfig`

**Comment by ToyoDAdoubi** [comment]
After testing, this file can be used normally in systems that are not UTF-8 encoded.

However, I found a problem with DNS resolution for VPN mode.

When I visited Google, I got the wrong IP, and when I used the `nslookup -qt=A www.google.com 8.8.8.8` command, I got the correct IP.

But when I `ping www.google.com` , I get the wrong IP, even if I use the `ipconfig /flushdns` command to refresh the DNS cache.

Clearing the browser cache is invalid.

In the hosts file, when I point www.google.com to the correct IP, my browser can access www.google.com normally.

**Comment by txthinking** [comment]
Thanks. Please try:

Fixed DNS problem.
https://storage.googleapis.com/txthinking-file/_/brook_windows_amd64_1.exe

**Comment by ToyoDAdoubi** [comment]
After testing, everything is ok!

**Comment by txthinking** [comment]
OK, I have updated the binaries on the release page.
