### ISSUE TITLE
The latest version not work on Windows 10

### ISSUE THREAD

**Issue by Neil-Nimrod** [txthinking/brook#369]
When click on "Toggle"
The Brook said "The filename, directory name, or volume label syntax is incorrect"
I can only use the "20180601" or elder version on my computer
The latest  version is working well on my android phone

**Comment by Neil-Nimrod** [comment]
PS:I am a Chinese user
I wonder if Brook could not work on China Version Windows OS

**Comment by txthinking** [comment]
Try:
1. Uninstall brook GUI client for windows.
2. Download brook GUI client for windows and install.

**Comment by Neil-Nimrod** [comment]
I've tired already
But still not work

**Comment by mygoodsemail** [comment]
It works well on my windows 10 x64 v16299
![tim 20180905095758](https://user-images.githubusercontent.com/26641112/45066730-48843c00-b0f2-11e8-93c3-2b2a9c94e4cd.jpg)

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/issues/436
