### ISSUE TITLE
ios telegram always connecting..

### ISSUE THREAD

**Issue by suhaotian** [txthinking/brook#37]
ios 上的 telegram 无法连接网络，在 mac 的telegram客户端上可以设置 socks 5 代理为 ss 的代理地址，
但是在 ios 上怎么得到 brook 开的ip端口呢？

**Comment by txthinking** [comment]
> ios 上的 telegram 无法连接网络

猜测可能是tg应用或某些域名或某些IP没有走代理, [txthinking/pac](https://github.com/txthinking/pac)白名单里应该没有tg的域名，不知白名单IP段是不是包含了，需要抽空抓包看下

> 但是在 ios 上怎么得到 brook 开的ip端口呢

ios上监听的是 `127.0.0.1:1090` 如果是IPv4网络的话.
但是tg ios客户端没有地方设置代理吧?

**Comment by suhaotian** [comment]
有地方的, 登录后， 在 settings => Data and Storage， 滚到底部有个 Use Proxy 可以配置。

我试试 127.0.0.1:1090 一直显示 connecting to proxy ..

**Comment by txthinking** [comment]
那俺抽时间还得研究研究

**Comment by iinsta** [comment]
抓取的ip是： http://91.108.56.159:443

**Comment by txthinking** [comment]
已找到解决方案, 近几日抽空再测测没问题会发新包提交app store

**Comment by suhaotian** [comment]
@txthinking 有空分享下呗 :+1:

**Comment by txthinking** [comment]
Fixed iOS 20170716

**Comment by suhaotian** [comment]
测试了，现在一直显示 on updating...发信息也发不出去

**Comment by txthinking** [comment]
@iinsta 阁下那边tg可以访问吗

**Comment by iinsta** [comment]
也是

**Comment by iinsta** [comment]
和 @suhaotian 同样情况，发信息发不出去，

**Comment by iinsta** [comment]
要不找找设置socks5代理不行的原因？

**Comment by txthinking** [comment]
不要设置Telegram内部的代理配置。

**Comment by iinsta** [comment]
没，首先一直 updating... 然后再去试试设置代理，发现也不行。

**Comment by txthinking** [comment]
我的机器是 iPhone SE, 
Telegram 是美区: https://itunes.apple.com/us/app/telegram-messenger/id686449807
我的步骤是:

1. 下载Telegram
1. 配置Brook或Shadowsocks后Start (两个我都试过了，都可以)
1. 浏览器访问Google, 确保启动成功
1. 启动Telegram，登录 (正常)
1. Telegram 发消息 (正常)

**Comment by suhaotian** [comment]
刚刚测试，发信息可以了。 但是顶部一直显示 Updating....

**Comment by txthinking** [comment]
重新安装下tg试试

**Comment by suhaotian** [comment]
@txthinking

**Comment by blazing11** [comment]
@txthinking  升级到ios12后 也是一直connecting，无法登陆. vpn不奏效，其他的软件正常。

**Comment by yehh** [comment]
iOS 12,同样不能登录，Mac上可以设置Proxy

**Comment by MdWhat** [comment]
> 已找到解决方案, 近几日抽空再测测没问题会发新包提交app store

@txthinking 您好,我也遇到的同样的问题,telegram一直在connecting.....不知道您找到的方法可以分享一下吗? 非常感谢, 求大佬回复

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/issues/285
