### ISSUE TITLE
Brook is not compitable with IOS 12

### ISSUE THREAD

**Issue by FrankZhang002** [txthinking/brook#371]
Brook Version is V20180601 with IOS12 public beta 10.

After opening Brook on IOS12, the top VPN icon will soon disappear, and the connect between Brook and VPS will be interrupted.

**Comment by xiaoxiongke** [comment]
same with me,i think it relates to the beta system.

**Comment by chaodada** [comment]
我的也会是 ios12 正式版也是 一会就自动退出

**Comment by nuclearn** [comment]
#metoo

**Comment by SJTUboy** [comment]
Same Issue

**Comment by LizaCheung** [comment]
So... this issue cannot be fixed for now?😕...until the next version of Brook is released?

**Comment by nuclearn** [comment]
when to fix it?

**Comment by leosuperbugs** [comment]
quite a few people reported the same issue.

**Comment by linexy** [comment]
same issue,ios12

**Comment by cugxuan** [comment]
the same question!
wish the new release!

**Comment by txthinking** [comment]
#426
