### ISSUE TITLE
The version v20180909  dose not contain PAC model?

### ISSUE THREAD

**Issue by mygoodsemail** [txthinking/brook#374]
Thank you the BROOK author. 
The version v20180909  dose not contain PAC model?
![tim 20180905100620](https://user-images.githubusercontent.com/26641112/45067015-b4b36f80-b0f3-11e8-955c-85d24fceeda7.jpg)

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client

Open drawer and tap version 16 times to open mode page.

**Comment by kgbook** [comment]
tap 16 times works on Mac, but not on Android version.

Only Global, White List and Black List.

**Comment by mygoodsemail** [comment]
OK, thanks
