### ISSUE TITLE
Brook v20180909 is not working on my computer!

### ISSUE THREAD

**Issue by jslianglife** [txthinking/brook#379]
I've successfully installed Brook on my server. It does work on other computer, like my classmates'. However i doesn't work on my computer. When I turn off brook, something unexpected show up, as shown below. 
![image](https://user-images.githubusercontent.com/43058632/45201338-81b1dd00-b2a7-11e8-965e-e75985b01e1a.png)
In fact, I have installed other VPN software previously, which has been uninstalled now. If it's related to my problem? Thanks a lot and look forward to your help!

**Comment by txthinking** [comment]
It works when brook running?

**Comment by jslianglife** [comment]
On other computers, brook does work when it is running on my server. However, it doesn't work even if brook is started both on the server and my computer.

**Comment by Neil-Nimrod** [comment]
It's not working on my computer
The same situation as yours

**Comment by Neil-Nimrod** [comment]
Just use v20180601
It's working well on every computer I've tried

**Comment by jslianglife** [comment]
@Neil-Nimrod Thanks a lot, I will try it right now!
