### ISSUE TITLE
Can't work with iphone 6

### ISSUE THREAD

**Issue by iinsta** [txthinking/brook#38]
同一个账号在我的 iphone 7上可以使用，但是在iphone6不行，无法访问外网。 不知道什么原因 🙃

**Comment by iinsta** [comment]
系统都是最新的版本..

**Comment by iinsta** [comment]
试了 wingy 也不行，iphone 7 上可以，系统都是最新版。。。。

**Comment by iinsta** [comment]
和wingy一样： https://github.com/hellowingy/wingy-announcement/issues/39

**Comment by txthinking** [comment]
我记得有之前有朋友正常运行于iPhone6 plus。
iPhone6 上的系统是最新具体是 iOS 10.3.2 吗,
还有可以提供下现象及重现步骤吗， 比如:

配置好后，点击Start, 出现了[vpn]标识，但是上不了外网，可以上中华局域网。
配置好后，点击启动失败，根本就没有出现[vpn]标识
配置好后，点击Start, 出现了[vpn]标识，但是瞬间消失.

**Comment by suhaotian** [comment]
我这里也有这种情况，是第一种：配置好后，点击Start, 出现了[vpn]标识，但是上不了外网，可以上中华局域网。


微信可以发信息，就是无法访问网页

**Comment by txthinking** [comment]
周末让朋友的iPhone 6P试了下正常，没找到6. 6和6P会有很大差距么。

2017-07-18 16:09 GMT+08:00 suhaotian <notifications@github.com>:

**Comment by txthinking** [comment]
@iinsta Can you try new v20171111 on your iPhone 6?

**Comment by iinsta** [comment]
😄 已肉翻
