### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by zerozero123** [txthinking/brook#381]
#### Describe actual behavior
I want to konw why can not I bypass Chinese address?
#### What is your expected behavior
Increase routing
#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.
1.
2.

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/wiki/How-to-use-Brook-Android-Client%3F

all DNS queries are passed through the server now.

**Comment by zerozero123** [comment]
It means that the data goes globally

Cloud <notifications@github.com> 于 2018年9月9日 周日 05:49写道：
