### ISSUE TITLE
How to run VPN with Brook(GUI) on Mac

### ISSUE THREAD

**Issue by kgbook** [txthinking/brook#382]
I downloaded the latest release version [Brook-GUI_v20180909_Mac.dmg](https://github.com/txthinking/brook/releases/download/v20180909/Brook.dmg)

Reading [REDAME#vpn](https://github.com/txthinking/brook#vpn) and [wiki#vpn](https://github.com/txthinking/brook/wiki/How-to-run-VPN-on-Linux,-MacOS-and-Windows%3F), and It seems vpn mode need run in the Command Line environment.

The type of Brook Server in the setting of [Brook-GUI_v20180909_Mac](https://github.com/txthinking/brook/releases/download/v20180909/Brook.dmg)
is Brook, Brook Stream, and Shadowsocks. No type named vpn.

I knew it's not bad to configure vpn in system preference on Mac OS X, but switching proxy type with Brook seems more convenient.

I hope to run in vpn mode with  [Brook-GUI_v20180909_Mac](https://github.com/txthinking/brook/releases/download/v20180909/Brook.dmg), is it possible?

**Comment by txthinking** [comment]
On MacOS/Windows, GUI client maybe support vpn mode in next version.

**Comment by txthinking** [comment]
#629
