### ISSUE TITLE
In Commandline (MacOS) ,brook client doesn't work without setting Pac 

### ISSUE THREAD

**Issue by Ccapton** [txthinking/brook#383]
### Thank You Very Much
Hello txthinking!I'm a Chinese user.Thank you very much for offering us such a pretty tool to browse outdoor world! 
### My Question
I use brook in command line (MacOS) . Without setting SystemProxy a Pac url,It doesn't work until I set the pac. 
After I have set the systemproxy with pac url "https://blackwhite.txthinking.com/http_white.pac",It work  well!
- ### So ,Is it necessary to set systemproxy with pac url before starting brook client ?

**Comment by txthinking** [comment]
Yes. try $ brook systemproxy
