### ISSUE TITLE
vpn模式 ssh连接断开

### ISSUE THREAD

**Issue by EverCurse** [txthinking/brook#384]
> 我开启vpn模式 ubuntu16.04 vps
``` ./brook vpn --server 0.0.0.0:12345  --listen 127.0.0.1:10800  --password hello123 ```

>报错 我本地直接与服务器断开了ssh连接 
``` packet_write_wait: Connection to 193.110.203.111 port 22: Broken pipe ```

非常感谢作者 希望有空能解答

**Comment by Ccapton** [comment]
vpn模式就是全部端口的TCP/UDP流量走 你这个10800端口 连接到服务器的12345端口。所以会断开原有的端口 为22 的ssh服务 ，没毛病的

**Comment by Ccapton** [comment]
> > 我开启vpn模式 ubuntu16.04 vps
> > `./brook vpn --server 0.0.0.0:12345 --listen 127.0.0.1:10800 --password hello123`
> 
> > 报错 我本地直接与服务器断开了ssh连接
> > `packet_write_wait: Connection to 193.110.203.111 port 22: Broken pipe`
> 
> 非常感谢作者 希望有空能解答
vpn模式就是全部端口的TCP/UDP流量走 你这个10800端口 连接到服务器的12345端口。所以会断开原有的端口 为22 的ssh服务 ，没毛病的

**Comment by EverCurse** [comment]
@Ccapton 嗯嗯 我弄错了 我服务器运行客户端的命令了 。弄反了 谢谢了哈 现在测试没问题了 。

**Comment by Ccapton** [comment]
> @Ccapton 嗯嗯 我弄错了 我服务器运行客户端的命令了 。弄反了 谢谢了哈 现在测试没问题了 。

朋友在吗 我写了一个brook服务端管理程序，你可以帮我测试一下你的Linux吗
https://github.com/Ccapton/brook-ok

**Comment by EverCurse** [comment]
@Ccapton 在的 好的 我先看看

**Comment by Ccapton** [comment]
> @Ccapton 在的 好的 我先看看

我的微信号 Ccapton ，有问题麻烦给我个回应呦，谢谢了
