### ISSUE TITLE
vpn mode can't use server_address with a domain

### ISSUE THREAD

**Issue by Jake-Qu** [txthinking/brook#385]
centos7.5 
Brook version 20180909
when i execute "./brook vpn -l 127.0.0.1:1080 -s  example.com:443 -p mypassword"
then brook return a error:Error: any valid prefix is expected rather than "example.com".
it works on the ip address

**Comment by txthinking** [comment]
Only support IP.

**Comment by Jake-Qu** [comment]
can later version support domain?

**Comment by txthinking** [comment]
v20181212

**Comment by txthinking** [comment]
![image](https://user-images.githubusercontent.com/1241807/49128427-5cf95e80-f306-11e8-8c5c-4e0776294c55.png)
