### ISSUE TITLE
Can not find default gateway?

### ISSUE THREAD

**Issue by luckypoem** [txthinking/brook#389]
root@whme:~# wget https://github.com/txthinking/brook/releases/download/v20180909/brook -O brook_linux_amd64 && chmod 755 brook_linux_amd64
root@whme:~# ./brook_linux_amd64 vpn -l 127.0.0.1:1089 -s 0.0.0.0:7009 -p iloveson
Can not find default gateway
root@whme:~#

how to fix it?

**Comment by luckypoem** [comment]
@F-TD5X 
没法改main.go文件，我使用的是下载的可执行文件：
wget https://github.com/txthinking/brook/releases/download/v20180909/brook -O brook_linux_amd64 && chmod 755 brook_linux_amd64

你在你的linux vps上，有遇到我这样的错误：Can not find default gateway吗？
我试了好几个vps,都是这样的错误提示。真是怪事。

**Comment by F-TD5X** [comment]
Well, you can manually set defaultGateway like `brook vpn -l 127.0.0.1:<port> -s <server>:<port> -p <password> --defaultGateway <gateway>`

You can get your gateway by `netstat -m`,`route -n`, or view the `eth configs`

> What I showed to u is not want u to build your own version.
> By the way, this project has some import circle. Hoping author will fix it later.

**Comment by luckypoem** [comment]
hi.
help里说“Your default gateway, Only needed on windows ”，所以不用加--defaultGateway参数吧？？

root@whme:~# ./brook_linux_amd64 vpn -h
NAME:
   brook_linux_amd64 vpn - Run as VPN mode

USAGE:
   brook_linux_amd64 vpn [command options] [arguments...]

OPTIONS:
   --listen value, -l value    Client listen address, must use 127.0.0.1, like: 127.0.0.1:1080
   --server value, -s value    Server address, must use IP, like: 1.2.3.4:1080
   --password value, -p value  Server password
   --tcpTimeout value          connection tcp keepalive timeout (s) (default: 60)
   --tcpDeadline value         connection deadline time (s) (default: 0)
   --udpDeadline value         connection deadline time (s) (default: 60)
   --udpSessionTime value      udp session time (s), in most cases need this (default: 60)
   --tunDevice value           tun name (default: "tun0")
   --tunIP value               tun IP (default: "10.9.9.2")
   --tunGateway value          tun gateway (default: "10.9.9.1")
   --tunMask value             tun mask (default: "255.255.255.0")
   --defaultGateway value      Your default gateway, Only needed on windows that are not utf8 encoded.
   
root@whme:~# ./brook_linux_amd64 vpn -s 0.0.0.0:2355 -p iloveson --tunDevice tun1 --tunIP 10.9.9.2 --tunGateway 10.9.9.1 --tunMask 255.255.255.0 
NAME:
   brook_linux_amd64 vpn - Run as VPN mode

USAGE:
   brook_linux_amd64 vpn [command options] [arguments...]

OPTIONS:
   --listen value, -l value    Client listen address, must use 127.0.0.1, like: 127.0.0.1:1080
   --server value, -s value    Server address, must use IP, like: 1.2.3.4:1080
   --password value, -p value  Server password
   --tcpTimeout value          connection tcp keepalive timeout (s) (default: 60)
   --tcpDeadline value         connection deadline time (s) (default: 0)
   --udpDeadline value         connection deadline time (s) (default: 60)
   --udpSessionTime value      udp session time (s), in most cases need this (default: 60)
   --tunDevice value           tun name (default: "tun0")
   --tunIP value               tun IP (default: "10.9.9.2")
   --tunGateway value          tun gateway (default: "10.9.9.1")
   --tunMask value             tun mask (default: "255.255.255.0")
   --defaultGateway value      Your default gateway, Only needed on windows that are not utf8 encoded.
root@whme:~#

他这个程序很奇怪，就是运行不起来。我运行ifconfig，根本没看到这个brook创建了任何net interface.

**Comment by luckypoem** [comment]
@F-TD5X 运行什么命令，才能让这个brook创建它自己的net interface呢？

**Comment by txthinking** [comment]
You need run `$ brook vpn` on your client compute, not on your server. Your
server should run `$ brook server`.
Please check wiki.

**Comment by luckypoem** [comment]
@txthinking
果然ok，能翻墙了。
非常感谢

**Comment by luckypoem** [comment]
不过只能维持25分钟，客户端命令就退出了.在mac的终端里显示：
2018/10/09 09:49:54 dial udp my-vps-ip:2466: socket: too many open files
2018/10/09 09:49:55 dial udp my-vps-ip:2466: socket: too many open files
2018/10/09 09:49:57 dial udp my-vps-ip:2466: socket: too many open files
Quitting...
2018/10/09 09:49:59 pipe: too many open files
2018/10/09 09:49:59 pipe: too many open files
2018/10/09 09:49:59 close tcp 127.0.0.1:5566: use of closed network connection
accept tcp 127.0.0.1:5566: accept: too many open files
bogon:~ brite$

怎么解决？

**Comment by txthinking** [comment]
> 不过只能维持25分钟，客户端命令就退出了.在mac的终端里显示：
> 2018/10/09 09:49:54 dial udp my-vps-ip:2466: socket: too many open files
> 2018/10/09 09:49:55 dial udp my-vps-ip:2466: socket: too many open files
> 2018/10/09 09:49:57 dial udp my-vps-ip:2466: socket: too many open files
> Quitting...
> 2018/10/09 09:49:59 pipe: too many open files
> 2018/10/09 09:49:59 pipe: too many open files
> 2018/10/09 09:49:59 close tcp 127.0.0.1:5566: use of closed network connection
> accept tcp 127.0.0.1:5566: accept: too many open files
> bogon:~ brite$
> 
> 怎么解决？

https://github.com/txthinking/brook/issues/350

**Comment by luckypoem** [comment]
whew,你这个brook-vpn真是太好用了。真心谢谢你！！！
设置简单方便。

**Comment by luckypoem** [comment]
我在三台vps上，安装了这个brook,在mac上翻墙都成功。不过在第四个vps上安装后，在mac上翻墙失败。
在mac的终端里显示：
Ctrl-C to quit
2018/10/12 14:04:49 cipher: message authentication failed
2018/10/12 14:04:49 cipher: message authentication failed
2018/10/12 14:04:50 cipher: message authentication failed
2018/10/12 14:04:50 cipher: message authentication failed
2018/10/12 14:04:50 cipher: message authentication failed
2018/10/12 14:04:50 cipher: message authentication failed
2018/10/12 14:04:50 cipher: message authentication failed
2018/10/12 14:04:50 cipher: message authentication failed
2018/10/12 14:04:50 cipher: message authentication failed
2018/10/12 14:04:50 cipher: message authentication failed
2018/10/12 14:04:50 cipher: message authentication failed
2018/10/12 14:04:50 cipher: message authentication failed
2018/10/12 14:04:50 cipher: message authentication failed
2018/10/12 14:04:50 cipher: message authentication failed
2018/10/12 14:04:50 cipher: message authentication failed
2018/10/12 14:04:50 cipher: message authentication failed
2018/10/12 14:04:51 cipher: message authentication failed
2018/10/12 14:04:52 cipher: message authentication failed
2018/10/12 14:04:52 cipher: message authentication failed
2018/10/12 14:04:52 cipher: message authentication failed
2018/10/12 14:04:52 cipher: message authentication failed
2018/10/12 14:04:53 cipher: message authentication failed
2018/10/12 14:04:53 cipher: message authentication failed
2018/10/12 14:04:54 cipher: message authentication failed
2018/10/12 14:04:55 cipher: message authentication failed
2018/10/12 14:04:56 cipher: message authentication failed
2018/10/12 14:04:56 cipher: message authentication failed
2018/10/12 14:04:56 cipher: message authentication failed

不知为何，如何解决？

**Comment by luckypoem** [comment]
哦
/root/brook_linux_amd64 server -l 0.0.0.0:2466 -p mypassword --tcpDeadline 0

**Comment by luckypoem** [comment]
我在mac上运行ulimit -n 10000 && sudo ./brook_darwin_amd64 vpn -l 127.0.0.1:5566 -s my-vps-ip:2466 -p mypassword
显示：
Ctrl-C to quit

2018/12/01 07:11:28 Expired request
如何解决问题？
