### ISSUE TITLE
请添加“连接成功”和“连接失败”提示

### ISSUE THREAD

**Issue by stonedreamforest** [txthinking/brook#39]
我随便填写都可以链接vpn 但是连不上网...
![qq 20170715195555](https://user-images.githubusercontent.com/16742566/28239149-a20bcb42-6997-11e7-8cf8-eab7fc80190e.png)

**Comment by txthinking** [comment]
对，目前是配置好后，点击start便会启动系统vpn。真正使用到输入的server是在发起非白名单内请求时。

**Comment by stonedreamforest** [comment]
建议做个通信校验  比如”密码错误，未能成功连接服务器“之类情况的提示

**Comment by txthinking** [comment]
假设程序根据配置去判断是否能访问google.com，

client <---1---> server <---2---> google.com

发现无法正常访问，并不一定是密码错误，
还有可能是服务器地址正确，密码也正确，而服务器[2]不能访问google.com

**Comment by txthinking** [comment]
No response.
