### ISSUE TITLE
Can add the global mode into the Android client?

### ISSUE THREAD

**Issue by miyouzi** [txthinking/brook#390]
Now I'm using Android client (v20180909)
It seems working on PAC mode.
But I hope it can work on global mode.
I think it‘ll be better If the client can allow users to chose the route model.

**Comment by Ccapton** [comment]
> Now I'm using Android client (v20180909)
> It seems working on PAC mode.
> But I hope it can work on global mode.
> I think it‘ll be better If the client can allow users to chose the route model.

### You can change to Global Mode.It seems that **You forgot to tap the "v20180909"  option for 16 times**.After that ,you will see a new option "Mode" in the menu !!
<img src="https://raw.githubusercontent.com/Ccapton/FileRepertory/master/files/WechatIMG560.jpeg" width="300px">

**Comment by miyouzi** [comment]
Oh! It works. Thank you!
