### ISSUE TITLE
How to extend/append sites to the white list?

### ISSUE THREAD

**Issue by actor168** [txthinking/brook#393]
#### Describe actual behavior
I want to add some sites to the white list.

#### What is your expected behavior
Provide a self-defined website list to append to the white list

#### Specifications like the version of the project, operating system, or hardware
Brook v20180401
Windows/ Mac OS

#### Steps to deploy the server
0. 
1.
2.

#### Steps to reproduce the problem
0.
1.
2.

**Comment by chinanoahli** [comment]
I am curious too. I am using Mac GUI client and iOS client.

**Comment by Ccapton** [comment]
> #### Describe actual behavior
> I want to add some sites to the white list.
> 
> #### What is your expected behavior
> Provide a self-defined website list to append to the white list
> 
> #### Specifications like the version of the project, operating system, or hardware
> Brook v20180401
> Windows/ Mac OS
> 
> #### Steps to deploy the server
> 
> #### Steps to reproduce the problem

### see [https://github.com/txthinking/pac](https://github.com/txthinking/pac)

**Comment by Ccapton** [comment]
> I am curious too. I am using Mac GUI client and iOS client.

### see [https://github.com/txthinking/pac](https://github.com/txthinking/pac)

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client
