### ISSUE TITLE
Android device is not available!!!!

### ISSUE THREAD

**Issue by chancat** [txthinking/brook#395]
Hello author,
I have been using brook for a year, I am very satisfied, but after several recent updates, I found that my Android phone is not working properly, and the computer can be used normally.
Why is this? My server has updated the latest version of brook, the Android client, I tested three versions of brook, all of which are not available?

**Comment by reignsLiu** [comment]
> Hello author,
> I have been using brook for a year, I am very satisfied, but after several recent updates, I found that my Android phone is not working properly, and the computer can be used normally.
> Why is this? My server has updated the latest version of brook, the Android client, I tested three versions of brook, all of which are not available?

@chancat  Hi, you should open udp of the port in your server.
In centos 7 , just like :firewall-cmd --zone=public --add-port=8000/udp --permanent

**Comment by chancat** [comment]
> > 你好作者，
> > 我一直在使用小溪一年，我很满意，但经过几次最新的更新后，我发现我的Android手机工作不正常，电脑可以正常使用。
> > 为什么是这样？我的服务器更新了最新版本的brook，Android客户端，我测试了三个版本的brook，所有这些都不可用？
> 
> @chancat 嗨，您应该打开服务器端口的udp。
> 在centos 7中，就像：firewall-cmd --zone = public --add-port = 8000 / udp --permanent

Hello, my firewall opens the ports TCP and UDP are turned on.

**Comment by NomaPek** [comment]
Hi, I'm a new brook user, and I encountered the similar problem: brook works for all devices but android (v20180401 is ok, but 06/07/09 not). Looks like the problem is about the server's firewall, it blocked DNS queries. After allowing 53/tcp and 53/udp ports, everything works fine now. Hope this could help you.

**Comment by alonewoo** [comment]
It is firewall block issue in server side. After I simply setup permit in/out all package in server firewall, it is working well now.
