### ISSUE TITLE
Google Cloud Server service auto-stop issue

### ISSUE THREAD

**Issue by Engputer** [txthinking/brook#396]
#### Describe actual behavior

I have noticed that I have some issues about the brook service, running on a google cloud server.

The service automatically is down after activating it for a 1-2 days. You have to manually bring the service up once it's done. I have no idea why it happens.

#### What is your expected behavior

I think the service should be up unless I manually stop it.

#### Specifications like the version of the project, operating system, or hardware

I installed the latest brook on the server.
I also installed BBR to speed up the speed.
The server is Debian 8.
I am accessing the service for main-land-China.

#### Steps to deploy the server
0. As the tutorial
1. Install BBR as the tutorial

#### Steps to reproduce the problem
0. The service got stopped every 2 days.

I have no idea why this happened. Anyone can tell me what happened?

Best regards,

Engputer

**Comment by Ccapton** [comment]
> #### Describe actual behavior
> I have noticed that I have some issues about the brook service, running on a google cloud server.
> 
> The service automatically is down after activating it for a 1-2 days. You have to manually bring the service up once it's done. I have no idea why it happens.
> 
> #### What is your expected behavior
> I think the service should be up unless I manually stop it.
> 
> #### Specifications like the version of the project, operating system, or hardware
> I installed the latest brook on the server.
> I also installed BBR to speed up the speed.
> The server is Debian 8.
> I am accessing the service for main-land-China.
> 
> #### Steps to deploy the server
> 1. As the tutorial
> 2. Install BBR as the tutorial
> 
> #### Steps to reproduce the problem
> 1. The service got stopped every 2 days.
> 
> I have no idea why this happened. Anyone can tell me what happened?
> 
> Best regards,
> 
> Engputer

You can write  a shell-script to run Brook service every day.That is what I do to clear cache my vps everyday .

**Comment by txthinking** [comment]
Some error log?
