### ISSUE TITLE
Is there some bugs will cause the port be banned for several minutes?

### ISSUE THREAD

**Issue by miyouzi** [txthinking/brook#397]
#### Describe actual behavior
When I try to proxy ```QQ``` on Windows or try to run ```STUNner``` on Android (brook client runs on global mode), the brook cannot be used in several minutes even I reboot the VPS, unless I change the brook server port, but the problem still exist, once I do the things above, the new server port will cannot be used again.

#### What is your expected behavior
Proxy the ```QQ``` and won't time out

#### Specifications like the version of the project, operating system, or hardware
the server runs on ```Ubuntu 18 64bit``` and ```CentOS 7 64bit``` , and cause the same happening (different VPSs) (enable bbr).
brook server (v20180909)
Brook.Setup.exe  (v20180909) and Windows 10 (1803) 64bit
Brook.apk  (v20180909) and Android 8.1

#### Steps to deploy the server
```
wget https://github.com/txthinking/brook/releases/download/v20180909/brook
chmod +x brook
./brook -d server -l :8080 -p HelloWorldQAQ
```

#### Steps to reproduce the problem
0. run ```./brook -d server -l :8080 -p HelloWorldQAQ```
1. proxy ```QQ``` on Windows or run ```STUNner``` on Android (brook client runs on global mode)
2. use the browser to test the brook proxy, and will show ```ERR_TIMED_OUT```

#### Some logs when I proxy QQ
use debug mode on server
```
2018/09/25 22:12:50 dial tcp 183.232.94.212:80: connect: connection refused
2018/09/25 22:12:50 dial tcp 112.95.240.48:80: connect: no route to host
2018/09/25 22:12:57 dial tcp 112.95.240.48:443: connect: no route to host
2018/09/25 22:13:00 dial tcp 183.60.49.183:80: i/o timeout
2018/09/25 22:13:00 dial tcp 111.161.52.148:443: i/o timeout
2018/09/25 22:13:00 dial tcp 119.147.32.229:80: i/o timeout
2018/09/25 22:13:00 dial tcp 119.147.32.229:443: i/o timeout
```

#### iptables -nL
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

**Comment by Ccapton** [comment]
> #### Describe actual behavior
> When I try to proxy `QQ` on Windows or try to run `STUNner` on Android (brook client runs on global mode), the brook cannot be used in several minutes even I reboot the VPS, unless I change the brook server port, but the problem still exist, once I do the things above, the new server port will cannot be used again.
> 
> #### What is your expected behavior
> Proxy the `QQ` and won't time out
> 
> #### Specifications like the version of the project, operating system, or hardware
> the server runs on `Ubuntu 18 64bit` and `CentOS 7 64bit` , and cause the same happening (different VPSs) (enable bbr).
> brook server (v20180909)
> Brook.Setup.exe (v20180909) and Windows 10 (1803) 64bit
> Brook.apk (v20180909) and Android 8.1
> 
> #### Steps to deploy the server
> ```
> wget https://github.com/txthinking/brook/releases/download/v20180909/brook
> chmod +x brook
> ./brook -d server -l :8080 -p HelloWorldQAQ
> ```
> #### Steps to reproduce the problem
> 1. run `./brook -d server -l :8080 -p HelloWorldQAQ`
> 2. proxy `QQ` on Windows or run `STUNner` on Android (brook client runs on global mode)
> 3. use the browser to test the brook proxy, and will show `ERR_TIMED_OUT`
> 
> #### Some logs when I proxy QQ
> use debug mode on server
> 
> ```
> 2018/09/25 22:12:50 dial tcp 183.232.94.212:80: connect: connection refused
> 2018/09/25 22:12:50 dial tcp 112.95.240.48:80: connect: no route to host
> 2018/09/25 22:12:57 dial tcp 112.95.240.48:443: connect: no route to host
> 2018/09/25 22:13:00 dial tcp 183.60.49.183:80: i/o timeout
> 2018/09/25 22:13:00 dial tcp 111.161.52.148:443: i/o timeout
> 2018/09/25 22:13:00 dial tcp 119.147.32.229:80: i/o timeout
> 2018/09/25 22:13:00 dial tcp 119.147.32.229:443: i/o timeout
> ```
> #### iptables -nL
> ```
> Chain INPUT (policy ACCEPT)
> target     prot opt source               destination
> 
> Chain FORWARD (policy ACCEPT)
> target     prot opt source               destination
> 
> Chain OUTPUT (policy ACCEPT)
> target     prot opt source               destination
> ```

Hey,Guys.Please don't use global mode when you use chinese app in your phone,because many foreign servers can't connect to chinese servers directly.

Please use PAC mode in all of your client machines.

**Comment by miyouzi** [comment]
@Ccapton Hello, thank you for your answer.
> many foreign servers can't connect to chinese servers directly.

I don't think it's the reason of this problem. I try to use shadowsocks and that didn't cause the issue.
Now I'm at the outside of the GFW, I want to proxy some Chinese software because there are some limit of my school network.

**Comment by Ccapton** [comment]
> @Ccapton Hello, thank you for your answer.
> 
> > many foreign servers can't connect to chinese servers directly.
> 
> I don't think it's the reason of this problem. I try to use shadowsocks and that didn't cause the issue.
> Now I'm at the outside of the GFW, I want to proxy some Chinese software because there are some limit of my school network.

Please try to use Blacklist mode .
1 、Generate a black app list ,see [https://github.com/txthinking/pac](https://github.com/txthinking/pac)
2、Fill the blank with the black_app_list url made by you,then click download button to save black_list app package name in your android.
<img src="https://raw.githubusercontent.com/Ccapton/FileRepertory/master/files/IMG_20180930_173435.jpg" width="300px">

### That is only my suggestion.If something wrong happen,I can't forecast what's actully going to happen !!

**Comment by txthinking** [comment]
I think the answer is no.
