### ISSUE TITLE
IE cannot use proxy

### ISSUE THREAD

**Issue by MasonQAQ** [txthinking/brook#398]
#### Describe actual behavior
IE cannot use proxy by setting 127.0.0.1:1080

**Comment by MasonQAQ** [comment]
> > #### Describe actual behavior
> > IE cannot use proxy by setting 127.0.0.1:1080
> 
> ### Oh My God,It's 2018 man.Please use modern browser like Chrome、FireFox or Chromium etc.

I use Chrome every day. But I am in China, some application uses IE kernel. there is a great wall...QAQ

**Comment by F-TD5X** [comment]
@MasonQAQ IE only can use system proxy setting, which only support HTTP/HTTPS proxy.
If you have to, just try privoxy or use some software like proxifier.

**Comment by ZZYSonny** [comment]
Actually, this is also a problem for Edge Browser. I am currently using command line version and self set PAC.
I hope the GUI Brook can support HTTP proxy one day. (Even better with VPN mode)

**Comment by ZJUGuoShuai** [comment]
IE can only use HTTP/HTTPS proxy, so what you need is [Privoxy](http://www.privoxy.org/).

**Comment by txthinking** [comment]
Or try cli version.
