### ISSUE TITLE
When using VPN mode, killing the process directly causes errors

### ISSUE THREAD

**Issue by Aaron0-wang** [txthinking/brook#399]
#### Describe actual behavior

I didn't like the fact that Linux had to take a terminal when running brook, so I wrote a simple script that ran in the background using the nohup command and killed the process directly when not in use. There is no problem with the socks5 and HTTP modes, but when running in VPN mode, killing the process directly will cause an error to start the VPN mode next time, and the system will return to normal only when the system is restarted

![default](https://user-images.githubusercontent.com/38186870/46255705-ec36f100-c4d2-11e8-9e24-d0363298f212.png)

#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.
1.
2.

**Comment by txthinking** [comment]
> killing the process directly 
Which signal?

**Comment by Aaron0-wang** [comment]
1.netstat -lnp|grep 1080
2.kill -9 
![default](https://user-images.githubusercontent.com/38186870/47063842-9753e400-d20f-11e8-8db3-df91bd31a8cf.png)
then start brook in VPN mode again will report the error shown in my previous screenshot

**Comment by txthinking** [comment]
try `$ kill 26661`

**Comment by Aaron0-wang** [comment]
Now there is no error, it seems that I did not understand the kill command well
