### ISSUE TITLE
I got the following error

### ISSUE THREAD

**Issue by DonaldTang1995** [txthinking/brook#40]
#### Describe actual behavior
./brook: line 1: syntax error near unexpected token `newline'
./brook: line 1: `!<arch>'
#### Specifications like the version of the project, operating system, or hardware
go version go1.7.4 linux/amd64
#### Steps to reproduce the problem
I use the following command to compile the code
1. go get github.com/txthinking/socks5 ant pac  brook
2. sh cli/brook/buildAll.sh

Then it says the syntax error.

**Comment by txthinking** [comment]
Please try `cd brook/cli/brook`,  then run `./buildAll.sh`

**Comment by DonaldTang1995** [comment]
Is there an introduction of brook protocol?

**Comment by txthinking** [comment]
Not yet. ☃️. I assume you have built successfully.
