### ISSUE TITLE
Brook client seems to work normally but certain websites cannot be opened. 

### ISSUE THREAD

**Issue by LizaCheung** [txthinking/brook#401]
It looks like the Brook client works totally fine as it shows CONNECTED. And I ping ip in the terminal - everything works fine. But why the websites cannot be connected?

**Comment by luckypoem** [comment]
@LizaCheung 
哪些网站打不开？我没遇到打不开的网站

**Comment by LizaCheung** [comment]
> @LizaCheung
> 哪些网站打不开？我没遇到打不开的网站

问题解决了 不知道是什么原因Brook被关了😳。。。./brook.sh重新启动了下就好了
