### ISSUE TITLE
iOS Brook always disconnected when watching video in Youtube APP.

### ISSUE THREAD

**Issue by MonKong** [txthinking/brook#404]
Issue: iOS Brook always disconnected when watching  video in Youtube APP in about 2 minutes. But issue not happens in youtube website.
I guess it is caused by different video buffer mechanisms. The web version is always buffered to the end, and the app version is buffered to about 1 minute after the current viewing time.

Brook server v20180909
setup by one step script on doub.io

iOS client v20180601

iphone 8, iOS 12.

**Comment by MonKong** [comment]
duplicated...? So what's the original issue link?

**Comment by txthinking** [comment]
#371
