### ISSUE TITLE
是否考虑加入kcp和udp2raw功能

### ISSUE THREAD

**Issue by tesroom** [txthinking/brook#405]
之前我都是在SS下使用kcptun+udp2raw 加速网络的，我刚才试了下brook貌似不行的，可否加入此功能呢？brook原生支持UDP转发确实挺爽的，感谢作者。

**Comment by thomas0008** [comment]
在SS下使用kcptun+udp2raw 这个是不是仅能在PC端实现？在安卓手机以及苹果IOS端要如何实现与配置？
