### ISSUE TITLE
Clicked toggle, brook didn't start

### ISSUE THREAD

**Issue by ChuBingjie** [txthinking/brook#406]
#### Describe the actual behavior
Brook worked well both in IOS and Android. I download the latest version and setup everything. When I click the toggle, nothing happened. Anyone who can help me? I've checked all the past issues and tried several ways mentioned in the answer. It still didn't work.
#### What is your expected behavior
After clicked toggle, the status changed to brook started.
#### Specifications like the version of the project, operating system, or hardware
09version, win 10

**Comment by txthinking** [comment]
#436
