### ISSUE TITLE
brook server mode does not listen on ipv4

### ISSUE THREAD

**Issue by loongw** [txthinking/brook#407]
#### Describe actual behavior
brook server mode does not listen on ipv4.

#### What is your expected behavior
brook should listen on ipv4 address.

#### Specifications like the version of the project, operating system, or hardware

```
loong@brook:~/l/green/brook on $ ./brook -v
Brook version 20180909
loong@brook:~/l/green/brook on $ cat /etc/issue
Ubuntu 18.04.1 LTS \n \l
loong@brook:~/l/green/brook on $ cat /proc/version
Linux version 4.15.0-1021-gcp (buildd@lgw01-amd64-030) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #22-Ubuntu
 SMP Tue Sep 25 10:06:59 UTC 2018
```

#### Steps to deploy the server

./brook server -l :9999 -p fuck&

#### Steps to reproduce the problem
./brook server -l :9999 -p fuck&

![image](https://user-images.githubusercontent.com/6442159/46917863-1e317280-cffe-11e8-940e-1dadcc565382.png)

**Comment by loongw** [comment]
listening on ipv6 works fine.

**Comment by bannedbook** [comment]
same issue with version v20190601
./brook server -l :9999 -p password
will only run at ipv6
