### ISSUE TITLE
Brook Mac Client: 127.0.0.1: 1080 already in use

### ISSUE THREAD

**Issue by novicewu** [txthinking/brook#409]
#### Describe actual behavior
listen tcp 127.0.0.1: 1080: bind address already in use
<img width="326" alt="screen shot 2018-10-15 at 17 40 02" src="https://user-images.githubusercontent.com/8786994/46943065-6190ed00-d0a1-11e8-97ce-1da771927c88.png">

#### What is your expected behavior
I have some other app that may use port 1080. Is it possible to manually change brook client's default port?

**Comment by txthinking** [comment]
Enable mode page.
https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client

**Comment by novicewu** [comment]
Thanks. 
I've solved this problem with the instruction.

**Comment by GOODXIONG** [comment]
> Thanks.
> I've solved this problem with the instruction.

I can't change the Listen. How can I change the Listen?
![2019-02-10 12 24 56](https://user-images.githubusercontent.com/17375177/52523248-67eb4a80-2cca-11e9-8594-9c1810bddbad.png)

**Comment by GOODXIONG** [comment]
@txthinking @novicewu

**Comment by txthinking** [comment]
@GOODXIONG 

1. Just type 127.0.0.1:1081
2. Tap SAVE
3. Stop Brook
4. Start Brook again
5. Try $ telnet 127.0.0.1 1081`

**Comment by txthinking** [comment]
@GOODXIONG Looks like a bug, can your open a new issue? Thanks.
