### ISSUE TITLE
在“启用或关闭Windows功能”中关闭IE后，启动brook出现找不到IE的提示

### ISSUE THREAD

**Issue by mzxwt** [txthinking/brook#41]
你好！这个问题很早就想你反馈过了。对于我这种默认使用Chrome，关闭IE的强迫症晚期患者有点难受。另外，能不能增加随系统启动并自动start的功能？还有，能不能提供无托盘模式，像GoAgent那样默默在后台运行？

**Comment by txthinking** [comment]
目前windows修改代理是通过修改注册表(还可以通过win api修改，不太了解)
但是修改了注册表之后，代理必须重启IE才会生效，windows怪异的行为。

所以如果系统没有IE，就不会修改代理成功，就会需要自己去配置代理(比如通过chrome插件)，这样也增加了使用复杂度(因为Brook的目标就是尽量减少**配置**步骤)

另外如果没有托盘的话，启动后不方便停止吧

**Comment by mzxwt** [comment]
感谢你的回复！
关于IE修改代理的问题，是否可以借鉴shadowsocksr客户端的做法，添加选项，用户自行决定使用哪种方式改变代理
是否可以考虑隐藏托盘后，双击brook.exe显示托盘

**Comment by txthinking** [comment]
也可在windows cmd下尝试下cli端，那个就是一条命令监听一个端口，剩下的都是需要自己弄
