### ISSUE TITLE
Is there anyway to install brook client on merlin based routers?

### ISSUE THREAD

**Issue by maxhboss** [txthinking/brook#413]
I really would like a way to install brook client on merlin based routers just like SS/V2ray.

**Comment by txthinking** [comment]
Try https://github.com/txthinking/brook/issues?utf8=%E2%9C%93&q=openwrt

**Comment by DreamSeekerKaiser** [comment]
> Try https://github.com/txthinking/brook/issues?utf8=%E2%9C%93&q=openwrt

i don't know how to send private message to you guys  . can you send email to me ? i want buy your gui code for  add new  feature.
