### ISSUE TITLE
Ilegal instruction running armv7 version on Merlin mod for R6300v2 (ARMv7)

### ISSUE THREAD

**Issue by shural** [txthinking/brook#414]
Download the armv7 daily build to Merlin mod on Netgear R6300v2 router. Execute it and fail with Illegal instruction. NOte R6300v2 is ARMv7, so not sure the FPU emulation workaround for MIPS router works here.

**Comment by txthinking** [comment]
Is it related to #432 ?

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/issues/432
