### ISSUE TITLE
Win10(x64) Invalid version.

### ISSUE THREAD

**Issue by yunlong202** [txthinking/brook#416]
Server Version:v20180909          Client Version:v20180909

Server and Client runs in Brook protocol.  ios/android/macos works fine.  win10 now work and toggle stop it show "Invalid version".
Server and Client runs in Brook Stream protocol.  ios/android/macos/win10 all works fine.

Anther Problem: it's works on Chrome, not IE.

**Comment by swufexym** [comment]
I've got this error since my windows 10 is update to the version 1809, is there anybody has a solution?

**Comment by ZeroNobody** [comment]
I also have this problem today. IOS is not using exception. Win10 connection is not able to open web pages.

**Comment by txthinking** [comment]
#436

**Comment by nurettin** [comment]
I had this when I forgot `--http` in client.
