### ISSUE TITLE
Mac 10.14 can't start up

### ISSUE THREAD

**Issue by wangxin1248** [txthinking/brook#417]
#### Describe actual behavior

Brooks said 
Command failed:/Applications/Brooks.app/Contents/Resources/app/dist/electron/static/brook_darwin_am...

**Comment by vcfger** [comment]
Me too  same problem

**Comment by vcfger** [comment]
Me too same problem

**Comment by TinaAreadyLose** [comment]
# after I change an account， I meet this problem as you，but windows and Android can use 。
I use mac 13.16
（我之前使用很正常，但是自从换了一个账号之后，微软和安卓都可以用，就是mac 提示这种错误）

**Comment by TinaAreadyLose** [comment]
![Uploading Screen Shot 2018-10-25 at 1.04.58 PM.png…]()
is this exe has problem？？

**Comment by txthinking** [comment]
#435
