### ISSUE TITLE
Please release the ipa file since some area cannot download it from Appstore.

### ISSUE THREAD

**Issue by swufexym** [txthinking/brook#421]
Brook Cannot be downloaded from the Appstore in some area. Please release the complied iOS version which is the ipa file during next release. A tutorial of compling the iOS version is also acceptable. Thank you very much!

**Comment by MrBenFTW** [comment]
I'll compile it for you and send you the IPA if you have the src...

**Comment by Dr-Bluemond** [comment]
You can just buy a non-China appleid for no more than 10 RMB if you don't want to register it yourself
With a non-China account, Brook is available in China
