### ISSUE TITLE
Please test 20181212 on iOS 12

### ISSUE THREAD

**Issue by HSczy** [txthinking/brook#426]
如题 从2018.11.11日晚开始出现这个问题，windows系统、安卓系统、OSX10.13版本、iOS11均可正常代理，iOS12 和 OSX10.14版本的brook无法代理。希望早日解决。

**Comment by leslie0216** [comment]
the same... iso12, OSX10.11.6

**Comment by andyandyhs** [comment]
ios12 is dead,but my osx 10.13.6 can work

**Comment by Dr-Bluemond** [comment]
The same problem on IOS12, but my 10.41.1 Mac works well with cli.

**Comment by amd4466** [comment]
The same problem. ios12

**Comment by andyandyhs** [comment]
i found the way by enter “Mode” choose global ,maybe can work,anyone can try and report me? please

**Comment by zky999** [comment]
Same here.

**Comment by Gxz-NGU** [comment]
> i found the way by enter “Mode” choose global ,maybe can work,anyone can try and report me? please

it works

**Comment by bobwang3** [comment]
same issues. btw, enter “Mode”  in where?

**Comment by HSczy** [comment]
11月11日这个节点应该是ios12.1更新，然后MacOS10.14有一个小更新，我是更新之后出现了问题，没有更新的iOS12.1的朋友都没有这个问题。 然后 上面 @andyandyhs 说的方法手机能奏效，还是希望能尽早更新解决这个问题吧。谢谢

**Comment by Gxz-NGU** [comment]
click the menu button on the left corner of the menu in **iphone Brook APP**. then you can find Model and choose global.

**Comment by andyandyhs** [comment]
我沒更新12.1一樣有這問題 所以我一樣是使用global才能解決

**Comment by bobwang3** [comment]
> click the menu button on the left corner of the menu in **iphone Brook APP**. then you can find Model and choose global.

The global model can solve the problem that IOS12 can't connect. However, watching youtube will still automatically disconnect after a few minutes.

**Comment by PFei-He** [comment]
I have the same problem at ios12, it can work in mode global, but will automatically disconnect after a few minutes too. Please update the new version, thx!

**Comment by yuanhouer27** [comment]
At Mac OS 10.14.1, completely uninstall the Brook(I used the cleammymac), then install the Brook again. Problem solved！ I guess some configuration files that are not removed completely may cause the problem. Hope you guys solve it too.

**Comment by HSczy** [comment]
thank you for the info！

yuanhouer27 <notifications@github.com> 于2018年11月15日周四 上午11:38写道：

**Comment by SJTUboy** [comment]
After Win10 1809 update, the same issue occurs

**Comment by andyandyhs** [comment]
有人一樣在大陸但是vpn連上網路卻接不上嗎？

**Comment by optimusha** [comment]
I have the same problem.Additionally,brook in IOS is unstable.The client will automatically disconnect frequently.It makes me troubled.

**Comment by walix123** [comment]
waiting good news！

**Comment by txthinking** [comment]
Apple: Your app is waiting for review.

**Comment by txthinking** [comment]
Released

**Comment by HSczy** [comment]
yeah brook 20181212 remove the mode select, and the pac seem have a little problem cant connect INS etc

**Comment by txthinking** [comment]
Facebook-like apps don't work with 20181212. It looks like facebook's network library ignores system setting.
This reminds me of IE browser. 😰

**Comment by HSczy** [comment]
aha waiting for good news. BTW can brook limit the nums of connection s？

**Comment by RollingL** [comment]
ios12.1 appstore not work

**Comment by cugxuan** [comment]
Why the mode `Brook Stream`  has been removed?

**Comment by THETHINGSLX** [comment]
After opening the service, I can't use instagram, facebook, Dribbble applications, but they can be accessed through the browser. Version 20181212 on iOS 12.1.

**Comment by bobwang3** [comment]
After my test, the new version 20181212 has no problem on ISO12, and watching YouTube videos does not automatically disconnect. 
Well done, cheers.

**Comment by andyandyhs** [comment]
facebook instagram apps doesn’t work ios12.0

**Comment by txthinking** [comment]
> Why the mode `Brook Stream` has been removed?

Brook Server is less likely to be detected

**Comment by cugxuan** [comment]
> > Why the mode `Brook Stream` has been removed?
> 
> Brook Server is less likely to be detected

Oh，thanks！

**Comment by zeR0Lu** [comment]
Why delete the global option? Some app can't work for the version 20181212

**Comment by txthinking** [comment]
@LiYanan2004 What does 'can't work' mean?

**Comment by txthinking** [comment]
@zeR0Lu https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client

**Comment by LiYanan2004** [comment]
I typed the password and the sever address and connected VPN successfully, but I still can’t visit the website such as Google, Youtube or instagram.

**Comment by zty464513026** [comment]
@txthinking 我用抽屉打开了模式，改成了全局，但是还是访问不了INS facebook，这类  别的都正常

**Comment by LiYanan2004** [comment]
什么时候出新版解决下这个问题呢

**Comment by txthinking** [comment]
Thank you everyone. If there are still problems then open a new issue please.
