### ISSUE TITLE
VPN mode changes IPV4 DNS server on Windows

### ISSUE THREAD

**Issue by Whtie4622** [txthinking/brook#428]
#### Describe actual behavior
Run brook as VPN mode, it works fine. But after I closed it with Ctrl+C, I found that my IPv4 server had been changed to 8.8.8.8, by which my PC cannot resolve domain name. I have to add a few more powershell scripts to configure it properly.

#### What is your expected behavior
DNS configuration set back to what it was after closing brook

#### Specifications like the version of the project, operating system, or hardware
brook: V20180909
my platform: windows 10 pro 1809

#### Steps to deploy the server
`brook server -l :PORT -p PSWD`

#### Steps to reproduce the problem
install tap-windows adapter v9
the gateway address below belongs to my WLAN Adapter
`brook vpn -l "127.0.0.1:1080" -s "IPV6_ADD:PORT" -p "PSWD" --defaultGateway "IPV6_GATEWAY"`
`CTRL+C`

**Comment by txthinking** [comment]
Because I don't have an IPv6  environment. Some questions:
Does your server support IPv6 IP?
Does your windows support IPv6?
Does your windows support IPv4?

Does
`$ brook vpn -l "127.0.0.1:1080" -s "IPV6_ADD:PORT" -p "PSWD" --defaultGateway "IPV6_GATEWAY"`
work?

**Comment by Whtie4622** [comment]
_Does your server support IPv6 IP?_ YES
_Does your windows support IPv6?_ YES
_Does your windows support IPv4?_ YES

_Does
$ brook vpn -l "127.0.0.1:1080" -s "IPV6_ADD:PORT" -p "PSWD" --defaultGateway "IPV6_GATEWAY"
work?_ YES. This functionality works fine, it just changes my dns server address which I hope not.

**Comment by txthinking** [comment]
Please try v20190205, waiting for your response :)

**Comment by Whtie4622** [comment]
still changes dns server at 20190205

**Comment by txthinking** [comment]
Looks like you delete your comment, in the 20190205, after your stop brook vpn, it will restore your original dns servers. Let me know it works or not, thank you.

**Comment by Whtie4622** [comment]
it works, thanks!
