### ISSUE TITLE
Please make it compatible with iPhone5 (with iOS10.3.3 installed), thx

### ISSUE THREAD

**Issue by Topos404** [txthinking/brook#430]
thanks

**Comment by gxggsrmyy** [comment]
@txthinking  mipsle 版本在最新的openwrt 18.06.1上运行出错
./brook_linux_mipsle: line 1: syntax error: unexpected "("

**Comment by txthinking** [comment]
I will try  https://github.com/flutter/flutter/issues/2089 when I have time

**Comment by txthinking** [comment]
v20200501
