### ISSUE TITLE
Please test 20181212 on MacOS

### ISSUE THREAD

**Issue by txthinking** [txthinking/brook#435]
https://storage.googleapis.com/txthinking-file/_/Brook.dmg

**Comment by SJTUboy** [comment]
Couldn't start up in macOS 10.14.1
———
The app icon keep dancing in dock, I have to force quit
———
After rebooting Mac, the same issure, it told me "You can't open...because it is not responding "

**Comment by txthinking** [comment]
1. Delete the old Brook
2. Open new Brook
3. Then go System Preferences -> Security & Privacy, click Open Anyway

**Comment by SJTUboy** [comment]
It works. Thanks a lot.

**Comment by zeR0Lu** [comment]
The App Couldn't start up, The Security & Privacy had set Open Anyway. I click the app,  after few second, it close auto.

**Comment by n12z** [comment]
10.14.1 设置open anyway之后客户端秒退

**Comment by laozhu999** [comment]
Can't open due to the lower version of system? Why do you want 10.14... instead of 10.13....?

**Comment by zd9027** [comment]
10.14.1 (18B75) . It works,thank you.

**Comment by GitSarp** [comment]
10.14.1 can not work. flash and you can not see icon on system bar ....just can not startup

**Comment by txthinking** [comment]
Thank you everyone. If there are still problems then open a new issue please.

**Comment by hulupiao** [comment]
> 10.14.1 (18B75) . It works,thank you.

怎么设置服务器信息的？我没有找到

**Comment by zd9027** [comment]
> > 10.14.1 (18B75) . It works,thank you.
> 
> 怎么设置服务器信息的？我没有找到

连续点击版本号

**Comment by bigzhou** [comment]
10.14.3  can not work.
