### ISSUE TITLE
Please test 20181212 on Windows

### ISSUE THREAD

**Issue by txthinking** [txthinking/brook#436]
https://storage.googleapis.com/txthinking-file/_/Brook.exe

**Comment by txthinking** [comment]
Please uninstall the old version first.

**Comment by GeraldXue** [comment]
It works

**Comment by hxhxd** [comment]
Win7, vpn mode, curl -v -L www.google.com would trigger brook client quit, with error message:  
2018/12/01 22:53:05 listen tcp 127.0.0.1:53: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

(Tried several times, actually visit any website would trigger that error and client quit)

**Comment by hxhxd** [comment]
Seems somehow the cmd window (or cmder window) will get a 'Win + C' whenever brook vpn mode starts, don't know why. Tried move into VM win7 to run, don't have this problem.

**Comment by txthinking** [comment]
Thank you everyone. If there are still problems then open a new issue please.
