### ISSUE TITLE
Please test 20181212 on Android

### ISSUE THREAD

**Issue by PFei-He** [txthinking/brook#437]
#### Describe actual behavior
Install the apk.
#### What is your expected behavior
Install success, but failed.
#### Specifications like the version of the project, operating system, or hardware
20181212, android p, Pixel XL
#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0.
1.
2.

**Comment by txthinking** [comment]
What does 'failed' mean?

**Comment by PFei-He** [comment]
Download the apk, and install. At last, show 'App not installed'.

**Comment by txthinking** [comment]
1. Uninstall the old version
2. Install the new version.

**Comment by PFei-He** [comment]
It works, thanks!

**Comment by wingljp** [comment]
samsung note8   android 8.0  Uninstall the old version
Install the new version
failed

**Comment by kikyou93** [comment]
HONOR 8 Uninstall the old veersion

**Comment by kikyou93** [comment]
HONOR 8 android 8.0 Uninstall the old version
Install the new version
failed

**Comment by kikyou93** [comment]
server v20180401 ,android 20171113,now it works, Thans

**Comment by vongoethe** [comment]
Moto z3, installation succeed.
Whitelist doesn't work.

**Comment by mistlost** [comment]
Server and Android client are the version of v20181212. Works on PC well but  doesn't work on Android phone.

**Comment by txthinking** [comment]
Thank you everyone. If there are still problems then open a new issue please.
