### ISSUE TITLE
作者是否考慮適配iOS 9或將iOS代碼開源？

### ISSUE THREAD

**Issue by billmatxas** [txthinking/brook#44]
iOS程序員一枚，手中有個不想升級的設備，不知道作者願不願意適配iOS 9或開源客戶端代碼？

**Comment by billmatxas** [comment]
感謝作者做出的貢獻和辛勤勞動！

**Comment by txthinking** [comment]
抱歉，iOS9不会再支持了。目前暂无计划。
能升级就升吧，反正早晚也得升。
