### ISSUE TITLE
previous release (0909) link seems to download latest release

### ISSUE THREAD

**Issue by zhirshya** [txthinking/brook#441]
#### Describe actual behavior
On macbook pro (early 2011), previously working release (0909) stopped working after overwritten by latest 1212 release.
I shouldn't have installed the latest 1212 release, which requires macos 10.14+.
The old release link seems to always download the latest release, which has a white overlapping "stop mark" atop the usual key icon and gives "...requires at least macos  10.14".

#### Steps to deploy the server
0.
1.
2.

#### Steps to reproduce the problem
0. macbook pro (early 2011) which can't be upgraded beyond macos 10.13.6.
1. download previous release (0909)
2. install

**Comment by txthinking** [comment]
Sorry. Please upgrade your OS.

**Comment by zhirshya** [comment]
I can't buy a new macbook.
Could you revert 0909 release link with the old one or upload on file.io and post the ID here.
Thank you.

**Comment by txthinking** [comment]
You might like the cli version.
