### ISSUE TITLE
windows10 brook 20181212...

### ISSUE THREAD

**Issue by Sesprie** [txthinking/brook#443]
"brook_windows_amd64v20181212.exe" client -l 127.0.0.1:1080 -i 127.0.0.1 -s xxx -p xxx
2018/11/30 12:56:08 write tcp 127.0.0.1:1080->127.0.0.1:55693: wsasend: An established connection was aborted by the software in your host machine.
2018/11/30 12:56:08 write tcp 127.0.0.1:1080->127.0.0.1:55692: wsasend: An established connection was aborted by the software in your host machine.
2018/11/30 12:56:24 write tcp 127.0.0.1:1080->127.0.0.1:55722: wsasend: An established connection was aborted by the software in your host machine.
2018/11/30 12:56:24 write tcp 127.0.0.1:1080->127.0.0.1:55723: wsasend: An established connection was aborted by the software in your host machine.
2018/11/30 12:56:24 write tcp 127.0.0.1:1080->127.0.0.1:55730: wsasend: An established connection was aborted by the software in your host machine.
2018/11/30 12:56:24 write tcp 127.0.0.1:1080->127.0.0.1:55729: wsasend: An established connection was aborted by the software in your host machine.
2018/11/30 12:56:25 write tcp 127.0.0.1:1080->127.0.0.1:55724: wsasend: An established connection was aborted by the software in your host machine.
2018/11/30 12:56:39 Invalid Version
2018/11/30 12:57:28 Invalid Version
2018/11/30 12:57:28 Invalid Version
2018/11/30 12:57:29 Invalid Version
2018/11/30 12:57:29 Invalid Version
我是在firefox中设置的proxy为socks5
127.0.0.1 1080
连接google.com， ipip.net秒开，但是连接youtube.com就会显示Invalid Version，一直连不上，GUI 版的brook 20181212 (此时关闭了firefox自定的proxy，使用系统默认) 也是这样

如果网站可以连接，会提醒前面的一堆，无法连接时会显示Invalid Version，服务器端也是20181212版，但是安卓端没有更新，使用的是20180909，都正常

萌新实在是找不到原因了，才来开issue，如果日志不够详细，我会再贴一点
![image](https://user-images.githubusercontent.com/22644587/49269542-83530180-f4a0-11e8-8e9e-90fa389b082a.png)

![image](https://user-images.githubusercontent.com/22644587/49269576-a2519380-f4a0-11e8-866c-7d5a4c7e4813.png)

![image](https://user-images.githubusercontent.com/22644587/49269622-d331c880-f4a0-11e8-8282-0afd599e0a4f.png)

;;;open的全部是英文issue，不会英语好尴尬 [逃]

**Comment by Sesprie** [comment]
忘了说了，使用20180909版的windows cli也是这样，删除用户目录下的配置文件，重新开brook，也是部分无法连接，原来一直用的brook tools，但是间歇性的断连，才想着来使用这种方式试试

**Comment by Dr-Bluemond** [comment]
I used to face this issue and found my server were blocked.
Try if you can reach your server with other tcp connections
你看看你的服务器是不是被墙了，比如能不能ssh

**Comment by Dr-Bluemond** [comment]
@Dr-Bluemond 还有你打开的谷歌能不能查东西

**Comment by Sesprie** [comment]
![image](https://user-images.githubusercontent.com/22644587/49289872-1eb79700-f4e0-11e8-9f87-b0c807879011.png)
![image](https://user-images.githubusercontent.com/22644587/49289922-532b5300-f4e0-11e8-9cf3-153f86e53d13.png)

现在是使用上面的方式chrome中正常，firefox访问google.com等国外被Q网站无法访问，
但是关掉cmd中的brook，使用brook tools后在chrome和firefox中都正常，是我配置方式有问题吗
![image](https://user-images.githubusercontent.com/22644587/49290023-aa312800-f4e0-11e8-8f96-e7ae16ad94b8.png)
使用下面的两种方式在firefox中都不行，上面的配置未做改动
![1](https://user-images.githubusercontent.com/22644587/49290401-de591880-f4e1-11e8-9f80-48aa88db052d.png)

**Comment by Sesprie** [comment]
![image](https://user-images.githubusercontent.com/22644587/49323633-7e9e5400-f559-11e8-9819-a42f23911c98.png)
firefox不能连我就没有管了，偶然间，打开测试一下，又可以了，很迷

谢谢

**Comment by Sesprie** [comment]
好像firefox间歇性抽风，额。。。

**Comment by zombie110year** [comment]
FireFox 使用内置证书, 好像只要发生 "断网重连", "重启 Brook" 的情况就会出现证书错误. 我的解决方案是在网络情况稳定时重启 FireFox...
