### ISSUE TITLE
iOS12.1 v1212 can't paste

### ISSUE THREAD

**Issue by gogo008** [txthinking/brook#444]
![image](https://user-images.githubusercontent.com/29323256/49278361-7bef2080-f4bf-11e8-9928-48146868e25d.png)
iOS12.1 v1212版无法粘贴密码，跳出这个界面

**Comment by txthinking** [comment]
Yes, it is a bug. Can only be entered manually now

**Comment by gzl1979** [comment]
同样的问题。

**Comment by gzl1979** [comment]
从此再无逗比

**Comment by gogo008** [comment]
更新v20190205版后问题同样存在！

**Comment by txthinking** [comment]
This problem only happens on Chinese system(at least, works well on English
language iOS)
Sorry, hope fixed in next version.

**Comment by txthinking** [comment]
I found a solution, will be fixed in next version. 🤝

**Comment by txthinking** [comment]
fixed: https://itunes.apple.com/us/app/brook-a-cross-platform-proxy/id1216002642?ls=1&mt=8

**Comment by joviqiao** [comment]
Windows has the same problem，v 20190401,
can not paste, so sad @txthinking
