### ISSUE TITLE
您好，我这里有一个迫切需要解决的问题

### ISSUE THREAD

**Issue by karasuma7** [txthinking/brook#447]
首先我要说的是，上次我曾经用英文来提出这个问题，作者大大您回复我让我阅读说明书以及寻找旧问题，在我寻找到一个类似的解决方案 #124 以后，尝试使用该方案解决，并没有解决问题，所以这里再次提出问题
恳请！恳请！恳请！作者大大给一个可以解决问题的办法，这个问题真的困扰我很久了，真的真的拜托了，如果关闭这个提问，恳请至少给一个解决的办法，我可以去尝试，鞠躬，拜谢！

以下是问题详情（中文版）：
作者您好，我是您的软件brook的用户，在这里我想要向您反馈一个关于brook的重大bug问题，希望您能回复此信息，对我的问题进行解决，多谢了。这个问题在于，在使用软件成功建立连接以后，打开所有的网站，例如我举个例子“http://www.dlsite.com/maniax/”这个网站，在打开以后，页面只会停留在你第一次打开的界面，对于所有滚动的内容他并不会进行自动的刷新，即使我们建立在一个延迟十分低的服务器上面，他也只是会快速的打开网站的页面，然后不再进行自动连接，从而后续所有的内容无法打开。我在举一个例子，例如我们现在开启一款游戏，他叫kantai collcetion。这款游戏是一个网页游戏，在开启这款游戏的途中，我们就会遇到很多问题，读取账号界面之后，网站便不会再自动刷新，在你手动刷新无数次登录游戏以后，因为这是一个网页游戏，他会随着你的操作与游戏服务器进行不停的数据交互，但是如果使用brook进行连接，在短时间的几次交互之后，游戏就会卡顿在一个交互界面，数据不再进行交互，直到你手动刷新这个网页，他就会出现我们一开始登录游戏的问题。我再举最后一个例子，我在安卓系统中使用brook，连接一款手机游戏的时候遇到的问题，这款手机游戏在进行游戏剧情的时候，剧情的内容不会事先缓存在手机上面，而是在你选择进行剧情的时候从游戏服务器进行下载，我在下载剧情的时候，如果是较为小的剧情文件，因为我架设的brook服务器速度比较快，会在很快的时间内下载完毕，从而让游戏正常进入剧情，但是如果剧情文件比较大的时候，进度条会在加载到一定进度的时候，永远的停止，不再进行下载，这种问题跟我之前举的两个例子“服务器不会进行自动数据刷新连接”十分的相近。同时，我对是否该问题是我的服务器的问题进行了排除法实验，我使用的ssr在我的服务器进行架设，试验之后并无任何我上述反映的各类问题，所以基本可以确定是brook这款软件自身的问题。我所想反馈的问题大概就是这三个，希望我反馈的三个例子能够正确的让作者您理解我所想表达的问题，并且这类问题十分严重的影响了对brook这款软件日常的使用，还请您对此类问题进行排查修复，在这里先行感谢了。

English：
Hi, I am a user of your software brook. I would like to feedback a major bug problem about brook here. I hope you can reply this information and solve my problem. The problem is that after the successful connection is established using software, open all websites, such as I, for example "http://www.dlsite.com/maniax/" the site, after open the page will only stay on for the first time you open interface, for all the content of the scroll he does not automatically refresh, even if we build on a server delay is very low, he also only will quickly open the website page, and then no longer automatically connection, which all subsequent content could not be opened. Let me give you an example, let's say we're starting a game called kantai collcetion. This game is a web page game, in open the game's on the way, we will encounter many problems, read the account interface, the website will not automatically refresh, after manual refresh countless time you log in the game, because this is a web game, he will follow your operation with the game server data interaction, but if you use a brook to connect, after several interactions in a short period of time, the game will be caton in an interactive interface, data no longer interact, until you manually refresh the web page, he will have our first login problem of the game. I'll give a final example, I use the brook in the android system, connection problems when a mobile game, this kind of mobile phone game in the plot, plot content not cached in the mobile phone in advance, but when you choose to plot from the game server to download, I downloaded the plot, if it is a relatively small plot files, because I set up the brook server speed is faster, will be in soon time, the download is complete so as to make the game into the normal plot, but if the file is bigger, plot the progress bar will be loaded into a certain progress, This problem is very similar to the two examples I gave earlier, "the server will not have an automatic data refresh connection." At the same time, I conducted an experiment on whether the problem was a problem of my server. The SSR I used was installed on my server. After the test, there were no problems I reflected above. The problem I want to feedback is probably these three. I hope the three examples I give can help the author understand the problem I want to express to you correctly. Moreover, such problem has seriously affected the daily use of brook software.That is all，thank you。

**Comment by txthinking** [comment]
please follow the issue format
