### ISSUE TITLE
更新成20181212版本时候，我全局模式也访问不了instagram和facebook

### ISSUE THREAD

**Issue by zty464513026** [txthinking/brook#452]
### Prerequisites

访问不了INS 

### Environment

* Brook Version:V20181212
* Server Operating System:
* Server Operating System Version:V20181212
* Server Operation System Language:
* Client Operating System:IOS12
* Client Operating System Version:20181212
* Client Operation System Language:

### Steps to Reproduce

1.
2.
3.

**Comment by txthinking** [comment]
#1018
