### ISSUE TITLE
20181212, android version, whitelist not working

### ISSUE THREAD

**Issue by vongoethe** [txthinking/brook#453]
### Environment

* Brook Version: 20181212
* Server Operating System: Centos
* Server Operating System Version: Centos 7
* Server Operation System Language: English
* Client Operating System: Android
* Client Operating System Version: Android 8.1
* Client Operation System Language: English

### Expected Behavior
whitelist
### Current Behavior
whitelist not working
### Steps to Reproduce

1. baidu.com, searching keyword 'ip'
2. google.com, searching keyword 'ip'
3. both baidu and google return the same 'ip' which should be different in whitelist mode.

**Comment by txthinking** [comment]
Will be fixed in next version.

**Comment by K2Y71011** [comment]
666666

**Comment by txthinking** [comment]
Fixed in v20190205.
