### ISSUE TITLE
VPN not support ipv6 anymore

### ISSUE THREAD

**Issue by Whtie4622** [txthinking/brook#454]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Discussion
At version 20180909 brook could run on vpn mode and support ipv6 address, but since I have updated it to 20181212, the prompt now says "Can not find server v4 IP". Does anyone have the same problem?

**Comment by txthinking** [comment]
Please try v20190205, waiting for your response :)

**Comment by Whtie4622** [comment]
it works perfectly!

**Comment by Whtie4622** [comment]
it works perfectly!
