### ISSUE TITLE
Android: Apk engaging in usage tracking?

### ISSUE THREAD

**Issue by gerroon** [txthinking/brook#456]
Hi

According to https://apt.izzysoft.de/fdroid/index/apk/com.txthinking.brook , the Android apk tracks the user activity. Can you please shed some lights on this issue given that this is a sensitive networking app?

**Comment by txthinking** [comment]
Yes, it contains firebase analytics SDK:
https://firebase.google.com/products/analytics/

**Comment by gerroon** [comment]
Thanks
