### ISSUE TITLE
some way to fix issue that "Can not get default gateway in non-English version Windows platform"

### ISSUE THREAD

**Issue by Arktische** [txthinking/brook#457]
### In non-English version Windows platform,  specify default gateway is needed. That's inconvenient.
I have read the source code of Brook and had some solutions to fix this problem, but I'm not sure whether you're willing to accept solutions with cgo or other dependencies. So maybe I should take a discuss before I start a pull request ?

### solution using syscall
Here's a win32 API  `PIP_ADAPTER_INFO` contains the default gateway for each adapter. Using syscall to load the functions in `iphlpapi.dll`.
defect: data structure in this API is not compatible with Go.

### solution using cgo
defect: cross-compilation disabled.

### solution with an alone dynamic link library
Package this interface into a dll, release binary file with it on Windows platform.
defect: inconvenient.

BTW, this interface even contains the function operating ip routing table. I think it may be helpful for Brook project.

**Comment by eternal-flame-AD** [comment]
I think this could be implemented without `CGO`, though the use of unsafe memory operations is inevitable but much better than CGO in my opinion.

**Comment by txthinking** [comment]
v20200101, If still not working let me know, thx
