### ISSUE TITLE
iOS12.1 v1212 can't work on instagram

### ISSUE THREAD

**Issue by Pray3** [txthinking/brook#459]
### Prerequisites

We can access the telegram by setting up a proxy, but what about Instagram?

### Environment

* Brook Version: v20181212
* Server Operating System:centos 
* Server Operating System Version:centos 7
* Server Operation System Language:english
* Client Operating System:IOS
* Client Operating System Version:IOS12
* Client Operation System Language:chinese

### Steps to Reproduce

1.
2.
3.

**Comment by txthinking** [comment]
Fixed in v20190205.

**Comment by txthinking** [comment]
#1018
