### ISSUE TITLE
Support specify black/white list in CLI

### ISSUE THREAD

**Issue by maxchendt** [txthinking/brook#462]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version:  20181212
* Operating System: Ubuntu 
* Operating System Version: 18.04
* Operation System Language: en

### Question
In ss-libev, for access control (I am using)

    /usr/bin/ss-local -c ./shadowsocks-IPv6.json  --acl ./gfwlist.acl  -6 -u  -v

where gfwlist.acl is from https://github.com/shadowsocks/shadowsocks-libev/raw/master/acl/gfwlist.acl 

I am now testing brook.  Is it possible that (or some other way around in Linux)

    ./brook  client -l 127.0.0.1:1080 -i 127.0.0.1 -s [2402:dc:12d::]:6868 -p RrOUdksZNxCg --acl  ./black.list

where black.list is from https://blackwhite.txthinking.com/black.list

**Comment by txthinking** [comment]
Yes. this is possible. I will consider this feature :)
