### ISSUE TITLE
ios version12.12 not work 

### ISSUE THREAD

**Issue by yoelvi** [txthinking/brook#465]
### Prerequisites
ios version1212 can only work on safari and youtube, facebook app and instagram app not work

### Environment

* Brook Version:
* Server Operating System: Ubuntu 
* Server Operating System Version:  16.04
* Server Operation System Language: English
* Client Operating System:  ios
* Client Operating System Version: 12.1.1
* Client Operation System Language: Chinese

### Current Behavior
facebook and instagram app not work

### Possible Solution
Add the function that we can add the pac file locally or specify my own pac url.
In the windows version 0909, when the whitelist server is blocked,I have built a server on my vps,
and specified my own pac file. It works well. Thank you.

**Comment by txthinking** [comment]
Fixed in v20190205.

**Comment by txthinking** [comment]
#1018
