### ISSUE TITLE
v20181212 cannot be open by MacOS 10.14

### ISSUE THREAD

**Issue by rnsvarsitybball** [txthinking/brook#467]
Trying to open the app, but after it is jumping on my dock, it quit by it self.

**Comment by ychaoyang** [comment]
can't work 10.14  MACOS

**Comment by donaldzou** [comment]
@ming871 You can try to reinstall the previous version, v20180707, and reinstall the server brook to v20180909 and it works. But the thing is, only global mode works well, not even pac and white/black list. (Or you can download the pac file from https://github.com/txthinking/pac and you can host it on your own server. That works too :)

**Comment by RenruiLiu** [comment]
same problem, pls fix plsss

**Comment by lpnpcs** [comment]
me too 。。。

**Comment by lpnpcs** [comment]
> @ming871 You can try to reinstall the previous version, v20180707, and reinstall the server brook to v20180909 and it works. But the thing is, only global mode works well, not even pac and white/black list. (Or you can download the pac file from https://github.com/txthinking/pac and you can host it on your own server. That works too :)

hello where can I find v20180707 app  i can not find it thx

**Comment by lpnpcs** [comment]
> > > @ming871 You can try to reinstall the previous version, v20180707, and reinstall the server brook to v20180909 and it works. But the thing is, only global mode works well, not even pac and white/black list. (Or you can download the pac file from https://github.com/txthinking/pac and you can host it on your own server. That works too :)
> > 
> > 
> > hello where can I find v20180707 app i can not find it thx
> 
> Hi, I still have it in my google drive :)
> https://drive.google.com/file/d/1iWmLiNGI_tTdaAc8hDoVkFNk4XJLT2Iu/view?usp=sharing

thank you

**Comment by txthinking** [comment]
Please try to remove the old version clean, and install the latest version follow the wiki.
