### ISSUE TITLE
I try to compile brook as a framework by gomobile, but failed,so do you have a plan to supported gomobile?

### ISSUE THREAD

**Issue by Mondaydream** [txthinking/brook#468]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
yes
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
yes
* [x] Are you running the latest version?
yes
* [x] I will write this according to this template.
yes
* [x] I will write this in English.
yes

### Discussion
I try to compile brook as a framework by gomobile, but failed,so do you have a plan to supported gomobile?

**Comment by donaldzou** [comment]
Tried `sudo gomobile build -target=ios -bundleid=org.lang.todo github.com/txthinking/brook`

no luck :)

**Comment by Mondaydream** [comment]
> Tried `sudo gomobile build -target=ios -bundleid=org.lang.todo github.com/txthinking/brook`
> 
> no luck :)

not work and the correct command should be gomoblie bind

**Comment by donaldzou** [comment]
> > Tried `sudo gomobile build -target=ios -bundleid=org.lang.todo github.com/txthinking/brook`
> > no luck :)
> 
> not work and the correct command should be gomoblie bind

I Tried, but this came up:

`gomobile: /usr/local/go/bin/gobind -lang=go,objc -outdir=/tmp/gomobile-work-265923639 -tags=ios github.com/txthinking/brook failed: exit status 2
functions and methods must return either zero or one values, and optionally an error
functions and methods must return either zero or one values, and optionally an error
functions and methods must return either zero or one values, and optionally an error
functions and methods must return either zero or one values, and optionally an error
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1223b27]

goroutine 1 [running]:
golang.org/x/mobile/bind.(*funcSummary).asMethod(0x0, 0xc0028923c0, 0xd, 0x7)
	/usr/local/go/src/golang.org/x/mobile/bind/genobjc.go:557 +0x37
golang.org/x/mobile/bind.(*ObjcGen).genStructH(0xc0028923c0, 0xc0016bcd20, 0xc002f90f60)
	/usr/local/go/src/golang.org/x/mobile/bind/genobjc.go:1136 +0xe15
golang.org/x/mobile/bind.(*ObjcGen).GenH(0xc0028923c0, 0x17, 0x137cdc0)
	/usr/local/go/src/golang.org/x/mobile/bind/genobjc.go:186 +0x15e1
main.genPkg(0x7ffeefbffb32, 0x4, 0xc0001d7a90, 0xc0022e0700, 0x12, 0x20, 0xc000444000, 0x1, 0x1, 0x0, ...)
	/usr/local/go/src/golang.org/x/mobile/cmd/gobind/gen.go:144 +0x1628
main.run()
	/usr/local/go/src/golang.org/x/mobile/cmd/gobind/main.go:158 +0xa27
main.main()
	/usr/local/go/src/golang.org/x/mobile/cmd/gobind/main.go:45 +0x27`

Could you help me please? Thanks!

**Comment by txthinking** [comment]
Sorry, this is not in the plan. I think you'd better learn iOS dev first.
