### ISSUE TITLE
白名单和win64客户端闪退问题

### ISSUE THREAD

**Issue by YKetty** [txthinking/brook#47]
安卓国际版微博不在白名单内。。。

虽然自定义代理应用会有悖于简单容易配置的初衷，

但还是真心希望添加这个功能，毕竟白名单难免会有疏漏。

我用的是WIN7 X64，但32 64位客户端闪退了，管理员运行也是如此。

**Comment by txthinking** [comment]
国际版微博是https://play.google.com/store/apps/details?id=com.weico.international 这个吗

Windows客户端是用的https://github.com/txthinking/brook/releases/download/v20170516/Brook.exe
 这个吗

**Comment by YKetty** [comment]
是那个微博，没错

看了你另一个issues的回答，明白怎么回事了，

我下的是20170723的brook_windows_386.exe ，brook_windows_amd64.exe，

使用5.16的Brook.exe正常

releases里面的命名有点混乱，容易让人搞不清，统一并标注一下server和client就好了

**Comment by txthinking** [comment]
好的，得空把这个国际微博加到白名单。
感谢建议。

**Comment by txthinking** [comment]
Android v20170809已添加
