### ISSUE TITLE
what is server?

### ISSUE THREAD

**Issue by zhangliaosong** [txthinking/brook#471]
```
name: Question
labels: question
about: Have any questions regarding how to use brook?
```

### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ ] I will write this according to this template.
* [ ] I will write this in English.

### Environment

* Brook Version:
* Operating System:
* Operating System Version:
* Operation System Language:

**Comment by Dr-Bluemond** [comment]
A server is a computer which isn't located in China. It usually runs Linux that you don't familiar with. You should pay some money to rent a server, and then use SSH to access to it.

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/wiki/How-to-run-Brook-Relay-Server-on-Linux%3F
