### ISSUE TITLE
Mac browser can access google, the terminal can not access 

### ISSUE THREAD

**Issue by wedaren** [txthinking/brook#472]
```
name: Mac browser can access google, the terminal can not access
labels: question
```

### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version:20181212
* Operating System:macOS
* Operating System Version: 10.14
* Operation System Language:Chinese

### Question

Mac browser can access google, the terminal can not access

**Comment by echokk11** [comment]
you need set http_proxy/https_proxy in terminal

**Comment by wedaren** [comment]
> you need set http_proxy/https_proxy in terminal

Why does the terminal need it but the browser doesn't need it?

**Comment by HSczy** [comment]
Same Problem I have set http_proxy=socks5:localhost:1080 It didn't work for me .
What can I do?

**Comment by txthinking** [comment]
@wedaren Because Terminal application ignore system proxy.

**Comment by txthinking** [comment]
@HSczy https://github.com/txthinking/brook/issues/486

**Comment by txthinking** [comment]
@wedaren Another solution: just use brook cli VPN mode

**Comment by fahamjv** [comment]
> Solution 0: Use brook cli vpn mode.

How can i use the brook cli vpn mode, what's the instroduction ?
Cisco anyconnect cover the terminal too without any additional config. how can i use brook like this ?
![image](https://user-images.githubusercontent.com/20015479/140797844-1ed7662c-dd79-4eb2-80c2-3166befbe9bb.png)
