### ISSUE TITLE
VPN mode was started successfully on macOS 10.14.2 but none DNS name cannot be resolved

### ISSUE THREAD

**Issue by zky999** [txthinking/brook#480]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Are you running the latest version?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version: 20181212
* Server Operating System: CentOS
* Server Operating System Version: 7.4
* Server Operation System Language: English
* Client Operating System: macOS Mojave
* Client Operating System Version: 10.14.2
* Client Operation System Language: English

### Expected Behavior
Any local applications could access a remote host by its domain name.

### Current Behavior
Remote host name cannot be resolved.

### Steps to Reproduce
1. start brook vpn:
`$ sudo brook_darwin_amd64 -d vpn -l 127.0.0.1:1080 -s server_host_name:port -p server_password`

2. access google.com via cURL
`$ curl -v 'google.com'`
> \* Rebuilt URL to: google.com/
> \* Could not resolve host: google.com
> \* Closing connection 0
> curl: (6) Could not resolve host: google.com

### Detailed Description
1. Looks like local DNS server was started:
`$ nmap -p53 127.0.0.1`
> ...
> PORT   STATE  SERVICE
> 53/tcp open domain

2. But resolve google.com failed:
`$ dig @127.0.0.1 google.com`
> ...
> ;; connection timed out; no servers could be reached

### Possible Solution
I don't know.

**Comment by txthinking** [comment]
Does your same server/password work on Brook GUI client?
Or try to restart your compute.

**Comment by txthinking** [comment]
And try to remove `-d`

**Comment by zky999** [comment]
Version 20190205 works like a charm! Thank you!
