### ISSUE TITLE
Cannot connect to Google Firebase/Firestore

### ISSUE THREAD

**Issue by RenruiLiu** [txthinking/brook#481]
### Environment

* Brook Version: 20181212
* Operating System: Mac GUI 、 iOS
* Operating System Version: 
* Operation System Language: Chinese

### Question

I'm developing an app using Google Firebase/Firestore (https://console.firebase.google.com  & like https://insviewer-68b24.firebaseio.com/). And I was trying to write or read data in database, but there was no network respond

**Comment by txthinking** [comment]
Configure and use system proxy when you send a network request in your iOS app code.
