### ISSUE TITLE
macos系统下使用无线网卡连接网络时，点击brook开始，会报错802.11n nic is not a recognized network service,**error:the parameters is not valid.exit status 4.

### ISSUE THREAD

**Issue by xiaoxiongke** [txthinking/brook#483]
### Prerequisites

* [o] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [o] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [o] Are you running the latest version?
* [o] I will write this according to this template.
* [ ] I will write this in English.

### Environment

* Brook Version:20181212
* Server Operating System:macos 10.14
* Server Operating System Version:latest
* Server Operation System Language:chinese
* Client Operating System:latest
* Client Operating System Version:20181212
* Client Operation System Language:chinese

### Steps to Reproduce
macos系统下使用无线网卡连接网络时，点击brook开始，会报错802.11n nic is not a recognized network service,**error:the parameters is not valid.exit status 4.

### Possible Solution
可能时没有识别无线网卡。。

**Comment by blockchainsecure** [comment]
mac OS  下都无法用gui，我用的命令行模式下，连接不稳定！

**Comment by txthinking** [comment]
I will write this in English.
