### ISSUE TITLE
当brook  Run as multiple brook servers 时，brook android 20181212 连接不上服务器

### ISSUE THREAD

**Issue by bigbighill** [txthinking/brook#484]
# Run as multiple brook servers 时
$ brook servers -l ":9999 password" -l ":8888 password"
这种模式下，brook android 20181212 连接不上服务器，
服务器端错误日志：
2019/01/17 22:26:08 cipher: message authentication failed
2019/01/17 22:26:08 cipher: message authentication failed
2019/01/17 22:26:12 cipher: message authentication failed
2019/01/17 22:26:17 cipher: message authentication failed
2019/01/17 22:26:20 cipher: message authentication failed

**Comment by txthinking** [comment]
You used the wrong password in android app.
