### ISSUE TITLE
the proxy connection refused

### ISSUE THREAD

**Issue by zhangguanzhang** [txthinking/brook#486]
```
   IPv4 地址 . . . . . . . . . . . . : 10.0.23.72
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 10.0.23.1
```
```
[root@CentOS76 ~]# export http_proxy=socks5://10.0.23.72:1080
[root@CentOS76 ~]# export https_proxy=socks5://10.0.23.72:1080
[root@CentOS76 ~]# curl www.google.com
curl: (7) Failed connect to 10.0.23.72:1080; Connection refused
[root@CentOS76 ~]# unset http_proxy
[root@CentOS76 ~]# unset https_proxy
[root@CentOS76 ~]# export ALL_PROXY=socks5://10.0.23.72:1080
[root@CentOS76 ~]# curl www.google.com
curl: (7) Failed connect to 10.0.23.72:1080; Connection refused
[root@CentOS76 ~]# curl www.google.com
curl: (7) Failed connect to 10.0.23.72:1080; Connection refused
[root@CentOS76 ~]# telnet 10.0.23.72 1080
Trying 10.0.23.72...
telnet: connect to address 10.0.23.72: Connection refused
```
firewalld is already closed，How to resovle it

**Comment by dabiaoge** [comment]
The Linux system natively does not support the socks5 protocol. So the following command does not work:

> export http_proxy=socks5://10.0.23.72:1080

If you really need to provide a proxy for the Linux system,you need a http proxy.Please  consider converting the socks5 protocol to the http protocol using some software just like polipo or haproxy ,then set the HTTP_PROXY  environmental variable to your Linux system.
In addition, Linux systems are case sensitive, which means ，you need **HTTP_PROXY**  not http_proxy.

**Comment by zhangguanzhang** [comment]
The haproxy should run at the book server or the user's terminal

**Comment by dabiaoge** [comment]
Either side is OK. In your case, 10.0.23.72  may be better.

**Comment by dabiaoge** [comment]
Forgot to remind you, brook can convert socks5 protocol to http protocol ,you do not need a third-party software ! Try the following command
> brook socks5tohttp -l :8080 -s 127.0.0.1:1080
run it in 10.0.23.72 and then you can set your linux host's proxy as : 
> export HTTP_PROXY=http://10.0.23.72:8080

**Comment by dabiaoge** [comment]
Forgot to remind you, brook can convert socks5 protocol to http protocol ,you do not need a third-party software ! Try the following command

> brook socks5tohttp -l :8080 -s 127.0.0.1:1080


run it in 10.0.23.72 and then you can set your linux host's proxy as :

> export HTTP_PROXY=http://10.0.23.72:8080
