### ISSUE TITLE
How to compile an Android project on windows

### ISSUE THREAD

**Issue by catsay217994** [txthinking/brook#488]
I can't compile with gomobile on windows 10 x64

**Comment by catsay217994** [comment]
Can I provide a compilation method on Windows 10 x64?

**Comment by catsay217994** [comment]
Can you provide a compilation method on Windows 10 x64?

**Comment by txthinking** [comment]
Please try brook linux cli version

**Comment by catsay217994** [comment]
Thank you for your answer, I will go to the test now.
