### ISSUE TITLE
when server run as socks5, which mode should the client running?

### ISSUE THREAD

**Issue by ywray** [txthinking/brook#489]
In service ,  I start the brook used follow cmd:
./brook socks5 -l :9999 -i 111.111.111.111(service ip)

when i run client in my pc, the follow cmd didnot work correct
./brook_darwin_amd64 client -l 127.0.0.1:1081 -i 127.0.0.1 -s 111.111.111.111:9999

what is the correct method to start a client when service is running as socks5?

thanks a lot !!!

**Comment by dabiaoge** [comment]
You do not need a brook client, just set your proxy ip and port  applying  to any software that support socks5 protocol. But ,always remember, socks5  protocol is **not encrypted** , any node between your socks5  proxy server and client can sniff ,filter and censor all the transferred content.

**Comment by txthinking** [comment]
As @dabiaoge said.
