### ISSUE TITLE
不明IP连接，有后门？

### ISSUE THREAD

**Issue by guolilong2012** [txthinking/brook#49]
![ip 110 19 183 212](https://user-images.githubusercontent.com/747329/29059582-d328cad6-7c48-11e7-9311-654100590db5.png)

**Comment by guolilong2012** [comment]
有后门，还是啥问题。求大神解释。

**Comment by guolilong2012** [comment]
我在两台vps上搭建了brook，同一时刻110.19.183.212这个IP都在连我的两个vps。有后门，还是啥问题？求大神解释。

**Comment by txthinking** [comment]
你的本机IP是？

**Comment by txthinking** [comment]
> 有后门
无
> 还是啥问题？
不知
> 好吓人，求大神解释。
不知

**Comment by guolilong2012** [comment]
我的两台vps ip是*.*.*.239、*.*.*.34，开启2000端口，连我的IP是110.19.183.212。同一时刻，这个IP都在连我的两台vps，吓我一跳。不知道咋回事。

**Comment by guolilong2012** [comment]
110.19.183.212，这个不是我本机IP。

**Comment by guolilong2012** [comment]
110.19.183.212，这个不是我本机IP。
