### ISSUE TITLE
右击brook gui， 选择setting, 为什么弹出网页？

### ISSUE THREAD

**Issue by anlexN** [txthinking/brook#490]
```
name: 右击brook gui， 选择setting, 为什么弹出网页？
labels: 右击brook gui， 选择setting, 为什么弹出网页？
about: Have any questions regarding how to use brook? yes
```

### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version: v20181212
* Operating System: windows 10 pro
* Operating System Version: windows 10 pro
* Operation System Language: chinese

### Question
where is settings? only webpage?
![image](https://user-images.githubusercontent.com/8686739/51665835-993ff700-1ff7-11e9-928f-3e2631545406.png)

**Comment by txthinking** [comment]
I will write this in English.

**Comment by anlexN** [comment]
@txthinking, but can you tell me where brook settings is?
