### ISSUE TITLE
Brook does not work in iOS 12.1.3

### ISSUE THREAD

**Issue by lut777** [txthinking/brook#491]
iOS client Brook Version: 20181212
ServerVersion:  20181212

### Expected Behavior
Google, youtube, PH and so on should be accessible on both iOS and MacOS.

### Current Behavior
Brook MacOS client work well, HOWEVER, iOS client does not work. 
Any web service through Brook is inaccessible.

### Detailed Description
No.

### Possible Solution
Still trying. 
I can not find the  "Global Mode" in this iOS client version as mentioned in other issues.

**Comment by RollingL** [comment]
I have the same problem.

**Comment by UniversalFlamer** [comment]
Same Problem here.
Works well on Windows while unable to work on iOS.

**Comment by luckyBricks** [comment]
> Same Problem here.
> Works well on Windows while unable to work on iOS.

Update to the lasted version

**Comment by raamking** [comment]
same problem and fixed by 0205 version.but could explain why
 This is a bug ？before that the ios and app doesn’t change anything ,just the time changes and iOS client not work?

**Comment by lut777** [comment]
problem solved after updating Brook to v20190205.
