### ISSUE TITLE
Fail in IOS11.4.1

### ISSUE THREAD

**Issue by akakleo99** [txthinking/brook#493]
Can’t connected to internet after brook client was started. 
IOS11.4.1
Can’t connected to internet both outside China and inside China.

**Comment by 2foil** [comment]
+1

**Comment by 2foil** [comment]
It also fails on iOS 12.1.3.

**Comment by txthinking** [comment]
Does your same server/password work on desktop in same network?

**Comment by 2foil** [comment]
On macOS 10.14.2 and win10 with the same server/password, the Brook client works well.
But a few days ago, the iOS client cannot connect to internet. May it be a bug of iOS itself?

**Comment by txthinking** [comment]
same network?

**Comment by 2foil** [comment]
> same network?

Yes, in the same network.

**Comment by txthinking** [comment]
Never work?

**Comment by txthinking** [comment]
Not a bug. If you still have problem, please open a new issue and fill in the format. let me know how to reproduce it. thank you.
