### ISSUE TITLE
Does Brook support Android TV box?

### ISSUE THREAD

**Issue by lalawoo** [txthinking/brook#494]
RT
无法连接

**Comment by txthinking** [comment]
I have no Android TV box, can you provide more information like: installation steps? The detail abnormal information?

**Comment by kalhori124** [comment]
Hi @txthinking 

I have an Android TV box  ( Xiaomi Mi Box S ), What information do you need?

**Comment by txthinking** [comment]
@kalhori124  Thank you. I just don't know how to help @lalawoo .
@lalawoo If you can provide more information, @kalhori124 may help you.
