### ISSUE TITLE
how to install it on macOS 10.13.6

### ISSUE THREAD

**Issue by lin8yy8** [txthinking/brook#495]
i install Brook.dmg,
but it didn't work after i c it.

listed below：
You are using macOS 10.13.6. The application requires macOS 10.14 or later.

Can I install and use this version of macOS 10.13.6 without upgrading?

**Comment by txthinking** [comment]
Please upgrade your MacOS. This is a good habit.

**Comment by zhoubowen-sky** [comment]
I have the same problem, the latest system does not save power.
