### ISSUE TITLE
v20190205 still can't open by macOS 10.14.3 (18D42)

### ISSUE THREAD

**Issue by donaldzou** [txthinking/brook#497]
Has been removed before install, and restarted, then drag the new one into application folder. Allow unidentified developer, then brook logo jump for once and turn off.....

**Comment by txthinking** [comment]
This is really strange.
Can you provide a video please?

**Comment by donaldzou** [comment]
[brrok.mov.zip](https://github.com/txthinking/brook/files/2845947/brrok.mov.zip)

**Comment by txthinking** [comment]
![image](https://user-images.githubusercontent.com/1241807/52492099-7f133500-2c03-11e9-9c2a-a2ca7d1c014a.png)
The default tray icon is black.

![image](https://user-images.githubusercontent.com/1241807/52492121-89cdca00-2c03-11e9-8c6c-fbaf6daffbce.png)

Maybe your brook is already started.
Move your mouse into system bar area for checking.

![image](https://user-images.githubusercontent.com/1241807/52492301-ddd8ae80-2c03-11e9-804f-d3f50aa31810.png)

**Comment by yipkakit** [comment]
the same problem happened in my mbp.....SOS... (the same env..OSX10.14.3)....
when i open the Brook.app floder >Contents > MacOS and double click the Brook.


i got this 
——————————————
CherishdeMBP:~ cherish$ /Volumes/Brook/Brook.app/Contents/MacOS/Brook ; exit;
2019/02/09 00:51:46 creating tray failed: canceller.cancelled
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]
——————————————————


and i try to run in command line.


———————————————————
sh-3.2# /Volumes/Brook/Brook.app/Contents/MacOS/Brook
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100 pc=0x43584e2]

goroutine 52 [running]:
github.com/asticode/go-astilectron.(*Astilectron).NewNotification(0x0, 0xc00038c000, 0x2e)
	/Users/tx/go/src/github.com/asticode/go-astilectron/astilectron.go:425 +0x22
main.hi(0x46b9720, 0xc000388000)
	/Users/tx/go/src/github.com/txthinking/brookdesktop/main.go:362 +0xa9
main.main.func5.1()
	/Users/tx/go/src/github.com/txthinking/brookdesktop/main.go:141 +0x5e
created by main.main.func5
	/Users/tx/go/src/github.com/txthinking/brookdesktop/main.go:138 +0x8f

**Comment by yipkakit** [comment]
omg ！！！！u r right ！the brook is already running..but it seems like invisible in the system bar....thankyou！

**Comment by txthinking** [comment]
@yipkakit
Another suggestion, the better way is  drag the Brook.app from dmg into Application folder.
After copied, path like
this:
/Applications/Brook.app
not:
/Volumes/Brook/Brook.app

**Comment by donaldzou** [comment]
@txthinking Ah i see!!! Thank you soooo much!
