### ISSUE TITLE
Can't work with macOS 10.14.2

### ISSUE THREAD

**Issue by GOODXIONG** [txthinking/brook#498]
### Environment

* Brook Version:20181212
* Server Operating System:CentOS 7 x64
* Server Operating System Version:https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/brook.sh
* Server Operation System Language:English
* Client Operating System:macOS 
* Client Operating System Version:10.14.2
* Client Operation System Language:English

### Detailed Description
when I click 'start',
![2019-02-09 5 28 46](https://user-images.githubusercontent.com/17375177/52519163-440c1280-2c92-11e9-8892-ca22566a6773.png)
How can I fix it?

**Comment by txthinking** [comment]
1. install latest version.
2. restart your computer
3. run brook on your computer
