### ISSUE TITLE
build local online PAC

### ISSUE THREAD

**Issue by txthinking** [txthinking/brook#50]
Sometimes remote online pac was blocked by GFW.

**Comment by txthinking** [comment]
| Download | Server/Client  | OS | Arch | Remark |
| --- | --- | --- | --- |
| brook | Server & Client | Linux | amd64 | CLI |
| brook | Server & Client | Linux | amd64 | CLI |
| brook | Server & Client | Linux | amd64 | CLI |
| brook | Server & Client | Linux | amd64 | CLI |

**Comment by txthinking** [comment]
v20170809

**Comment by GJCav** [comment]
> v20170809
I'm a user of Brook for andriod.
The client version(apk version) is v20190405.
And I wonder if I can use a customized PAC rules(or if I can modify the PAC rules)?

**Comment by txthinking** [comment]
Plan this feature in the next release

Track: https://github.com/txthinking/brook/issues/54
