### ISSUE TITLE
使用xshell透过brook代理连接远端ssh终端时有一个奇怪的现象

### ISSUE THREAD

**Issue by kleveralt** [txthinking/brook#500]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [ ] I will write this according to this template.
* [ ] I will write this in English.

### Environment

* Brook Version: latest
* Server Operating System: linux centos7.x 64bit
* Server Operating System Version: 
* Server Operation System Language:
* Client Operating System: windows 10 64bit
* Client Operating System Version:
* Client Operation System Language:

### Expected Behavior
ssh连接正常关闭

### Current Behavior
ssh连接无法正常关闭

### Detailed Description
当使用xshell6透过brook代理连接远端ssh时，在终端执行logout退出终端时无法正常关闭TCP连接，似乎处于一个等待TCP关闭信号但一直等不到的状态，采用直连远端ssh或者透过ssr代理连接，都不会有这个现象。

不正常现象
![unn](https://user-images.githubusercontent.com/20249351/52522313-84818580-2cbe-11e9-9cb5-b353150ed194.png)
正常
![non](https://user-images.githubusercontent.com/20249351/52522319-8c412a00-2cbe-11e9-887c-4ab86bdcd006.png)

### Possible Solution
无解

**Comment by txthinking** [comment]
Can you try this on your terminal instead of xshell:
```
$ ssh -o ProxyCommand='nc -x 127.0.0.1:1080 %h %p' user@server.com
$ logout
```

**Comment by kleveralt** [comment]
> Can you try this on your terminal instead of xshell:
> 
> ```
> $ ssh -o ProxyCommand='nc -x 127.0.0.1:1080 %h %p' user@server.com
> $ logout
> ```

在windows无法完成测试，
![non](https://user-images.githubusercontent.com/20249351/52524941-9a527300-2cdd-11e9-93da-f71eb64395e0.png)

在运行brook的linux主机上运行一个brook client实例，并且用ssh和proxycommand命令可以完成测试并且socket可以正常关闭

可是我的问题是，同样是xshell，在透过ssr提供的socks代理，或者直连，都不会有socket无法关闭的现象。

**Comment by txthinking** [comment]
Sorry, I am not familiar with xshell.
