### ISSUE TITLE
Brook Mac Client: Can't change listen address

### ISSUE THREAD

**Issue by GOODXIONG** [txthinking/brook#501]
### Environment

* Brook Version: v20190205
* Server Operating System: Centos
* Server Operating System Version: 7
* Server Operation System Language: English
* Client Operating System: macOS
 Client Operating System Version: 10.14.2
* Client Operation System Language: Simplified Chinese

### Detailed Description
listen tcp 127.0.0.1: 1080: bind address already in use
![2019-02-09 5 28 46](https://user-images.githubusercontent.com/17375177/52530513-db7c6e80-2d41-11e9-8afb-cebc78e4b0e2.png)

I try to use the Enable mode.
https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client

But I can't change the Listen. I can't type anything in Listen.
How can I change the Listen?
![2019-02-10 12 24 56](https://user-images.githubusercontent.com/17375177/52530525-2a2a0880-2d42-11e9-9e0e-6446fd648893.png)

**Comment by GOODXIONG** [comment]
@txthinking

**Comment by txthinking** [comment]
It's a bug. Will be fixed in next version.

**Comment by txthinking** [comment]
I rewrote the client, I will improve it step by step.
