### ISSUE TITLE
Brook as Point To Point VPN

### ISSUE THREAD

**Issue by kalhori124** [txthinking/brook#502]
Hi.

Is it possible to configuration Brook as Point to Point VPN like Wireguard?
Does it support TCP/UDP Protocols?

I am looking for a guide to set up Brook as P2P VPN.

Best Regards,

**Comment by txthinking** [comment]
Yes, your can access any TCP/UDP services on your server from your client through brook.

**Comment by txthinking** [comment]
In next version.
You can access any TCP/UDP services running on your server from your client through `$ brook server` <--> `$ brook vpn`.

**Comment by txthinking** [comment]
v20190401, Please try:

### On server
```
$ brook server ... # start brook
$ Start mysql and listen on 10.140.0.3:3306 # 10.140.0.3 is your server private IP
```
### On client (Your desktop computer)

```
$ sudo brook vpn ...
$ mysql -h 10.140.0.3 # connect to mysql which running on your server
```

**Comment by kalhori124** [comment]
It works! 
Thanks you

**Comment by amosbird** [comment]
Can we also support a reversed vpn? that is, `brook server` tries to connect to a `brook vpn` instance. It's useful when one'd like to temporarily share the local machine's network to remote. Of course we can make that `brook vpn` only accept one connect at a time.

**Comment by txthinking** [comment]
@amosbird maybe try https://github.com/txthinking/mr2 ?

**Comment by likev** [comment]
> That's not the use case I was seeking for. It's to allow the local server access the Internet using client as the gateway, not to expose its services

first: run `brook socks5 --listen :1080 --socks5ServerIP 1.2.3.4` at client
then: use [zoro (mr2)](https://github.com/txthinking/zoro) to expose client socks5
now you can access local machine's network through exposed socks5
