### ISSUE TITLE
请问服务器端没有发布docker镜像吗

### ISSUE THREAD

**Issue by haohowey** [txthinking/brook#504]
如题，SS和V2ray都有docker，非常方便进行升级、维护和管理
另外如果android能在play store上发布就更方便了

**Comment by chenhw2** [comment]
Refer: https://cloud.docker.com/repository/docker/chenhw2/brook

**Comment by txthinking** [comment]
https://www.google.com/search?newwindow=1&ei=BVlmXOOfMork-Aa18omgAg&q=google+terminated+developer+account&oq=google+terminated+developer+account&gs_l=psy-ab.3..0i8i30l2.20596.20596..20792...0.0..0.147.147.0j1......0....1..gws-wiz.......0i71.CcFTwCCVW20
