### ISSUE TITLE
Strange connectivity issue with 4G network on Android devices

### ISSUE THREAD

**Issue by georgelyu** [txthinking/brook#505]
### Prerequisites

* [ checked ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [ checked ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ checked ] Are you running the latest version?
* [ checked ] I will write this according to this template.
* [ checked ] I will write this in English.

### Discussion

I have this server running Brook that's all fine. I can browse websites through Brook on my laptop and anything. When I start Brook on my Android phone under WiFi, it is still running smoothly. However, it does not work when I switch to 4G network. I tried to visit a webpage on the server under 4G network with my phone and it has no problem, which shows that it is not a connectivity issue with the server under my 4G network. Then I switched on WiFi Hotspot and had my laptop connected to it. Strange thing happened, it all works if I use the PC version of Brook with my 4G network but not on the Android version. So that means good probability of a bug in the Android client. Posted to see if anyone has encountered the same problem and hope for a fix maybe. Thx.

**Comment by bosco85** [comment]
the same situation on ios 12.1.4

**Comment by txthinking** [comment]
Can you confirm:
4G network <---- tcp/udp ----> Your server
?

**Comment by txthinking** [comment]
This is usually caused by your network.
