### ISSUE TITLE
Use with Haproxy

### ISSUE THREAD

**Issue by machsix** [txthinking/brook#506]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version: v20190205
* Server Operating System: CentOS
* Server Operating System Version: 7
* Server Operation System Language: en_US
* Client Operating System: Any

### Detailed Description
The condition for me is that my company blocks request to website on internet with ports other than 443 and 80. Thus, many programs need to share the same port. On my VPS, I use haproxy to forward TCP request to nginx and ssh based on the feature of data. For example, the first few bytes of SSH protocol are always `SSH-2.0`. I wonder if brook has something similar to [this feature of V2ray](https://toutyrater.github.io/advanced/wss_and_web.html), or if there are some specific features of the protocol used by Brook. I did notice that Brook server needs to listen to both TCP and UDP, so maybe it's impossible to achieve this? :cry: 
I know I could achieve this by SSH port forwarding, but it is too painful to setup port forwarding on IOS.

Thanks for your great work!

**Comment by txthinking** [comment]
I am not particularly aware of your needs description.
Do you mean `Brook client <--- WebSocket(TCP) ---> Brook server`?

**Comment by machsix** [comment]
Yes, exactly! It will be great if we can customize [SNI](https://en.m.wikipedia.org/wiki/Server_Name_Indication). In such sense, haproxy can easily forward request to brook by an acl rule matching req.ssl_sni and HTTPS/Brook multiplexing is achieved. This would be useful for users whose company/country blocks access to all ports other than 80 and 443.

**Comment by txthinking** [comment]
try v20200101  brook wsserver
