### ISSUE TITLE
日志里有可疑的错误

### ISSUE THREAD

**Issue by jd16320** [txthinking/brook#507]
今天无意中查了下日志，发现有错误如下：
`Feb 13 05:54:15 debian brook[18770]: 2019/02/13 05:54:15 EOF
Feb 13 05:54:16 debian brook[18770]: 2019/02/13 05:54:16 cipher: message authentication failed
Feb 13 07:16:33 debian brook[18770]: 2019/02/13 07:16:33 cipher: message authentication failed
Feb 13 07:16:33 debian brook[18770]: 2019/02/13 07:16:33 cipher: message authentication failed
Feb 13 07:16:33 debian brook[18770]: 2019/02/13 07:16:33 cipher: message authentication failed
Feb 13 07:16:33 debian brook[18770]: 2019/02/13 07:16:33 EOF
Feb 13 08:47:57 debian brook[18770]: 2019/02/13 08:47:57 unexpected EOF
Feb 13 08:47:57 debian brook[18770]: 2019/02/13 08:47:57 cipher: message authentication failed
Feb 13 08:47:57 debian brook[18770]: 2019/02/13 08:47:57 cipher: message authentication failed
Feb 13 15:20:11 debian brook[18770]: 2019/02/13 15:20:11 cipher: message authentication failed`
查了一下cipher是密码的意思，后面还提到了消息认证。我今天没有连接VPS，这是WALL在主动探测的痕迹吗？

**Comment by txthinking** [comment]
As long as your server is open on the Internet, it will be scanned frequently.
