### ISSUE TITLE
UDP support

### ISSUE THREAD

**Issue by Shadowhack0419** [txthinking/brook#51]
请问大大大神，有没有考虑添加UDP传输呢，行的话那真是太好啦，打游戏都可以用Brook啦。^_^

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by txthinking** [comment]
I am working on this feature.

**Comment by txthinking** [comment]
Fixed in v20171111 @Shadowhack0419
