### ISSUE TITLE
一加5,安卓9开启brook代理只能访问国内网站及Telegram,其余均连接失败. 同样情况PC正常使用

### ISSUE THREAD

**Issue by 768927433** [txthinking/brook#510]
### Prerequisites

* [Y ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [Y ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ Y] Are you running the latest version?
* [ Y] I will write this according to this template.
* [Y ] I will write this in English.

### Environment

* Brook Version: v20190205
* Server Operating System: Debian
* Server Operating System Version: Debian 8 x86_64  
* Server Operation System Language: Go
* Client Operating System: Android
* Client Operating System Version: ### Android 9(H2OS 9.0.1)
* Client Operation System Language:Go

### Expected Behavior
安卓能正常访问网站及各种APP
### Current Behavior
国外网页无法打开(连接超时).只能打开Telegram,其余国外软件均无法使用,同时国内app正常
### Steps to Reproduce

1.打开Brook,输入服务器IP和密码
2.开启服务
3.国外网页访问失败

### Possible Solution
推测与防火墙无关,是软件的锅

**Comment by txthinking** [comment]
This is not about brook.

The reason is:
Your 4G network < --- tcp unreachable or udp unreachable ---> Your server.

**Comment by txthinking** [comment]
Please use English. Thank you.

**Comment by Aries000004** [comment]
@768927433 您好.问题解决了吗?我的手机为1加5t,情况一样

**Comment by Gxz-NGU** [comment]
> This is not about brook.
> 
> The reason is:
> Your 4G network < --- tcp unreachable or udp unreachable ---> Your server.

Indeed, not happy! F**k CMCC 4G network. Are there any ways to sovle this problem? Need Help..T_T
