### ISSUE TITLE
Something error when i choose to systemctl enable brook.service

### ISSUE THREAD

**Issue by DemoMacro** [txthinking/brook#511]
### Environment

* Brook Version:
* Server Operating System: debian
* Server Operating System Version: Debian 8 64 bit
* Server Operation System Language: en-US
* Client Operating System: deepin
* Client Operating System Version: Deepin 15.9
* Client Operation System Language: zh-cn

### Steps to Reproduce
When I type `systemctl enable brook` ,it shows as
```
brook.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable brook
insserv: warning: script 'K01brook' missing LSB tags and overrides
insserv: warning: script 'brook' missing LSB tags and overrides
insserv: warning: current start runlevel(s) (2 3 4 5 S) of script `brook' overrides LSB defaults (2 3 4 5).
insserv: fopen(.depend.stop): Permission denied
update-rc.d: error: brook Default-Start contains no runlevels, aborting.
```
and I can't let brook boot.

**Comment by marvinroger** [comment]
Just move your systemd file https://serverfault.com/a/849508

**Comment by txthinking** [comment]
Brook expects to provide the most basic and simplest way to use it.
For your case, please learn systemd, https://en.wikipedia.org/wiki/Systemd, it is not difficult too.

**Comment by DemoMacro** [comment]
Thank you for your help
