### ISSUE TITLE
Android 9 brook can only access domestic websites, WIFI and 4G are the same, TCP and UDP ports are tested open with netcat.

### ISSUE THREAD

**Issue by 768927433** [txthinking/brook#512]
### Prerequisites
* [Y ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [Y ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ Y] Are you running the latest version?
* [ Y] I will write this according to this template.
* [Y ] I will write this in English.

### Environment
* Brook Version: v20190205
* Server Operating System: Debian
* Server Operating System Version: Debian 8 x86_64
* Server Operation System Language: Go
* Client Operating System: Android
* Client Operating System Version: ### Android 9(H2OS 9.0.1)
* Client Operation System Language:Go

### Expected Behavior
安卓能正常访问网站及各种APP

### Current Behavior
国外网页无法打开(连接超时).只能打开Telegram,其余国外软件均无法使用,同时国内app正常

### Steps to Reproduce
1.打开Brook,输入服务器IP和密码
2.开启服务
3.国外网页访问失败

### Possible Solution
推测与防火墙无关,是软件的锅
**### TCP,UDP端口测试正常**

**Comment by Ezhhes** [comment]
1. 不是英语开发者不会回复的

2.1. 试试开启Brook后杀死需要FQ的进程再重新启动
2.2. 重新安装最新版本

**Comment by echokk11** [comment]
小米8 android9 同样情形

**Comment by mistlost** [comment]
Xperia XZ Premium, with Android 9.0 system, also has this problem. Websites in China mainland can be  accessed directly, but some others that must go through the agency cannot be connected. Everything is OK on the server and PC clients.

**Comment by leeassamite** [comment]
me too

**Comment by FZelin** [comment]
很明显是安全权限的问题，之前我们开发android9设备游戏也是这个问题。

**Comment by femaimi9527** [comment]
如果使用的的是中国移动的4G网络 那就是中国移动的锅

**Comment by txthinking** [comment]
This is usually caused by your phone/ROM if your server works well.

**Comment by Gxz-NGU** [comment]
@femaimi9527 有没有什么可以让移动4G有解么？联通宽带还是挺快挺稳定的，自从2月份之后吧，移动的流量基本上不去了。能上去也就几秒钟就不能上了。但是服务器ip没被封。也不知道移动到底做了啥，好像还挺厉害的样子。

**Comment by txthinking** [comment]
### How to test if your server is blocked in your client network

> If your want to test cellular network, create hotspot on your mobile then let your computer connect to it.

```
$ brook tunnel -l 127.0.0.1:1080 -t 8.8.8.8:53 -s your_server_address -p password

## Test UDP
$ dig google.com @127.0.0.1 -p 1080

# Test TCP
$ dig +tcp google.com @127.0.0.1 -p 1080
```

**Comment by kevinzu007** [comment]
pc ok，手机不行，等待解决  ， xiaomi 8

**Comment by kevinzu007** [comment]
$ brook tunnel -l 127.0.0.1:1080 -t 8.8.8.8:53 -s your_server_address -p password

## Test UDP
$ dig google.com @127.0.0.1 -p 1080

这个测试通过了，手机端就可以了
把服务器端的udp端口打开就好了

**Comment by txthinking** [comment]
like @kevinzu007 said
