### ISSUE TITLE
Version inmformations don't match.

### ISSUE THREAD

**Issue by predawnang** [txthinking/brook#513]
### Prerequisites

* [Y ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [ Y] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ Y] Are you running the latest version?
* [ Y] I will write this according to this template.
* [ Y] I will write this in English.

### Environment

* Brook Version: Latest
* Server Operating System: CentOS
* Server Operating System Version: 7
* Server Operation System Language:
* Client Operating System: MacOS
* Client Operating System Version: 10.14.1
* Client Operation System Language:

### Steps to Reproduce

1.
2.
3.

### Detailed Description
I updated brook to latest version yesterday, then I found that the version infromation on statu bar is v20190205, but the one on GUI still v20181212. I also reinstalled it, but still the same. Why is that
<img width="119" alt="screen shot 2019-02-17 at 5 03 47 am" src="https://user-images.githubusercontent.com/37857978/52905279-ec157300-3272-11e9-82ac-58ff0d6f8fd3.png">
<img width="690" alt="screen shot 2019-02-17 at 5 04 14 am" src="https://user-images.githubusercontent.com/37857978/52905280-f172bd80-3272-11e9-910d-e5ccf621bf3c.png">

**Comment by txthinking** [comment]
Yes, a bug. I forgot  change the v20181212 to v20190205 on the page.

**Comment by predawnang** [comment]
okay :D

**Comment by txthinking** [comment]
Please try https://github.com/txthinking/brook/issues/536
