### ISSUE TITLE
Brook MacOS Client Can Not Work With USB Wireless Card

### ISSUE THREAD

**Issue by sanelakes** [txthinking/brook#514]
### Environment

* Brook Version: 20181212 & 20190205
* Server Operating System: CentOS
* Server Operating System Version: 6.8
* Server Operation System Language: English
* Client Operating System: MacOS
* Client Operating System Version: 10.12.6
* Client Operation System Language: English

### Current Behavior

Click either 'Start' or 'Quit' causes an error on MacOS 

### Detailed Description

The Brook GUI Client couldn't start and quit when I using USB Wireless Card to access wifi.

xxx is not a recognized network service.
** Error: The parameters were not valid...

![screen shot 2019-02-17 at 6 40 37 pm](https://user-images.githubusercontent.com/46300669/52912170-b7440300-32e8-11e9-8611-ded9627e178f.png)

**Comment by txthinking** [comment]
Try v20200101 and let me know if it still not working
