### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by duanluan** [txthinking/brook#515]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

|Name|Detail|
| ------ | ------ |
|Brook Version|**v20181212、v20190205**|
|Client Operating System And Version|**Windows 10 Pro 1803 (Chinese)**|

### Current Behavior

Pop-up error box.

### Detailed Description

Unable to upload files. Text description is as follows: 

The title is "**A JavaScript error occurred in the main process**", The description is:
```
Uncaught Exception: 
Error: read ECONNRESET
    at exports._errnoException (util.js:1024:11)
    at TCP.onread (net.js:610:25)
```

### Possible Solution

It seems that after I installed some software, it suddenly didn't work well. Maybe there was something wrong with the running environment?

It should be about Electron, but I don't know much about it.

`The above is from Baidu Translation.`

**Comment by femaimi9527** [comment]
![image](https://user-images.githubusercontent.com/42115908/53385172-7ae36780-39b8-11e9-9410-a27b7065fcea.png)
A JavaScript error occurred in the main process
### Environment
Name	Detail
Brook Version	**v20181212、v20190205**
Client Operating System And Version	**Windows 7 sp1 X64 (Chinese)**
![image](https://user-images.githubusercontent.com/42115908/53385242-b847f500-39b8-11e9-888e-e49f58113019.png)

**Comment by femaimi9527** [comment]
我电脑重启后又正常使用了，
now i can use it without any problem after i reboot my laptob. thank u !

**Comment by duanluan** [comment]
I updated the system to v1809, and I fantasized that it would suddenly run.
However, no.

**Comment by duanluan** [comment]
I tried to close all the ports used by desktop clients, but it didn't work.

**Comment by txthinking** [comment]
Please try https://github.com/txthinking/brook/issues/536
