### ISSUE TITLE
能否只代理 ipv4 流量

### ISSUE THREAD

**Issue by tylermathliu** [txthinking/brook#517]
网络环境是国内的教育网，但我的服务器只支持 ipv4，每次访问纯 ipv6 网站都要先关闭代理非常麻烦，能否添加只代理 ipv4 流量的功能

**Comment by johnnychen94** [comment]
Try [switchomega](https://github.com/FelisCatus/SwitchyOmega)

**Comment by txthinking** [comment]
As @johnnychen94 said.
