### ISSUE TITLE
20190205 android client, blacklist not working

### ISSUE THREAD

**Issue by HappyCtest** [txthinking/brook#518]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version: v20190205
* Server Operating System: Cent OS
* Server Operating System Version: Cent OS 6
* Server Operation System Language: English
* Client Operating System: Android
* Client Operating System Version: Android 9.0 MIUI 9.2
* Client Operation System Language: Chinese Simplified

### Expected Behavior
Switched to Blacklist Mode on Android Client. I should've been able to visit the limited websites.
### Current Behavior
The Balcklist Mode is not working for me.
### Steps to Reproduce

1. Brook Android client, switch to Blacklist Mode, Connect the server.
2. Visit Google.com in browser.
3. Connection failed. Googlee Chrome says: ERR_NETWORK_CHANGED.

### Detailed Description
With Blacklist Mode on, VPN is on. I can visit the China domestic websites like Baidu, but can't visit the blocked websites like Google, Facebook, Twitter, etc. But I noticed that I could visit tensorflow.org (blocked in China) with Blacklist Mode, which means the Blacklist Mode is working, but with problem. The Global Mode and the Whitelist Mode work fine with me, which means it's not about my server but the client.
### Possible Solution
Maybe it's a bug of the Android client?

**Comment by 768927433** [comment]
How can you switch Blacklist Mode,White Mode and the Global mode?

**Comment by HappyCtest** [comment]
Click the version part in the app drawer, you'll find it.

**Comment by 768927433** [comment]
I can't work.
I can only open the global mode.
But I can only access domestic website.

**Comment by txthinking** [comment]
It looks like the blacklist https://github.com/txthinking/pac need to improve.

**Comment by HappyCtest** [comment]
Yes, I think so. But how to update whitelist, blacklist for Android client?

**Comment by HappyCtest** [comment]
and recently, under blacklist mode and whitelist, google play app is not accessible. only under global mode it works.

**Comment by HappyCtest** [comment]
I reset my phone and updated to 20190401 version, and the problem remains.

**Comment by txthinking** [comment]
If you choose Black Mode[0],
Only domains in black list[1] will be resolved by 8.8.8.8 DNS server, and If the result IP is in the black_cidr list[2], then connect it through remote server.

But, the black_list[1] and black_cidr list[2] content is not enough, please send PR together to perfect it

0: https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client
1: cn is in https://github.com/txthinking/blackwhite/blob/master/black.list
2: https://github.com/txthinking/blackwhite/blob/master/black_cidr.list

**Comment by txthinking** [comment]
v20200101 and wiki
