### ISSUE TITLE
Please remove Firebase Analytics

### ISSUE THREAD

**Issue by IzzySoft** [txthinking/brook#520]
A VPN client is a sensitive application, it should not come with trackers. Could you please remove them from the Android app? I mean mainly Firebase and Firebase Analytics, ideally also GMS. I wouldn't want my VPN (connection) data to be recorded on "foreign servers" – especially not on Google's. So me and other privacy proponents wouldn't trust a VPN app that comes with such trackers.

Thanks for considering!

**Comment by IzzySoft** [comment]
@txthinking Does that mean "wontfix" – or "isfixed"?

**Comment by txthinking** [comment]
I think the data is anonymous, and I can see the installation rate of different versions and the crash of different machines to help make better decisions.

**Comment by IzzySoft** [comment]
I see. But that's just the details displayed to you in the console. The library is proprietary, so you cannot tell for sure what is collected. And so-called "anonymous" data often can be deanonymized – especially if the company collecting it has that many other reference points as Google has.
