### ISSUE TITLE
Windows client no work.(v20190205)

### ISSUE THREAD

**Issue by PFei-He** [txthinking/brook#521]
### Prerequisites

* [ ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [ ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ ] Are you running the latest version?
* [ ] I will write this according to this template.
* [ ] I will write this in English.

### Environment

* Brook Version: 20190205
* Server Operating System: CentOS
* Server Operating System Version: 9
* Server Operation System Language:
* Client Operating System: Windows
* Client Operating System Version: 7
* Client Operation System Language:

### Steps to Reproduce

1.
2.
3.

### Detailed Description
I updated brook to latest version yesterday, then I found that the version infromation on statu bar is v20190205, but the one on GUI still v20181212. I also reinstalled it, but still the same. Why is that?
![2b3isykur0sgjztt j5l1d](https://user-images.githubusercontent.com/5790425/53617561-a2d60380-3c22-11e9-84a8-7c62a6f2c065.png)

Also, it's no work this version, but I used v20181212 is worked now!

**Comment by txthinking** [comment]
Please try https://github.com/txthinking/brook/issues/536
