### ISSUE TITLE
connect: network is unreachable

### ISSUE THREAD

**Issue by hxse** [txthinking/brook#523]
### Prerequisites

* [yes] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [yes] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [yes] Are you running the latest version?
* [yes] I will write this according to this template.
* [yes] I will write this in English.

### Environment

* Brook Version: brook-20190205-1
* Server Operating System:Ubuntu
* Server Operating System Version:4.15.0-36
* Server Operation System Language:english
* Client Operating System:manjaro
* Client Operating System Version:4.19.24-1
* Client Operation System Language:chinese

### Expected Behavior
connection is successful
### Current Behavior
connect: network is unreachable
### Steps to Reproduce

1. brook server -l :9999 -p password
2. brook client -l 127.0.0.1:8080 -i 127.0.0.1 -s server_address:port -p password --http
3. brook client -l 127.0.0.1:1080 -i 127.0.0.1 -s server_address:port -p password

### Detailed Description
socks5 proxy is connection successful ,working normally
http(s) proxy is not connection successful, in Server, that Report error, example as follows:
2019/03/02 15:30:51 dial tcp [2001:b28:f23f:f005::a]:80: connect: network is unreachable

### Possible Solution
I can't figure it out.

**Comment by txthinking** [comment]
Looks like you want to access a IPv6 address from, but your server can't connect it

**Comment by txthinking** [comment]
I guess when your app(I don't know how you use the http proxy and in what environment) connect to xxx.com, your app resolves the IP of xxx.com in your local network(your local network support IPv6), and got the IP is v6, then sent to the http proxy, http proxy send to your server to connect it(but your server doesn't support IPv6).

**Comment by txthinking** [comment]
v20200101
