### ISSUE TITLE
brook CLI client in Mac OS 10.13 doesn‘t work

### ISSUE THREAD

**Issue by Zefiend** [txthinking/brook#525]
### Prerequisites

* [yes] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [yes] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [yes] Are you running the latest version?
* [yes] I will write this according to this template.
* [yes] I will write this in English.

### Environment

* Brook Version:20190205
* Server Operating System:Cent OS 
* Server Operating System Version:7
* Server Operation System Language:EN
* Client Operating System:Mac OS
* Client Operating System Version:10.13
* Client Operation System Language:CN

### Expected Behavior
I can access websites like Google after running in Terminal 
### Current Behavior
can't access the websites, "dial tcp [hostip: port]: i/o timeout" popping up in terminal
### Detailed Description
As the lastest GUI in Mac can't be used in 10.13 I wanted to have a try in CLI client and it just didn't work. Then I renewed the pac list and check system firewall which didn't work either.
![2](https://user-images.githubusercontent.com/38494658/53691953-c8017800-3dc2-11e9-8f1b-6c1a53212aff.jpeg)

**Comment by chriskanww** [comment]
My Mac is 10.14.3 and the client can't open.

**Comment by johnnychen94** [comment]
`brook client -l 127.0.0.1:1080 -i 127.0.0.1 -s myserver:8989 -p mypass` 

this works for my MacOS `10.13.6`

Can you have a double check:

1. if there's any extra settings in your `System Preferences->Network->Advanced..->Proxies`
2. if you have installed and enabled some proxy extensions in your browsers, e.g., SwitchyOmega

**Comment by Zefiend** [comment]
> `brook client -l 127.0.0.1:1080 -i 127.0.0.1 -s myserver:8989 -p mypass`
> 
> this works for my MacOS `10.13.6`
> 
> Can you have a double check:
> 
> 1. if there's any extra settings in your `System Preferences->Network->Advanced..->Proxies`
> 2. if you have installed and enabled some proxy extensions in your browsers, e.g., SwitchyOmega
checked. No proxy setting, no SwitchOmega
still not work for me.

**Comment by txthinking** [comment]
https://blackwhite.txthinking.com/http_white.pac works with fixed proxy:
http://127.0.0.1:8080

**Comment by Zefiend** [comment]
Thank you. It finally works. But I still have to turn on and off my sock5 proxy setting in my System Preferences->Network->Advanced..->Proxies every time.
