### ISSUE TITLE
CPU usage is too high though network is idle

### ISSUE THREAD

**Issue by julee** [txthinking/brook#526]
Brook version v20190205 ,
Android 8.0,
Samsung s8.

Though none any app is using network, start up brook, brook cpu usage is almost cost 100% CPU.

Below is output monitor by top with adb:
![image](https://user-images.githubusercontent.com/1493342/53693772-cdb98680-3ddf-11e9-9ac5-f017bce3f68a.png)

**Comment by txthinking** [comment]
v20200101
