### ISSUE TITLE
MacOS GUI client backward compatibility to High Sierra

### ISSUE THREAD

**Issue by johnnychen94** [txthinking/brook#528]
I really want to try new features of Brook https://github.com/txthinking/brook/issues/355 , but the latest Brook version supporting MacOS `10.13` High Sierra is `v20180707`

I can't upgrade my MacOS Version because 

* It's a Macintosh I use
* there's a bunch of customization settings; it's highly possible that things would break up if I did so.
* there's no game-changing performance improvement of Mojave over High Sierra, I don't want to take the risk.

@txthinking So I'm asking if you can provide a release compatible with High Sierra, or could you provide a compile manual so that I can compile it myself? 

Best wishes

**Comment by zzzdtz** [comment]
I have the same problem.

**Comment by kilvn** [comment]
I have the same problem.

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/issues/536
