### ISSUE TITLE
macOS Majove crash

### ISSUE THREAD

**Issue by shequ123** [txthinking/brook#529]
### Prerequisites

* [√] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [√ ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [√ ] Are you running the latest version?
* [√ ] I will write this according to this template.
* [ √] I will write this in English.

### Environment

* Brook Version: latest version mac(gui)
* Server Operating System:no
* Server Operating System Version:no
* Server Operation System Language:no
* Client Operating System:macOS Majove
* Client Operating System Version:10.14.3 (18D109)
* Client Operation System Language:Chinese

### Expected Behavior
run normal
### Current Behavior
crash when open(GUI)

### Steps to Reproduce

open application will flash once and then crash,like happen nothing

### Detailed Description
don;t k

**Comment by ken0403** [comment]
I had the same problem. MacOS Mojave 10.14.3. Is there a solution?

**Comment by txthinking** [comment]
I can't reproduce on macOS 10.14.3.
Did you check the wiki?

**Comment by ken0403** [comment]
This is a misunderstanding! When my Mac is set to a dark theme, I can't see the black key icon in the status bar. When the icon in the dock bar disappeared a few times, I thought brook had collapsed. Now I change back to the light theme, I saw the key at the top, everything is normal, I hope to help people who have the same problem, thank you.
This is English from Google Translate.
