### ISSUE TITLE
Compile Openwrt Version

### ISSUE THREAD

**Issue by buutuud** [txthinking/brook#53]
#### Describe actual behavior
I want to use this in openwrt,How to do it???

**Comment by txthinking** [comment]
Openwrt is also linux, so you can download and run as general linux.

Try:
1. Download brook base your linux arch, https://github.com/txthinking/brook#download
1. $ chmod+x brook
1. Run, https://github.com/txthinking/brook#client-cli
1. Run as daemon, https://github.com/txthinking/brook#run-as-daemon

**Comment by vsxen** [comment]
OpenWrt不只有x86  ARM还有MIPS等
比如
https://wiki.openwrt.org/toh/asus/rt-n66u

**Comment by txthinking** [comment]
Thank you. I will build MIPS version when I am free.

**Comment by vsxen** [comment]
Thank you for your work  👍 
you can also build by youself  @buutuud 
https://conoroneill.net/three-ways-to-build-go-14-binaries-for-mips32-onion-omega-golang/

**Comment by txthinking** [comment]
Thanks for your help and time. @vsxen
