### ISSUE TITLE
Do we have a config file like .brookrc ?

### ISSUE THREAD

**Issue by johnnychen94** [txthinking/brook#531]
I came up with this question because the CLI help is not quite accurate IMO. 

For example, the usage says `brook vpn` works without any options, but indeed, we need to `brook vpn -l 127.0.0.1:1080 -s server_address:port -p password` -- Those aren't _optional_ arguments at all

One possible explanation for this is that we have a `$HOME/.brookrc` file

If there is, then what's the format of the config file? I searched the wiki but found nothing related.

```
NAME:
   brook vpn - Run as VPN mode on client-site

USAGE:
   brook vpn [command options] [arguments...]

OPTIONS:
   --listen value, -l value    Client listen address, must use 127.0.0.1, like: 127.0.0.1:1080
   --server value, -s value    Server address, like: 1.2.3.4:1080
   --password value, -p value  Server password
   --tcpTimeout value          connection tcp keepalive timeout (s) (default: 60)
   --tcpDeadline value         connection deadline time (s) (default: 0)
   --udpDeadline value         connection deadline time (s) (default: 60)
   --udpSessionTime value      udp session time (s), in most cases need this (default: 60)
   --tunDevice value           tun name (default: "tun0")
   --tunIP value               tun IP (default: "10.9.9.2")
   --tunGateway value          tun gateway (default: "10.9.9.1")
   --tunMask value             tun mask (default: "255.255.255.0")
```

**Comment by txthinking** [comment]
There is no config file, I think it is simple to write a bash script

**Comment by johnnychen94** [comment]
This is exactly what I did.  Just curious about the existence of `.brookrc`.

Thanks for replying.

**Comment by PRNDA** [comment]
抱歉重新打开一下，很需要这个功能，因为直接在命令行运行的话，能登录服务器的人都能直接`ps aux`看到命令行上的密码等参数，在多人使用的环境里有安全问题。

**Comment by txthinking** [comment]
v20240404
