### ISSUE TITLE
Where is the proxy mode switch (Global/White list/Black list)?

### ISSUE THREAD

**Issue by zky999** [txthinking/brook#532]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version: v20190205
* Server Operating System: CentOS
* Server Operating System Version: 7.4
* Server Operation System Language: English
* Client Operating System: iOS
* Client Operating System Version: 12.2
* Client Operation System Language: English

### Expected Behavior
There should be a proxy mode switch on the GUI as the old versions do, which specifies how Brook handling the network traffic based on the requested host name.

### Current Behavior
But there is none.

**Comment by 768927433** [comment]
touch the vision 16 times

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client
