### ISSUE TITLE
你好，能否基于这个，提供一套client的基本接口，外壳能够自己封装...

### ISSUE THREAD

**Issue by joviqiao** [txthinking/brook#534]
你好，能否基于这个，提供一套client的基本接口，外壳能够自己封装...
如果付费的话也可以的。。

### Prerequisites

* [ ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [ ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ ] Are you running the latest version?
* [ ] I will write this according to this template.
* [ ] I will write this in English.

### Environment

* Brook Version: a
* Server Operating System: a
* Server Operating System Version: a
* Server Operation System Language: a
* Client Operating System: a
* Client Operating System Version: a
* Client Operation System Language: a

**Comment by txthinking** [comment]
Please use English.
