### ISSUE TITLE
Client (CLI) make -i optional

### ISSUE THREAD

**Issue by maxchendt** [txthinking/brook#535]
Run as brook client, start a socks5 proxy socks5://127.0.0.1:1080

```
brook client -l 127.0.0.1:1080 -i 127.0.0.1 -s server_address:port -p password
```

can we omit the `-i 127.0.0.1`?  Since the IP is set in `-l` . Say

```
brook client -l 127.0.0.1:1080  -s server_address:port -p password
```

**Comment by txthinking** [comment]
Yes, I will do this in next version

**Comment by txthinking** [comment]
I rethink this issue, some cloud platforms usually provide external IP, a clear IP address required by socks5 UDP  protocol.
Despite most situations 127.0.0.1 works, but let the user explicitly specify that it is usually better than the default one.

**Comment by maxchendt** [comment]
How about let the `-i` optional? only if I need to bound to an IP different from my listening IP? And in most case, we can omit the `-i` option
