### ISSUE TITLE
Please try the new macOS/Windows GUI client

### ISSUE THREAD

**Issue by txthinking** [txthinking/brook#536]
https://storage.googleapis.com/txthinking-file/_/Brook.dmg

https://storage.googleapis.com/txthinking-file/_/Brook.exe

It is not good enough at the moment, but simple may be better compatible.

**Comment by johnnychen94** [comment]
Still incompatible to High Sierra
```You have macOS 10.13.6. The application requires macOS 10.14 or later.```

**Comment by kkc2309** [comment]
I can't paste address and password  in win 7.

**Comment by THETHINGSLX** [comment]
When I click the close button, the client quits directly and disconnects. Can it be set to hide? Although I still like the client icon in the menu bar. (MacOS10.14.4)

**Comment by txthinking** [comment]
I also like to hide to the tray, but it still needs some work :)

**Comment by duanluan** [comment]
Laugh, what's your mailbox, I'll send you the tools I use for your reference?

**Comment by LoveAlwaysYoung** [comment]
Oh,I think the GUI of 0205 is better.(from macOS 10.14)

**Comment by clearloop** [comment]
Try to nest the config interface in menu bar? it might be lighter.

**Comment by ayufish** [comment]
I double click the brook.exe-v20190401, but nothing happened, no brook appeared in the tray. I have to continue to use v20190205. (win10 1809)

**Comment by joviqiao** [comment]
Yes, v20190401 can not set global model. @txthinking ,it's need work, i want donation you.

**Comment by StephenAnboer** [comment]
Why do you give up the client like version 20190205 ? Just curious..

**Comment by txthinking** [comment]
The old version is not very compatible, I admit that this new version doesn't look too good, don't worry, I am perfecting it, it won't be long.

**Comment by joviqiao** [comment]
waiting, Recommended reference v2ray ...

**Comment by hnlxl** [comment]
Windows client does not have tray and cannot run in the background.

**Comment by txthinking** [comment]
Please try macOS client dev version:
https://storage.googleapis.com/txthinking-file/_/Brook_develop.dmg

**Comment by johnnychen94** [comment]
:( Still incompatible to High Sierra

Luckily, CLI works fine on MacOS

**Comment by benwu7** [comment]
I tried it on windows 10, after start, I still could not browse site like google.com I am in mainland china. My macbook and iphone client work without any problem. Do I need to do anything else?

**Comment by johnnychen94** [comment]
@benwu7 Check your firewall configuration.

**Comment by benwu7** [comment]
> @benwu7 Check your firewall configuration.

I have turned off Windows Defender Firewall. Anything else?

**Comment by johnnychen94** [comment]
🤔 have you tried it on a different browser? For example, Chrome+SwitchyOmega works in my case.

**Comment by benwu7** [comment]
oh, i have not. I used edge. Is there a tutorial for SwitchyOmega?

**Comment by johnnychen94** [comment]
There're many examples/blogs available

add a new `Proxy Profile` with `Name Brook`, `Protocol Socks5`, `server 127.0.0.1`, and `port 1080` (IIRC it's 1080)

**Comment by benwu7** [comment]
> There're many examples/blogs available
> 
> add a new `Proxy Profile` with `Name Brook`, `Protocol Socks5`, `server 127.0.0.1`, and `port 1080` (IIRC it's 1080)

cool. I need to use v20190205 instead with Chrome and SwitchyOmega. v20190401 won't work...

**Comment by txthinking** [comment]
Released

**Comment by txthinking** [comment]
@johnnychen94 
https://www.apple.com/macos/how-to-upgrade/
