### ISSUE TITLE
Connected thru ipv6.

### ISSUE THREAD

**Issue by donaldzou** [txthinking/brook#538]
Hi, I connected through a Canada Mobile Service 'Fido'. Recently they changed to use ipv6. And I found out I can't connect to my server anymore. Is it the server side problem or is me. Thank you!

**Comment by txthinking** [comment]
IPv6-Only?

**Comment by donaldzou** [comment]
I’m not sure, there is a IPV4 address after I looked up on whatismyipaddress.com<http://whatismyipaddress.com>. But I just won’t connect to my brook server. But I think they all routed to ipv6.

Donald Zou


On Apr 3, 2019, at 11:33 PM, Cloud <notifications@github.com<mailto:notifications@github.com>> wrote:

IPv6-Only?

**Comment by txthinking** [comment]
Try v20200101 and https://github.com/txthinking/brook/wiki/IPv6

**Comment by txthinking** [comment]
In v20200101, if you mobile and server both support IPv6, brook will choose IPv6 first.
