### ISSUE TITLE
Block traffic

### ISSUE THREAD

**Issue by WakamizuLee** [txthinking/brook#539]
### Prerequisites

* [ *] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [ *] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ *] Are you running the latest version?
* [ *] I will write this according to this template.
* [ *] I will write this in English.

### Discussion

In recent months, the brook service has been frequently detected by isp, and it is temporarily blocked by isp for about one minute. We can only find and transfer the service on the port in the shortest time. Can you try to optimize it? ? For example, convert to data of type https.
Thank you for your reading.

**Comment by txthinking** [comment]
Don't be sensational, provide reproduced steps
