### ISSUE TITLE
Custom rules

### ISSUE THREAD

**Issue by srcbase** [txthinking/brook#54]
非常完美的工具, 希望手机客户端可以自行修改pac URL.

**Comment by wuweij888** [comment]
没没没耨提顶替get会咯

**Comment by guanmfei** [comment]
同求，加上gfwlist和gfwwhiltlist就好了

**Comment by hybtoy** [comment]
@txthinking 
Would be great we can change rules manually, such is exclude local connections (192.168.0.0/16 and etc.)

**Comment by XGZepto** [comment]
Just download the default rules, edit it, and upload it to somewhere like OneDrive, and replace the link in Brook App using the OneDrive Download Link.

**Comment by txthinking** [comment]
For now, apple said: your app should not let users type a custom http link :(
I should also talk to Apple.

**Comment by txthinking** [comment]
v20200101 and wiki

**Comment by dongyuwei** [comment]
remote online pac was blocked by GFW, android brook v20200101. 
Why this issue closed? There is no way to config a custom pac url.

**Comment by dongyuwei** [comment]
sorry, just found https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client.
