### ISSUE TITLE
AWS Brook does not solve DNS but connection works flawlessly.

### ISSUE THREAD

**Issue by ATheCoder** [txthinking/brook#541]
### Prerequisites

* [X] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [X] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [X] Are you running the latest version?
* [X] I will write this according to this template.
* [X] I will write this in English.

### Environment

* Brook Version: 20190401
* Server Operating System: Ubuntu (AWS)
* Server Operating System Version: 18.04
* Client Operating System: Android

### Expected Behavior
Connecting to the Server with brook, DNS should be solved.
### Current Behavior
Connecting to the Server with brook does not solve DNS names, However The connection does work.
### Steps to Reproduce

1.`./brook server -l :9999 -p password`
2. connect using the latest APK of brook (downloaded from here)
3. Telegram works but web browser does not.

### Detailed Description
 I can use Telegram and Whatsapp for instance but my web browser does not work. (DNS Resolving Error) I have tried using MacOS to connect too, same thing happens.
### Possible Solution
I have no idea

**Comment by txthinking** [comment]
Please make sure this two tests pass:
https://github.com/txthinking/brook/issues/512#issuecomment-478339892
