### ISSUE TITLE
ubuntu 18.10 server How to print log? 

### ISSUE THREAD

**Issue by joviqiao** [txthinking/brook#543]
How to let server in ubuntu print log? 

suggest： Output specific logs when be scanned, record the scanner's IP，use fail2ban ban scanner ip.

### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version:
* Server Operating System:
* Server Operating System Version:
* Server Operation System Language:
* Client Operating System:
* Client Operating System Version:
* Client Operation System Language:

**Comment by txthinking** [comment]
> Output specific logs when be scanned, record the scanner's IP，use fail2ban ban scanner ip.
This sounds useful
