### ISSUE TITLE
How to set custom upstream DNS server on Linux

### ISSUE THREAD

**Issue by ookangzheng** [txthinking/brook#544]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version: Latest april 
* Server Operating System: Linux Debian9 64bit
* Server Operating System Version: Debian9
* Server Operation System Language: English
* Client Operating System: Android
* Client Operating System Version: 9
* Client Operation System Language: English

### Expected Behavior
On client side expected to allow use custom upstream DNS server

### Current Behavior
Route me to Google DNS

### Possible Solution
I hope on server side configuration, I can do something like
`./brook server -l :4500 -p imapassword -dns 9.9.9.9`

**Comment by joviqiao** [comment]
Has the author been invited to tea? lol : )

**Comment by chenhw2** [comment]
set server's DNS server

**Comment by ookangzheng** [comment]
my server /etc/resolv.conf is pointed to cloudflare 1.1.1.1
on client side I saw Google DNS

**Comment by txthinking** [comment]
Android client using 8.8.8.8.
In theory, both client/server can support/redirect other dns.

But is this a very important requirement?

**Comment by ookangzheng** [comment]
Im have my ad-block DNS, and I dont want share my DNS to Google or Cloudflare either.

**Comment by mrbluecoat** [comment]
This would be useful. There are a lot of free DNS services out there to block ads, privacy trackers, adult content, and more.

**Comment by txthinking** [comment]
20210214, feel free to comment if still has problem
