### ISSUE TITLE
Android domestic apps cannot work normally

### ISSUE THREAD

**Issue by Sowon24** [txthinking/brook#549]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ ] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version: v20190205
* Server Operating System: Debian
* Server Operating System Version: Debian 7
* Server Operation System Language: English
* Client Operating System: Android
* Client Operating System Version: Android 9.0 H2OS 9.0.4
* Client Operation System Language: Chinese Simplified

### Expected Behavior
After Launching brook, domestic apps use a direct connection, and the foreign apps and limited websites use a proxy connection. 

### Current Behavior
While brook running, all the apps and websites connect network with a proxy connection. And these are no blacklist or white list settings, it's just running in global mode. 

### Steps to Reproduce

1. Open the brook android client and active it, connect to the sever. 
2. Launch douyu live, 开心消消乐 or other domestic apps. 
3. Some features of the app cannot work, for example, the douyu live can't check in(it shows changing DNS and retry), and the 开心消消乐 cannot connect network. 

### Detailed Description
Running the brook, it's OK to visit google.com in browser or launch some apps like Instagram, but some domestic apps work in a slow network connection or even can't connect to internet.
 
### Possible Solution
Maybe there is a setting to control running mode, and make brook running in blacklist or automatic switching like it works in win chrome?

**Comment by wstlxx** [comment]
Did you check if you can access the port through UDP, in my case the TCP connection is normal and iOS and PC version (non-vpn-mode) still works.
Android and PC VPN mode client won't work.
I checked the port using nmap ,the port is open under TCP but open/filtered under UDP. Not sure if this has sth to do with the problem.

**Comment by Sowon24** [comment]
> Did you check if you can access the port through UDP, in my case the TCP connection is normal and iOS and PC version (non-vpn-mode) still works.
> Android and PC VPN mode client won't work.
> I checked the port using nmap ,the port is open under TCP but open/filtered under UDP. Not sure if this has sth to do with the problem.

I've checked with nmap, the report is the same: UDP connection open/filtered, I have no idea about this.

**Comment by txthinking** [comment]
Try this first
https://github.com/txthinking/brook/issues/512#issuecomment-478339892

**Comment by Sowon24** [comment]
Results after trying the command in #512.
1. I can't run as tunnel mode(No result after executing the command). In my computer, I was using v20180112, it's OK to reach websites that's blocked after connecting to the hotspot created by my smartphone. But v20190401 is not working. 

2.After using brook v20180112 in my computer with connecting to the hotspot. 
The results of dig: 

    ; <<>> DiG 9.14.1 <<>> google.com @127.0.0.1 -p 1080

    ;; global options: +cmd

    ;; connection timed out; no servers could be reached 


    ;; communications error to 127.0.0.1#1080: network unreachable

In #512, he can't reach the foreign websites that is blocked, but in my case, it's OK. Just some domestic apps can't reach the network normally. I don't know what to do now. @txthinking 

Just in case: 
国外应用网页运行正常，但小部分国内应用响应缓慢或者无法正常连接网络。Brook像是进行了全部流量的代理而不是以代理自动配置的方式。

**Comment by txthinking** [comment]
```
# Test UDP
$ dig google.com @127.0.0.1 -p 1080

If it fails, your network is not connected to your server through the udp protocol.
```
```
# Test TCP
$ dig +tcp google.com @127.0.0.1 -p 1080

If it fails, your network is not connected to your server through the tcp protocol.
```

**Comment by wstlxx** [comment]
> 
> 
> ```
> $ brook tunnel -l 127.0.0.1:1080 -t 8.8.8.8:53 -s your_server_address -p password
> ```
> 
> ```
> # Test UDP
> $ dig google.com @127.0.0.1 -p 1080
> 
> If it fails, your network can not connect to your server through the udp protocol.
> ```
> 
> ```
> # Test TCP
> $ dig +tcp google.com @127.0.0.1 -p 1080
> 
> If it fails, your network can not connect to your server through the tcp protocol.
> ```

I checked the tunnel mode and looks fine.
So i redownloaded and restarted everything and the android client is now working. very strange.
But vpn mode on windows still unable to work,
messaged from client is like below :

2019/05/05 16:18:09 dial udp 1.2.3.4:1234: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
2019/05/05 16:18:11 write udp 10.9.9.2:51839->1.2.3.4:1234: wsasend: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2019/05/05 16:18:12 EOF
2019/05/05 16:19:17 dial tcp 1.2.3.4:1234: i/o timeout

And the client consumes CPU a lot.
The SSTAP is already installed on my PC, and CMD is running by admin.
Did I miss something?

**Comment by txthinking** [comment]
If you have another question, please open an new issue.
