### ISSUE TITLE
VPN mode not functional

### ISSUE THREAD

**Issue by wstlxx** [txthinking/brook#551]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version:20190401
* Server Operating System:Debian
* Server Operating System Version:Debian 3.16.7
* Server Operation System Language:System
* Client Operating System:windows
* Client Operating System Version:windows10
* Client Operation System Language:Chinese

### Expected Behavior
VPN mode running correctly
### Current Behavior
VPN mode not functional , with error logs
### Steps to Reproduce

1.SSTAP already installed
2.on debian server , brook server -l :PORT -p PASSWORD
3.on windows PC ,brook vpn -l 127.0.0.1:1080 -s ADDRESS:PORT -p PASSWORD
4.error logs keeps poping out

### Detailed Description
error logs were like below
2019/05/05 16:18:09 dial udp ADDRESS:PORT: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
2019/05/05 16:18:11 write udp 10.9.9.2:51839->ADDRESS:PORT: wsasend: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
2019/05/05 16:18:12 EOF
2019/05/05 16:19:17 dial tcp ADDRESS:PORT: i/o timeout

In th e meantime ,the client consumes CPU and RAM a lot.

### Possible Solution
unknown

**Comment by leo2n** [comment]
same as me.

**Comment by txthinking** [comment]
> 1.SSTAP already installed

Try without SSTAP?

**Comment by txthinking** [comment]
#629
