### ISSUE TITLE
gomobile bind failed

### ISSUE THREAD

**Issue by kenives** [txthinking/brook#552]
error info like this:

XuKelvindeMacBook-Pro:brook Kenives$ gomobile bind -target=ios
gomobile: /usr/local/Cellar/go/1.12.4/bin/gobind -lang=go,objc -outdir=/var/folders/7g/vtzd6tsd0r16sbygx2jffc100000gn/T/gomobile-work-792578728 -tags=ios . failed: exit status 2
functions and methods must return either zero or one values, and optionally an error
functions and methods must return either zero or one values, and optionally an error
functions and methods must return either zero or one values, and optionally an error
functions and methods must return either zero or one values, and optionally an error
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1231f07]

goroutine 1 [running]:
golang.org/x/mobile/bind.(*funcSummary).asMethod(0x0, 0xc002eafe60, 0xd, 0xc001d24ed0)
	/usr/local/Cellar/go/1.12.4/libexec/src/golang.org/x/mobile/bind/genobjc.go:558 +0x37
golang.org/x/mobile/bind.(*ObjcGen).genStructH(0xc002eafe60, 0xc000a30410, 0xc002cf4780)
	/usr/local/Cellar/go/1.12.4/libexec/src/golang.org/x/mobile/bind/genobjc.go:1139 +0xdd3
golang.org/x/mobile/bind.(*ObjcGen).GenH(0xc002eafe60, 0x17, 0x13ab440)
	/usr/local/Cellar/go/1.12.4/libexec/src/golang.org/x/mobile/bind/genobjc.go:187 +0x1736
main.genPkg(0x7ffeefbff990, 0x4, 0xc0003b1400, 0xc0004db700, 0x12, 0x20, 0xc000092010, 0x1, 0x1, 0x0, ...)
	/usr/local/Cellar/go/1.12.4/libexec/src/golang.org/x/mobile/cmd/gobind/gen.go:144 +0x183a
main.run()
	/usr/local/Cellar/go/1.12.4/libexec/src/golang.org/x/mobile/cmd/gobind/main.go:158 +0xa4a
main.main()
	/usr/local/Cellar/go/1.12.4/libexec/src/golang.org/x/mobile/cmd/gobind/main.go:45 +0x78

**Comment by txthinking** [comment]
This is not related to this project, and designed without considering gomobile, please open issue on gomobile project.
