### ISSUE TITLE
Proxy Pool Usage?

### ISSUE THREAD

**Issue by cs16lover** [txthinking/brook#553]
Can brooks be used as a rotating proxy server with different protocol (http, https, socks4, socks5) proxy_ip:proxy_port list?

**Comment by txthinking** [comment]
Can you explain in detail what you want to do?

**Comment by cs16lover** [comment]
> Can you explain in detail what you want to do?

Think about you have a list of proxy information (proxyip:port:user:password:type). 

It exposes a port and everytime I make a request it forwards to a different proxy.

So there will a proxy pool

**Comment by txthinking** [comment]
No random polling strategy now
