### ISSUE TITLE
How to configure proxy for client applications like Dropbox

### ISSUE THREAD

**Issue by aronsoyol** [txthinking/brook#556]
Hi, I'm running brook client(brook.dmg 20190401) on mac, and the browser can open the site like google.com etc. But the apps like DropBox, google sync& backup are not working. How do I configure these Apps with brook? 

![image](https://user-images.githubusercontent.com/2179397/58296701-51937580-7e07-11e9-8a2b-0024a20c35b0.png)

Below is how I run it on my remote server

```brook server -l :9999 -p 123456```

Best regards

**Comment by txthinking** [comment]
The brook macOS GUI client will start a proxy: socks5://127.0.0.1:1080

**Comment by txthinking** [comment]
1. Run `brook server ... ` on your server
2. Run Brook macOS GUI client on your macOS
3. Configure dropbox client with socks5://127.0.0.1:1080

**Comment by aronsoyol** [comment]
Thank you
