### ISSUE TITLE
Brook WebSocket + CDN

### ISSUE THREAD

**Issue by kalhori124** [txthinking/brook#558]
Hi @txthinking 

Thank you so much for your useful application !

I would like to know do have any plan to add WebSocket and HTTP/2 in Brook for transferring data through a third-party gateway ? for example Cloudflare 

With this, we can escape from the government firewall because they cannot block CDN providers.

Brook Client -> Firewall -> CDN ( Cloudflare ) -> VPS runs Brook Server

Hiding VPS IP address behind a CDN

**Comment by Alvin9999** [comment]
目前封锁很厉害，但一些能够套CDN的工具表现都还不错，所以建议开发者考虑一下哦

**Comment by txthinking** [comment]
Coming soon

**Comment by Alvin9999** [comment]
@txthinking nice!

**Comment by hsuzo1** [comment]
及时雨

**Comment by txthinking** [comment]
Released: v20200101

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/wiki/How-to-run-Brook-WebSocket-Server

**Comment by txthinking** [comment]
Note: 

- CLI Client, macOS GUI Client, Windows GUI Client support both `ws://` and`wss://`
- iOS GUI Client, Android GUI client don't support `wss://` yet

**Comment by bannedbook** [comment]
[Brook之TLS+WebSocket+CDN翻墙教程](https://github.com/bannedbook/fanqiang/blob/master/v2ss/Brook%E4%B9%8BTLS%2BWebSocket%2BCDN%E7%BF%BB%E5%A2%99%E6%95%99%E7%A8%8B.md)

**Comment by txthinking** [comment]
done
