### ISSUE TITLE
 How to capture http(s) protocol content using tcp-only

### ISSUE THREAD

**Issue by liuyongqing1** [txthinking/brook#559]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)? yes
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)? yes
* [x] Are you running the latest version? yes
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version: 20190401
* Server Operating System: ubuntu
* Server Operating System Version: ubuntu 18
* Server Operation System Language: englist
* Client Operating System: android
* Client Operating System Version: android 8
* Client Operation System Language: chinese

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/wiki/How-to-capture-https(s)-data-using-TCP-Only-Mode

**Comment by liuyongqing1** [comment]
@txthinking  thanks
