### ISSUE TITLE
Windows client crash

### ISSUE THREAD

**Issue by kexul** [txthinking/brook#560]
### Environment

* Brook Version:latest
* Server Operating System: Ubuntu 
* Server Operating System Version: 16.04
* Server Operation System Language: en_us
* Client Operating System: windows
* Client Operating System Version: 7
* Client Operation System Language: zh_cn

### Expected Behavior
connect and proxy for me .
### Current Behavior
After click start, the client shows 'starting', 'stop' and then crashed.
### Steps to Reproduce

1.download and install the win client of brook
2.fill the sever and password in the client, then click start

**Comment by txthinking** [comment]
Sorry, I didn't find window7, I only have windows10, can you try it on windows10?

**Comment by JulyJohn** [comment]
@txthinking hi, win10 encountered the same problem.

**Comment by txthinking** [comment]
v20200101
