### ISSUE TITLE
how to find the file brook-client.sh?

### ISSUE THREAD

**Issue by Ericliu68** [txthinking/brook#561]
where can i find this file like '.sh' which run on linux client

**Comment by txthinking** [comment]
What is `brook-client.sh`?

**Comment by Dang-h** [comment]
Read the article maybe can help you👉[article](https://www.aioscn.com/internet/brook5.html),
the password is `www.aioscn.com`

**Comment by Dang-h** [comment]
> where can i find this file like '.sh' which run on linux client

Read the article maybe can help you 👉 [article](https://www.aioscn.com/internet/brook5.html)，
If it needs the password , this → `www.aioscn.com`

**Comment by txthinking** [comment]
It looks like the `brook-client.sh` is helper script written by the author of this article, so there is no it here😇
But you can still read the wiki: https://github.com/txthinking/brook/wiki for some helpful things
