### ISSUE TITLE
why i can not use brook-ckient on ubuntu or windows

### ISSUE THREAD

**Issue by Ericliuzi** [txthinking/brook#562]
i have own server,use on phone,brook is working,
but ubuntu18.04 64bit can not work,
windows 10 64bit ，The top right corner of the arrow is in a circle. After a while, the interface is not open.

**Comment by txthinking** [comment]
What does`not work` mean?

**Comment by Ericliuzi** [comment]
i use this command ' brook client -l 127.0.0.1:1080 -i 127.0.0.1 -s server_address:port -p password'
open chrome ,can not use google,

**Comment by txthinking** [comment]
You may need:
https://chrome.google.com/webstore/detail/padekgcemlokbadohgkifijomclgjgif
and
https://github.com/txthinking/blackwhite#pac

**Comment by txthinking** [comment]
What does `windows 10 64bit ，The top right corner of the arrow is in a circle. After a while, the interface is not open.` mean?

**Comment by Ericliuzi** [comment]
sorry,i am a chinese,english is not well,windows 10 64bit,run the exe did not have anything,i check the process，did not have brook or like 'brook'

**Comment by txthinking** [comment]
```
windows 10 64bit,run the exe 
```

Did you run Brook.exe v20190601?

**Comment by Dang-h** [comment]
> sorry,i am a chinese,english is not well,windows 10 64bit,run the exe did not have anything,i check the process，did not have brook or like 'brook'

[你可以下载这个试试看](https://github.com/txthinking/brook/releases/download/v20181212/Brook.exe)；

**Comment by txthinking** [comment]
Why not use the latest version

**Comment by Dang-h** [comment]
> Why not use the latest version

The new version cannot run in the background of my computer. Close the window and close everything.

**Comment by txthinking** [comment]
@Dang-h 
The compatibility of the old version is not very good, but I will try to do it well.
Yes, sorry for the imperfect, If the old version really doesn't work, please endure the shortcomings of the new version.

And an article I found on the site you provided https://doubibackup.com/g4b_0oy6.html

**Comment by Dang-h** [comment]
> @Dang-h
> The compatibility of the old version is not very good, but I will try to do it well.
> Yes, sorry for the imperfect, If the old version really doesn't work, please endure the shortcomings of the new version.
> 
> And an article I found on the site you provided https://doubibackup.com/g4b_0oy6.html

This is a great project and I really like your simple client.
I've read this article, too, and the client is great, but not concise enough😁

**Comment by Ericliuzi** [comment]
thanks ，i find the version which can run on windows,
作者你真好！认真帮助我们，github上遇到的最热心的作者了
