### ISSUE TITLE
Could you write a wiki about how to build brook from source code?

### ISSUE THREAD

**Issue by mzh741** [txthinking/brook#564]
### Prerequisites

* [yes ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [yes ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ yes] Are you running the latest version?
* [yes ] I will write this according to this template.
* [ yes] I will write this in English.

### Environment
Ubuntu 19.04 and Android

* Brook Version:
* Server Operating System:
* Server Operating System Version:
* Server Operation System Language:
* Client Operating System:
* Client Operating System Version:
* Client Operation System Language:

### Detailed Description
I hope to make some changes to this project, but I am new in golang. Using "go get -u" to get all the packages that required, I still can not find the finnal file whitch can run in ubuntu or android after execute the command of "go build" or "go install". Hope you can answer me. Have a good day!

**Comment by mzh741** [comment]
The linux version can build by cli/brook/buildAll.sh, but  I still do not kown if "GOOS=android GOARCH=arm64 go build -o brook_arm64.apk" can build an android version. Thanks a lot!

**Comment by mzh741** [comment]
Hope you can send me a copy of the GUI code, I won't send to anyone else.
base64: bXpoNzQ4MTU5MjYzQDEyNi5jb20=

**Comment by txthinking** [comment]
It can build android cli version. Not GUI version.
