### ISSUE TITLE
invalid server

### ISSUE THREAD

**Issue by alen9788** [txthinking/brook#565]
Hi

We got the "Invalid Server" For the use of widows server 2019 with the version 20181212
The server and the password are the same with the configuration.

**Comment by yousifun** [comment]
I have the same problem

**Comment by txthinking** [comment]
If you use the Brook Link and your link has `default%20`, then remove it.

For example:
change 
`brook://default%20fra1.brookfree.pw%3A7000%20DOUBIPpw34DBAxm`
to
`brook://fra1.brookfree.pw%3A7000%20DOUBIPpw34DBAxm`

**Comment by salamsoliman** [comment]
How to change  brook://default%20fra1.brookfree.pw%3A7000%20DOUBIPpw34DBAxm  to brook://fra1.brookfree.pw%3A7000%20DOUBIPpw34DBAxm

**Comment by txthinking** [comment]
Just remove `default%20`

**Comment by salamsoliman** [comment]
I use iOS and connect the vpn, and It show the vpn icon my top right of iPhone screen, but why cannot I still open youtube and google ?

@txthinking

**Comment by txthinking** [comment]
v20200101 and wiki
