### ISSUE TITLE
iOS 12.3.1 cannot paste

### ISSUE THREAD

**Issue by webcoderkz** [txthinking/brook#567]
iOS 12.3.1 cannot copy/paste password / ip address / username. When i hold the tap, "Paste" tooltip shows up, but pressing on it - does nothing. On a password field - holding the tap doesn't show tooltip to paste.

**Comment by codelast** [comment]
Android P with Brook v20190601 has the similar problem, which is extremely inconvenient when the password is super complex(and it should be [normal] for a password to be complex, right?).
So I don't understand the logic of not allowing the password to be pasted. For security reason?

**Comment by txthinking** [comment]
v20200101
