### ISSUE TITLE
got a problem can't start brook exec:"chcp" :excutable file not found in %PATH%

### ISSUE THREAD

**Issue by bjking2014** [txthinking/brook#568]
as title
I just install a new windows10 operation system,then I download and install brook which version is v20190601.After input ip:port and password, and click button "starting" then i got an  error appearing in the lower right corner.

**Comment by txthinking** [comment]
I am using genuine and latest Windows 10.
After OS installed. I just installed Brook and Chrome, and Brook works well.

Can you try: https://stackoverflow.com/questions/8142058/chcp-is-not-recognized-as-an-internal-or-external-command-operable-program-or

**Comment by bjking2014** [comment]
> I am using genuine and latest Windows 10.
> After OS installed. I just installed Brook and Chrome, and Brook works well.
> 
> Can you try: https://stackoverflow.com/questions/8142058/chcp-is-not-recognized-as-an-internal-or-external-command-operable-program-or


Thanks a lot!
After adding `;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;` in the %PATH% and it works.

**Comment by txthinking** [comment]
v20200101
