### ISSUE TITLE
BBR negative effect on brook?

### ISSUE THREAD

**Issue by cooolper** [txthinking/brook#569]
I observed no improvement of network speed using BBR on my server while using Brook. Anyone faces the same issue? Or it SHOULDN'T install such thing on the server because it conflict with Brook??

**Comment by pcprinciple** [comment]
I am using the lanqingniao’s BBR and it operates well.

**Comment by cooolper** [comment]
> I am using the lanqingniao’s BBR and it operates well.

Why not using the original Google BBR instead? Poor capability?

**Comment by txthinking** [comment]
I vote @cooolper
