### ISSUE TITLE
About whitelist

### ISSUE THREAD

**Issue by jamewhite** [txthinking/brook#57]
您好，我使用的是iOS客户端，发现“晴空”App（PureSky，一款空气质量的App）刷新空气质量数据需要等待很长时间。已测试在关闭Brook时刷新数据快得多，且关闭服务端、启用客户端时无法连接，因此推测“晴空”联网的网址（测试为阿里云IP）并没有包含在白名单内，希望予以添加。

“晴空”联网网址：https://sky.wzpo.net

PS：貌似不少国内新闻网站以及一些App联网网址并没有包含在内。虽然目前白名单包含的网址比较全面，但还是希望可以在内置白名单的基础上增加手动添加网址白名单的功能，毕竟内置列表很难做到完全覆盖。

**Comment by txthinking** [comment]
抱歉，最近忙着赶项目，估计近期不会增加新功能。另外白名单的更新，大家有时间抓了接口可以发PR到pac项目。

**Comment by jamewhite** [comment]
好的。其实自己的需求应该不太重要，开启Brook时那个App刷新一般6~10s左右，也基本可以接受了。

**Comment by txthinking** [comment]
再次抱歉。因为相对大点（主流）的应用，其应该都会对国外线路做优化，即使用经过代理效果也不是很差。除了一些多媒体产品，比如视频，多图等。所以就做成了白名单模式。
