### ISSUE TITLE
Regression: Brook has no version number on macOS

### ISSUE THREAD

**Issue by core-code** [txthinking/brook#570]
download the latest version of 'Brook', and select it in the Finder and you'll see that the 'Version Number' is missing.

Both the CFBundleVersion and the CFBundleShortVersionString entries are missing from the Info.plist file of the current release.

previous versions up to and including version 20180909 did not have this problem

**Comment by core-code** [comment]
<img width="370" alt="Screenshot 2019-06-14 at 17 07 29" src="https://user-images.githubusercontent.com/1261954/59518893-f82edb80-8ec6-11e9-9a9c-2bd866fd1beb.png">

**Comment by core-code** [comment]
both the CFBundleVersion and the CFBundleShortVersion entries are missing in the Info.plist of the latest download

```
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>CFBundleName</key>
		<string>Brook</string>
		<key>CFBundleExecutable</key>
		<string>brook</string>
		<key>CFBundleIconFile</key>
		<string>icon.icns</string>
		<key>CFBundleIdentifier</key>
		<string>com.txthinking.brook</string>
        <key>NSHighResolutionCapable</key>
        <true/>
        <key>LSUIElement</key>
        <false/>
	</dict>
</plist>

```

**Comment by txthinking** [comment]
v20200101

**Comment by core-code** [comment]
please re-open. 

20210214 again contains neither a CFBundleVersion nor a CFBundleShortVersionString

**Comment by core-code** [comment]
same for 20210701

**Comment by txthinking** [comment]
I ignored CFBundleVersion and why you need to know the version on Info.plist.

**Comment by core-code** [comment]
> I ignored CFBundleVersion

thats a bug. if you read Apple's documentation you'll see that each app needs it. 

> you need to know the version on Info.plist.

as you can see in the screenshot, the version numbers of you app don't show up in the Finder. Mac users expect to be able to see all version numbers in the Finder. also, 3rd party updaters won't work without then. also, the system will get confused if the app is installed multiple times.

**Comment by txthinking** [comment]
Thank you. I see.

**Comment by txthinking** [comment]
v20230101

**Comment by core-code** [comment]
yes it is fixed now. thanks!
