### ISSUE TITLE
2019/06/28 16:20:03 cipher: message authentication failed

### ISSUE THREAD

**Issue by salamsoliman** [txthinking/brook#574]
### Environment

* Brook Version: 20190601
* Server Operating System: centos7
* Server Operating System Version: 
* Server Operation System Language:
* Client Operating System:
* Client Operating System Version: macos majave
* Client Operation System Language:

### Current Behavior
I installed brook on my centos7 server and got the address, port,ps,etc.
and downloaded the latest macOS client v20190601, can clicked "start" button. but I cannot browser youtube.com and google

log:

2019/06/28 16:20:03 cipher: message authentication failed

**Comment by txthinking** [comment]
check your password

**Comment by JacobWay** [comment]
I have the same problem, and checked the password. And the server IP can be pinged.

**Comment by txthinking** [comment]
or someone want to detect your server

**Comment by tylerliu1998** [comment]
I always have this same problem after it works for a while. The password is correct. The server system is CentOS 7. The client system is macOS Mojave.

**Comment by tylerliu1998** [comment]
I think you are right. After that seeing that message, the port is blocked from mainland China. If you switch to another port, it will work for a while and the port got blocked again.

**Comment by tylerliu1998** [comment]
I wonder how the detecter worked though.

**Comment by tylerliu1998** [comment]
Does anyone have any solution for this? For example, only enabling access to Brook server from certain IPs and block all other requests.

**Comment by tylerliu1998** [comment]
> I think you are right. After seeing that message, the port is blocked from mainland China. If you switch to another port, it will work for a while and the port got blocked again.
Well, after changing ports several times, my IP address got blocked.

**Comment by JacobWay** [comment]
Port is blocked, then IP is blocked.

**Comment by txthinking** [comment]
`message authentication failed` caused by invalid data received.
- you set wrong password on your client
- someone send invalid data to your port, this is common because there are countless automatic scanning robots in the internet.
