### ISSUE TITLE
Can't connect? Please test your server first.

### ISSUE THREAD

**Issue by txthinking** [txthinking/brook#575]
### How to test whether your server is blocked in your client network

```
Client network <----> Server network
```

**If your want to test cellular network, create hotspot on your mobile then let your computer connect to it**

---

Suppose you have already started the server.

Then in your client network:
```
$ brook tunnel -l 127.0.0.1:1080 -t 8.8.8.8:53 -s your_server_address -p password

# Test UDP
$ dig google.com @127.0.0.1 -p 1080

If it fails, your client network can not connect to your server through the udp protocol.

# Test TCP
$ dig +tcp google.com @127.0.0.1 -p 1080

If it fails, your client network can not connect to your server through the tcp protocol.
```

Make sure the above two tests pass before open `I can't connect to server...` issue.

**Comment by dongyuwei** [comment]
昨天 Android Brook客户端（v20190601, Ubuntu 18.10 服务器端Brook使用同样版本）启动后一直连接不了 Google，今天才发现服务器端Brook挂掉了，Brook客户端也没有错误提示。建议增强Android Brook客户端，在遇到这种情况时给出较准确的错误提示。

感谢作者的出色工作。

**Comment by AmibaWorld** [comment]
已经在两个vps 搭建了，但是都无法链接，无法查看brook status，

**Comment by txthinking** [comment]
@AmibaWorld https://talks.txthinking.com

**Comment by txthinking** [comment]
https://gist.github.com/txthinking/37856843d975b949b18314cbc1fd5e95#gistcomment-3419799

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/discussions/755
