### ISSUE TITLE
Can't connect Line in iOS

### ISSUE THREAD

**Issue by hsly109** [txthinking/brook#576]
### Prerequisites

* [ ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
sure
* [ ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
sure
* [ ] Are you running the latest version?
sure iOS v20190401
* [ ] I will write this according to this template.
got it
* [ ] I will write this in English.
ok

### Environment

* Brook Version: v20190401
* Server Operating System:  Debian
* Server Operating System Version:  Debian Stretch 9.9
* Server Operation System Language: English
* Client Operating System: iOS 
* Client Operating System Version: 12.3.2
* Client Operation System Language: Chinese Taiwan

### Expected Behavior
connect to brook server 
### Current Behavior
after connected to brook server ,can't use Line normally

### Possible Solution
I think the inner rules is not including Line server address full

the line server address list 

// Line
lin.ee
line.me
line.naver.jp
line-apps.com
line-cdn.net
line-scdn.net
nhncorp.jp

**Comment by hsly109** [comment]
I advise the author use this rules

**Comment by txthinking** [comment]
#689
