### ISSUE TITLE
How to use brook client on linux?

### ISSUE THREAD

**Issue by Ericliu68** [txthinking/brook#579]
The server has been set up, the brook client（for windows）  can be accessed normally , but can not be used for linux in two ways.    
# Run as brook client, start a socks5 proxy socks5://127.0.0.1:1080
$ brook client -l 127.0.0.1:1080 -i 127.0.0.1 -s server_address:port -p password
# Run as brook client, start a http(s) proxy http(s)://127.0.0.1:8080
$ brook client -l 127.0.0.1:8080 -i 127.0.0.1 -s server_address:port -p password --http

**Comment by txthinking** [comment]
Google: how to use socks5/http proxy on linux.
