### ISSUE TITLE
在部分电脑上安装1.0.14，程序运行后，没有翻墙效果。安装20190601的版本，可以翻墙，但是IDM6.33下载设置中的代理服务器设置，点击从IE获取，得到的是一个https://blackwhite.txthinking.com/white.pac 远程的网址和文件，但不能支持下载youtube的视频。

### ISSUE THREAD

**Issue by lyricofgod** [txthinking/brook#581]
### Prerequisites

* [ ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [ ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ ] Are you running the latest version?
* [ ] I will write this according to this template.
* [ ] I will write this in English.

### Environment

* Brook Version:
* Server Operating System:
* Server Operating System Version:
* Server Operation System Language:
* Client Operating System:
* Client Operating System Version:
* Client Operation System Language:

### Steps to Reproduce
在部分电脑上安装1.0.14，程序运行后，没有翻墙效果。安装20190601的版本，可以翻墙，但是IDM6.33下载设置中的代理服务器设置，点击从IE获取，得到的是一个https://blackwhite.txthinking.com/white.pac 远程的网址和文件，但不能支持下载youtube的视频。
1.
2.
3.

**Comment by duanluan** [comment]
用 Proxifier 全局代理吧。你没按规范填写 issue。
