### ISSUE TITLE
 Instability in Android Platform

### ISSUE THREAD

**Issue by mygoodsemail** [txthinking/brook#582]
I've been using this tool for a year. Thank you very much for this tool, so I can go to Google to find many answers for my questions. 
I found that this tool has not been as stable as PC and IOS on Android platforms.  My server has opened UDP protocol.  It worked well on Android a few days ago, but today it suddenly no working, and my server hasn't changed anything. The same thing happened when I reboot the server: it works well on PC and IOS, but dose not on Android. 
I used to solve this problem by reinstalling this tool, but I never knew what caused it.  Who else has a better solution? 
Thank you!

**Comment by mygoodsemail** [comment]
### Prerequisites

* [√] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [√] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [√] Are you running the latest version?
* [√] I will write this according to this template.
* [√] I will write this in English.

### Environment

* Brook Version: v20190601
* Server Operating System: CentOS
* Server Operating System Version: CentOS Linux release 7.5.1804 (Core)
* Server Operation System Language: English
* Client Operating System:
* Client Operating System Version: Android 9
* Client Operation System Language: Chinese

Error message screenshot:
Link：https://pan.baidu.com/s/1AuRbNTZHqtHduRQaKJMw5Q 
Code：7n6b

**Comment by bluesmi** [comment]
do you solve it ? i meet the same question like you now

**Comment by pengyichaoll** [comment]
i meet the same question like you now

**Comment by zzcv155** [comment]
anyone has solve this problem yet?

**Comment by SUMWW** [comment]
the problem happened many times,it need to be solved

**Comment by Whtie4622** [comment]
Now it only works for a few minutes every time I turned it on.

**Comment by txthinking** [comment]
Please test first https://github.com/txthinking/brook/issues/575

**Comment by decemberpei** [comment]
+1, android version is very unstable, ios version been much better.
