### ISSUE TITLE
Custom routes for VPN mode

### ISSUE THREAD

**Issue by maddie** [txthinking/brook#588]
### Environment

* Brook Version: 20190601
* Server Operating System: Linux
* Server Operating System Version: Ubuntu 18.04.3
* Server Operation System Language: English
* Client Operating System: macOS
* Client Operating System Version: Mojave 10.14.6
* Client Operation System Language: English

### Expected Behavior
Don't install default routes i.e. `0.0.0.0/1` and `128.0.0.0/1`, and let user specify

### Current Behavior
Installs default routes

### Detailed Description
I'm considering to embed `brook` into one of my projects to use as a VPN solution in place of PPTP/L2TP. `VPN` mode seems to be the best option that I can use, which supports point-to-point connections. But right now, `brook` installs the default route that routes all traffic via `brook` (and on my macOS client, it interferes with `brook`'s own connection to the server).

I'm looking to customize the routes that's going to be installed, or have an option to route only the point-to-point interface traffic via `brook`, i.e. `server<->client` bidirectional tunnel. Is it possible to configure `brook` as such?

### Possible Solution
N/A

**Comment by txthinking** [comment]
#629
