### ISSUE TITLE
How can I avoid dns polluted in Brook app of android

### ISSUE THREAD

**Issue by archerhu77** [txthinking/brook#589]
### Prerequisites

* [ y] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [ y] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ y] Are you running the latest version?
* [ y] I will write this according to this template.
* [ y] I will write this in English.

### Environment

* Brook Version:v20190601
* Server Operating System: centos
* Server Operating System Version: 7
* Server Operation System Language: english
* Client Operating System: Android
* Client Operating System Version: 9
* Client Operation System Language: English

### Detailed Description
I couldn't access internet after I start Brook, and I am sure that because DNS was polluted.

### Possible Solution
Is there any way to enable dns proxy in brook app of android? I think it's useful in my country.

**Comment by yanzhuan051** [comment]
I ran into the same problem because of the limitation of mobile phone and need to change a mobile phone

**Comment by txthinking** [comment]
Please provide reproduce steps of ` I am sure`

**Comment by txthinking** [comment]
And #575
