### ISSUE TITLE
Windows 32bit, which one should I download? I can't find it.

### ISSUE THREAD

**Issue by lily8220** [txthinking/brook#590]
the old version I use just don't work today.

version: 20180122

now I can't find which one to download on the list.

**Comment by ylfzq** [comment]
![image](https://user-images.githubusercontent.com/8508493/65756615-020fde00-e148-11e9-9d40-d1ee68c1e1b3.png)
Please check this page

**Comment by txthinking** [comment]
U can use CLI version or move to 64bit OS
