### ISSUE TITLE
start by osx client, get 'NoSuchMethodError'

### ISSUE THREAD

**Issue by nkuflk** [txthinking/brook#592]
### Prerequisites

![image](https://user-images.githubusercontent.com/1674342/64353665-b5495380-d030-11e9-921b-80a219244f34.png)

i have connected success ever, and everything works correct. But when i stop it, and restart the connection, i got this error.

My enviroment: macOs 10.14.5 and Brook client lastest

**Comment by alex-cham** [comment]
IOS v20190401 has the same problem. 
Server is v20190601. Protocol is brook newer version.

**Comment by txthinking** [comment]
v20200101
