### ISSUE TITLE
 brook_windows_amd64.exe invalid version

### ISSUE THREAD

**Issue by zzddsg** [txthinking/brook#594]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version: v20190601
* Server Operating System: Centos
* Server Operating System Version: 7.6.1810
* Client Operating System: windows
* Client Operating System Version: 10 

### Current Behavior
I set up my server like:
```
./brook servers -l :port passwd
```
Then I used GUI version client on win10 and it worked well.

When I use command line version brook_windows_amd64.exe(my computer is 64-bit):
```
brook client -l 127.0.0.1:local_port -i 127.0.0.1 -s server:server_port -p passwd
```
It showed up `invalid version`.
I check the server and client version , both are `20190601`.
And it never happened before, this  really confuse me.

**Comment by windyzhaowang** [comment]
Wanna reply this problem

**Comment by shiraha777** [comment]
Please checkout your protocol, CLI client use socks5 as default.

`# Run as brook client, start a socks5 proxy socks5://127.0.0.1:1080`
`$ brook client -l 127.0.0.1:1080 -i 127.0.0.1 -s server_address:port -p password`
`# Run as brook client, start a http(s) proxy http(s)://127.0.0.1:8080`
`$ brook client -l 127.0.0.1:8080 -i 127.0.0.1 -s server_address:port -p password --http`

**Comment by AnonymousCyberWarrior** [comment]
Thank you

发自我的 iPhone

**Comment by zzddsg** [comment]
> Please checkout your protocol, CLI client use socks5 as default.
> 
> > `# Run as brook client, start a socks5 proxy socks5://127.0.0.1:1080`
> > `$ brook client -l 127.0.0.1:1080 -i 127.0.0.1 -s server_address:port -p password`
> > `# Run as brook client, start a http(s) proxy http(s)://127.0.0.1:8080`
> > `$ brook client -l 127.0.0.1:8080 -i 127.0.0.1 -s server_address:port -p password --http`

My server and client both use sock5。

**Comment by txthinking** [comment]
`invalid version` means  you didn't use the socks5 proxy correctly in your browser or other app.
If you don't know to how to do this, reference the Brook GUI client do.
