### ISSUE TITLE
透明代理模式下如何PAC分流？

### ISSUE THREAD

**Issue by edmundzhong888** [txthinking/brook#596]
[很感谢作者提供这么好用的工具！今天本人尝试在一台ubuntu上运行“透明模式”，参照：(https://github.com/txthinking/brook/wiki/How-to-run-transparent-proxy-on-Linux%3F) 可以成功FQ，即其他电脑的网关指向该台ubuntu主机的IP地址即可，但测试过并没有分流，也即虽然能正常上网但等于是“全局FQ模式”，请问如何分流？谢谢

**Comment by txthinking** [comment]
$ iptables -t mangle -A PREROUTING -d xxx -j RETURN
https://github.com/txthinking/blackwhite/blob/master/white_cidr.list

**Comment by edmundzhong888** [comment]
按你文档说明建了一个脚本执行以下指令，能正常VPN模式FQ，但按楼主上面的说明我新增一条规则 【带**的这行】后，这个指定的IP地址1.2.3.4就不能正常访问了，不知道是那条规则搞错，请指教！谢谢
-------------------------------------
ip rule add fwmark 1 lookup 100
ip route add local 0.0.0.0/0 dev lo table 100
iptables -t mangle -F
iptables -t mangle -X
iptables -t mangle -A PREROUTING -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A PREROUTING -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A PREROUTING -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A PREROUTING -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A PREROUTING -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A PREROUTING -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A PREROUTING -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A PREROUTING -d 240.0.0.0/4 -j RETURN
**iptables -t mangle -A PREROUTING -d 1.2.3.4 -j RETURN**
iptables -t mangle -A PREROUTING -p tcp -m socket -j MARK --set-mark 1
iptables -t mangle -A PREROUTING -p tcp -j TPROXY --tproxy-mark 0x1/0x1 --on-port 1080
iptables -t mangle -A PREROUTING -p udp -m socket -j MARK --set-mark 1
iptables -t mangle -A PREROUTING -p udp -j TPROXY --tproxy-mark 0x1/0x1 --on-port 1080

**Comment by txthinking** [comment]
`iptables -t mangle -A PREROUTING -d 1.2.3.4 -j RETURN`
It indicates direct connection when accessing 1.2.3.4

**Comment by edmundzhong888** [comment]
多谢你的回复！我也知道这命令是直连的意思，我的意思是例如把test.com的IP地址1.2.3.4 RETURN了，这样我就无法访问test.com了，并不是分流的结果！还望指教
