### ISSUE TITLE
Android Client can't connect to a forwarded server,But Linux client can 

### ISSUE THREAD

**Issue by ihipop** [txthinking/brook#598]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version: v20190601
* Server Operating System: Ubuntu 
* Server Operating System Version: 16.04.2 LTS
* Server Operation System Language: en
* Client Operating System: Android
* Client Operating System Version: Android 9 / MIUI 10.3.4
* Client Operation System Language: zh_CN

### Expected Behavior
Both work

### Current Behavior
Android client not work

### Steps to Reproduce

1. Assume the **PC IP:** `192.168.1.2`,**BROOK SERVER IP**: `1.2.3.4:5555`
1. Use `socat` to forward `1.2.3.4:5555` to `192.168.1.2:5555`
`socat -v TCP4-LISTEN:5555,reuseaddr,fork TCP4:1.2.3.4:5555`
1. Set the **Android client** to connect to `192.168.1.2:5555` ,did not work
1. Set the **Linux client** to connect to `192.168.1.2:5555` ,it  works

**Comment by txthinking** [comment]
This has nothing to do with Brook.
Try google step 2. or try brook relay...

**Comment by ihipop** [comment]
@txthinking but Why brook-linux client works？

Step 2 is just an example，I use another `secure tunnel protocol` to forward brook. `socat` is just an example and test to prove that the problem is not relative with the ` secure tunnel protocol`

**Comment by txthinking** [comment]
Try $brook relay ... to forward(I don't know socat)? Try enable global mode on android GUI client?

**Comment by ihipop** [comment]
1. `socat` is just a port forward Program in user space.It just forward packet .

1. global mode on android also tried.

1. with default mode on brook android ,use direct IP of brook server,it works

1. The reason I don't use `brook relay` is that I want use another secure tunnel protocol to forward brook to local server,I have the reason not to Communication with brook server in brook protocol,This works for `SS` and `brook-linux` ,not for brook-android
