### ISSUE TITLE
Does brook support batch port relay?

### ISSUE THREAD

**Issue by rexx0520** [txthinking/brook#599]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version: 20190601
* Server Operating System: Debian
* Server Operating System Version: 9
* Server Operation System Language: English

### Expected Behavior
`brook relays -l "SOURCE:9000-10000 DEST:9000-10000"`
Should forward 9000-10000 port from SOURCE to DEST.
### Current Behavior
`address tcp/9000-10000: unknown port`

**Comment by txthinking** [comment]
no.

**Comment by ylfzq** [comment]
you can use iptables to relay traffics

**Comment by txthinking** [comment]
Like @ylfzq said, thx.
