### ISSUE TITLE
GFW can recognize the brook protocol TOTALLY!

### ISSUE THREAD

**Issue by lipeng1667** [txthinking/brook#600]
I just created two different VPS in vultr, after ONE success query to google, the IP address of VPS was blocked to ping...

Just ONE single successful connection var VPN, your VPS will be blocked. 

I AM SOOOOOO shocked!!!!!!!!!!!!!!!!!!!!!!!!!!

What should we do?

**Comment by zhixiangjoy** [comment]
really? I just learn brook at a monment.

**Comment by lipeng1667** [comment]
你懂的。。。
> really? I just learn brook at a monment.

**Comment by ps2xu** [comment]
@lipeng1667 Yes, use it long time, I have same feeling too.

**Comment by txthinking** [comment]
NO.
They block the IPs of your favorite VPS on 10.1.
`block` means: Unconditional block or block it without knowing it

**Comment by lipeng1667** [comment]
> NO.
> They block the IPs of your favorite VPS on 10.1.
> `block` means: Unconditional block or block it without knowing it

I don't think so, cause before the brook/ss  service start, or before connections pass the VPN, my IP is safe and available.

**Comment by JacobWay** [comment]
Yes, I am agreed with you @lipeng1667 . How do they block your IP if they do NOT know the IP. They blocked the IP as you used it. @txthinking

**Comment by txthinking** [comment]
You do not know what I mean.
Many **popular VPS providers** have own CIDR, this CIDR i know, you know and everyone know, things are actually complicated, you created two VPS, but the IP maybe already marked before you.
I won't say a lot. You should think hard, this thing is complicated.

**Comment by lipeng1667** [comment]
OK, how could explain this thing, 
I created a new server in the same VPS(vultr) and this time, I deploy my ladder using v2ray. Now, my IP is safe, everything works fine. 

Men, admit the truth. There is nothing to be shy

**Comment by txthinking** [comment]
Believe in yourself, your feelings and words are correct, never doubt :)

**Comment by ijustyce** [comment]
For me, brook work fine in the past. But recently it not. Work sometimes and not work sometimes. When not work, I even can't connect to my server through ssh. Maybe it's time to consider to use cdn + brook.
