### ISSUE TITLE
Windows 10 Edge and IE 11 doesn't support socks5

### ISSUE THREAD

**Issue by ylfzq** [txthinking/brook#601]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Discussion

I'm using the latest version(20190601) both in server and client. 

- My server is ubuntu 16.04 which doesn't matter with this discussion. 
- My clients are cli and GUI in Windows 10.

Usage 1: 
> Use Windows GUI client, fill the correct server settings and click start button.

Usage 2: 
> 1. Use Windows cli client, run the command in cmd.exe: `brook_windows_amd64.exe client -l 127.0.0.1:1080 -i 127.0.0.1 -s <serverIp>:<serverPort> -p <password>`
> 2. Go the proxy setting page, set to:
> ![image](https://user-images.githubusercontent.com/8508493/65679108-1344e600-e087-11e9-9726-cba7db697c10.png)

Result 1:
> Failed to open google.com and facebook.com when using Edge or IE 11.

Result 2:
> Got client's console message saying: Invalid Version

Result 3:
> Succeeded to open google.com when using Firefox with this setting:
> ![image](https://user-images.githubusercontent.com/8508493/65682792-3e7f0380-e08e-11e9-8f7f-fc3938a9b6c6.png)

My use cases are:
Usage 1 => Result 1 & Result 3
Usage 2 => Result 1 & Result 2 & Result 3

So can I draw a conclusion that Edge and IE 11 doesn't support socks5 protocol? I just installed my Windows 10 hours ago.

**Comment by txthinking** [comment]
Yes. Please love to use chrome.
