### ISSUE TITLE
Is it possible to have brook only use tcp connections?

### ISSUE THREAD

**Issue by bobwang3** [txthinking/brook#603]
### Prerequisites

* [ ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [ ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ ] Are you running the latest version?
* [ ] I will write this according to this template.
* [ ] I will write this in English.

### Discussion

Currently GFW has a large amount of UDP traffic for the same port and will be blocked soon. It doesn't matter to reduce the efficiency of use. Stable connections are the most important.

**Comment by txthinking** [comment]
I think you are using some software that transfers data mainly through UDP on your VPS, like kcp? before using brook.

**Comment by txthinking** [comment]
v20190101
