### ISSUE TITLE
How to config brook in a ALiYun Linux computer that can proxy all the stream from my vultr's computer?So I can connect to the ALiYun Computer to visit Google!!!!

### ISSUE THREAD

**Issue by OrdinaryYZH** [txthinking/brook#609]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version: v20190601
* Server Operating System: CentOS
* Server Operating System Version: 7
* Server Operation System Language: English
* Client Operating System: Windows and Linux
* Client Operating System Version:win10 and CentOS7
* Client Operation System Language:Chinese 、English

### Expected Behavior
Let my Windows can visit google through a ALiYun/ALiCloud Linux computer.

### Current Behavior
I don't know how to conf the brook in the ALiYun computer

**Comment by OrdinaryYZH** [comment]
背景：因为我所在的运营商问题，我基本ssh不到vultr的主机（其他地方可以），所以想通过另一台阿里云服务器代理vultr的流量

**Comment by OrdinaryYZH** [comment]
I get the way possibly...
https://github.com/txthinking/brook/wiki/How-to-run-Brook-Relay-Server-on-Linux%3F

**Comment by txthinking** [comment]
Yes. You got it.

**Comment by kevvvinyao** [comment]
> https://github.com/txthinking/brook/wiki/How-to-run-Brook-Relay-Server-on-Linux%3F

This link will be redirected to https://github.com/txthinking/brook 

Where can I visit content about **Brook Relay** now?
I've visited https://txthinking.github.io/brook/, but I didn't get how to create a ws/wss tunnel by brook to relay other types of proxy (shadowsocks).
Maybe there is a new website/page introducing detailed config of ws/wss tunnel relay, but I don't know.
Chinese is my mother tongue, so I'll repeat my question again in Chinese below:

> https://github.com/txthinking/brook/wiki/How-to-run-Brook-Relay-Server-on-Linux%3F

这个链接会直接跳转到brook项目的github主页了

我想了解一下关于brook转发的详细内容。
我已经看了https://txthinking.github.io/brook/的内容，已经实现了最基本的brook relay转发，但是没有理解如何创建ws和wss隧道。我想在落地机用shadowsocks，然后在落地机和中转机之间使用brook构建ws或者wss隧道，来中转shadowsocks的tcp流量。
