### ISSUE TITLE
brook v20190601 server mode does not listen on ipv4

### ISSUE THREAD

**Issue by bannedbook** [txthinking/brook#612]
### Prerequisites

* [y ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [y] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [y] Are you running the latest version?
* [y] I will write this according to this template.
* [y] I will write this in English.

### Environment

* Brook Version: v20190601
* Server Operating System: debian 
* Server Operating System Version:8
* Server Operation System Language: english

### Expected Behavior
listen on ipv4 
### Current Behavior
listen on ipv6 only
### Steps to Reproduce
1. vultr vps, new server,debian 8, not enable ipv6, download v20190601 refer to :https://github.com/txthinking/brook/wiki/How-to-run-Brook-Server-on-Linux%3F 
2. ./brook server -l :9999 -p password
3.netstat -an|grep LISTEN

### Detailed Description
 v20190601, on debian 8
./brook server -l :9999 -p password
will only run at ipv6
### Possible Solution
./brook server -l ipv4-address:45678 -p yourpassword

**Comment by txthinking** [comment]
brook server -l :45678 ... will listen all IP on your host, If you don't
believe, try `telnet IP 45678`
