### ISSUE TITLE
Enable users to fill out GFWList URL on their own 

### ISSUE THREAD

**Issue by iwoow** [txthinking/brook#614]
GFWList URL(Github): https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**Notwithstanding Github is competent for distribution, to hedge outages or connection issues we still recommend using any URL below.**

Official mirror URLs:

Pagure: https://pagure.io/gfwlist/raw/master/f/gfwlist.txt

Repo.or.cz: http://repo.or.cz/gfwlist.git/blob_plain/HEAD:/gfwlist.txt

Bitbucket: https://bitbucket.org/gfwlist/gfwlist/raw/HEAD/gfwlist.txt

Gitlab: https://gitlab.com/gfwlist/gfwlist/raw/master/gfwlist.txt

TuxFamily: https://git.tuxfamily.org/gfwlist/gfwlist.git/plain/gfwlist.txt

Mirrors can alleviate the problem caused by raw file fetch at GitHub which might be a breach of GitHub ToS.

**Comment by txthinking** [comment]
I prefer simple thing, check v20200101 please.
