### ISSUE TITLE
some problem on openwrt about tproxy

### ISSUE THREAD

**Issue by oceanchang** [txthinking/brook#615]
### Prerequisites

* [ok] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [ok] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ok] Are you running the latest version?
* [ok] I will write this according to this template.
* [ok] I will write this in English.

### Environment

* Brook Version: v20190601
* Server Operating System: ubuntu 
* Server Operating System Version: 18.04
* Server Operation System Language: English
* Client Operating System: openwrt
* Client Operating System Version: 3.18.29
* Client Operation System Language: English

### Expected Behavior
1.  proxy udp and dns working is ok
2. how to proxy linux box local stream?
3. how to find brook log? 
### Current Behavior
set rules follow https://github.com/txthinking/brook/wiki/How-to-run-transparent-proxy-on-Linux%3F
the domain name dns cannot be resolved, and direct access the ip web page is ok.  Ping 8.8.8.8 is ok.

**Comment by txthinking** [comment]
#575
