### ISSUE TITLE
20191115 not work in telegram

### ISSUE THREAD

**Issue by daisyjuer** [txthinking/brook#618]
Brook version: v20190401
ios 13.2
Brook is working in others apps but only in telegram
when i tried the Proxy in brook, there are always a notice'SOCKS5, checking'
Please solve this problem

**Comment by txthinking** [comment]
restart your tg

**Comment by daisyjuer** [comment]
hello txthinking, i used the serveur 127.0.0.1 which you provided and it works now. but with the serveur which i owned it always on status connecting.

**Comment by txthinking** [comment]
Try v20200101. Telegram has a bug: always connecting when you set proxy first time. So Restart Telegram Client.
