### ISSUE TITLE
Android can not call vpn configuration 

### ISSUE THREAD

**Issue by yanzhuan051** [txthinking/brook#619]
### Prerequisites

* [ ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [ ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ ] Are you running the latest version?
* [ ] I will write this according to this template.
* [ ] I will write this in English.

### Environment

* Brook Version:v20190601
* Server Operating System:cnteros7
* Server Operating System Version:CentOS Linux release 7.5.1804 (Core)
* Server Operation System Language:english
* Client Operating System:
* Client Operating System Version:Android 7
* Client Operation System Language:chinese

### Expected Behavior
     click submit can open vpn configuration
### Current Behavior
   The Android client has not called the VPN configuration request in the process of opening

**Comment by txthinking** [comment]
Try v20200101. If still not work. Please provide more information about your phone, I will reopen this, maybe someone can help you.
