### ISSUE TITLE
Android 7.x crash

### ISSUE THREAD

**Issue by stevennight** [txthinking/brook#62]
Xiao Mi 5 miui9 Crash:
java.lang.SecurityException: get package uid: Neither user 10225 nor current process has android.permission.INTERACT_ACROSS_USERS.
	at android.os.Parcel.readException(Parcel.java:1683)
	at android.os.Parcel.readException(Parcel.java:1636)
	at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1924)
	at android.net.VpnService$Builder.establish(VpnService.java:769)
	at com.txthinking.brook.vpn.BrookVPNService.run(BrookVPNService.java:125)
	at java.lang.Thread.run(Thread.java:760)

**Comment by txthinking** [comment]
收到，有时间研究下。小米miui9是基于android的几的

**Comment by stevennight** [comment]
@txthinking 貌似是7.0,感谢。

**Comment by txthinking** [comment]
@stevennight Could you try to give permission manually? Here are the steps in My Pixel (8.0) (7.0 similar):

1. Open `Settings` app
1. Tap `Apps & notifications`
1. Tap `App info`
1. Find and tap `Brook`
1. Tap `Permissions`
1. Enable `Camera`, `Phone`, `Storage` permisions
1. Try to restart Brook

**Comment by stevennight** [comment]
I have been tried to give permission for the app like this:

![Screenshot](https://raw.githubusercontent.com/stevennight/hello-world/master/pic/Screenshot_2017-10-24-22-33-21-944_com.miui.secur.png)

but it's still crash..

I can't found the phone permission it seem.

**Comment by txthinking** [comment]
Thank you for your time. This is a bug. Will be fixed in next release.

**Comment by txthinking** [comment]
@stevennight Can you try the v20171111?

**Comment by stevennight** [comment]
Oh... I sorry, because I had already flash the AOSP rom and can not test it.

**Comment by txthinking** [comment]
You are right, just keep away MIUI. :D

**Comment by txthinking** [comment]
If anyone run success on Android 7.x(with google play installed), please comment here, thanks.
If anyone run success on Android 7.x(without google play installed), please comment here, thanks.

**Comment by triaqu** [comment]
我的一加5安卓7.11，运行后点连接显示连接中就没有其他任何提示了。在程序里权限灰色。

**Comment by stevennight** [comment]
@txthinking It seem work well on my AOSP 7.1.2 rom with google play installed by the Brook v20171112(Installed by Google play).

**Comment by Wonderland2017** [comment]
@txthinking The latest version (v20171114) of this app installed via Gooleplay works well on my MIUI9 Phone.
![photo_2017-11-10_06-08-11](https://user-images.githubusercontent.com/33520929/32632292-072bca34-c5de-11e7-97cc-0051f1f789dd.jpg)

**Comment by txthinking** [comment]
Thanks for your help.
Brook Android does not provide other method to stop, **the Disconnect button is provided by your custom OS,** native android OS does not have this button.
Please use Brook Stop Button.

**Comment by txthinking** [comment]
Looks like run success on Android 7.0. If anyone has other problem, please open new issue. Thanks.
