### ISSUE TITLE
Latest Android client have no global mode?

### ISSUE THREAD

**Issue by NaughtDZ** [txthinking/brook#620]
OR where's it!
![Screenshot_2019-11-26-09-39-18-899_com txthinking brook](https://user-images.githubusercontent.com/37768911/69592394-ba66df00-1030-11ea-9a49-56c2687f7f34.jpg)

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client
