### ISSUE TITLE
Request Multi-IP Help

### ISSUE THREAD

**Issue by gaoyuoppa** [txthinking/brook#621]
* Brook Version:v20190601
* Server Operating System:centos 7 x64
* Server Operating System Version:7
* Server Operation System Language:en	
* Client Operating System:win 10
* Client Operating System Version: 1903
* Client Operation System Language:cn

### Expected Behavior
Request Multi-IP Help
Server with multiple IPs, how to specify the server exit IP?
For example: 1.1.1.1 and 2.2.2.2
Accessed through 1.1.1.1, the server exit shows that the IP is 1.1.1.1
Accessed through 2.2.2.2, the server exit shows that the IP is 2.2.2.2

### Current Behavior
Take the main IP as the exit

**Comment by txthinking** [comment]
or maybe iptables?

**Comment by txthinking** [comment]
If your server has two network interfaces 

with external NAT IP

like 192.168.0.2, and 192.168.0.3
try `$ brook serverr -l 192.168.0.2:port ...`

without external NAT IP

like 1.1.1.1, and 2.2.2.2
try `$ brook serverr -l 1.1.1.1:port ...`

**Comment by txthinking** [comment]
Or iptables
