### ISSUE TITLE
How can I use brook to tunnel into another brook server?

### ISSUE THREAD

**Issue by hasanparasteh** [txthinking/brook#623]
I used brook as a single server and it worked quite perfect. But now I want to set-up brook to tunnel through 2 servers.

**Server one** is a normal brook server and maybe I should use `brook server -l :9999 -p password` to run it. The **second server** will connect to the 1st server and simultaneously all of clients connect to the second server to pass through it. but how can I implement such thing?
(I mean VPN tunnel inside other VPN tunnel)

**Comment by txthinking** [comment]
The *second server:*
$ brook relay -l :anyport -r firstserveraddress

**Comment by hasanparasteh** [comment]
Thanks
