### ISSUE TITLE
brook Windows客户端局域网透明代理模式下如何进行pac分流

### ISSUE THREAD

**Issue by wudifrank** [txthinking/brook#625]
Brook真的是个很棒的软件，
我已经用了1年多
从原来的安卓版不稳定
到现在几个月都不用管服务器还是稳定
感谢作者的辛勤付出
你做的软件真的很棒

我有个疑问想请教
我用的Win2008系统
用逗比的brook tools开启了局域网透明代理
但是所有网页都是走的代理
这样打开部分网站会很慢
请问Windows版如何在局域网透明代理模式下
打开pac分流

请不吝指教，谢谢。
再次向您献上我的感谢和感恩。

**Comment by txthinking** [comment]
Please check v20200101 and wiki
