### ISSUE TITLE
After the proxy is enabled on the iOS client, there is no VPN icon and no proxy function.

### ISSUE THREAD

**Issue by liuxu379** [txthinking/brook#627]
* Brook Version:20190401
* Server Operating System:CentOS 7
* Server Operating System Version:
* Server Operation System Language:
* Client Operating System:
* Client Operating System Version:iOS12.4
* Client Operation System Language:

### Current Behavior
After the proxy is enabled on the iOS client, there is no VPN icon and no proxy function.
### Detailed Description
![Snipaste-07641](https://user-images.githubusercontent.com/21291399/70335986-5986a480-1883-11ea-9927-668ad89fc200.png)

**Comment by liuxu379** [comment]
@txthinking

**Comment by txthinking** [comment]
What is your server format behind the mosaic

**Comment by liuxu379** [comment]
> What is your server format behind the mosaic

ip:port

**Comment by txthinking** [comment]
My iOS version is 13.1.2 and it works as expected, can you try upgrade your OS

**Comment by liuxu379** [comment]
> My iOS version is 13.1.2 and it works as expected, can you try upgrade your OS

My iOS version is 12.4 and the device is jailbroken.

**Comment by txthinking** [comment]
Sorry, I have no chance to test it on a jailbroken device

**Comment by liuxu379** [comment]
> Sorry, I have no chance to test it on a jailbroken device

There had been no problems in the previous months, but these two days suddenly appeared.

**Comment by txthinking** [comment]
> > Sorry, I have no chance to test it on a jailbroken device
> 
> There had been no problems in the previous months, but these two days suddenly appeared.

Try to use another server? or change to another WI-FI?

**Comment by liuxu379** [comment]
> Try to use another server? or change to another WI-FI?

I've tried them all, and I still have problems.

**Comment by txthinking** [comment]
Sorry, I can't help your about jailbroken problem :(
