### ISSUE TITLE
$ brook tun feature is experimental, let's discuss it here

### ISSUE THREAD

**Issue by txthinking** [txthinking/brook#629]
https://github.com/txthinking/brook/wiki/How-to-run-tun-on-Linux,-macOS-and-Windows

**Comment by wuzhongjie1997** [comment]
Is it possible to use VPN mode with websockets? currently brook (20200101) doesn't recognise ws:// addresses in vpn mode

**Comment by txthinking** [comment]
$ brook vpn renamed to $ brook tun

**Comment by txthinking** [comment]
https://github.com/txthinking/ipio
