### ISSUE TITLE
Cant run on Win10

### ISSUE THREAD

**Issue by ero2333** [txthinking/brook#63]
Have been try to run as administrator,and the same server configuration runs well on my Android.But somehow can not run on Win10,is there any other issues I should be notice？

**Comment by txthinking** [comment]
Please describe the behavior.
And happened in which step?

Is #60 related?

**Comment by ero2333** [comment]
運行後彈出IE瀏覽器窗口，一秒後IE窗口閃退。程序顯示running，使用Chrome瀏覽器到任何鏈接都load不出來。退出brook後正常流量國內網站。ps.系統已設置自動試用代理。

**Comment by txthinking** [comment]
What does "系統已設置自動試用代理" mean?
Use Brook for windows, you don't and never need configure system proxy
manually.

**Comment by txthinking** [comment]
And don't run other proxy software at same time.

**Comment by txthinking** [comment]
Anyone run on windows 10 success. I only have a windows 7 on virtualBox.

**Comment by Lynchie** [comment]
WIN10成功，brook stream是什么协议，和brook什么区别呀

**Comment by txthinking** [comment]
@Lynchie Thanks for your help. If we want to talk about a new topic, I think we should open a new issue. Keep the issue clean,  only one topic.

**Comment by ero2333** [comment]
problem solved,turned out that I didn't upgrade the server to latest.
