### ISSUE TITLE
v20200101:Problems during MSI version installation

### ISSUE THREAD

**Issue by NaughtDZ** [txthinking/brook#631]
Win10
================
Pop up window during installation:

Could not write value VersionMajor to ke \products\892F7BF29DB7B1E458E989BDB6CC630E\InstallProperties.
Verify thet you have sufficient access to that key, or contact your support personnel

**Comment by txthinking** [comment]
Just tap `ignore`

**Comment by txthinking** [comment]
Because v20200101 just released, maybe other people will also encounter this problem, so keep this open for a while.

**Comment by mrkoalaz** [comment]
ME too .
OS version : windows 10 1909 18363.535 
Language : Chinese
Brook version : 0601
I UNINSTALL old version before setup v20200101 msi .
The msi package show pic 1&2  during installation and I click "ignore" twice time.
![setup1](https://user-images.githubusercontent.com/37821106/71406409-02e6dc00-2673-11ea-82b9-40df695cb701.png)
![setup2](https://user-images.githubusercontent.com/37821106/71406412-037f7280-2673-11ea-89ea-4928b8ffd68c.png)

Then i run brook GUI application , input IP and pwd click "start" , it show me pic 3 like below:

![run](https://user-images.githubusercontent.com/37821106/71406415-09755380-2673-11ea-962b-d938b427f099.png)

**Comment by mrkoalaz** [comment]
ME too .
OS version : windows 10 1909 18363.535
Language : Chinese
Old  version : 0601
I UNINSTALL old version before setup v20200101 msi .
Setup:
First , It show me : 
` Could not write value VersionMajor to Key \Products\892F7BF29DB7B1E458E989BD6CC630E\InstallProperties. Verify that you have sufficient access to that key. or contact your support personnel.`
I taped "ignore".
Second, It show me : 
`Could not write value VersionMajor to key \Software\Microsoft\Windows\CurrentVersion\Uninstall\{2FB7F298-7BD9-4E1B-859E-98DB6BCC36E0}. Verify that you have sufficient access to that key, or contact your support personnel.`
I taped "ignore" again, then setup finish.

Then I run brook GUI application.
After input IP&pwd infomation and click "start", GUI application show me:
`FormatException : Bad UTF-8 encoding 0xb4(at offset 0)`

**Comment by txthinking** [comment]
Could you try global mode and let me know it works or not?  Thx.

> Open drawer and tap version 16 times to open mode page

https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client

**Comment by mrkoalaz** [comment]
global mode it works fine

**Comment by NaughtDZ** [comment]
> 您可以尝试全局模式，让我知道它是否有效吗？谢谢。
> 
> > 打开抽屉并点击版本16次以打开模式页面
> 
> https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client

Here is other issue. Sometimes I can't open the menu in the program, and the program will not respond directly.

**Comment by JsonSong89** [comment]
v20200201 has the same error  as  mrkoalaz
os is win10

**Comment by txthinking** [comment]
v20200502
