### ISSUE TITLE
multiple servers mode, only one server up!

### ISSUE THREAD

**Issue by maxchendt** [txthinking/brook#632]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version:  20200101
* Server Operating System: Ubuntu 18.04 en
* Server Operating System Version: Ubuntu 18.04 en
* Server Operation System Language: Ubuntu 18.04 en
* Client Operating System: Ubuntu 18.04 en
* Client Operating System Version: Ubuntu 18.04 en
* Client Operation System Language: Ubuntu 18.04 en

### Expected Behavior
multiple servers mode, all servers should work

### Current Behavior
multiple servers mode, only one server up

### Steps to Reproduce

1. `/usr/local/bin/brook servers -l ":6489 pwdxx" -l ":4848 pwdyy" `
2.
3.

### Detailed Description
port 6489 is not fired up

```
# lsof -i -P -n | grep brook
brook     1023          nobody    3u  IPv6  23455      0t0  UDP *:4848 
brook     1023          nobody    5u  IPv6  23457      0t0  TCP *:4848 (LISTEN)
```

### Possible Solution
run `brook` for each server?

**Comment by txthinking** [comment]
Looks like a bug :<

**Comment by maxchendt** [comment]
seems not fixed yet.  say, only port "4848" is active

**Comment by txthinking** [comment]
OK, binary update.

**Comment by txthinking** [comment]
v20200502
