### ISSUE TITLE
How to use wsserver on other (except 80 and 443) ports?

### ISSUE THREAD

**Issue by bobwang3** [txthinking/brook#635]
I'm glad that Brook can support WS, which is great. But I already have the nginx service on my server, taking up ports 80 and 443. How do I run brook wsserver on another port?
I don't need to worry about brook renewing the certificate, because brook's ws can share the certificate with my Nginx.

**Comment by txthinking** [comment]
It looks like you can
1. Start brook with `$ brook wsserver -l :anyport -p password`
2. Configure your nginx(your domain in nginx config)  proxy to your brook wsserver port

**Comment by bobwang3** [comment]
> It looks like you can
> 
> 1. Start brook with `$ brook wsserver -l :anyport -p password`
> 2. Configure your nginx(your domain in nginx config)  proxy to your brook wsserver port

Your explanation made me confused.
I tried running "brook wsserver -l: 8080 -p abcabc" on my server without changing the nginx service status, and my Android client can already connect using ws://AnyDomainPointingMyServer:8080, it looks like it has nothing to do with my Nginx. 
I have tried using wss://, the Android client prompts that this is not supported, let me use ws://

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/issues/558#issuecomment-568423885

**Comment by bobwang3** [comment]
I want to know what kind of packets will be used in WS mode without TLS. Is it pure TCP?

**Comment by txthinking** [comment]
> I want to know what kind of packets will be used in WS mode without TLS. Is it pure TCP?

Don't worry, every thing is **encrypted** even if use ws://

**Comment by bobwang3** [comment]
I have two questions to ask.
1.The classic mode of Brook uses TCP and UDP to work together. The firewall is not friendly to UDP, and the reason may be that the port is blocked.  I hope the ws:// mode can solve this problem, which is why I care if it is pure TCP.
2. How does brook starting with "wsserver -l: anyport" use TLS?

**Comment by txthinking** [comment]
> I have two questions to ask.
> 1.The classic mode of Brook uses TCP and UDP to work together. The firewall is not friendly to UDP, and the reason may be that the port is blocked. I hope the ws:// mode can solve this problem, which is why I care if it is pure TCP.

Yes, websocket is a part of  HTTP protocol, HTTP is a TCP protocol. 

> 2. How does brook starting with "wsserver -l: anyport" use TLS?

Assume it is 127.0.0.1:9999, this address is a **standard HTTP Server** and WebSocket path is /ws.
I think you should google: nginx, proxy, websocket

**Comment by bobwang3** [comment]
If a port is enabled in nginx, how can it be used by Brook WS at the same time?

**Comment by txthinking** [comment]
> If a port is enabled in nginx, how can it be used by Brook WS at the same time?

No way, regardless of any software.

Just let your `brook wsclient` connect your `nginx`, and `nginx` proxy to `brook wsserver`  in your case

**Comment by bobwang3** [comment]
> > If a port is enabled in nginx, how can it be used by Brook WS at the same time?
> 
> No way, regardless of any software.
> 
> Just let your `brook wsclient` connect to your `nginx`, and `nginx` proxy to `brook wsserver` in your case

thank! I've done it.
