### ISSUE TITLE
Realize WS tunnel, then transfer traffic

### ISSUE THREAD

**Issue by ThereChave** [txthinking/brook#636]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version:
* Server Operating System:
* Server Operating System Version:
* Server Operation System Language:
* Client Operating System:
* Client Operating System Version:
* Client Operation System Language:

### Detailed Description

Excuse me, can I use brook to build WS tunnel, which means that the traffic can go through one server, then go through the WS tunnel of brook and connect to another server?

**Comment by txthinking** [comment]
I don't quite understand what you mean.I guess you can try:
.. <--->`$ brook tunnel` <---> `$ brook wsserver` <---> ...

**Comment by txthinking** [comment]
I know it, keep in mind the next version
