### ISSUE TITLE
GUI can't worked but CLI is well

### ISSUE THREAD

**Issue by alonewoo** [txthinking/brook#637]
### Prerequisites

* [Y ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [Y ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [Y ] Are you running the latest version?
* [Y ] I will write this according to this template.
* [Y ] I will write this in English.

### Environment
server: Google CLoud: debian-9
Client: winidow 7
            ios 13.1.3

* Brook Version: 20200102
* Server Operating System: 
* Server Operating System Version:
* Server Operation System Language:
* Client Operating System:
* Client Operating System Version:
* Client Operation System Language:

### Expected Behavior
Hope client will connect with server well under CLI or GUI

### Current Behavior
GUI can't worked but CLI is well

### Steps to Reproduce

1. server:  screen -dmS brook ./brook servers -l ":9001 password" -l ":9002 password" -l ":9003 password"
2.  client CLI in window 7:   brook_windows_386 client -l 127.0.0.1:8080 -i 127.0.0.1 -s 35.189.47.117 :9001 -p password --http
     then everything is ok. I can connect www. google.com
3.   GUI(version 20200102) in windows and iOS/iPAD OS: can't connect the server. pls see the attached file from ios.
![webwxgetmsgimg](https://user-images.githubusercontent.com/44246977/71418710-d1880380-26a6-11ea-8f74-7f7eaf61d664.jpg)

**Comment by alonewoo** [comment]
Ps: In the last attached ios screen shot, the server port should be  35.189.47.117 :9001,

**Comment by txthinking** [comment]
The magic is https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client

**Comment by alonewoo** [comment]
that's ok. it is working when mode set to globle. But it is not working when set to white/black list mode. where can I find the setup manual
