### ISSUE TITLE
wsclient provid socks5 or others?

### ISSUE THREAD

**Issue by ThereChave** [txthinking/brook#639]
Does the - L parameter of the browser's wsclient provide a local Socks5 port? Or you can directly forward the traffic to this port
like： brook wsclient **-l 127.0.0.1:1080** -i 127.0.0.1 -s ws://1.2.3.4:5 -p password

i try to use one vps run the brook wsserver ,and other run brook wsclient,i try to use Android to connect wserver ,i's ok,but,use linux cli to connect,and use curl command with socks5,but it can not use

**Comment by txthinking** [comment]
**127.0.0.1:1080** is socks5 proxy.

try `$ curl -x socks5://127.0.0.1:1080 ifconfig.co`

**Comment by littlesker** [comment]
> **127.0.0.1:1080** is socks5 proxy.
> 
> try `$ curl -x socks5://127.0.0.1:1080 ifconfig.co`

You are so kind. Can Brook provide a virtual network card tun like openvpn, which is very convenient to operate, because socks5 is very inconvenient on Linux and udp support is not good

**Comment by txthinking** [comment]
$ brook tun
