### ISSUE TITLE
about multi-network support 

### ISSUE THREAD

**Issue by xLabel** [txthinking/brook#640]
my server has two network card.
does it support bind specifying local outbound ip ?
e.g:
intranet ip -> extranet ip
10.0.0.2     -> A
10.0.0.3     -> B

client A-> 10.0.0.2 -> A-> target internet
clientB->  10.0.0.3 -> B-> target internet

**Comment by txthinking** [comment]
Yes. "it"[1] can listen on all of IPs of your server.

**Comment by txthinking** [comment]
If still need help, detail it and reopen
