### ISSUE TITLE
Can you add "only not China IP " model?

### ISSUE THREAD

**Issue by NaughtDZ** [txthinking/brook#641]
### Prerequisites

* [y] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [y] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [y] Are you running the latest version?
* [y] I will write this according to this template.
* [y] I will write this in English.

### Environment

* Brook Version:202002
* Server Operating System:CentOS7
* Client Operating System:Windows 10
====================================================
I'm not sensitive to the speed of network parsing. I would like to add a function to check whether the linked IP address belongs to the outside of mainland China. If so, go to the proxy. Instead of the current whitelist blacklist mechanism.

**Comment by edmundzhong888** [comment]
我也希望能加入这个功能，如果有LUCI界面最好了！

**Comment by txthinking** [comment]
This is not simple.
For example, If a domain have both China IP and US IP, so what we should do?
In this case, we need a list, like brook already did with
https://github.com/txthinking/blackwhite

**Comment by txthinking** [comment]
The problem is: If we want to route it based IP, we MUST know the IP first.

**Comment by edmundzhong888** [comment]
How can I run or import the list? Dobi's windows client can do that, but I don't know cmd command is? thx


> 在 2020年1月22日，上午10:31，Cloud <notifications@github.com> 写道：
> 
> ﻿The problem is: If we want to route it based IP, we MUST know the IP first.
>

**Comment by takuron** [comment]
Same demand. Or at least keep the option global model on the Android client, I sometimes cannot get the blacklist on the Android client.

**Comment by txthinking** [comment]
@takuron https://github.com/txthinking/brook/wiki/Mode-in-Brook-GUI-client ?

**Comment by takuron** [comment]
I know this model actually exists, but the new Android GUI client (And Windows GUI client) appears to have removed the settings page.

**Comment by txthinking** [comment]
v20200501
