### ISSUE TITLE
provide password via stdin?

### ISSUE THREAD

**Issue by wuzhongjie1997** [txthinking/brook#642]
### Prerequisites

* [1] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [1] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [0] Are you running the latest version?
* [1] I will write this according to this template.
* [1] I will write this in English.

### Discussion

On a multi-user Linux machine, my Brook password is clearly visible when someone else runs a 'top' command. Any user (not just root) can do this. Is it possible to add an option to specify the password on stdin instead of on the command line? After all, file permissions are easier to control :-D
PS: I am using v20190601

**Comment by wuzhongjie1997** [comment]
My point is, exposing both the server IP, port and password to someone else means giving them access to the server network (and certain services on the server e.g. the web GUI of Syncthing or BitTorrent), which I consider as a security problem

**Comment by txthinking** [comment]
Sorry no plan for this.
