### ISSUE TITLE
Learn this project

### ISSUE THREAD

**Issue by gzhsnail** [txthinking/brook#645]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [ ] I will write this according to this template.
* [ ] I will write this in English.

###Environment

    Brook Version:V20200101
    Server Operating System: Centos 7
    Client Operating System: Windows 10

### Discussion
I have a server at home with a lot of virtual machines.I set up the service on one of the virtual machines and mapped the ports to the public network.When I connect with the client, the connection fails, and there are a lot of TCP requests that take up memory.
I use the command line operation, do not know where the problem, I am a beginner, I hope to get guidance.

**Comment by gzhsnail** [comment]
Can you give me a design document for this project? Help me study, I will be very grateful.

**Comment by txthinking** [comment]
Please provide steps let us reproduce your problem, then we may find the
solution.

**Comment by gzhsnail** [comment]
I started the service in the virtual machine and mapped the port to the public network. When I used the VNP client connection, the server was not reachable.
![20200107142336](https://user-images.githubusercontent.com/54012788/71873140-700d6d80-3159-11ea-8b05-b8f6a7f73e8e.png)

**Comment by txthinking** [comment]
Read the readme, wiki, and 
tutorial: https://talks.txthinking.com

(and google translate if need)

If still need help, just provide the steps all you did
