### ISSUE TITLE
When can I support the database？

### ISSUE THREAD

**Issue by free798** [txthinking/brook#646]
I want my website to support Trojan and brook at the same time. I've been focusing on brook for a long time. I only recently learned about Trojan because they support connecting to databases. Do you have any plans to support databases！

**Comment by FenghenHome** [comment]
Yes, I also need to support the database

**Comment by txthinking** [comment]
Sorry. No plan for this.

**Comment by free798** [comment]
OMG, It's too sad～  i love brook ~

Cloud <notifications@github.com> 于2020年1月21日周二 下午7:22写道：
