### ISSUE TITLE
Brook windows GUI can't start on windows server 2012

### ISSUE THREAD

**Issue by freewind** [txthinking/brook#647]
I have a windows server 2012. I tried to install brook windows GUI client, it was successfully installed, but when I start it, nothing happened. No error, no dialog, nothing. I tried with several versions, including the latest one and several others published in 2019, but none works. Need your help

**Comment by gitee-cn** [comment]
我在windows 10上也遇到了这个问题。
1、window_386无法打开
2、window_amd64 无法打开
3、brook.msi  打开安装界面后，下一步直接kill了应用

window 10专业版

**Comment by ou475454353** [comment]
> 我在windows 10上也遇到了这个问题。
> 1、window_386无法打开
> 2、window_amd64 无法打开
> 3、brook.msi 打开安装界面后，下一步直接kill了应用
> 
> window 10专业版

My win 10 computer has the same problem.

**Comment by cathywife** [comment]
me too

**Comment by wakedautumn** [comment]
关掉安全设置，安装成功后再打开。

**Comment by txthinking** [comment]
> 我在windows 10上也遇到了这个问题。
> 1、window_386无法打开
> 2、window_amd64 无法打开
> 3、brook.msi 打开安装界面后，下一步直接kill了应用
> 
> window 10专业版

Please know the difference of CLI and GUI 

https://talks.txthinking.com

(and google translate if need)

**Comment by txthinking** [comment]
Please try v20200801, if any problem reopen or create an issue please.
