### ISSUE TITLE
When run brook in vpn mode, how to exclude some ip or host from proxy?

### ISSUE THREAD

**Issue by freewind** [txthinking/brook#648]
I run brook like:

```
sudo ~/bin/brook_darwin_amd64 vpn -l 127.0.0.1:1080 -s myserver:8888 -p "mypass"
```

Is it possible to exclude some hosts(like taobao.com) from proxy, just visit directly?

**Comment by NaughtDZ** [comment]
Just use client mod.
Like : brook_windows_amd64.exe client -l 127.0.0.1:2080 -i 127.0.0.1 -s x.x.x.x:xxxx -p xxxxxxxx
Then if you use Chrome.Go use browser plug-in "SwitchyOmega".
Or you can use like "Proxifier" or else software.
----
Client mod,brook will make a local Socks5 proxy.
So....you can got it.

**Comment by freewind** [comment]
@NaughtDZ Thanks. But for some reason, I can't use client mode, and have to use vpn mode

**Comment by edmundzhong888** [comment]
You can do that !
ex. route add -net 192.168.0.0/16 eth0
or  route add -net 1.2.3.4/32 eth0

**Comment by txthinking** [comment]
try https://github.com/txthinking/ipio
