### ISSUE TITLE
Hope to be compatible with standard Socks5, especially Android version

### ISSUE THREAD

**Issue by chenwc520** [txthinking/brook#650]
Hope to be compatible with standard Socks5, especially Android version

**Comment by txthinking** [comment]
Yes. Brook Android Client supports standard Socks5.
Let's make it clear, `standard Socks5` supports both TCP and UDP. but many
socks5 server only support TCP, so they are NOT `standard Socks5`.

If your socks5 server is started by brook, then it is a `standard Socks5`
