### ISSUE TITLE
About brook log error i / o timeout

### ISSUE THREAD

**Issue by jiutianjuju** [txthinking/brook#651]
### Prerequisites

* [ ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [ ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
No
* [ ] Are you running the latest version?
Client and server are up to date
* [ ] I will write this according to this template.
* [ ] I will write this in English.

### Environment

* Brook Version:v20200101
* Server Operating System:centos7.4
* Server Operating System Version:
* Server Operation System Language:
* Client Operating System:win10
* Client Operating System Version:
* Client Operation System Language:

### Steps to Reproduce

1.When the brook client is running, there are errors in the log
2.
3.

### Detailed Description
![image](https://user-images.githubusercontent.com/40514186/72325411-01478b80-36e8-11ea-9f91-326c81df456c.png)

**Comment by txthinking** [comment]
As it shows, your client doesn't connect to xx.xx.59.106:8080.
