### ISSUE TITLE
linux manjaro: vpn "expired request" error 

### ISSUE THREAD

**Issue by tea2go** [txthinking/brook#652]
### Prerequisites

* [ x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [ x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x ] Are you running the latest version?
* [ x] I will write this according to this template.
* [ x] I will write this in English.

### Environment

* Brook Version: client side: 20200102 // server side: unknown (set up 2 months ago/can't access my account)
* Server Operating System: debian / google vps
* Server Operating System Version: 9
* Server Operation System Language: english
* Client Operating System: manjaro
* Client Operating System Version: 18.1.5
  kernel: x86_64 Linux 5.3.18-1-MANJARO
* Client Operation System Language: english

### Expected Behavior
I use to be able to connect to client and it worked (earlier manjaro version). However in order to do so I couldn't upgrade some network related apps. Otherwise I got a timeout i/o error. 

> networkmanager 1.14.7dev+3+g35...
Network Manager 1.8.21dev+3+gb4...
nfs-utils 2.3.3-1
ntp 4.2.8.p13-2
openconnect 1.8.02-1
vpnc 1.0.5.3.r454.r67-1 <

Since about a week this workaround doesn't help anymore. (not sure which package actually was necessary to be blocked from upgrade)

### Current Behavior
I upgraded and installed whole system new and did not downgrade any apps. Now I get this if I connect to the client and try to load google.com

> 2020/01/21 18:44:57 Expired request
2020/01/21 18:44:57 Expired request
2020/01/21 18:45:02 Expired request
2020/01/21 18:45:04 Expired request
2020/01/21 18:45:08 Expired request
2020/01/21 18:45:09 Expired request
2020/01/21 18:45:09 Expired request
2020/01/21 18:45:13 Expired request
^CQuitting... <
2020/01/21 18:45:17 accept tcp 127.0.0.1:1080: use of closed network connection

SIDE NOTE: It currently still works on ios and mac os. However recently it started to be a bit troublesome as well.

### Steps to Reproduce

1. 
2.
3.

**Comment by txthinking** [comment]
Please check and ensure your client OS time is correct.

**Comment by oldbbold** [comment]
Not sure what you mean but this is my guess. Let me know if you need another log but provide me with a command as I am a bit overwhelmed with this troubleshoot.
`brook -time`

> COPYRIGHT:
   https://github.com/txthinking/brook
2020/01/21 19:56:25 flag provided but not defined: -time
<

**Comment by txthinking** [comment]
https://stackoverflow.com/questions/18458839/how-can-i-get-the-current-date-and-time-in-the-terminal-and-set-a-custom-command

**Comment by txthinking** [comment]
```
$ date
```

**Comment by oldbbold** [comment]
Okay I got that. Sorry it took so long but I had to setup my VPS from scretch again. I checked the time and you were right about it that was set to CST. Now I set both to Hong Kong time.

`sudo rm -f /etc/localtime`
`sudo cp /usr/share/zoneinfo/Hongkong /etc/localtime`

However I still get the same error when I try to connect on Manjaro

> Ctrl-C to quit
2020/01/21 23:28:20 Expired request
2020/01/21 23:28:24 Expired request
2020/01/21 23:28:29 Expired request
2020/01/21 23:28:29 Expired request
^CQuitting...
2020/01/21 23:28:37 accept tcp 127.0.0.1:1080: use of closed network connection>

Forgot to mention I also have BBRplus configured. 
https://raw.githubusercontent.com/chiakge/Linux/NetSpeed/master/tcp.sh

**Comment by txthinking** [comment]
CST is time zone.[1]
You just change the time zone, not time.

First of all, let us know:

### What is the problem?

Common operating system(like macOS, Windows, iOS...) have system time.
**Brook need your server OS and client OS both have correct time.**

### How to check and update system time?

Here is a Arch Linux wiki page which explains system time[2]

### Similar issues

This is a similar issue[3]

1. https://en.wikipedia.org/wiki/Time_zone
2. https://wiki.archlinux.org/index.php/System_time_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)
3. https://github.com/txthinking/brook/issues/318

**Comment by oldbbold** [comment]
Ah cool I did not know that a Computer actually runs different time in the background. Well I think I set up the time and time zone correct for my client (manjaro os). I used those commands:

`sudo timedatectl set-ntp true`
`sudo timedatectl set-timezone Asia/Macau`

So now if I hit `timedatectl` I get this:

> Local time: Wed 2020-01-22 22:56:15 CST
           Universal time: Wed 2020-01-22 14:56:15 UTC
                 RTC time: Wed 2020-01-22 14:56:15
                Time zone: Asia/Macau (CST, +0800)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
>

However on the server I cant use those because apparently timedatectl is not installed and I could not find out how to install it either. Now the only time I did manage to change was the local time (timezone). How can I change the UTC and RTC? 

Also I tried `hwclock --show` but I also get a msg back that it is not installed. Thank you so much for your hints so far.

**Comment by oldbbold** [comment]
Now I got `date` to Honk Kong time and `date -u` to UTC Greenwich time on both the server and client side. 
I think I had to start ntp on server to get the correct hardware-clock.
```
$ sudo service ntp start
```
Nonetheless I still cannot connect to brooks vpn service. But the expired request error is gone and now I just can't connect to any website. If I hit ctrl+c I only get:
```
^CQuitting...
2020/01/23 22:20:37 accept tcp 127.0.0.1:1080: use of closed network connection
```

**Comment by oldbbold** [comment]
Hey me again... ;l

So I don't know what I am doing at this point. My idea was to open the brook port on my client. I did that:
```
$ sudo nano /etc/services
```
And there I added 1080 tcp&udp as well as 5678 tcp&udp (used port on my brook server). Now this error does not show up any more when I quit brook. However I still can't access the free internet. Any suggestions?

**Comment by txthinking** [comment]
Please provide reproduce steps.

**Comment by txthinking** [comment]
expired request, means your server OS time is incorrect or your client OS time is incorrect.

**Comment by duanluan** [comment]
> Please check and ensure your server OS and client OS system time are correct, and let me know

我最近就是 PC 端突然连接没用了，安卓上就可以，试了好多种办法都不行，Server 端改了时区就好了。
