### ISSUE TITLE
how to use brook_darwin_amd64 on mac?

### ISSUE THREAD

**Issue by gwl002** [txthinking/brook#654]
I can install the gui version on mac by install the .pkg file directly.But how to install the cli version?When use the brook command,it tips brook command not found

**Comment by teheavy** [comment]
Same here, and after installing, brook does not open on MacOS 10.11.

**Comment by ziyenano** [comment]
@gwl002 @teheavy you should install either of GUI or CLI. If your mac os version is 10.14 or higher  , install GUI directly. FYI,  for CLI installation refer to [link](https://github.com/ziyenano/Brook_CLI_Helper).

**Comment by txthinking** [comment]
Read CLI basic knowledge
https://talks.txthinking.com

(and google translate if need)
