### ISSUE TITLE
NOT WORKING IN CHINA

### ISSUE THREAD

**Issue by celioZhao** [txthinking/brook#656]
* Brook Version: v20200101
* Server Operating System Version: Ubuntu 18.04 x86_64  
* Server Operation System Language: English
* Client Operating System Version: macOS Catalina 10.15.3 & iOS 13.3.1
* Client Operation System Language: English

### Expected Behavior
Can visit those websites banned by China.

### Current Behavior
Both mac client and iOS client are not able to visit those website banned by China. Such as google, youtube, etc.

### Steps to Reproduce
I'm living in China right now and I purchased a server in Bandwagon.
It used to be working fine before last month.
I tried to reinstalled brook with the cmd  below. (I also reinstalled client side)
sudo apt update
sudo apt install snapd
sudo snap install brook

And startup the server with cmd below
/snap/brook/107/bin/brook server -l :1111 -p test &

I tried to clicked both mac and iOS Brook "Start" button
Both are connected without any error msg occurred.

### Detailed Description
I tied to switch some other network, also not working. 
I used my friend's Windows OS to try, also cannot.
I can ssh my server, I can telnet my server ssh port. (Base on this, I don't think China is blocking anything for VPN)
Brook port I used in my server side is not able to telnet. 

I'm not familiar with network, can somebody guide me to debug this issue?
Thank you so much 😊

**Comment by mpx2m2** [comment]
try Shadowsocks run in background, works in China, test it just now.
In server:
`brook ssserver -l :9999 -p password &`
In Client:
use Shadowsocks option

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/issues/575

**Comment by txthinking** [comment]
1. Don't use `snap`, I do not maintain the snap package continuously, Just download latest brook on Github page.
2. Check firewall
3. #575

**Comment by celioZhao** [comment]
Thank you guys.
It seems someone blocked my port.
It works well again since I changed my brook server port.
For someone who use VPN in China. DO NOT SHARE YOUR VPN SERVER.
