### ISSUE TITLE
WSServer Add new features “Coexist with an actual Web server”

### ISSUE THREAD

**Issue by llfj** [txthinking/brook#658]
### Prerequisites

* [ ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [ ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ ] Are you running the latest version?
* [ ] I will write this according to this template.
* [ ] I will write this in English.

### Environment

* Brook Version:
* Server Operating System:
* Server Operating System Version:
* Server Operation System Language:
* Client Operating System:
* Client Operating System Version:
* Client Operation System Language:

### Possible Solution
Can you add new features for WSServer like "Coexist with an actual Web server" for ss-simple-obfs？
Thank you！

https://github.com/shadowsocks/simple-obfs

**Comment by bannedbook** [comment]
[Brook之TLS+WebSocket+Webserver config](https://github.com/bannedbook/fanqiang/blob/master/v2ss/Brook%E4%B9%8BTLS%2BWebSocket%2BWeb%E7%BF%BB%E5%A2%99%E6%95%99%E7%A8%8B.md)
just use google translate to read.

**Comment by llfj** [comment]
Thank you！

**Comment by txthinking** [comment]
Yes, nginx + brook wsserver can do it.

**Comment by txthinking** [comment]
via [nico](https://github.com/txthinking/nico)
```
$ brook wsserver --listen :9999 --password hello
$ nico 'domain.com /path/to/web/root' 'domain.com/ws http://127.0.0.1:9999'
```

```
$ brook wssclient --wssserver wss://domain.com:443 --password hello --socks5 127.0.0.1:1080
```

**Comment by moh3n9595** [comment]
> via [nico](https://github.com/txthinking/nico)
> 
> ```
> $ brook wsserver --listen :9999 --password hello
> $ nico 'domain.com /path/to/web/root' 'domain.com/ws http://127.0.0.1:9999'
> ```
> 
> ```
> $ brook wssclient --wssserver wss://domain.com:443 --password hello --socks5 127.0.0.1:1080
> ```

302 Found error in client after run brook + nico
