### ISSUE TITLE
Some question about install brook.msi in window10

### ISSUE THREAD

**Issue by ou475454353** [txthinking/brook#659]
When i install brook.msi in window10，it said “User installations are disabled via policy on the machine.”

**Comment by cathywife** [comment]
My win10 1809 ent ltsc isn't install too. msi amd64 x86 version isn't ok.

**Comment by 1iver** [comment]
try "run as administrator"?

**Comment by ImportTaste** [comment]
@ou475454353 Use one of these three solutions:

---

### Solution 1
From an admin command prompt, run the command `msiexec /i Brook.msi`

---

### Solution 2
From an admin command prompt, run the command
```cmd
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Installer" /t REG_DWORD /v "DisableMSI" /d 0 /f
```
And then, reboot. MSI installations will no longer fail.

---

### Solution 3
Create a new file with the .reg extension and save it with the following contents:
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Installer]
"DisableMSI"=dword:00000000
```
Then double-click the file and select 'Yes' on the prompt that comes up. Afterwards, reboot. MSI installations will no longer fail.

---

### Solution 4

Use the `brook_windows_amd64.exe` standalone file instead. Rename it to brook.exe and then add the directory you place it in to your System Variables by running `rundll32 sysdm.cpl,EditEnvironmentVariables` from an admin command prompt and using the GUI that pops up.

**Comment by wakedautumn** [comment]
Made it by turning off all "Threat & Virus protection".

**Comment by txthinking** [comment]
Please try v20200801, if any problem reopen or create an issue please.
