### ISSUE TITLE
If it shows 'Invalid Version' in Client?what can I deal with it?

### ISSUE THREAD

**Issue by ZAKERR** [txthinking/brook#660]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
Yes
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
Yes
* [x] Are you running the latest version?
Yes
* [x] I will write this according to this template.
* [x] I will write this in English.
Yes

### Environment

* Brook Version:
v20200201
* Server Operating System:
Linux 
* Server Operating System Version:
Centos OS8
* Server Operation System Language:
English
* Client Operating System:
Windows
* Client Operating System Version:
Windows10 Enterprise
* Client Operation System Language:
Chinese

### Expected Behavior
run the brook with ws in my clinet to surf the Internet 

### Current Behavior
It doesn't work ans shows 'Invalid Version' in my client,and my vps shows 'cipher: message authentication failed' .But my phone can run the brook with ws in my clinet to surf the Internet 

### Steps to Reproduce

1. my servers:  input  './brook wsserver -l :9999 -p password /dev/null 2>&1 &'
2. my pc :download brook_windows_386.exe and rename brook
3. my pc: input  `brook wsclient -l 127.0.0.1:1080 -i 127.0.0.1 -s ws://ip:port -p password`

**Comment by 1iver** [comment]
Same error for me. 
WS model uses Socks5 proxy protocol in your local mechine. I think you may use Chrome with SwitchyOmega whichs set local proxy server HTTP. you may try switch HTTP to Socks5

**Comment by 1iver** [comment]
"Invalid Version": your local mechine keep listening on port 1080 for Socks5 protocol data. Please make sure the data transimission to port 1080 use Socks5 not HTTP.

**Comment by ZAKERR** [comment]
> "Invalid Version": your local mechine keep listening on port 1080 for Socks5 protocol data. Please make sure the data transimission to port 1080 use Socks5 not HTTP.

oh, my god . Thank u for your help. It helps me deal with the problem.
