### ISSUE TITLE
Where to get server name and password

### ISSUE THREAD

**Issue by igaresh** [txthinking/brook#661]
Hi guys

I don't understand where is to get server address and password

I run Shadowsocks with Outline and there is everything is straight forward

Thanks

**Comment by txthinking** [comment]
When you use outline, how to get server?

**Comment by igaresh** [comment]
Thanks for reply

I understand that. I need to install first. But I can't actually get it. Can you help to find installation file/path please?

"You already have a Brook server, $ brook server..." - frankly I don't understand how to make a server. Even with my skills running v2ray, shadowsocks trough cloudfare

Also, I will test it in Turkmenistan, where is all vpn, proxy aggressively monitored
  
Thanks mate. Hope to hear from you

**Comment by bannedbook** [comment]
> how to make a server.

 how to make a server, firstly you need to buy a vps server, you can[ read this ](https://github.com/bannedbook/fanqiang/blob/master/v2ss/%E8%B4%AD%E4%B9%B0Vultr%20VPS%E5%9B%BE%E6%96%87%E6%95%99%E7%A8%8B.md  )
use google translate to read.

**Comment by igaresh** [comment]
> > how to make a server.
> 
> how to make a server, firstly you need to buy a vps server, you can[ read this ](https://github.com/bannedbook/fanqiang/blob/master/v2ss/%E8%B4%AD%E4%B9%B0Vultr%20VPS%E5%9B%BE%E6%96%87%E6%95%99%E7%A8%8B.md)
> use google translate to read.to run VPS it is not a problem. I nave VPS on GCC, AWS, ORACLE, Vultr....
I run shadowsocks-libev, outline, wineguard...

I can't find where is here installation file to use in shell

**Comment by igaresh** [comment]
To run VPS it is not a problem. I nave VPS on GCC, AWS, ORACLE, Vultr....
I run shadowsocks-libev, outline, wineguard...
I can't find where is here installation file to use in shell

**Comment by bannedbook** [comment]
It look like need not to install.
just download and run it.
eg:
wget https://github.com/txthinking/brook/releases/download/v20200201/brook
chmod +x brook
./brook wsserver --domain www.mydomain.com -p yourPassword
or
brook server -l :9999 -p yourPassword

**Comment by txthinking** [comment]
Look at the github readme
