### ISSUE TITLE
How to use vpn mode without set brook as default route?

### ISSUE THREAD

**Issue by qiudaomao** [txthinking/brook#663]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version:
* Server Operating System:
* Server Operating System Version:
* Server Operation System Language:
* Client Operating System:
* Client Operating System Version:
* Client Operation System Language:

### Detailed Description
I want set route manually only for specific ip groups.

**Comment by zjl88858** [comment]
All VPN need route to work.
If u don't want set to default route u can delete 0.0.0.0/0 route and add ur lan ip to default.
`route del 0.0.0.0
route add 0.0.0.0 192.168.1.1(or 10.0.0.1 etc) mask 0.0.0.0`

**Comment by txthinking** [comment]
Accept in next version

**Comment by txthinking** [comment]
You can use https://github.com/txthinking/ipio

$ ipio tun2brookserver -s 1.2.3.4:9999 -p hello

And write an auto bash script to edit your routes again
