### ISSUE TITLE
wss:// on mobile platform

### ISSUE THREAD

**Issue by GaranYeon** [txthinking/brook#664]
![Screenshot_20200306-080938__01](https://user-images.githubusercontent.com/18183124/76037782-df011a00-5f82-11ea-9bc1-0997ad510af4.jpg)

**Comment by zjl88858** [comment]
Please, use websocket without TLS.
Wss is not supported on mobile.

**Comment by txthinking** [comment]
Yes, wss://  still need some work on mobile platform.
