### ISSUE TITLE
error：/etc/init.d/brook: line 58: 30378 Killed

### ISSUE THREAD

**Issue by jiutianjuju** [txthinking/brook#667]
### Prerequisites

* [ ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
yes
* [ ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
yes
* [ ] Are you running the latest version?
yes
* [ ] I will write this according to this template.
* [ ] I will write this in English.

### Environment

* Brook Version:v20200201
* Server Operating System:centeros7
* Server Operating System Version:
* Server Operation System Language:
* Client Operating System:win10
* Client Operating System Version:
* Client Operation System Language:

### Expected Behavior
The recent brook stability is very poor. I went to the server to check the logs, and then I got an error.
### Current Behavior
![image](https://user-images.githubusercontent.com/40514186/76399533-b9787400-63b9-11ea-9ca3-3b214a6d71e2.png)
Why did you kill this port？
### Steps to Reproduce

1.View brook logs
2.
3.

**Comment by jiutianjuju** [comment]
No timeout error was reported this time, only EOF

**Comment by jiutianjuju** [comment]
View the log today and report an error：cipher: message authentication failed

**Comment by jiutianjuju** [comment]
The problem has been solved so far. I changed the Brook server to v20200101 and changed the port.

**Comment by txthinking** [comment]
https://talks.txthinking.com
