### ISSUE TITLE
What is --ip/-i for?

### ISSUE THREAD

**Issue by dausruddin** [txthinking/brook#669]
### Prerequisites

* [Yes] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [Yes] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [Yes] Are you running the latest version?
* [Yes] I will write this according to this template.
* [Yes] I will write this in English.

### Environment

* Brook Version: 20200201
* Server Operating System: Ubuntu
* Server Operating System Version: 18.04
* Server Operation System Language: English
* Client Operating System:
* Client Operating System Version:
* Client Operation System Language:

### Expected Behavior
N/A

### Current Behavior
N/A

### Detailed Description
Hi. I am sorry, but I am not sure if I understand correctly what is Brook for.
I want a socks5 server to connect multiple clients which is my another server and my own pc.
So I installed Brook on a special server and it required this parameter
```
--ip value, -i value      Client IP address, like: 127.0.0.1
```
My server has a static IP, but my PC has dynamic IP. Also seems that I can only put 1 IP in that parameter. So how do I actually fill it it?

I have tried putting IPs like `0.0.0.0`, `127.0.0.1`, and `1xx.xxx.xxx.xxx` (Brook server IP), and they all works. My PC and my server can access the socks5 proxy and all is working fine. So what is the point having the parameter `--ip/-i` required?

Also I have a lot of this line in my log
```
2020/03/15 16:55:04 dial tcp 127.0.0.1:9614: connect: connection refused
```

Also some `EOF`

Thanks.

### Possible Solution
N/A

**Comment by dausruddin** [comment]
I have read [this](https://github.com/txthinking/brook/issues/96#issuecomment-343127726) but seems that I am still lost because looks like it affect Brook clients. 
In my case, I want to use the SOCKS5 server in browser and applications.
Can someone explain in simpler and shorter sentences?

**Comment by txthinking** [comment]
Don't assume that the listener knows what you think.
So:
> ### Prerequisites
> * [Yes] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
> * [Yes] Did you search in [issues](https://github.com/txthinking/brook/issues)?
> * [Yes] Are you running the latest version?
> * [Yes] I will write this according to this template.
> * [Yes] I will write this in English.
> 
> ### Environment
> * Brook Version: 20200201
> * Server Operating System: Ubuntu
> * Server Operating System Version: 18.04
> * Server Operation System Language: English
> * Client Operating System:
> * Client Operating System Version:
> * Client Operation System Language:
> 
> ### Expected Behavior
> N/A
> 
> ### Current Behavior
> N/A
> 
> ### Detailed Description
> Hi. I am sorry, but I am not sure if I understand correctly what is Brook for.
Before I answer this question, let me ask you what do you need or want? This is a prerequisite for answering the following questions.

> I want a socks5 server to connect multiple clients which is my another server and my own pc.
I don't understand this description, please detail this.
> So I installed Brook on a special server and it required this parameter
What is special server? What is the command?
> 
> ```
> --ip value, -i value      Client IP address, like: 127.0.0.1
> ```
> 
> My server has a static IP, but my PC has dynamic IP. Also seems that I can only put 1 IP in that parameter. So how do I actually fill it it?
What is the full command? Where does the command run? server? pc?
> 
> I have tried putting IPs like `0.0.0.0`, `127.0.0.1`, and `1xx.xxx.xxx.xxx` (Brook server IP), and they all works. My PC and my server can access the socks5 proxy and all is working fine. So what is the point having the parameter `--ip/-i` required?
> 
> Also I have a lot of this line in my log
> 
> ```
> 2020/03/15 16:55:04 dial tcp 127.0.0.1:9614: connect: connection refused
> ```
> 
> Also some `EOF`
> 
> Thanks.
> 
> ### Possible Solution
> N/A

I assume that:
* you have a remote server, a local pc. the remote server is in public internet.
* you want to create a proxy between your remote server and pc, and you want the proxy is socks5 proxy

So you just:
* Run this command on your remote server: `$ brook socks5 -l :1080 --ip IP`
      * IP is your server's public IP
* use socks5://IP:1080 on your local pc

**Comment by dausruddin** [comment]
Thanks. I really appreciate that. That answered my questions.

**Comment by txthinking** [comment]
BTW, `$ brook socks5 ...` can also work with username and password

but: 
* server<--unencrypted-->local pc.

If you want remote server<--encrypted-->local pc

1. on your remote server: `$ brook server -l :9999 -p password`
2. on your local pc: `$ brook client -l :1080 -i 127.0.0.1 -s SERVER_PUBLIC_IP:9999 -p password`
3. use socks5://127.0.0.1:1080 on your local pc

Only you can use you
