### ISSUE TITLE
Why ip.cn show remote server IP?

### ISSUE THREAD

**Issue by lonely720** [txthinking/brook#67]
Android客户端能否加入账号切换和分应用代理
另外ip.cn，显示的是vps的ip

**Comment by txthinking** [comment]
Brook android use
this white app list: https://github.com/txthinking/pac/blob/master/white_apps.list
and
this white list: https://github.com/txthinking/pac/blob/master/white.list

Your can start brook and visit:
https://www.ipip.net  (This will show your local IP)
https://www.baidu.com/s?word=ip (This will show your local IP)
https://ifconfig.co  (This will show your VPS IP)

And *.cn in white list, so should show your local IP, but why ip.cn show remote IP, maybe this is a individual exception.

**Comment by lonely720** [comment]
有些不常见的国内app也走代理了，建议自行选择哪些应用走代理，哪些不走

**Comment by txthinking** [comment]
Because ip.cn use geo IP. Brook Android use 8.8.8.8 DNS server.
This is correct.
