### ISSUE TITLE
How to route video game's TCP and UDP socket traffics on client side to the brook proxy server

### ISSUE THREAD

**Issue by owen800q** [txthinking/brook#670]
### Prerequisites

* [ x ] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [ x ] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [ x ] Are you running the latest version?
* [ x ] I will write this according to this template.
* [ x ] I will write this in English.

### Discussion

Normally in order to route HTTP/HTTPS traffics of browser to brook, I would set the socks5 proxy in browser proxy setting control panel. Or system-wide proxy by setting env variables. But it does not work on video game. Especially for games running on steam platform. For those types of game, they communicate with server by socket connections directly not using HTTP/HTTPS. Coz in wireshark I did not see any https traffics sent out Instead they have a custom protocol built on top of TCP.
How to make brook working on video games?

**Comment by owen800q** [comment]
@txthinking

**Comment by txthinking** [comment]
try $ brook vpn ...

**Comment by iamid0** [comment]
How about transparent proxy with brook, you may need something like nanopi R1S or nanopi R2S.

**Comment by txthinking** [comment]
Try https://github.com/txthinking/brook/issues/629
