### ISSUE TITLE
Feature request: Add path support for websocket mode

### ISSUE THREAD

**Issue by hzlmy2002** [txthinking/brook#671]
### Prerequisites

* [x] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [x] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [x] Are you running the latest version?
* [x] I will write this according to this template.
* [x] I will write this in English.

### Environment

* Brook Version:20200221
* Server Operating System:Ubuntu
* Server Operating System Version:18.04.4
* Server Operation System Language:en_US
* Client Operating System:Ubuntu
* Client Operating System Version:18.04.4
* Client Operation System Language:en_US

### Expected Behavior
Brook wss mode should support url like **example.com:443/your_path_here** in order to work with web server like nginx correctly.
### Current Behavior
Currently brook only use default path "/ws" which means if you want brook cooperates with nginx you can't custom the path and can only use "/ws" ,which is easy to be detected.
### Detailed Description
```
#nginx setting
 location /ws {
               proxy_redirect off;
               proxy_pass http://127.0.0.1:20000;
               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "upgrade";
               proxy_set_header Host $http_host;
               proxy_set_header X-Real-IP $remote_addr;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               }

```
Currently,only this configuration takes effect. If you substitute "/ws" with any other path, brook client can't connect to the server successfully.
```
#brook server command

brook -d wsserver -l 127.0.0.1:20000 -p your_password_here

#brook client command

wsclient -l 127.0.0.1:10000 -i 127.0.0.1 -s wss://example.com:443 -p your_password_here
```
### Possible Solution
Support url like **wss://example.com:443/your_path_here** so that we can use custom websocket path **your_path_here** in nginx, making it more difficult to be detected.

**Comment by txthinking** [comment]
Accept, will add in next version.

But for now, this can help you https://serverfault.com/questions/379675/nginx-reverse-proxy-url-rewrite

**Comment by hzlmy2002** [comment]
Thanks for your help.

**Comment by hzlmy2002** [comment]
This feature has been added to the newest version, closed.
