### ISSUE TITLE
Dns request on ipv6-only vps failed

### ISSUE THREAD

**Issue by Genkin** [txthinking/brook#678]
### Prerequisites

* [Y] Did you check the [wiki](https://github.com/txthinking/brook/wiki)?
* [Y] Did you search in [issues](https://github.com/txthinking/brook/issues)?
* [Y] Are you running the latest version?
* [Y] I will write this according to this template.
* [Y] I will write this in English.

### Environment

* Brook Version:v20200201
* Server Operating System:Centos
* Server Operating System Version:8
* Server Operation System Language:en_us
* Client Operating System:android/ios
* Client Operating System Version:android 10/ios 10.3.3
* Client Operation System Language:en_us

### Expected Behavior
request  to an ipv6 dns resolver.

### Current Behavior
default using dns 8.8.8.8:53

### Steps to Reproduce

1.run as a ws server(tried brook but failed)
2.connect to the server successfully
3.log  shows that conection to 8.8.8.8:53 was failed.

### Detailed Description
my vps doesn't support ipv4.

### Possible Solution
change the dns resolver or use ipv6 dns resolver as default.

**Comment by txthinking** [comment]
The Android client doesn't support IPv6.

But are you really sure that iOS doesn't support IPv6?

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/wiki/IPv6

**Comment by txthinking** [comment]
Please try v20200801, if any problem reopen or create an issue please.
