### ISSUE TITLE
openwrt support

### ISSUE THREAD

**Issue by vvxiang** [txthinking/brook#68]
在电脑上面测试brook的效果比用SSR速度要快。想在路由器上面安装一个客户端，有出op客户端的计划吗，谢谢

**Comment by aoxiangtianji** [comment]
嗯嗯，我也希望呢

**Comment by binext** [comment]
确实迫切希望能有openwrt类路由器上使用的

**Comment by txthinking** [comment]
可以根据你的openwrt CPU选择下面某个文件(或者主页的某个arm版本):

https://storage.googleapis.com/txthinking-file/_/tmp/brook_linux_mips
https://storage.googleapis.com/txthinking-file/_/tmp/brook_linux_mips64
https://storage.googleapis.com/txthinking-file/_/tmp/brook_linux_mipsle
https://storage.googleapis.com/txthinking-file/_/tmp/brook_linux_mips64le
https://storage.googleapis.com/txthinking-file/_/tmp/brook_linux_ppc64
https://storage.googleapis.com/txthinking-file/_/tmp/brook_linux_ppc64le

不要忘记 chmod +x

**Comment by WouldChar** [comment]
The mips binary file is too large for my router's 8M flash. Did you build a more micro client for openwrt?

**Comment by keeno1982** [comment]
@txthinking Please added mips and mipsel to daliy relase

**Comment by txthinking** [comment]
You mean it works?

**Comment by chenhw2** [comment]
Enabled FPU Emulator, Golang can work on mips SoC.

**Comment by tugodxx** [comment]
请问有问有 openwrt 可用的客户端package 文件，你的文件太大了，我的路由器没有那么大空间了

**Comment by chenhw2** [comment]
@tugodxx 这样放不下，打包成ipk一样放不下

**Comment by spikeninja** [comment]
请问有makefile文件吗，想编译自己的路由器ipk文件

**Comment by spikeninja** [comment]
mips的版本在我路由上无法运行，估计是编译环境不同造成的，能否放上makefile文件，我好自己编译。

**Comment by txthinking** [comment]
What happend when you run brook_linux_mips?

Here is no makefile, just build script in
https://github.com/txthinking/brook/blob/master/cli/brook/buildAll.sh

**Comment by spikeninja** [comment]
mips在openwrt路由上运行时提示Illegal instruction

**Comment by txthinking** [comment]
@spikeninja Solution: https://github.com/golang/go/issues/18880#issuecomment-276665458

**Comment by txthinking** [comment]
Please follow #117

**Comment by evilchris** [comment]
有没有开发luci-app-brook的计划？

**Comment by WouldChar** [comment]
写了一个简单的brook的luci插件，功能比较少，仅用于透明代理和dns tunnel，支持IP路由模式和gfwlist模式，附带去广告。https://github.com/WouldChar/openwrt-brook-tproxy
在openwrt源码或SDK编译都可，ipk不包含brook可执行文件，另需自己下载放到路由器/usr/bin/下。

**Comment by Captain1** [comment]
Please compile a mipsel version with no FPU needed, many thanks.

**Comment by txthinking** [comment]
Tracking https://github.com/txthinking/brook/issues/432

**Comment by wangda1** [comment]
When I run the cmd  `./brook_linux_mips` on my router (the env is mips 32,os is openwrt), it shows 
> ./brook_linux_mips: line 1: syntax error: unexpected "("    

 there some ways that i could try? thanks
