### ISSUE TITLE
when i close the tun mode 

### ISSUE THREAD

**Issue by daloyanf** [txthinking/brook#681]
goroutine 1 [running]:
github.com/txthinking/gotun2socks.(*Tun2Socks).Stop(0xc000282ab0)
        /Users/tx/go/src/github.com/txthinking/gotun2socks/gotun2socks.go:82 +0x12c
github.com/txthinking/brook.(*Tun).ListenAndServe.func6(0x11e1a300, 0x0)
        /Users/tx/go/src/github.com/txthinking/brook/tun.go:129 +0x35
github.com/txthinking/runnergroup.(*RunnerGroup).Done(0xc000294620, 0x0, 0x0)
        /Users/tx/go/src/github.com/txthinking/runnergroup/runnergroup.go:85 +0xe4
github.com/txthinking/brook.(*Tun).Shutdown(0xc000048ae0, 0xc000006018, 0xc0002d9920)
        /Users/tx/go/src/github.com/txthinking/brook/tun.go:144 +0xfa
main.main.func7(0xc0002922c0, 0xd, 0x18)
        /Users/tx/go/src/github.com/txthinking/brook/cli/brook/main.go:558 +0x5d9
github.com/urfave/cli.(*Command).Run(0xc00007f680, 0xc000047e00, 0x0, 0x0)
        /Users/tx/go/src/github.com/urfave/cli/command.go:161 +0x43d
github.com/urfave/cli.(*App).Run(0xc000031380, 0xc00007c000, 0x8, 0x8, 0x0, 0x0)
        /Users/tx/go/src/github.com/urfave/cli/app.go:294 +0x756
main.main()
        /Users/tx/go/src/github.com/txthinking/brook/cli/brook/main.go:1262 +0x543d

what does it mean?
Is it working correctly?

**Comment by daloyanf** [comment]
any esle?

**Comment by txthinking** [comment]
You can try master. $ go get github.com/txthinking/brook/cli/brook

**Comment by txthinking** [comment]
Please try https://github.com/txthinking/ipio
