### ISSUE TITLE
amd64 server crashes after android client connects

### ISSUE THREAD

**Issue by LiangPingPiJiu** [txthinking/brook#682]
Hi,

on my amd64 server the brook-server crashes regulary about one minute after the android client connects with the following output:
`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x903834]

goroutine 9107 [running]:
github.com/txthinking/brook.(*Server).UDPHandle.func2.1(0xc000124a80, 0xc00000cfa0)
	   /Users/tx/go/src/github.com/txthinking/brook/server.go:346 +0x64
github.com/txthinking/brook.(*Server).UDPHandle.func2(0xc000124a80, 0xc00000cfa0)
	   /Users/tx/go/src/github.com/txthinking/brook/server.go:385 +0x438
created by github.com/txthinking/brook.(*Server).UDPHandle
	   /Users/tx/go/src/github.com/txthinking/brook/server.go:342 +0x5ad
`

I start the the server with the following command:
./brook_linux_amd64 server -l :nnn -p xxx

Also tried with different passwords and ports, doesn't seem to have any influence.

This error does NOT accur
- with the same command but an older version of brook_linux_arm64 server (arm not amd!)
- and also NOT if I connect with brook_linux_amd64 client
- and NOT if I connect through a kcp-tunel and a brook_linux_amd64 client afterwards

Versions I used:
- Brook version 20200501 (newest)(amd64 server and client)
- Brook version 20200201 (arm64 which dows not crash)
- Android: v20200501 (newest)
- amd64 server system is debian 9 (stretch)
- amd64 client system is debian 9 (stretch)
- arm64 server system is debian 10 (buster)

edit:
I just tried Brook version 20200201 on amd64 server and it works also.
So the error accurs only with the newest version 20200501

**Comment by txthinking** [comment]
Brook CLI v20200501 has  this bug. Try v20200502(CLI)

**Comment by LiangPingPiJiu** [comment]
Wow, this was fast, thank you! :)
Actually I've seen the update, seems like I accidently downloaded the old version :o 
Seems to work stable now, at least for several minutes already :)
