### ISSUE TITLE
 I would like to ask what the role of the client is

### ISSUE THREAD

**Issue by mrs-joker** [txthinking/brook#683]
### You may find solutions from the following resources:

* https://github.com/txthinking/brook/wiki
* https://github.com/txthinking/brook/issues
* https://talks.txthinking.com
* https://www.youtube.com/channel/UC5j8-I5Y4lWo4KTa4_0Kx5A

**Comment by mrs-joker** [comment]
I would like to ask what the role of the client is

**Comment by txthinking** [comment]
https://txthinking.github.io/brook/#/brook-client
