### ISSUE TITLE
Bypass mode app to not proxying them. (Apps VPN mode).

### ISSUE THREAD

**Issue by ingnelson** [txthinking/brook#684]
Hello admin.

Can you add a option to not proxying apps  or apps vpn mode ,please ?
That option is useful when I try to use http proxy before Brook app. 
Example: use a http header proxy before Brook or send a http header request request before Brook .
Or other connection like fragment request. 

And I can connect via local Host (127.0.0.1) to Brook.
For example shadowsocks has that option : 
![IMG_20200520_192841](https://user-images.githubusercontent.com/6626845/82513444-45043480-9ad0-11ea-88c4-b5bea3271407.jpg)
![IMG_20200520_192803](https://user-images.githubusercontent.com/6626845/82513445-46cdf800-9ad0-11ea-8ff1-0371d86fb5b8.jpg)

**Comment by txthinking** [comment]
one issue one topic please
