### ISSUE TITLE
可能存在的漏洞

### ISSUE THREAD

**Issue by 960PRO** [txthinking/brook#687]
Brook团队，你们好。隔壁V2ray爆出严重漏洞https://github.com/v2ray/v2ray-core/issues/2523
这种漏洞可能影响Brook，请排查一下Brook是否有这种缺陷。
谢谢，致敬你们这些开发者。

**Comment by LinhaiSuccess** [comment]
如果你用中文描述这个问题，我不知道Brook团队是否能理解。你可以用英语描述它

**Comment by txthinking** [comment]
All is well. Thx.
