### ISSUE TITLE
Only the first time turning on tun mode on linux succeed!

### ISSUE THREAD

**Issue by archerbtw** [txthinking/brook#688]
I tried tun mode on two linux pc several times.
Only the first time using tun on each pc succeed.
Can't connect successfully since the second time.
I don't know why??

**Comment by archerbtw** [comment]
Is it from the second time that Brook had a problem configuring the virtual network card?

**Comment by txthinking** [comment]
it about the route, your can see with $ ip route.

I am rewriting this.
