### ISSUE TITLE
Fail to use brook in macOS

### ISSUE THREAD

**Issue by hustzoujia** [txthinking/brook#689]
### You may find solutions from the following resources:

* https://github.com/txthinking/brook/wiki
* https://github.com/txthinking/brook/issues
* https://talks.txthinking.com
* https://www.youtube.com/channel/UC5j8-I5Y4lWo4KTa4_0Kx5A

### Please describe step by step any commands and operations you have performed, environment and version:

- mac version：10.15.5 (19F101)
- brook version：v20200501

- under the same server config, both my android client and windows10 work well, I also check https://github.com/txthinking/brook/issues/610   but I didn't solve the problem, Looking forward to your  reply, thanks.

networksetup -listnetworkserviceorder
-------------------------
An asterisk (*) denotes that a network service is disabled.
(1) USB 10/100/1000 LAN
(Hardware Port: USB 10/100/1000 LAN, Device: en4)

(2) AX88772A
(Hardware Port: AX88772A, Device: en5)

(3) Wi-Fi
(Hardware Port: Wi-Fi, Device: en0)

(4) Bluetooth PAN
(Hardware Port: Bluetooth PAN, Device: en3)

(5) Thunderbolt Bridge
(Hardware Port: Thunderbolt Bridge, Device: bridge0)

route -n get default
-------------------------
   route to: default
destination: default
       mask: default
    gateway: 192.168.2.1
  interface: en0
      flags: <UP,GATEWAY,DONE,STATIC,PRCLONING>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0

curl -x socks5://127.0.0.1:1080 ifconfig.co/country
----------------------------------------
curl: (52) Empty reply from server

scutil --proxy
-------------------------------------
<dictionary> {
  ProxyAutoConfigEnable : 1
  ProxyAutoConfigURLString : http://localhost:6789/proxy.pac
  ProxyAutoDiscoveryEnable : 0
}

Could you tell me how to fix the issue. thanks very much.

**Comment by txthinking** [comment]
Try cli version to make sure it works first

**Comment by hustzoujia** [comment]
I try cli version,  ./brook_darwin_amd64 client -s ip:port -p pwd -i 127.0.0.1 -l :1080
input: curl -x socks5://127.0.0.1:2080 ifconfig.co/country
output: curl: (52) Empty reply from server
so I change the local port from 1080 to 2080(./brook_darwin_amd64 client -s ip:port -p pwd -i 127.0.0.1 -l :2080), and curl -x socks5://127.0.0.1:2080 ifconfig.co/country
return: United States
but I can't visit google, seems brook doesn't work.

**Comment by hustzoujia** [comment]
![image](https://user-images.githubusercontent.com/35829737/84872055-f12b4200-b0b3-11ea-9138-fa5230b506a4.png)

**Comment by hustzoujia** [comment]
oh, yes, i forget the socks config, thanks for your help.
