### ISSUE TITLE
Error: Command requires admin privileges

### ISSUE THREAD

**Issue by bobwang3** [txthinking/brook#690]
### You may find solutions from the following resources:

* https://github.com/txthinking/brook/wiki
* https://github.com/txthinking/brook/issues
* https://talks.txthinking.com
* https://www.youtube.com/channel/UC5j8-I5Y4lWo4KTa4_0Kx5A

### Please describe step by step any commands and operations you have performed, environment and version:

After macOS Catalina is upgraded to os 10.15.5, after running the brook program, clicking the start button will prompt the following error:
_PlatformException(error, ** Error: Command requires admin privileges. exit status 14, null)_

This issue did not occur before this upgrade. After the problem occurred,  I upgraded the software from the v20200101 version to the latest v20200502, the problem is the same.

**Comment by txthinking** [comment]
Thank you. I will upgrade and try later.

**Comment by txthinking** [comment]
I still have not received the 10.15.5 update push.
Now I am on 10.15.2, is 10.15.5 under development or preview?

**Comment by txthinking** [comment]
Sorry, got it after restart.

**Comment by txthinking** [comment]
Please try v20200801, if any problem reopen or create an issue please.
