### ISSUE TITLE
Invalid server when connecting socks5 server

### ISSUE THREAD

**Issue by Pzixel** [txthinking/brook#692]
### You may find solutions from the following resources:

* https://github.com/txthinking/brook/wiki
* https://github.com/txthinking/brook/issues
* https://talks.txthinking.com
* https://www.youtube.com/channel/UC5j8-I5Y4lWo4KTa4_0Kx5A

### Please describe step by step any commands and operations you have performed, environment and version:
I'm running a socks5 server in docker on my server (`serjs/go-socks5-proxy` exactly if you wonder).
I can see it running from telegram app which allows to connect to socks5 server with password:

![image](https://user-images.githubusercontent.com/11201122/87148078-66a2c080-c2b6-11ea-818f-53571af2fd8d.png)

But when I use the same settings in brooks I got `Invalid server` error:

![image](https://user-images.githubusercontent.com/11201122/87148153-8df98d80-c2b6-11ea-8c42-af480c4f28aa.png)

Does brooks only works with another brooks server? It can't work via generic socks5 protocol?

**Comment by txthinking** [comment]
Please try v20200801, if any problem reopen or create an issue please.
