### ISSUE TITLE
The Android client cannot be used on version 20200701.

### ISSUE THREAD

**Issue by bobwang3** [txthinking/brook#694]
### You may find solutions from the following resources:

* https://github.com/txthinking/brook/wiki
* https://github.com/txthinking/brook/issues
* https://talks.txthinking.com
* https://www.youtube.com/channel/UC5j8-I5Y4lWo4KTa4_0Kx5A

### Please describe step by step any commands and operations you have performed, environment and version:

After the brook program on the server side was upgraded to 20200701, I tested 20200701 and 202000502 on an Android client, but none of them worked, I couldn't open anything, but the windows client test both two versions can work. I rolled back to version 202000502 on the server side, and the Android client started working.

Why did no one submit bug issues after the 20200701 version was released? Is it only me that continues to use this app?

**Comment by txthinking** [comment]
try v20200901 and  test it

https://github.com/brook-community/socks5.js
