### ISSUE TITLE
If Android client v20200701 does not work well:

### ISSUE THREAD

**Issue by txthinking** [txthinking/brook#695]
1. Tell me more information about v20200701 Android client(I need info to make it better)
2. Choose a previous version to use

**Comment by bobwang3** [comment]
Oneplus 5T, Android 9, OxygenOS, Magisk & EdXposed.
Versions before 20200502 (including this version) can work. Regarding this update, first I upgraded 20200701 on the server, and upgraded the brook of the Android phone to 20200701, found that it did not work, but the win client did.  Then I uninstalled the mobile app and rolled back to 20200502, but it still doesn't work. I ran a 20200502 while the server was running 20200701 and found that the program of this version can work if I connect to 20200502.

**Comment by txthinking** [comment]
Please try v20200801, if any problem reopen or create an issue please.
