### ISSUE TITLE
"there was an error parsing the package" - what is the minimal android version?

### ISSUE THREAD

**Issue by LiangPingPiJiu** [txthinking/brook#699]
Hi,

I've got the error "there was an error parsing the package" while install on an older android 4.4.4 phone.
Might it be, that brook requires a newer android version? What is the oldest version currently supported?

Thanks,
LiangPingPiJiu

**Comment by txthinking** [comment]
This information may help you:

compileSdkVersion 30
buildToolsVersion "30.0.0"
minSdkVersion 26
targetSdkVersion 30

**Comment by LiangPingPiJiu** [comment]
HI,

thank you for such a quick answer!
sdk-verision means android 8.0, this explains everything...

LiangPingPiJiu
