### ISSUE TITLE
ios 14 public beta 5

### ISSUE THREAD

**Issue by webcoderkz** [txthinking/brook#705]
OS: iOS 14 public beta 5

Connects via socks5, but cannot browse through this proxy. Is it a known issue?

**Comment by txthinking** [comment]
https://github.com/brook-community/socks5.js

Test your socks5 first

**Comment by webcoderkz** [comment]
my socks5 server is using dante and it works.

**Comment by txthinking** [comment]
1. dante support both TCP and UDP?
2. 'it works' means your problem has been solved?

**Comment by webcoderkz** [comment]
1. yes
2. You previously asked to test my socks5 server at first, so i meant - my socks5 server works fine on my mac, but not on ios 14.

**Comment by txthinking** [comment]
On Wed, Aug 26, 2020 at 12:56 PM Alexander Kim <notifications@github.com>
wrote:

>
>    1. yes
>    2. You previously asked to test my socks5 server at first, so i meant
>    - my socks5 server works fine on my mac, but not on ios 14.
>
> 'works file on my mac' does not mean 'works file on Android or iOS',
because:
1. mac (default proxy mode) only needs your socks5 support TCP
2. android and ios need your socks5 support both TCP and UDP.
So, I send your a that link, let you test your socks5 TCP and UDP.

**Comment by txthinking** [comment]
BTW, the test script does not support username/password socks5 yet.

**Comment by txthinking** [comment]
supported user/pass now

**Comment by txthinking** [comment]
dante socks5 server is not "full" socks5 server.

You can create socks5 server use `$ brook socks5`
