### ISSUE TITLE
Server fail to update to v20200901

### ISSUE THREAD

**Issue by yehui-h** [txthinking/brook#707]
--2020-08-23 10:38:06--  https://github.com/txthinking/brook/releases/download/v20200901/brook
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-08-23 10:38:06 ERROR 404: Not Found.

**Comment by JHrockice** [comment]
> wget -N --no-check-certificate "https://github.com/txthinking/brook/releases/download/v20200901/brook_linux_amd64"
> mv brook_linux_amd64 brook
> 
> This way i used.

Yes, it works as you say to change brook.sh.
