### ISSUE TITLE
Cannot run in win7

### ISSUE THREAD

**Issue by openBetaa** [txthinking/brook#71]
I downloaded the newest brook.exe,but I can't run it,which has error:
reg add acu::exec: "reg": executable file not found in %PATH%.

BTW,I can run older version of brook.exe. So I think maybe the exe file not bulid in right way, please check this issue. Thanks a lot!

**Comment by txthinking** [comment]
Actually new version don't modify this part.

Please tell me what happen do this steps:

1. WIN + R
1. Type `cmd` and press Enter
1. Type `reg /?` and press Enter

**Comment by openBetaa** [comment]
C:\Windows\system32>reg /?

REG Operation [Parameter List]

  Operation  [ QUERY   | ADD    | DELETE  | COPY    |
               SAVE    | LOAD   | UNLOAD  | RESTORE |
               COMPARE | EXPORT | IMPORT  | FLAGS ]

返回代码: (除了 REG COMPARE)

  0 - 成功
  1 - 失败

要得到有关某个操作的帮助，请键入:

  REG Operation /?

例如:

  REG QUERY /?
  REG ADD /?

**Comment by openBetaa** [comment]
Is it helpful?

**Comment by txthinking** [comment]
The error means: reg command not found in %PATH%
Actually reg is in your %PATH%.
So, please check the wiki, maybe you forgot something:
https://github.com/txthinking/brook/wiki/How-to-use-Brook-Windows-Client%3F

**Comment by openBetaa** [comment]
还是不行，建议后期能记录报错日志的客户端

**Comment by txthinking** [comment]
Do you prefer #105 ?

**Comment by txthinking** [comment]
Let's discuss in #105  please. :)
