### ISSUE TITLE
How abnout to set HTTP proxy by default? 

### ISSUE THREAD

**Issue by hunter-xue** [txthinking/brook#711]
Most of OS support http proxy but not socks5, so we have to run to instances of brook, one for connect to remote server and another one for covert local socks5 to http.

**Comment by heihuhu310** [comment]
I agree with you, i run Brook client CLI as a http server on version 20200701, but when i upgrade to 20200909 the --http flag is removed, so i MUST use socks5tohttp command to do converting. 
i think the reserved http proxy client is a good idea.

**Comment by txthinking** [comment]
The latest GUI client will create both socks5 and http proxy server
