### ISSUE TITLE
iOS client requires iOS >=13. Android client requires Android >=8

### ISSUE THREAD

**Issue by edmundzhong888** [txthinking/brook#712]
Today upgrade my HuaWei M2 mobile device , but the Brook 20200909 version show me the error message at the moment, so , I can't install the APP !

**Comment by txthinking** [comment]
#699

**Comment by poorren** [comment]
hello @txthinking 
If I want to deply on Android 6.0 or elder phones, which tag version is Okay for us? 
I tried v20200502, it seems that the Android apk could be installed correctly. But, the VPN connection is false connected. 

The remote server is installed as follow.
$ curl -L https://github.com/txthinking/brook/releases/download/**v20200502**/brook_linux_amd64 -o /usr/bin/brook
$ chmod +x /usr/bin/brook

then, setup server
$ brook server -l :9999 -p hello

But, when I try to connect to server with global(全局) mode, than whitelist (白名单) mode from Android. The connection seems not work. 

While, I could do it well with latest release version.

**Comment by txthinking** [comment]
Maybe < v20200901. (Sorry, I only have a android 11)
And can't connect, you may test first your server first with cli:
https://github.com/txthinking/brook/issues/575

**Comment by txthinking** [comment]
20210214, feel free to comment if still has problem
