### ISSUE TITLE
how to apply the proxy to a  specific app，not the apply the proxy to all app on a device?

### ISSUE THREAD

**Issue by luuillu** [txthinking/brook#713]
I am Android App Developer, The brook is Very useful for me to capture net package, and then analyze the network status。If the Brook support selecting single app to apply proxy, it will be more  convenient to monitor a  specific app for app developers.
As Android VpnService already support this function, would you please add  this feature in Brook?
Thank you.

**Comment by txthinking** [comment]
bypass all other apps. exclude the one you want to proxy. v20220501

**Comment by luuillu** [comment]
Listen to me. Thank you
Because you warm the four seasons

> bypass all other apps. exclude the one you want to proxy. v20220501
