### ISSUE TITLE
Brook.exe v20200909 can't input ip address and password

### ISSUE THREAD

**Issue by ijustyce** [txthinking/brook#715]
I can't input ip address, Brook.exe will lose response once I type the ip address, I can click the button before type any word, if Ipress any letter then brook.exe will lose response, can't input or click. I already have add brook.exe to white list of antivirus software. And the old version work fine but you know the recent update has breaking change, I should update both client and server.

Thanks for your great work, I use Manjaro Linux most of time, and brook works fine.

**Comment by txthinking** [comment]
Brook.exe tested on English Windows OS with default english input method.
Could you try changing your input method to default English input method?

**Comment by ijustyce** [comment]
Tks again, after change the system laguage and keyboard to English, brook.exe work fine now.
