### ISSUE TITLE
【功能增强】无缝升级brook

### ISSUE THREAD

**Issue by YulinChan** [txthinking/brook#717]
### You may find solutions from the following resources:

* https://github.com/txthinking/brook/wiki
* https://github.com/txthinking/brook/issues
* https://talks.txthinking.com
* https://www.youtube.com/channel/UC5j8-I5Y4lWo4KTa4_0Kx5A

### Please describe step by step any commands and operations you have performed, environment and version:
用nami对brook进行升级前得先停止brook，升级完还得手动再重新执行一遍之前输入的命令，如果开了好几个brook服务的话还挺麻烦的。

能不能在升级的时候自动停止brook服务，升级完成后自动恢复之前的brook服务配置？我看隔壁的v2ray就是这么干的，升级只需要执行安装脚本。

**Comment by txthinking** [comment]
如果brook是通过joker运行的。会支持“无缝升级”。

1. 升级nami
```
nami install nami
```
或
```
nami install github.com/txthinking/nami
```
2. nami install brook
