### ISSUE TITLE
brook.exe not work

### ISSUE THREAD

**Issue by xiaobaiying** [txthinking/brook#718]
I downloaded the brook.exe of ver_20200909 , but after opening it, the page is completely stuck. The same situation exists on other brook.exe versions, only the previous installation package of brook.msi can be used
@txthinking 

![QQ截图20200914144826](https://user-images.githubusercontent.com/37145715/93053270-2555d500-f69a-11ea-9b50-0bdb2c273b86.png)

**Comment by DpangD** [comment]
The same problem...

**Comment by liuxingshine** [comment]
The same problem,my win10 Pro version is 19041.450

**Comment by txthinking** [comment]
Even radio and buttons cannot be clicked?

**Comment by xiaobaiying** [comment]
> Even radio and buttons cannot be clicked?

once click the ip button and prepare to input ip, the App will be stuck immediately.

**Comment by DemoMacro** [comment]
I have a similar problem...

**Comment by txthinking** [comment]
It is tested only in Windows 10 (English version) with default English input method.
Try change input method to the default English input method?

**Comment by xiaobaiying** [comment]
> It is tested only in Windows 10 (English version) with default English input method.
> Try change input method to the default English input method?

it works
