### ISSUE TITLE
iOS14 V20200909 Issue

### ISSUE THREAD

**Issue by xue253** [txthinking/brook#719]
After upgrading to ios14, the connection between the client and the server often drops. I hope the next version supports Chinese.

**Comment by dachoume** [comment]
I have the same problem in ios14,but ios13 was ok.

**Comment by xue253** [comment]
> I have the same problem in ios14,but ios13 was ok.

However, I can't work with ios13.7

**Comment by xue253** [comment]
The new version solves some issues, it is not often disconnected. I'll continue to test.

**Comment by eshibudaoweng** [comment]
the same problem on ios14

**Comment by txthinking** [comment]
Please try latest iOS client :)
