### ISSUE TITLE
Why there is no binary release after v20200801 ？

### ISSUE THREAD

**Issue by BrunuhVille** [txthinking/brook#722]
![image](https://user-images.githubusercontent.com/55394446/94980113-6b93ab00-0559-11eb-934f-850301cd5841.png)
the v20200801 release includes binary file
(number of total files is 32)

![(1W8NPAWDCGHZOQ$_ TTO$N](https://user-images.githubusercontent.com/55394446/94980079-469f3800-0559-11eb-9398-940b9b263ef9.png)
but in v20200909 and v20200909, there is no binary release
(number of total files is 31)

**Comment by txthinking** [comment]
File "brook" == file "brook_linux_amd64"
