### ISSUE TITLE
The windows GUI v20200909 can not work in ipv6,but brook_windows_amd64.exe can work in ipv6.

### ISSUE THREAD

**Issue by herossr** [txthinking/brook#724]
When I use brook in server mode, 
The windows  GUI client v20200909 can not work in ipv6,Microsoft Windows [ver 10.0.18363.1082],
( https://github.com/txthinking/brook/releases/download/v20200909/Brook.exe ),

but the brook_windows_amd64.exe can work in ipv6
(https://github.com/txthinking/brook/releases/download/v20200909/brook_windows_amd64.exe).

**Comment by txthinking** [comment]
It's better If you can provide steps and don't assume others know what you
did.
