### ISSUE TITLE
listen tcp :443: bind: address already in use?

### ISSUE THREAD

**Issue by luckypoem** [txthinking/brook#725]
hi.

root@localhost:~# ./brook_linux_amd64_v20200909 wsserver --domain mydomain.com -p mypassword
2020/10/08 09:48:24 main.go:940: listen tcp :443: bind: address already in use
root@localhost:~#

我服务器的 443端口已被其他程序占用，此命令“./brook_linux_amd64_v20200909 wsserver --domain mydomain.com -p mypassword”如何指定其他端口？

**Comment by McDull-GitHub** [comment]
`./brook_linux_amd64_v20200909 wsserver -l :9999 -p yourpassword`

**Comment by txthinking** [comment]
the auto ssl will be use 80 and 443, if you want to choose other port, use wsserver without domain and put domain to nginx.
