### ISSUE TITLE
Reverse Socks Proxy

### ISSUE THREAD

**Issue by ffcommax** [txthinking/brook#726]
Hi
I want to connect two different local network to each other through socks proxy running on VPS 

Pc1
10.10.10.100
VPS public IP:
20.20.20.20
Pc2:
192.168.1.100

pc1<--->VPS<----pc2

pass pc2 traffic through socks proxy to pc1 local network

how can i do it?
Thank you

**Comment by txthinking** [comment]
I assume I understand you mean. Then:

pc1:
$ brook socks5 --socks5 20.20.20.20:1080

pc1:
Test server: https://github.com/txthinking/httpserver
$ httpserver -l 10.10.10.100:8080

pc2:
pc2 can visit pc1's LAN services
$ curl -x socks5://20.20.20.20:1080 http://10.10.10.100:8080 -v

**Comment by ffcommax** [comment]
yes exactly
but how connect pc1 to VPS server?
on pc1 start socks server then connect to VPS server after that we need access to pc1 network through socks
actually we need a bidirectional connection that pc1 accepts incomming ang outgoing connection

**Comment by txthinking** [comment]
Oh, I understand now.

You want to create an virtual LAN network between two or more devices
through a public vps?

I think this is not available yet. But I have intention to implement this.

**Comment by rokups** [comment]
Since issue was closed, did anything change regarding this feature?

**Comment by txthinking** [comment]
For bidirectional connection, I am building a new product:
https://github.com/zonenetio
