### ISSUE TITLE
IOS V2020090.10.01 affects other application notification push

### ISSUE THREAD

**Issue by xue253** [txthinking/brook#729]
At present, the latest v2020090.10.01 still has problems. The problem is that after connecting, the applications such as WeChat and Alipay can not push notification. Is it necessary to add new routing rules?
At the same time, when I chat on wechat frequently, brook will be cut off for non-human reasons.

**Comment by txthinking** [comment]
iOS?

**Comment by txthinking** [comment]
Apple does not allow using proxy access 17.0.0.0/8.

We added this into
https://github.com/txthinking/bypass/blob/master/chinacidr4.list#L3888

Try to refetch the cidr list.

**Comment by txthinking** [comment]
20210214, feel free to comment if still has problem
