### ISSUE TITLE
20200909 cannt connect

### ISSUE THREAD

**Issue by Hisser** [txthinking/brook#730]
I downloaded the brook.exe of ver_20200909 , but after opening it, but cannt connect ,How to solve it

![image](https://user-images.githubusercontent.com/24617075/97967531-4f08be00-1df8-11eb-8d9c-f4aacb59028b.png)

**Comment by Hisser** [comment]
@txthinking

**Comment by txthinking** [comment]
20210214, feel free to comment if still has problem
