### ISSUE TITLE
How to build brook from source?

### ISSUE THREAD

**Issue by hongyi-zhao** [txthinking/brook#731]
I looked through [the documents of brook](https://txthinking.github.io/brook/) but still can't figure out how to build brook with the source code cloned from github. Any hints will be highly appreciated.

Regards,
HY

**Comment by briteming** [comment]
cd $GOPATH
go get -u -v github.com/txthinking/brook/cli/brook/
等待命令完成，可执行文件brook就会生成在$GOBIN/下。

最好先给git设置http proxy,才运行go get 命令。

**Comment by txthinking** [comment]
see build.sh
