### ISSUE TITLE
Convert a socks5 to a https proxy.

### ISSUE THREAD

**Issue by hongyi-zhao** [txthinking/brook#732]
I noticed that the current brook implementation supports the [socks5tohttp](https://txthinking.github.io/brook/#/brook-socks5tohttp) functionality. But I want to convert a socks5 to a https proxy. Could you please add this feature to brook?

Regards,
HY

**Comment by Hawaii-ol** [comment]
I don't get your point, isn't `socks5tohttp` exactly what you need?

**Comment by txthinking** [comment]
http proxy can proxy https proxy, such as curl -x http://127.0.0.1:8888 https://google.com
what is your use case.

**Comment by hongyi-zhao** [comment]
Thanks for clarifying this. I am just curious and want to know how can I use a real HTTPS proxy when I visit HTTPS sites. As we all know, HTTPS needs a certificate for authentication and data encryption. So, if we browse the HTTPS sites via a real HTTPS proxy, the valid SSL/TLS certificate for the proxy must be deployed properly.

As you told above, the HTTP proxy can be used to access the HTTPS protocol enabled websites, but this approach still lacks the encryption and security features that certificates provide.

**Comment by txthinking** [comment]
If the http proxy created by brook(brook server etc, brook client etc, brook socks5tohttp), then don't worry, data is strong encrypted two times over the internet.
