### ISSUE TITLE
write udp [Server_IP]:56040->[DNS_IP]:53: write: operation not permitted

### ISSUE THREAD

**Issue by chwilley** [txthinking/brook#74]
在服务端配置 iptables 的 OUTPUT 规则时，根据  iptables log 的提示，对 udp 协议、dport=53 放行。
从客户端连接 brook 服务时，在服务端出现以下提示：
write udp [Server_IP]:56040->8.8.8.8:53: write: operation not permitted

当服务端对  OUTPUT 规则全部放行时，以上提示消失，同时 brook 能正常工作。

**Comment by txthinking** [comment]
Chain output should accept any UDP.
Because server will send data to client port(dynamic)
