### ISSUE TITLE
Creating PAC from CIDR input

### ISSUE THREAD

**Issue by nickaein** [txthinking/brook#744]
I'm trying to create a PAC file from a customized CIDR list with following command [as demonstrated here](https://github.com/txthinking/blackwhite/blob/master/build.sh):

```
./brook_linux_amd64 pac -p 'SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080; DIRECT' -m black -c cidr.txt -f black.pac
```

and I get the following error:

```
2021/01/28 18:17:34 main.go:928: flag provided but not defined: -m
```

Even after omitting `-m` flag, `brook` doesn't recognize the `-c` flag either. Are these flags removed from the recent versions?

I'm using Brook version 20210101 for linux_amd64 downloaded from [latest release](https://github.com/txthinking/brook/releases/tag/v20210101).

**Comment by txthinking** [comment]
20210214, feel free to comment if still has problem
