### ISSUE TITLE
brook socks5 bug

### ISSUE THREAD

**Issue by dksslq** [txthinking/brook#745]
即使指定了 --socks5 127.0.0.1:1080，brook依然监听0.0.0.0:1080

![image](https://user-images.githubusercontent.com/21374813/106346858-0f694980-62f5-11eb-9dd5-cf4f7110935f.png)

**Comment by txthinking** [comment]
因为socks5需要明确指定server的IP(不然无法响应UDP请求), 所以运行的命令者需要告诉命令.

之前的版本socks5相关命令要求分别指定 监听地址(IP:PORT) 和 socks5服务器IP
因为监听IP不一定是socks5的服务器IP(比如云的外挂IP, 你无法监听监听外挂IP, 而实际上), 这也是之前有issue提到为什么需要需要单独指定IP.

因此新版socks5相关命令, 则简化了, --socks5 后面就是你最终要使用的socks5 server

**Comment by dksslq** [comment]
so, Is there a way to specify socks5 bind addr? xd

**Comment by txthinking** [comment]
20210214

**Comment by Handsome1080P** [comment]
so, Is there a way to specify socks5 bind addr? xd

**Comment by txthinking** [comment]
![image](https://user-images.githubusercontent.com/1241807/120415584-63149e00-c38e-11eb-9304-0ef43f61074e.png)

**Comment by Handsome1080P** [comment]
How brook client to socks5 bind a special IP?

**Comment by txthinking** [comment]
Please create a new issue for that command. Thx.
