### ISSUE TITLE
Some systems bar color are same as Brook's

### ISSUE THREAD

**Issue by pinkolt** [txthinking/brook#75]
#### Describe actual behavior
win10打开客户端只有Brook.exe进程无法配置
#### What is your expected behavior
服务器端已经配置好，手机客户端已经可以访问，但是下载打开win客户端只有Brook.exe进程，无法配置地址密码信息。
#### Specifications like the version of the project, operating system, or hardware
WIN10 64位 BROOK WINDOWS GUI CLIENT
#### Steps to reproduce the problem
0.
1.
2.

**Comment by Rpeiol** [comment]
只能等，等个大概十分钟才行

**Comment by txthinking** [comment]
@pinkolt  What happened when you click `Setting`?

**Comment by txthinking** [comment]
This wiki may be helpful:
https://github.com/txthinking/brook/wiki/How-to-use-Brook-Windows-Client%3F

**Comment by pinkolt** [comment]
看了wiki说明说任务栏有图标，找到原因了，任务栏是黑色的，brook图标也是黑色的，导致像没有一样，点击后已经配置好。
请关闭，谢谢。

**Comment by txthinking** [comment]
Fixed in v20171113
