### ISSUE TITLE
Android apk cannot copy and paste server information

### ISSUE THREAD

**Issue by htmlrust** [txthinking/brook#752]
### You may find solutions from the following resources:

* https://github.com/txthinking/brook/wiki
* https://github.com/txthinking/brook/issues
* https://talks.txthinking.com
* https://www.youtube.com/channel/UC5j8-I5Y4lWo4KTa4_0Kx5A

### Please describe step by step any commands and operations you have performed, environment and version:
Android 11
Install brook apk from github
Copy text
Open the software
Try to paste
Can't paste

**Comment by txthinking** [comment]
20210214
