### ISSUE TITLE
新版20210214windows客户端win10系统无法打开

### ISSUE THREAD

**Issue by d4rkblue** [txthinking/brook#757]
### You may find solutions from the following resources:

* https://github.com/txthinking/brook/wiki
* https://github.com/txthinking/brook/issues
* https://talks.txthinking.com
* https://www.youtube.com/channel/UC5j8-I5Y4lWo4KTa4_0Kx5A

### Please describe step by step any commands and operations you have performed, environment and version:
环境: Win10TLSC版 版本：20210214
客户端brook_windows_amd64.exe
表现为：窗口闪现一下就消失了。测试了三台电脑均为此情况，应该是客户端的问题。

**Comment by txthinking** [comment]
你下载的这个是 cli 文件
gui 是 .msi

如果不了解cli和gui的概念 可以看下文档

**Comment by txthinking** [comment]
https://txthinking.github.io/brook/#/zh-cn/?id=brook%e7%9a%84cli%e6%96%87%e4%bb%b6%e5%92%8cgui%e6%96%87%e4%bb%b6
