### ISSUE TITLE
最新的windows安装程序安装完成之后没有生成快捷图标

### ISSUE THREAD

**Issue by killgcd4ever** [txthinking/brook#762]
### You may find solutions from the following resources:

* https://github.com/txthinking/brook/wiki
* https://github.com/txthinking/brook/issues
* https://talks.txthinking.com
* https://www.youtube.com/channel/UC5j8-I5Y4lWo4KTa4_0Kx5A

### Please describe step by step any commands and operations you have performed, environment and version:

看了文档，好像是有意这么设计的？但是我记得以前.msi安装程序会生产啊，为啥现在就不行了？安装完之后连搜索都找不到，当时还以为没有安装成功，傻傻得执行了好几遍安装程序，后面去控制面板看了已经存在了。
没有快捷方式就算了，好歹做个图标出来吧，光秃秃的一个默认程序图标很难看啊

**Comment by txthinking** [comment]
BrookLite.exe

**Comment by Jekyllew** [comment]
快捷方式可以设置在属性编辑图标，安装目录里有icon图片。

**Comment by txthinking** [comment]
试试 https://github.com/txthinking/brook/releases/download/v20210214/Brook.exe

**Comment by txthinking** [comment]
v20210401
