### ISSUE TITLE
Windows10安转不了Brook.msi

### ISSUE THREAD

**Issue by iamyinweijianGH** [txthinking/brook#763]
### Please read the document first

* https://txthinking.github.io/brook/

### Please describe step by step any commands and operations you have performed, environment and version: v20210214
一闪而过，我大意了

**Comment by htmlrust** [comment]
Brook Windows 图形客户端, 安装后并不会自动创建桌面快捷方式, 可以在C:\Program Files (x86)或C:\Program Files里找到

**Comment by iamyinweijianGH** [comment]
好家伙，我直接号家伙，真会藏，我喜欢
