### ISSUE TITLE
socks5 to brook

### ISSUE THREAD

**Issue by htmlrust** [txthinking/brook#764]
### Please read the document first

* https://txthinking.github.io/brook/

### Please describe step by step any commands and operations you have performed, environment and version:
I want to use the socks5 proxy as the front proxy of brook server, that is
I have a socks5 proxy, I want to use brook server proxy as the server to forward the data of socks5 proxy.

**Comment by txthinking** [comment]
Why don't use `socks5(created by brook client) -> brook client -> brook server`?
