### ISSUE TITLE
msi服务器只有添加没有删除功能

### ISSUE THREAD

**Issue by htmlrust** [txthinking/brook#765]
### Please read the document first

* https://txthinking.github.io/brook/

### Please describe step by step any commands and operations you have performed, environment and version:
msi服务器只有添加没有删除功能

**Comment by txthinking** [comment]
服务器列表-点其中一个右边的眼睛-详情页最下面有个flat删除按钮吧

**Comment by htmlrust** [comment]
有了，比较难找，谢谢
