### ISSUE TITLE
建议可以实现 动态修改Brook账号信息 或 托盘菜单中加入 Restart 选项以重启 快速更换Brook账号信息，另外希望添加客户端错误日志功能

### ISSUE THREAD

**Issue by ToyoDAdoubi** [txthinking/brook#77]
1. 今天在更新Brook一键脚本的时候，因为需要频繁测试，所以需要来回更换 Brook账号信息，然后发现了这点很麻烦的事情，所以希望作者实现 动态修改Brook账号信息（这样最好），如果暂时不行，那么就在托盘菜单中加入 Restart 选项(或 Reload选项)来重启以快速更换Brook账号配置。
2. 希望添加 客户端（Windows）错误日志输出功能，以便更好的排除客户端运行后无法使用的原因。

哈，前几天作者更新了 v20171111 版本后，我就更新了一遍我写的 服务端手动教程、客户端使用教程 以及 Brook一键管理脚本（支持多端口和更换协议）
脚本：https://doub.io/brook-jc3/

更新时没事试了试，发现新版本的Brook协议速度很快，于是就在我网站安利了。通过我的文章传播后，最近使用Brook的人增多了不少，很多人都反映 Brook新协议很快呢。感谢作者的辛苦 :)

**Comment by txthinking** [comment]
首先感谢阁下的对大家帮助的教程

**Comment by anzhengru** [comment]
逛git都能遇到doubi....不过brook在我阿里云香港vps上测试确实brook比其他的s5代理快很多，感谢作者！

**Comment by txthinking** [comment]
I just close this. If request too, reopen it.
