### ISSUE TITLE
请问能否通过 wsserver 来实现 map、dns 等功能？

### ISSUE THREAD

**Issue by Herbert8** [txthinking/brook#778]
`wsserver` + `wsclient` 的组合非常方便，对于通过防火墙或者只能通过 Nginx 反向代理提供服务的场景非常方便。但是这种方式目前好像没有 `server` 功能那么完整，只支持创建本地代理，而没办法实现 `brook map` 和 `brook dns` 这样的功能。请问能否实现？

**Comment by txthinking** [comment]
有空了加上

**Comment by txthinking** [comment]
v20210601
