### ISSUE TITLE
The pac command did not split successfully

### ISSUE THREAD

**Issue by htmlrust** [txthinking/brook#779]
Three txt files used

https://txthinking.github.io/bypass/chinadomain.txt
https://txthinking.github.io/bypass/chinacidr4.txt
https://txthinking.github.io/bypass/chinacidr6.txt

`./brook_linux_arm64 pac -listen 127.0.0.0:1980 -proxy "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080;HTTP 127.0.0.1:1081; DIRECT" -bypassDomainList chinacidr4.list chinacidr6.list chinadomain.list`

Then I visit the domestic ip138.com, the foreign ip displayed, and the foreign ip search website, the foreign ip is displayed, it only has the proxy function, and the domain name whitelist is not effective.

**Comment by txthinking** [comment]
`127.0.0.0`?

---

```
brook pac -listen 127.0.0.1:1980 -proxy "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080;HTTP 127.0.0.1:1081; DIRECT" -bypassDomainList https://txthinking.github.io/bypass/chinadomain.txt
```

---

```
curl https://txthinking.github.io/bypass/chinadomain.txt -o chinadomain.txt
brook pac -listen 127.0.0.1:1980 -proxy "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080;HTTP 127.0.0.1:1081; DIRECT" -bypassDomainList ./chinadomain.txt
```

---

maybe I forgot to add `--bypassCIDR4List` parameter, because SOCKS5 and HTTP proxy will use remote dns server, and IP host is rare?

**Comment by htmlrust** [comment]
> `127.0.0.0`?
> 
> ```
> brook pac --listen 127.0.0.1:1980 --proxy "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080;HTTP 127.0.0.1:1081; DIRECT" --bypassDomainList https://txthinking.github.io/bypass/chinadomain.txt
> ```
> 
> ```
> curl https://txthinking.github.io/bypass/chinadomain.txt -o chinadomain.txt
> brook pac --listen 127.0.0.1:1980 --proxy "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080;HTTP 127.0.0.1:1081; DIRECT" --bypassDomainList ./chinadomain.txt
> ```
> 
> maybe I forgot to add `--bypassCIDR4List` parameter, because SOCKS5 and HTTP proxy will use remote dns server, and IP host is rare?

https://github.com/txthinking/bypass/blob/master/china.pac
I see an example of ip in your pac, it seems that ip needs to be escaped?

127.0.0.0 is a mistake I filled in, it turned out to be a private public ip

**Comment by txthinking** [comment]
That are some LAN CIDRs

**Comment by htmlrust** [comment]
Similar to the ip address of [1729798144,1729799167], it seems to be another way of expressing IPV4, I checked it looks like it is a public network ip

**Comment by txthinking** [comment]
Yes, the latest `brook pac` removed --bypassCIDRList parameter, so it
will not generate CIDR decimal.
Because I think most hosts are domains, maybe I should add it back?

**Comment by htmlrust** [comment]
I want my remote vps not to visit websites and ips within China, so as to prevent being blocked. There are also ip forms for websites in China. However, the correct query method is to resolve ip through domain name, and then whether the match is within the range of ip, perform whitelist without proxy, can pac implement domain name resolution and then match ip whitelist without proxy?

**Comment by txthinking** [comment]
It cannot meet your requirements?
```
brook pac --listen 127.0.0.1:1980 --proxy "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080;HTTP 127.0.0.1:1081; DIRECT" --bypassDomainList https://txthinking.github.io/bypass/chinadomain.txt
```

**Comment by htmlrust** [comment]
For example, gsxt.gdgs.gov.cn is a website in China, but not in Chinadomain. If I use a foreign ip to visit a website in China, it may cause the foreign vps ip to be recorded by the Chinese website.

**Comment by txthinking** [comment]
https://github.com/txthinking/bypass/blob/master/chinadomain.txt#L3209

all subdomains of `cn` will be bypassed, such as `*.cn`, `*.*.cn`, ...

**Comment by txthinking** [comment]
you can test it with https://chrome.google.com/webstore/detail/ipvbar/copjmgogifdfjkaenpallapiidcpkjbm
If it show your proxy ip then it is proxies, otherwise it is bypassed.

**Comment by htmlrust** [comment]
Thank you very much, the domain name is enough to meet my needs.

**Comment by txthinking** [comment]
Sounds great. 🎉
