### ISSUE TITLE
latest GUI on win, mac and android does not exist.

### ISSUE THREAD

**Issue by mikelxk** [txthinking/brook#784]
### Please read the document first

* https://txthinking.github.io/brook/

### Please describe step by step any commands and operations you have performed, environment and version:

The released of 20210401 doesn't contain the GUI of win, mac and android.
https://github.com/txthinking/brook/releases/download/v20210401/Brook.dmg
https://github.com/txthinking/brook/releases/download/v20210401/Brook.exe
https://github.com/txthinking/brook/releases/download/v20210401/Brook.apk
Those links appear to be 404.

**Comment by mikelxk** [comment]
The brook.exe seems to be 20210401.
The brookLite.exe still seem to be an old build.
![image](https://user-images.githubusercontent.com/32220948/113156673-c853f200-926c-11eb-8db8-e7f7f4c3155d.png)
And whenever I tried to connect it shows
![image](https://user-images.githubusercontent.com/32220948/113156783-e6b9ed80-926c-11eb-81d6-c9ce9b5510ee.png)
That bug didn't occur on Brook.exe on windows 10.

**Comment by txthinking** [comment]
It looks like browser cache, could you try disable cache and refresh the page?

![image](https://user-images.githubusercontent.com/1241807/113158593-83c95600-926e-11eb-8984-6bc9561679ec.png)

**Comment by mikelxk** [comment]
Disable the cache did work! 👍
