### ISSUE TITLE
Why not http(s) proxies ?

### ISSUE THREAD

**Issue by hammerfunctor** [txthinking/brook#786]
### Please read the document first

* https://txthinking.github.io/brook/

### Please describe step by step any commands and operations you have performed, environment and version:
I found in history issues that `Brook` doesn't support http(s) proxies is not supported at present. But why? Many softwares ( both graphical and terminal ) cannot utilize socks, and one more tool to forward http to socks is sometimes annoying.

**Comment by McDull-GitHub** [comment]
`brook socks5tohttp`?

**Comment by McDull-GitHub** [comment]
![image](https://user-images.githubusercontent.com/30206217/113388628-2a257080-93c1-11eb-84ec-09842f78ee3e.png)
Done!

**Comment by hammerfunctor** [comment]
That's awesome! Thank you.
BTW, I find another way to get over this. I previously use Clash and proxies provided by the merchant. Just adding a little more lines in clash config files, like:
```yaml
- name: <server name or something else>
  type: socks5
  server: 127.0.0.1
  port: <port>
```
this allows fine-tune control on flow by utilizing the power of clash.

**Comment by txthinking** [comment]
It does.

[Drawer] - Proxy & Tun
