### ISSUE TITLE
wssserver not working

### ISSUE THREAD

**Issue by PRNDA** [txthinking/brook#789]
/opt/brook//brook wssserver --domain mydomain.ltd --password hello 
2021/04/06 12:13:33 http: TLS handshake error from 1.2.3.4:53014: acme/autocert: unable to satisfy "https://acme-v02.api.letsencrypt.org/acme/authz-v3/12129049210" for domain "mydomain.ltd": no viable challenge type found
2021/04/06 12:13:39 http: TLS handshake error from 6.7.8.9:44011: acme/autocert: missing certificate
2021/04/06 12:13:39 http: TLS handshake error from 6.7.8.9:44012: acme/autocert: missing certificate
2021/04/06 12:13:40 http: TLS handshake error from 6.7.8.9:44013: acme/autocert: missing certificate
2021/04/06 12:13:40 http: TLS handshake error from 6.7.8.9:44014: acme/autocert: missing certificate
2021/04/06 12:13:41 http: TLS handshake error from 6.7.8.9:44015: acme/autocert: missing certificate
2021/04/06 12:13:41 http: TLS handshake error from 6.7.8.9:44017: acme/autocert: missing certificate
2021/04/06 12:13:41 http: TLS handshake error from 6.7.8.9:44018: acme/autocert: missing certificate
2021/04/06 12:13:41 http: TLS handshake error from 6.7.8.9:44016: acme/autocert: missing certificate
2021/04/06 12:13:41 http: TLS handshake error from 6.7.8.9:44019: acme/autocert: missing certificate

(for privacy reason, actual domain and ip addresses are replaced by a fake one)

**Comment by txthinking** [comment]
Did you config A or AAAA record of your domain?

**Comment by PRNDA** [comment]
> Did you config A or AAAA record of your domain?

of cause i did, 100% sure, I can also connect to 443 port by running `telnet mydomain.tld 443`

**Comment by txthinking** [comment]
Do you use cloudflare dns like this issue https://github.com/golang/go/issues/37489 ?

**Comment by PRNDA** [comment]
> Do you use cloudflare dns like this issue [golang/go#37489](https://github.com/golang/go/issues/37489) ?

no, i'm not using cloudflare, i'm just create an A record pointing to my ip.

you see, this error,  `http: TLS handshake error from 6.7.8.9:44019: acme/autocert: missing certificate` indicating that, the an authorization request from let's encrypt is reached to this server.

**Comment by txthinking** [comment]
How about this `curl https://youdomain.com -v`

**Comment by PRNDA** [comment]
i got this output:

```
* Rebuilt URL to: https://mydomain.ltd/
*   Trying 1.2.3.4...
* TCP_NODELAY set
* Connected to mydomain.ltd (1.2.3.4) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS alert, Server hello (2):
* error:14004438:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert internal error
* stopped the pause stream!
* Closing connection 0
curl: (35) error:14004438:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert internal error

```

**Comment by txthinking** [comment]
Maybe your port 80 or 443 is occupied by other programs

**Comment by PRNDA** [comment]
> Maybe your port 80 or 443 is occupied by other programs
> 
> with root user run `lsof -i :80` and `lsof -i :443`

oh man! you saved my day!

443 is using by brook that's ok, but 80 is using by docker! holly shit.......

**Comment by txthinking** [comment]
Glad to help you. This is a question, I will move it to Discussions
