### ISSUE TITLE
Mac系统

### ISSUE THREAD

**Issue by ywx1983cn** [txthinking/brook#79]
启动要多次填写密码，不能记住密码。
看腾讯视频发现地区受限，变成全局代理了。
希望能添加pac全局切换功能。

**Comment by txthinking** [comment]
Can you show that video link?

**Comment by txthinking** [comment]
Mac客户端用的这个白名单 https://github.com/txthinking/pac/blob/master/white.list

我看了一个冈仁波齐 https://v.qq.com/x/cover/w3ieh3f84a1kjqb.html 没有问题。
请检查是否有其他软件，或其他设置。

请参考wiki：
https://github.com/txthinking/brook/wiki/How-to-use-Brook-MacOS-Client%3F

仍有问题，请重新打开此issue，提供具体视频地址
