### ISSUE TITLE
Not able to download the lastest version v20210401, but fine with the earlier.

### ISSUE THREAD

**Issue by Lancelearner** [txthinking/brook#791]
### Please read the document first

* https://txthinking.github.io/brook/

### Please describe step by step any commands and operations you have performed, environment and version:

Hello, Dalao,

I'm a new beginner. Today I wanna upgrade the version for server end, it gives the following feedbacks.

------------------------------
请输入数字 [0-10]:2
请输入要下载安装的 Brook 版本号 [ 格式是日期，例如: v20180707 ]
版本列表请去这里获取：[ https://github.com/txthinking/brook/releases ]
直接回车即自动获取:v20210401
[信息] 开始下载 Brook [ v20210401 ] 版本！
[信息] 发现 Brook 已有新版本 [ v20210401 ]，旧版本 [ v20200801 ]
是否更新 ? [Y/n] :y
--2021-04-08 22:00:05--  https://github.com/txthinking/brook/releases/download/v20210401/brook
Resolving github.com (github.com)... 192.30.255.112
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-04-08 22:00:05 ERROR 404: Not Found.

[错误] Brook 下载失败 !

----------------------------

It's weied because I could download v20200801 by manually input the version number, also It's the one I'm using instead.
As I understand, there're not much difference between these URLs.
https://github.com/txthinking/brook/releases/download/v20210401/brook
https://github.com/txthinking/brook/releases/download/v20200801/brook

Anyone else got similar issue? Don't know it's a network issue or ?

Hope you could have a look on this post , thank you in advance.

**Comment by txthinking** [comment]
参考 https://brook-community.github.io/script/
