### ISSUE TITLE
Is it  a lifetime free software?

### ISSUE THREAD

**Issue by mygardenfield** [txthinking/brook#8]
It is a good software and way better than many other vpn.But is it  a lifetime free software?
I used lantern before ,but it is not free any more and not as stable  as before. And brook is way better than it!!!
thx for your against to gfw!

**Comment by txthinking** [comment]
Yes. Free and GPLv3

**Comment by mygardenfield** [comment]
<3 @txthinking  ,btw my smartphone is android 4.4.4 , is it adapt to Brook ,even if its not android5.0 or higher?

**Comment by txthinking** [comment]
Recommend to use 5.0+, (6.0+/7.0+ is better)
