### ISSUE TITLE
android客户端

### ISSUE THREAD

**Issue by miao-o** [txthinking/brook#80]
1.
11月4日晚部署了Brook，并在安卓客户端测试一切正常，但是一天后客户端连接后无法正常访问，同一vps的SSR正常，查看Brook服务端正常，重启服务客户端仍无法访问网站。11.6早更新了2.6.8可以访问了，但是使用一小时后又发生了之前的情况。
2.安卓客户端存在另外bug，在连接了其他代理软件时打开Brook，会显示停止按钮并且点击会导致应用卡住、掉帧。

**Comment by txthinking** [comment]
Which Type? Brook? Brook Stream? Shadowsocks?

**Comment by txthinking** [comment]
What is 2.6.8?

**Comment by miao-o** [comment]
默认配置，安卓版本20171112

**Comment by txthinking** [comment]
The 1 problem. Does your server is shadowsocks?

**Comment by txthinking** [comment]
2. Yes, for now, android client stop will need 1-60s, for releasing resources. I will add some tips.

**Comment by txthinking** [comment]
1. Please try Brook protocol.
2. Please try Brook Android v20171113.
