### ISSUE TITLE
希望为 socks5tohttp 功能增加指定使用远端 DNS 的参数

### ISSUE THREAD

**Issue by Herbert8** [txthinking/brook#806]
### 现象
在一个 SOCKS5 Server 上，使用 hosts 做了自己的域名和 IP 映射，通过 `curl -x socks5h://` 的方式，可以实现由 SOCKS5 Server 来对自定义域名进行解析。在使用 Privoxy 将 SOCKS5 Proxy 转为 HTTP Proxy 的时候，也有类似配置。
但是 `brook socks5tohttp` 在将 SOCKS5 Proxy 转为 HTTP Proxy 再通过这个 HTTP Proxy 反问的时候，会访问失败，报如下错误：
```html
    <body>
        <h1>Error response</h1>
        <p>Error code: 404</p>
        <p>Message: File not found.</p>
        <p>Error code explanation: HTTPStatus.NOT_FOUND - Nothing matches the given URI.</p>
    </body>
```
### 原因猜测
`brook socks5tohttp` 是否默认使用了本地 DNS，导致在 SOCKS5 Server 上做的自定义域名无法使用。

**Comment by txthinking** [comment]
> 再通过这个 HTTP Proxy 反问的时候

展开下

**Comment by txthinking** [comment]
```
brook client -s xxx -p xxx --socks5 127.0.0.1:1080
brook socks5tohttp -s 127.0.0.1:1080 -l 127.0.0.1:8080
curl -x http://127.0.0.1:8080 https://google.com # 此时dns是由远端解析的
```
