### ISSUE TITLE
socks5tohttp 不能使用远端服务器的 /etc/hosts 配置

### ISSUE THREAD

**Issue by Herbert8** [txthinking/brook#812]
```
brook client -s xxx -p xxx --socks5 127.0.0.1:1080
brook socks5tohttp -s 127.0.0.1:1080 -l 127.0.0.1:8080
curl -x http://127.0.0.1:8080 https://google.com # 此时dns是由远端解析的
```

_Originally posted by @txthinking in https://github.com/txthinking/brook/issues/806#issuecomment-846507128_

这种方式的确可以使用远端服务器的 DNS，但是不能识别 /etc/hosts 中的自定义域名与 IP 的映射。Privoxy 通过 forward-socks5 将 SOCKS5 代理转为 HTTP 代理就没这个问题。

**Comment by txthinking** [comment]
远端的host？
