### ISSUE TITLE
Windows: tun mode: Active code page: 65001 The object already exists.

### ISSUE THREAD

**Issue by mikelxk** [txthinking/brook#816]
### Please read the document first

* https://txthinking.github.io/brook/

### Please describe step by step any commands and operations you have performed, environment and version:

latest BrookLite.exe tun mode errors out
![image](https://user-images.githubusercontent.com/32220948/120114305-25a6e980-c1b1-11eb-9f65-7a82ed3005ad.png)

**Comment by txthinking** [comment]
如果你之前安装了tap-windows.exe, 它会创建一个网卡 **TAP-Windows Adapter**
![image](https://user-images.githubusercontent.com/1241807/120135059-01272d80-c202-11eb-9b29-9f504de72f16.png)
**新版Brook.exe/BrookLite.exe的tun模式不再依赖这个网卡, 即tun模式不必再额外安装tap-windows.exe**, 可以将其禁掉(或删除卸载?)
![image](https://user-images.githubusercontent.com/1241807/120135154-329ff900-c202-11eb-99ff-b64d36456c5f.png)
![image](https://user-images.githubusercontent.com/1241807/120135176-40ee1500-c202-11eb-9117-ff86bec26b23.png)

**Comment by mikelxk** [comment]
disable did solve the problem
