### ISSUE TITLE
brook因IE浏览器不存在而运行错误

### ISSUE THREAD

**Issue by Alexinst** [txthinking/brook#82]
你好，打扰一下。

因为我不用IE，且IE被我卸载了，
所以打开Brook，设置好账号密码后，点击运行，出现提示[Brook]ie start:exec:"c:\\Program Files\\Internet Explorer\\iexplore.exe":file does not exist 

这该如何处理？必须安装IE吗？
期待作者的答复，非常感谢！

**Comment by txthinking** [comment]
For now: yes. Brook need IE to let proxy take effect.

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/wiki/How-to-use-Brook-Windows-Client%3F

**Comment by Alexinst** [comment]
非常感谢！

**Comment by txthinking** [comment]
You are welcome. 🤒
