### ISSUE TITLE
[Enhancement] Several suggestions for future improvement

### ISSUE THREAD

**Issue by lewisxy** [txthinking/brook#83]
Tested the server on Ubuntu 14.04 LTS with Linux kernel 4.2.0
Client on Windows (GUI), Android (GUI)
Both server and client is the latest version (20171113)

### Server
1. **No config file.** I know Brook is intended to be simple, but a config file will allow users to configure the program in a more structurally systematic way, instead of leaving a long line of command line parameters. (the current version does not have a lot of parameters, but future versions may have)

2. **Limited logs.** As I started the server, there is nothing printed out showing the status of the program. Although I did not encounter any issues during the test, it may be difficult to debug the configuration without adequate information.  

### Clients

3. **VPN mode only Client.** I did not run enough test on clients, but it seems like the windows client is run in VPN mode, or global mode, which means all data are transmitted to the local daemon and then redistributed. It is highly appreciated to develop a mode that listens on a specific port (like ss) and redistribute all data in that port since we don't like global mode in some cases. 

4. **Clear text password display and popup IE window.** Both Android and Windows clients display the password in clear text. This is a minor issue but hope to get fixed soon. When I start and stop the Windows Client, the IE Window was opened and disappeared in a second. I am not sure what it was doing. 

In my test, the connection speed of this program is slightly faster than SSR with auth_chain_a on the same server. It would be appreciated that developers publish document containing the detail schematics of this program (data structure, encryption, etc.)

**Comment by txthinking** [comment]
Thanks for your advice.
1. Now we can write a .sh file, like `echo 'brook server ...' > brookserver.sh`. or run with systemd https://github.com/txthinking/dotfiles/tree/master/brook

2. Yes, it needs more log.

3. Not VPN mode, It listens on 1080 port(socks5), and with this rule: https://github.com/txthinking/pac. Yes, you can use Proxy SwitchyOmega or any other tools to create new rule.

4. About IE #105
