### ISSUE TITLE
iOS 14 VPN connection auto disconnect after screen off

### ISSUE THREAD

**Issue by ookangzheng** [txthinking/brook#834]
### Please read the document first

* https://txthinking.github.io/brook/

### Please describe step by step any commands and operations you have performed, environment and version:

on IOS 14, I found VPN automatically disconnected when using  Brook SOCKS5 and Server method with latest Brook iOS version application.

Any idea?

Thanks

**Comment by txthinking** [comment]
What does this means: `and Server method`

I tested just now it works.

1. On Ubuntu `$ brook socks5 --socks5 public_ip:1080`
2. On Brook iOS
3. choose `socks5 server`
4. type Server : `public_ip:1080`
5. tap Add button
6. tap Connect button on home page.
7. visit https://ipip.ooo

**Comment by txthinking** [comment]
I will moved this to discussions, just comment there.
