### ISSUE TITLE
Brook Android client

### ISSUE THREAD

**Issue by Docop2** [txthinking/brook#836]
Hi
 So very great project, over centos7 i can run wss server and client all connect fine. Putting same info in the android client, it show connection is up. But i cannot get any app to work with the sock5 setting.
 Is removing the password can get access or if a feature option that i haven't put on to enable a proxy system wide ?  I see your video about an app and you select different app. But i do not see this in the lastest brook.apk release.  Thanks in advance

**Comment by txthinking** [comment]
I moved this to discusstions.
