### ISSUE TITLE
can not listen to ipv4 addr

### ISSUE THREAD

**Issue by cpucorecore** [txthinking/brook#838]
nohup ./brook_linux_amd64 server -l 0.0.0.0:6666 -p password &

netstat -nalp |grep -i listen                                                                                                                           [10:56:07]
tcp        0      0 127.0.0.1:26657         0.0.0.0:*               LISTEN      329916/dipd         
tcp        0      0 127.0.0.1:6060          0.0.0.0:*               LISTEN      329916/dipd         
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      392/systemd-resolve 
tcp        0      0 0.0.0.0:5910            0.0.0.0:*               LISTEN      1034/sshd: /usr/sbi 
**tcp6       0      0 :::6666                 :::*                    LISTEN      503207/./brook_linu** 
tcp6       0      0 :::26656                :::*                    LISTEN      329916/dipd

**Comment by txthinking** [comment]
on linux, by default, net.ipv6.bindv6only is 0, so ipv4 packets could also be received from
ipv6 sockets with ipv4-mapped ipv6 address. thus you only need to listen on tcp6 socket
and we can support both ipv4 and ipv6.

https://groups.google.com/g/golang-nuts/c/F5HE7Eqb6iM

If you want to listen on a IP only, just -l THAT_IP:6666

**Comment by cpucorecore** [comment]
> on linux, by default, net.ipv6.bindv6only is 0, so ipv4 packets could also be received from ipv6 sockets with ipv4-mapped ipv6 address. thus you only need to listen on tcp6 socket and we can support both ipv4 and ipv6.
> 
> https://groups.google.com/g/golang-nuts/c/F5HE7Eqb6iM
> 
> If you want to listen on a IP only, just -l THE_IP_ON_INTERFACE:6666

thank you for your reply. i can not explore website on my iphone when brook client connecting to my brook server for serival mouth after updating the client, so i update my brook server as well, but it donest work also. i'll try it out when i have free time
