### ISSUE TITLE
Incorrect Usage: flag provided but not defined: -listen

### ISSUE THREAD

**Issue by kgbook** [txthinking/brook#845]
Brook version: 20210701

start brook as below:
https://github.com/ToyoDAdoubiBackup/doubi/blob/master/service/brook_debian#L57

or run the command directly as below：
```bash
./brook servers --listen :$PORT --password $PASSWD
```

It's ok if using the command  is `brook server`, but not ok if using `brook servers`.

And it's ok with the brook version 20210601 if using `brook servers --listen :$PORT --password $PASSWD`.

Is the command`brook servers` deprecated?

**Comment by txthinking** [comment]
Please use ./brook server --listen :$PORT --password $PASSWD

**Comment by kgbook** [comment]
ok, thanks
