### ISSUE TITLE
the server cannot be resolved, please check the network or switch to another network to try. 

### ISSUE THREAD

**Issue by kgbook** [txthinking/brook#846]
brook version: 20210701
macOS version: macOS Big Sur 11.2.3 (20D91)

The network between the server and the client is ok.
```bash
~ % ping -c 5 $IP 
PING $IP  ($IP ): 56 data bytes
64 bytes from $IP : icmp_seq=0 ttl=50 time=158.631 ms
64 bytes from $IP : icmp_seq=1 ttl=50 time=158.415 ms
64 bytes from $IP : icmp_seq=2 ttl=50 time=158.425 ms
64 bytes from $IP : icmp_seq=3 ttl=50 time=159.038 ms
64 bytes from $IP : icmp_seq=4 ttl=50 time=159.929 ms

--- $IP  ping statistics ---
5 packets transmitted, 5 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 158.415/158.888/159.929/0.568 ms
```

network state on server:
```bash
netstat -na | grep $PORT
tcp6       0      0 :::$PORT                 :::*                    LISTEN     
udp6       0      0 :::$PORT                 :::*                          
```

And the brook server is running with no error.
```bash
ps -ef | grep brook | grep -v grep | grep -v init.d
root       536   526  0 22:58 ?        00:00:00 ./brook server --listen :$PORT --password $PASSWD
```

brook (or *webview_darwin_amd64*?) prompt as bellow:
> Encountered an accident
>
> the server cannot be resolved, please check the network or switch to another network to try.

However, Brook 20210601 works well.

After I upgraded to 20210701, brook did not prompt me do firework setting, and the firework setting were not changed.

**Comment by txthinking** [comment]
Some questions:

1. Does your network is IPv4 Only / IPv6 only / IPv4&IPv6?
2. Does your brook server you typed on the GUI is `domain:port` / `v4ip:port` / `[v6ip]:port`?
3. If your brook server is `domain:port`, does your domain has A record / AAAA record / A&AAAA records?
4. Can your network successfully access https://api-ipv4.ip.sb/ip ?
5. Can your network successfully access https://api-ipv6.ip.sb/ip ?

**Comment by kgbook** [comment]
> Some questions:
> 
> 1. Your network is IPv4 Only / IPv6 only / IPv4&IPv6?
> 2. Your brook server you typed on the GUI  is`domain:port` / `v4ip:port` / `[v6ip]:port`?
> 3. If your brook server is `domain:port`, does your domain have A record / AAAA record / A&AAAA records?
> 4. If your brook server is `domain:port` and has A record, can your network successfully get IP via `dig -t A domain`
> 5. If your brook server is `domain:port` and has AAAA record, can your network successfully get IP via `dig -t AAAA domain`
> 6. Can your network successfully access https://api-ipv4.ip.sb/ip ?
> 7. Can your network successfully access https://api-ipv6.ip.sb/ip ?

Answer:
1. IPv4 Only;
2. v4ip:port
3. v4ip:port
4. v4ip:port
5. v4ip:port
6. yes
7. no

Additions:
brook on iOS could communicate with server without any issue, the version is 20210601. 
And the iOS client and the macOS client are in the same subnet.
Only my mac upgrade the latest version.

**Comment by kgbook** [comment]
wow, it's ok now.
The only thing i did was power on the mac again after I came back home.
