### ISSUE TITLE
v20210701 can't work

### ISSUE THREAD

**Issue by xue253** [txthinking/brook#854]
The IOS and MAC client of v20210701 can't work normally, and IOS can't go back to the old version.

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/discussions/755

https://github.com/brook-community/howtoask

**Comment by txthinking** [comment]
I tested it works. Please provide detailed information to reproduce, I will move it to the [Discusstions](https://github.com/txthinking/brook/discussions) before  making sure it's a bug
