### ISSUE TITLE
What is the difference between 2 protocols

### ISSUE THREAD

**Issue by smkweed** [txthinking/brook#86]
Is brookstream for streaming like YouTube?

**Comment by antmak** [comment]
I join the question. What is the difference between a stream and a non-stream mode?

**Comment by txthinking** [comment]
Stream mode uses stream cypher: https://en.wikipedia.org/wiki/Stream_cipher
Non-stream mode uses block cypher:
https://en.wikipedia.org/wiki/Block_cipher

Brook non-stream is more difficult to identify for now.
