### ISSUE TITLE
提示  no  such  file  or  directory

### ISSUE THREAD

**Issue by steel0613** [txthinking/brook#864]
### Please read the document first

* https://txthinking.github.io/brook/

### Please describe step by step any commands and operations you have performed, environment and version:
输入这段  https://github.com/txthinking/brook/releases/download/v20210101/brook_linux_amd64
提示提示  no  such  file  or  directory，哪个地方不对吗？有没有知道的朋友指点一下怎么解决

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/discussions/categories/video-show-%E8%A7%86%E9%A2%91%E6%BC%94%E7%A4%BA
