### ISSUE TITLE
服务器监听端口只能是四位数子吗?

### ISSUE THREAD

**Issue by Aquarian-Age** [txthinking/brook#869]
### Please read the document first

* https://txthinking.github.io/brook/
如题所述 不能把监听端口改为五位数字吗?

**Comment by txthinking** [comment]
> 服务器监听端口只能是四位数子吗?

不是`只能`

> 不能把监听端口改为五位数字吗?

能

**Comment by txthinking** [comment]
https://github.com/txthinking/brook/discussions/categories/q-a-%E9%97%AE%E7%AD%94
