### ISSUE TITLE
Brook on Mac with Tun mode DNS lookup failed in terminal

### ISSUE THREAD

**Issue by ookangzheng** [txthinking/brook#872]
### Please read the document first

* https://txthinking.github.io/brook/

### Please describe step by step any commands and operations you have performed, environment and version:
I use brook server on Debian and Client (Mac, tun mode).

When I do `dig google.com`, as my Mac (v11.5) DNS server is set to `94.140.14.14` as upstream, it returns a robust record.

![Screen Shot 2021-07-28 at 19 18 52](https://user-images.githubusercontent.com/6301735/127314320-1d0cfeaa-6e27-4ae4-822a-fa410a5c4cc2.png)

![Screen Shot 2021-07-28 at 19 23 01](https://user-images.githubusercontent.com/6301735/127314453-ca291098-81e4-4e4c-bab3-41375a4540be.png)

![Screen Shot 2021-07-28 at 19 22 54](https://user-images.githubusercontent.com/6301735/127314458-831292fb-17de-40f6-8544-b807fa72f077.png)

**Comment by txthinking** [comment]
What does 'it returns a robust record.' mean?

If your doubt is 240.0.4.63 is not google's IP, just change fakedns off.

**Comment by ookangzheng** [comment]
IP `240.0.4.63` is reserved for local network. And `fakedns` is off too.
It should return a valid `google.com` IP address.

> What does 'it returns a robust record.' mean? If your doubt is 240.0.4.63 is not google's IP, just change fakedns off.

**Comment by txthinking** [comment]
> IP `240.0.4.63` is reserved for local network. And `fakedns` is off too.

Disconnect and reconnect.

> It should return a valid `google.com` IP address. When I disconnect brook VPN, everything works perfectly on terminal
> 
> > What does 'it returns a robust record.' mean? If your doubt is 240.0.4.63 is not google's IP, just change fakedns off.
