### ISSUE TITLE
tproxy体验不是很好！

### ISSUE THREAD

**Issue by AlexanderZhan** [txthinking/brook#884]
体验了一下午，
想不明白tproxy模式下，
DNS绕过名单的原理，
后面看了代码才明白，
国内的流量也代理了，

体验不是很好，
这个名单能不能反过来，
比如建个海外的名单，
国内正常的流量不管，
被墙的走代理，
dns解析出来丢ipset里。

**Comment by diduweiwu** [comment]
首先,配置确实非常方便,非常赞~~
或者可以加个feature,如果流量不通,再尝试去代理.现在开了以后,阿里云盘用不了....

**Comment by txthinking** [comment]
--bypass 掉它的相关域名和ip

**Comment by txthinking** [comment]
另外 自动学习不通的 缓存住不能连通的列表 也是个好提议

**Comment by txthinking** [comment]
https://talks.txthinking.com/articles/brook.article
