### ISSUE TITLE
My network support IPV6 ,but Brook said no!

### ISSUE THREAD

**Issue by BohanRen** [txthinking/brook#890]
### Please read the document first

* https://txthinking.github.io/brook/

### Please describe step by step any commands and operations you have performed, environment and version:
![QQ截图20210901164311](https://user-images.githubusercontent.com/23572936/131641282-bd61ce66-c55d-4115-9ef0-5c1f8be18a96.png)
![QQ截图20210901164327](https://user-images.githubusercontent.com/23572936/131641287-6a6b4371-2514-41e3-a4d8-3b1e9478ac31.png)
![QQ截图20210901164618](https://user-images.githubusercontent.com/23572936/131641291-a1ef7a2f-526b-462b-835a-f0252f869179.png)

**Comment by txthinking** [comment]
Are you using tun mode?

**Comment by txthinking** [comment]
try CLI or wait #898
