### ISSUE TITLE
brook client可以针对tcp和udp分别连接不同ip:port的server

### ISSUE THREAD

**Issue by luxi78** [txthinking/brook#894]
因为众所周知的原因，国内部分地区访问海外的tcp流量相对udp而言更容易被阻隔，因此需要套用如 kcptun等工具实现tcp over udp。

但这样做会导致brook client 连接的tcp和udp不在同一个ip:port上，而brook client目前并不支持这样的设置。故提出这样的一个需求，望txthinking大佬考虑考虑，感谢

**Comment by txthinking** [comment]
如果不是暴力发包UDP应该更容易丢，可能不同地区现象不同吧

目前：
brook server: tcp over tcp, udp over tcp
brook wsserver/wssserver: tcp over tcp, udp over tcp

后期考虑会QUIC(UDP): tcp over quic, udp over udp
