### ISSUE TITLE
Windows GUI client IPv6 support

### ISSUE THREAD

**Issue by ghost** [txthinking/brook#898]
### Please read the document first

* https://txthinking.github.io/brook/

### Please describe step by step any commands and operations you have performed, environment and version:

![image](https://user-images.githubusercontent.com/93597222/139861631-bf83e2f3-7173-4210-9341-f46da83113fb.png)
无法在Windows 10 专业版21H1中使用windows的图形客户端连接到IPv6的brook server(尝试过brook wsserver和brook server,tun和proxy模式都不可以),命令行客户端可以正常连接使用

**Comment by txthinking** [comment]
Yes, Windows GUI client for IPv6 still need some work

**Comment by txthinking** [comment]
v20220406 GUI and IPv6

- Windows proxy mode: Yes
- Windows tun mode: need you configure route manually? (需要手动配置路由表?)

**Comment by txthinking** [comment]
不更新版本号了。

可以重新下载下 https://github.com/txthinking/brook/releases/download/v20220406/Brook.exe

- tun 模式已支持 IPv6 server
- tun 模式已支持 bypass 列表
- tun 模式实际接收v4 ip，但可以从ipv6 server出
- 当然可以开启fakeDNS，这样域名会从server解析
- 若要开启fakeDNS，记得【不要】把 10.0.0.0/8 bypass掉。如果使用的是 https://txthinking.github.io/bypass/china_cidr4.txt ，以前列表里有这个段，现在已经去掉了，可以直接重新fetch下

**Comment by txthinking** [comment]
不行就把 windows ipv6 关了，没发现如何控制先走v4 IP
