### ISSUE TITLE
listen tcp :1093: an attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by HIDE-r** [txthinking/brook#899]
我在Windows平台上，连接的时候总是发生
![image](https://user-images.githubusercontent.com/51672711/140633689-f4ddb6d4-46ce-4a74-822d-a8eb5d7f0b53.png)
我查端口也没看到这个端口被占用。
![image](https://user-images.githubusercontent.com/51672711/140633729-265cd3df-31d3-4841-a748-8be6f462682f.png)
怎么解决这个问题呢？

感觉我在enable WSL之前没出现这个问题，昨天刚弄了一下WSL， 不知道会不会有关系

**Comment by txthinking** [comment]
https://www.google.com/search?q=-baidu%20isten+tcp+%3A%3A+an+attempt+was+made+to+access+a+socket+in+a+way+forbidden+by+its+access+permissions

**Comment by HideOnLie** [comment]
已经解决这个问题了。确实是与WSL2有关系

这个命令可以看到tcp 端口排除范围，
`netsh interface ipv4 show excludedportrange protocol=tcp
协议 tcp 端口排除范围
 
开始端口    结束端口
----------    --------
      1026        1125`
可以看到1093 这个端口在这个排除范围内。这个是由于我开启了WSL2,所以默认开了Hyper-V, 系统默认会分配给一些保留端口供Hyper-V使用。

解决方案：
[https://www.cnblogs.com/xwgli/p/13609041.html](https://www.cnblogs.com/xwgli/p/13609041.html)
[https://segmentfault.com/a/1190000022338199](https://segmentfault.com/a/1190000022338199)

**Comment by txthinking** [comment]
https://stackoverflow.com/questions/15619921/an-attempt-was-made-to-access-a-socket-in-a-way-forbidden-by-its-access-permissi

**Comment by Tint0ri** [comment]
端口能否可配置？WSL或者Hyper-V使用还是挺常见的，尤其是开发环境中。

**Comment by txthinking** [comment]
[v20240214](https://github.com/txthinking/brook/releases/tag/v20240214)
