### ISSUE TITLE
Do not use QQ browser 

### ISSUE THREAD

**Issue by hmmy1012** [txthinking/brook#90]
#### Steps to reproduce the problem
0.can not access google.com/ncr or other blocked websites on QQ browser
1.It can be used on QQ browser or other browsers
2. Android 7.0

**Comment by GreatBigWhiteWorld** [comment]
Why do you use malware vendor's browser in the first place?

**Comment by hmmy1012** [comment]
I find another browser called Quark browser, it can access google.com.hk and much better useful and simple. Thanks

**Comment by txthinking** [comment]
Because QQ Browser in https://github.com/txthinking/pac/blob/master/white_apps.list
