### ISSUE TITLE
Github Actions compiler

### ISSUE THREAD

**Issue by ImportTaste** [txthinking/brook#902]
Manually compiling builds for every OS seems tedious. You should consider automating your workflow.

* Syntax and fields reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
* Environment reference: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
* GitHub Actions for Go: https://github.com/mvdan/github-actions-golang
* GitHub Actions with a specific version of Go: https://github.com/actions/setup-go

**Comment by txthinking** [comment]
Thanks, I prefer manual build with [nami](https://github.com/txthinking/nami) pubsh now
