### ISSUE TITLE
一键脚本无法下载

### ISSUE THREAD

**Issue by nichenzi** [txthinking/brook#908]
### Please read the document first

* https://txthinking.github.io/brook/

**Comment by txthinking** [comment]
报什么错吗

**Comment by txthinking** [comment]
用readme和文档里的其他方式

**Comment by txthinking** [comment]
bash <(curl -s https://raw.githubusercontent.com/txthinking/brook/master/bash/brook.sh)

**Comment by txthinking** [comment]
bash <(curl -s https://bash.ooo/brook.sh)
