### ISSUE TITLE
Brook VPN Server Fast & Easy Setup

### ISSUE THREAD

**Issue by HadiAbbasi** [txthinking/brook#910]
I've installed my brook vpn server in my vps using:

`bash <(curl -sL https://git.io/brook.sh)`

but for now, when I run it, the result is:

```
/dev/fd/63: line 1: syntax error near unexpected token `newline'
/dev/fd/63: line 1: `<!DOCTYPE html>'
```

that was so perfect & easy way to run a vpn server!
I know we could use CLI via curl, CLI and joker via curl, CLI via nami
but that way was so easy & user friendly!
thanks a lot...
All the best,
Hadi

**Comment by txthinking** [comment]
bash <(curl -s https://raw.githubusercontent.com/txthinking/brook/master/bash/brook.sh)

**Comment by HadiAbbasi** [comment]
thanks a lot...
It seems to be my required script.
but I don't know why the brook client was connected to the brook server that was made by the old script, but now I can't connect to this ip:port using defined password (managed by new script)!

**Comment by HadiAbbasi** [comment]
![image](https://user-images.githubusercontent.com/11533268/150644628-91874e7d-c48f-4649-8312-08e0e245c689.png)

as you see, I've completed server creation but when I set these values to client, it can't connect to created server!

![image](https://user-images.githubusercontent.com/11533268/150644744-6dc9010e-5d7f-4838-8a9c-1ee1b2c9964b.png)

**Comment by HadiAbbasi** [comment]
![image](https://user-images.githubusercontent.com/11533268/150644883-8e8a99a3-ab6e-44cc-8107-de02810d4a2a.png)

as you can see, my settings are ok, but there is no any connection from brook client to my server!

![image](https://user-images.githubusercontent.com/11533268/150645036-be38f59d-8312-4ba7-a717-6c97759fbfab.png)

**Comment by HadiAbbasi** [comment]
as you can see, I've set my client & server correctly but the connection is not successful!
it was working last month! but for now..!

![image](https://user-images.githubusercontent.com/11533268/150645228-67133f02-6194-494a-9a3c-93ac0c47892c.png)

**Comment by txthinking** [comment]
Is there a firewall?

**Comment by HadiAbbasi** [comment]
this is my ubuntu server that I've ran brook server!
![image](https://user-images.githubusercontent.com/11533268/150657246-94a8e7b3-4556-4127-92f8-20bba933de07.png)

**Comment by txthinking** [comment]
I have connected your brook server.
Your brook server is works well from my compute(Taiwan network)

> (I see your server IP before you delete your IP from posted message)

The problem is your network can't connect your server network, maybe your IP has been blocked by your ISP or your country.

![image](https://user-images.githubusercontent.com/1241807/150659839-ec5f282f-a246-4d2c-9556-e2a61c118cae.png)

**Comment by HadiAbbasi** [comment]
thanks a lot...
I don't know how can I check it...
I've checked it via 2 or 3 different internet ISPs but all of them can't connect to my brook!
also I've checked it via my laptop (windows) and also my mobile (android) and my busines pc (windows) and also there is no any connection to my brook server!

**Comment by txthinking** [comment]
> I have connected your brook server. Your brook server is works well from my compute(Taiwan network)
> 
> > (I see your server IP before you delete your IP from posted message)
> 
> The problem is your network can't connect to your server network, maybe your IP has been blocked by your ISP or **your country**.
> 
> ![image](https://user-images.githubusercontent.com/1241807/150659839-ec5f282f-a246-4d2c-9556-e2a61c118cae.png)
> 
> GUI test OK
> 
> ```
> FUCK html $ testbrook -s YourIP:12345 -p myvpn123
> Starting brook
> Testing TCP
> OK: TCP response is OK
> Testing UDP
> OK: UDP response is OK
> Stopping brook
> 2022/01/23 00:16:06 accept tcp [::]:1080: use of closed network connection
> Stopped brook
> ```
> 
> CLI test OK too

That means Your Local IP <-- blocked --> Your Server IP
- Try brook wsserver, OR
- Try brook wssserver, OR
- Move your brook to another server.

**Comment by HadiAbbasi** [comment]
thanks a lot...
this problem has been solved for me!
All The Best,
Hadi
