### ISSUE TITLE
win7 64 default gateway not available

### ISSUE THREAD

**Issue by Whiood** [txthinking/brook#92]
when i start brook my Internet can not connect
when i Try to fix my Internet,I get default gateway not available for 10+ times.

**Comment by txthinking** [comment]
Do you miss something: https://github.com/txthinking/brook/wiki/How-to-use-Brook-Windows-Client%3F

**Comment by Whiood** [comment]
thanks for ur answer,Problem is that there is already a SSR process,I killed  this process it can run very fan

**Comment by Whiood** [comment]
thanks for ur answer,Problem is that there is already a SSR process,I killed this process it can run fantastic.

**Comment by txthinking** [comment]
Good luck.
