### ISSUE TITLE
Cannot install Brook on AWS Ubuntu with or without manually inputed version

### ISSUE THREAD

**Issue by zhengshencn** [txthinking/brook#927]
### Please read the document first

* https://txthinking.github.io/brook/

### Please describe step by step any commands and operations you have performed, environment and version:
Brook installation scripts failed to download the bundle from github with the following errors. It cannot be fixed even if I manually input the version.

```
========================
        协议 : servers
========================

[信息] 开始安装/配置 依赖...
[信息] 开始检测最新版本...
请输入要下载安装的 Brook 版本号 [ 格式是日期，例如: v20180707 ]
版本列表请去这里获取：[ https://github.com/txthinking/brook/releases ]
直接回车即自动获取:v20210701
[信息] 开始下载 Brook [ v20210701 ] 版本！
[信息] 开始下载/安装...
--2022-02-20 12:29:32--  https://github.com/txthinking/brook/releases/download/v20210701/brook
Resolving github.com (github.com)... 52.69.186.44
Connecting to github.com (github.com)|52.69.186.44|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-02-20 12:29:32 ERROR 404: Not Found.

```
I saw the following scripts in brook.sh. And in my case it was `x86_64` (AWS EC2 with Ubuntu. )
```
        if [[ ${bit} == "x86_64" ]]; then
                wget --no-check-certificate -N "https://github.com/txthinking/brook/releases/download/${brook_new_ver}/brook"
        else
                wget --no-check-certificate -N "https://github.com/txthinking/brook/releases/download/${brook_new_ver}/brook_linux_386"
```
Brook installation script was trying to download from endpoint `https://github.com/txthinking/brook/releases/download/v20210701/brook` which is a `404`. I checked the release files and can find many other options including `brook_linux_386` but definitly no `brook` without any suffix.

**Could you please let me know what's the possible workaround?**

```
$ uname -a
Linux ip-172-31-13-5 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

Thank you for building this great open source project!

**Comment by txthinking** [comment]
用这个脚本

bash <(curl https://bash.ooo/brook.sh)

**Comment by zhengshencn** [comment]
It works! Thank you very much! Looks like I'm using an out-of-date installation scripts.
