### ISSUE TITLE
 brook client/wsclient/wssclient -> brook server/wsserver/wssserver -> socks5 -> dst

### ISSUE THREAD

**Issue by txthinking** [txthinking/brook#928]
```
 brook client/wsclient/wssclient -> brook server/wsserver/wssserver -> socks5 -> dst
```

**Comment by aa51513** [comment]
I mentioned an issue similar to this before, 

My English is not good and I didn't express it clearly, which caused my issue to be closed. 

But thank goodness it's finally here

**Comment by txthinking** [comment]
v20220404
