### ISSUE TITLE
windows Uninstall all antivirus softwares 具体指？

### ISSUE THREAD

**Issue by pyclear** [txthinking/brook#93]
1.是安装的时候，还是window clinet运行过程中始终不能使用杀毒软件
2. 是特指的国内的各种管家卫士还是all

**Comment by txthinking** [comment]
Changed to :
Uninstall all antivirus softwares (Optional)

   - If something wrong, please do this
   - If you are in China, strongly recommend do this


某国内的各种卫士管家杀毒强烈建议删的干干净净，这个原因网上已经有很多了。

**Comment by pyclear** [comment]
哎，朋友政府机构下属，要求必须用这种东西，不管他了。
