### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by BIGMONK** [txthinking/brook#930]
### Please read the document first

* https://txthinking.github.io/brook/

### Please describe step by step any commands and operations you have performed, environment and version:
日志如下：
>>> nami install joker brook jinbe
/root/.nami/bin/deno: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /root/.nami/bin/deno)
/root/.nami/bin/deno: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /root/.nami/bin/deno)
exit status 1

系统：
 Virtualization: kvm
 Operating System: CentOS Linux 7 (Core)
 CPE OS Name: cpe:/o:centos:centos:7
 Kernel: Linux 5.16.12-1.el7.elrepo.x86_64
 Architecture: x86-64

**Comment by txthinking** [comment]
升级centos。或者手动安装需要版本的glibc依赖。或者换ubuntu。

**Comment by txthinking** [comment]
upgrade centos OR install glibc manual OR move to another linux such as ubuntu
