### ISSUE TITLE
brook client not connecting to brok server

### ISSUE THREAD

**Issue by connected201** [txthinking/brook#933]
hi, i run brook with brook.exe client -s myip:5050 --password password --socks5 127.0.0.1:6050 but brook doesn't even try to connect on server, i make screenshot with my firewall where you can see that brook client create only proxy server!. no errors, nothing else, how to fix it?
![image](https://user-images.githubusercontent.com/20506433/159078830-033b1bd8-0f4a-4fc2-b0da-4326b5677ee7.png)

**Comment by txthinking** [comment]
https://chrome.google.com/webstore/detail/hnpgnjkeaobghpjjhaiemlahikgmnghb

or

https://txthinking.github.io/brook/#/install-gui-client
