### ISSUE TITLE
希望brook client 支持配置只代理制定的ip端口，类似于proxifier

### ISSUE THREAD

**Issue by loptreival** [txthinking/brook#934]
RT, 希望brook client 支持配置只代理制定的ip端口，也可以使用通配符去配置，这样既可以代理所有的，也可以代理制定ip端口的

**Comment by txthinking** [comment]
GUI?

**Comment by txthinking** [comment]
CLI 和 GUI 的 proxy 模式，只是单纯的创建一个socks5，怎么使用这个socks5由外层决定，比如chrome，系统代理。

GUI的tun模式，可以自己修改路由表来达到自己的目的

**Comment by txthinking** [comment]
https://talks.txthinking.com/articles/brook.article

**Comment by loptreival** [comment]
thanks
