### ISSUE TITLE
dial tcp [Server_IP]:[Server_Port]: i/o timeout

### ISSUE THREAD

**Issue by chwilley** [txthinking/brook#95]
Working well except some messages in the client:
dial tcp [Server_IP]:[Server_Port]: i/o timeout

So what's the matter?

**Comment by chwilley** [comment]
It seems that Web Browsing needs "brook server" not "brook streamsever" on the server side.
When I change to "brook server" on the server side the message disappeared.

**Comment by txthinking** [comment]
When you check those ips, you may find some ips are invalid, means GFW
sniffed you. So try new protocol.
