### ISSUE TITLE
host运行tproxy后docker容器外网通但无法更新和下载

### ISSUE THREAD

**Issue by molezz** [txthinking/brook#951]
运行brook tproxy后，测试容器可以ping通baidu，说明网通， 但是curl和wget -S无回馈，也无法正常进行npm install等。容器bridge模式， 未改网络设置。2个容器一样的情况，是不是网络哪里要设置下。

ubuntu，5.9.0-arm-64 #20.10 ； Docker version 20.10.14, build a224086，Brook version 20220406

host
inet 172.19.0.1/16 brd 172.19.255.255 scope global br-6860268

容器
inet 172.19.0.2/16 brd 172.19.255.255 scope global eth0

**Comment by molezz** [comment]
容器就是普通docker run出来的。没有设置过网关，ip等，默认的。 网段也是内网网段 172.19.0.1
host运行
brook_linux_arm64   tproxy -s wss://domain:8443 -p password -l :22222 --ca ……
别的电脑手动设置后使用正常， 就是host的docker有问题

**Comment by molezz** [comment]
> 

不是 docker内容器不走代理，就是日常普通网络用，有问题，要host关了tproxy才可以。以前没用brook tproxy，该容器正常。 最近启用trpoxy，发现容器有问题，才慢慢排查发现停了tproxy后正常

**Comment by txthinking** [comment]
> 看你的环境是，ubuntu系统，里面装了个docker，想让docker内走代理。不知道ipio行不行 by [unknown](https://t.me/brookgroup)

![image](https://user-images.githubusercontent.com/1241807/161469109-1f8b4a6c-03d4-4d42-8e65-8fc71375a812.png)

行。
主机（上图主机是Ubuntu）运行ipio
主机上的 docker内 同样会走代理
