### ISSUE TITLE
Does brook have plans to support mitm?

### ISSUE THREAD

**Issue by txthinking** [txthinking/brook#958]
### Discussed in https://github.com/txthinking/brook/discussions/915

<div type='discussions-op-text'>

<sup>Originally posted by **yuzifu** January 27, 2022</sup>
Brook is a great product, faster than SS and V2R in my case.
Based on some APPs, MITM needs to be modified to be used normally, such as tiktok. 
Does the brook client app have a plan to support mitm in the future? 
Or is there a way to support MITM now?

thanks again for your product.</div>

**Comment by txthinking** [comment]
v20220501

**Comment by yuzifu** [comment]
that is great!
