### ISSUE TITLE
‘Invalid args, please reopen app’ after upgrade

### ISSUE THREAD

**Issue by LeonTheAlchemist** [txthinking/brook#960]
Gui Client show error ‘Invalid args, please reopen app’ after upgrade the client and server to v20220406(from v20210701). the issue remains after reinstall both client and server.
Client: mac catalina
Server: debian10

**Comment by LeonTheAlchemist** [comment]
Yes, quit-reopen or delete-reinstall lead to the same error

**Comment by LeonTheAlchemist** [comment]
I’ve changed the server ip recently and no other. Will try the suggestion later :)

**Comment by LeonTheAlchemist** [comment]
Delete b.db and problem solved. Thanks very much :)

**Comment by GouMinghao** [comment]
I quit the GUI program first, then delete b.db and delete everything in the same directory of `brook.exe`.
The same error still occurs, is there any solution?

**Comment by GouMinghao** [comment]
This time I delete b.db, delete wintun.dll, wintun.h, cmroute.dll and then reboot and start brook. The same problem is still there.

I used to use very old version, and is upgraded to 0501 release. The server version is also upgraded. It work well on my mobile phone(old version client) but fails on Windows 11 (0501 release).

**Comment by GouMinghao** [comment]
清除Edge的缓存过后问题解决

**Comment by poena** [comment]
> if still getting error, you can
> 
> 1. quit GUI on the system tray
> 2. delete or rename $HOME/Library/Application Support/b.db to reset all options (Windows: C:\Users\xxxx\AppData\Roaming\b.db)
> 3. open GUI again
>    by [unknown](https://t.me/brookgroup)

Same issue on MacOS. How to resolve it?

**Comment by poena** [comment]
reopen and restart computer doesn't work.

**Comment by poena** [comment]
clear safari cache doesn't work.
But I've solve it. The default bypass and block list are invalid. 
By Disable these option or changing them to a valid url can solve this issue.
