### ISSUE TITLE
最新版本报 Windows 找不到 'msedge'。请确定文件名是否正确，再试一次

### ISSUE THREAD

**Issue by YaoZhengWu** [txthinking/brook#962]
最新版本报 Windows 找不到 'msedge'。请确定文件名是否正确，再试一次

**Comment by YaoZhengWu** [comment]
感谢，原来是，Windows: 需要你已经安装了最新版(基于 chromium 的那款)的 Edge 浏览器

**Comment by txthinking** [comment]
Install the latest Edge browser(chromium-based)
