### ISSUE TITLE
[Feature request] IPv4/IPv6 selective egress on dual IP stack servers.

### ISSUE THREAD

**Issue by Siss6678** [txthinking/brook#969]
Trying to reach regional contents on NETFLIX through BROOK, unfortunately NETFLIX only accepts my IPv6 address on the server which has also an IPv4, I can make it work by make use of the settings combination "sniffing and routing rules" provided by v2fly, but the lightning fast BROOK is just irresistible.

Any idea?

**Comment by txthinking** [comment]
You can let netflix domain  force to IPv6, 

```
systemctl stop systemd-resolved
systemctl disable systemd-resolved
echo nameserver 127.0.0.1 >  /etc/resolv.conf
```

Create a domain list `domain.txt`

```
a.domain.of.netflix
another.domain.of.netflix
```

```
brook dnsserver --listen 127.0.0.1:53 --disableIPv4DomainList /path/to/domain.txt
```

**Comment by txthinking** [comment]
v20221212
