### ISSUE TITLE
下载youtube上的视频老是断流

### ISSUE THREAD

**Issue by zhuhaijian** [txthinking/brook#97]
测试多次现象反复出现，在下载youtube视频的时候，开始速度很快，后来慢慢减为0，然后就中断下载了。

**Comment by txthinking** [comment]
Can you provide the steps to deploy the server?

**Comment by txthinking** [comment]
Can you provide the steps to reproduce the problem?

**Comment by txthinking** [comment]
No response.

**Comment by zhuhaijian** [comment]
1、brook_ver=$(wget -qO- "https://github.com/txthinking/brook/tags"| grep
"/txthinking/brook/releases/tag/"| head -n 1| awk -F "/tag/" '{print $2}'|
sed 's/\">//') && echo ${brook_ver}
2、wget -N --no-check-certificate "
https://github.com/txthinking/brook/releases/download/${brook_ver}/brook"
3、chmod +x brook
4、nohup ./brook server -l :2333 -p "doub.io" > /dev/null 2>&1 &

步骤基本上是这样的，根据逗比上的一个教程部署的。

2017-11-12 10:40 GMT+08:00 Cloud <notifications@github.com>:

**Comment by txthinking** [comment]
```
Clouds-MacBook-Pro:Downloads tx$ youtube-dl --proxy socks5://127.0.0.1:1080 https://www.youtube.com/watch?v=7pCNSD6V3-c
[youtube] 7pCNSD6V3-c: Downloading webpage
[youtube] 7pCNSD6V3-c: Downloading video info webpage
[youtube] 7pCNSD6V3-c: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] 7pCNSD6V3-c: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[dashsegments] Total fragments: 73
[download] Destination: 即便是汪峰也沒能將這首歌唱的如此攝人心骨-7pCNSD6V3-c.f135.mp4
[download]  41.1% of ~17.85MiB at 718.69KiB/s ETA 00:42
```

很顺畅

**Comment by zhuhaijian** [comment]
我下载的文件比较大，四百多M，开始速度飞快，到一百多M时速度就开始减慢，最后为0，然后就断了，重复几次都这样。

2017年11月13日 16:29，"Cloud" <notifications@github.com>写道：

**Comment by txthinking** [comment]
The solution:
@zhuhaijian 
#124
