### ISSUE TITLE
Brook iOS 换网需要重连

### ISSUE THREAD

**Issue by zed-wong** [txthinking/brook#974]
在WiFi下使用Brook正常，把WiFi关掉，切换成4G，就需要在Brook app里断开连接，再重新连接，否则就一直没有网络。

在不断开Brook连接的情况下，换WiFi也会遇到同样问题，但都会在重新连接之后恢复正常。

**Comment by zed-wong** [comment]
还有MacBook m1，在关盖再开盖后，也需要手动关闭Brook再重新连接，才能连上

**Comment by txthinking** [comment]
下一版本

**Comment by zed-wong** [comment]
修好了，大佬牛逼！

**Comment by txthinking** [comment]
v20220707
