### ISSUE TITLE
about the release 20220707

### ISSUE THREAD

**Issue by chenrui333** [txthinking/brook#980]
👋 noticed that the release for 20220707 seems a bit off, just raise an issue to confirm if that is desired. Thanks!

relates toi https://github.com/Homebrew/homebrew-core/pull/103888

**Comment by txthinking** [comment]
That is no problem, the version name is correct :), the release note added

**Comment by chenrui333** [comment]
what does 0707 stand for? shouldn't it be released on July 7 2022?

**Comment by chenrui333** [comment]
I can actually see it in the apple store

<img width="939" alt="image" src="https://user-images.githubusercontent.com/1580956/176092015-de70d523-0a9d-4ac3-80bc-b97ae3b953ee.png">

**Comment by chenrui333** [comment]
Thanks for clarifying it. 👍
