### ISSUE TITLE
IOS client cannot set up

### ISSUE THREAD

**Issue by changcui** [txthinking/brook#995]
The connection test is okay, but I cannot set up the VPN.
There is no VPN icon on the menu, and I cannot find any log or visit IG, Google, FB, etc, either.
The version of Brook is 20220707 (latest version in App Store)
The version of IOS is 15.6.

**Comment by txthinking** [comment]
iOS 15.6.1, can't reproduce

**Comment by changcui** [comment]
I update IOS to 15.6.1.
It cannot work, either..

**Comment by changcui** [comment]
It seems VPN has not been set up, but i do not know why.
I can open VPN at the system preference, for example Shadowrocket.
But I can not open Brook VPN.
And When Brook is enable, the VPN show no IP and gateway info.
I do not know about the vpn permission, what is it?

**Comment by changcui** [comment]
No, I didn't. I have no clue about the issue. I tried another smart phone,
it got the same error.

txthinking-bot ***@***.***>于2022年9月4日 周日上午9:50写道：

**Comment by changcui** [comment]
Yeah, I have tried to delete vpn config and reset, delete and reinstall
app, even change the region of the apple id. But neither was worked. So I
just give up and use Shadowrocket instead.
txthinking-bot ***@***.***>于2022年9月4日 周日上午10:10写道：
